Repository tldraw/tldraw, pull requests merged in 2023-11, with the labels that each got.

#2148 bump prerelease from alpha to beta
  lerna.json
  packages/assets/package.json
  packages/editor/package.json
  packages/state/package.json
  packages/store/package.json
  packages/tldraw/package.json
  packages/tlschema/package.json
  packages/utils/package.json
  packages/validate/package.json
Labels: internal

#2150 [feature] Things on the canvas
  apps/examples/src/examples/OnTheCanvas.tsx
  apps/examples/src/index.tsx
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/index.ts
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/components/default-components/DefaultInFrontOfTheCanvas.tsx
  packages/editor/src/lib/components/default-components/DefaultOnTheCanvas.tsx
  packages/editor/src/lib/hooks/useEditorComponents.tsx
  packages/tldraw/api/api.json
Labels: minor

#2168 Fix the problem with text not being correctly aligned in small geo shapes.
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
Labels: patch

#2169 Allow users to select shapes when drag starts on top of a locked shape.
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/test/commands/lockShapes.test.ts
Labels: patch

#2173 Fix crash with zero length arrow
  packages/editor/src/lib/editor/shapes/shared/arrow/curved-arrow.ts
  packages/editor/src/lib/editor/shapes/shared/arrow/straight-arrow.ts
  packages/tldraw/api/api.json
Labels: patch

#2174 Fix arrow dropdown localizations.
  packages/tldraw/src/lib/ui/components/StylePanel/DoubleDropdownPicker.tsx
Labels: patch

#2176 instant bookmarks
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteUrl.ts
Labels: minor

#2171 Don't show scrollbars.
  packages/tldraw/src/lib/ui.css
Labels: patch

#2177 Fix printing.
  packages/tldraw/src/lib/ui/hooks/usePrint.ts
Labels: patch

#2180 fix scroll event coords
  packages/editor/src/lib/hooks/useGestureEvents.ts
Labels: patch

#2185 Only use the hack if we are in safari.
  packages/tldraw/src/lib/ui/hooks/useCopyAs.ts
  packages/tldraw/src/lib/ui/hooks/useExportAs.ts
  packages/tldraw/src/lib/utils/export.ts
Labels: patch

#2182 add missing semicolon
  packages/editor/editor.css
Labels: patch

#2184 Fix an issue with edit link.
  packages/tldraw/package.json
  packages/tldraw/src/lib/ui/components/ActionsMenu.tsx
  packages/tldraw/src/lib/ui/components/ContextMenu.tsx
  packages/tldraw/src/lib/ui/components/HelpMenu.tsx
  packages/tldraw/src/lib/ui/components/MoveToPageMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/DropdownMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/Popover.tsx
  public-yarn.lock
Labels: patch

#2187 [fix] actions menu freezing ui
  packages/editor/src/lib/hooks/useCanvasEvents.ts
  packages/tldraw/src/lib/ui/hooks/menuHelpers.ts
  packages/tldraw/src/lib/ui/hooks/useActionsMenuSchema.tsx
Labels: patch

#2186 Fix an error when using context menu.
  packages/tldraw/src/lib/ui/components/ContextMenu.tsx
Labels: patch

#2188 Add tldraw component exports
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/canvas/TldrawCropHandles.tsx
  packages/tldraw/src/lib/canvas/TldrawHandles.tsx
  packages/tldraw/src/lib/canvas/TldrawHoveredShapeIndicator.tsx
  packages/tldraw/src/lib/canvas/TldrawScribble.tsx
  packages/tldraw/src/lib/canvas/TldrawSelectionBackground.tsx
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
Labels: patch

#2192 Revert "bump prerelease from alpha to beta"
  lerna.json
  packages/assets/package.json
  packages/editor/package.json
  packages/state/package.json
  packages/store/package.json
  packages/tldraw/package.json
  packages/tlschema/package.json
  packages/utils/package.json
  packages/validate/package.json
Labels: internal

#2193 VS code bump 2.0.16
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: patch

#2197 [fix] masked bounds calculation
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#2199 Japanese translations. (update)
  assets/translations/ja.json
Labels: patch

#2203 No impure getters pt3
  apps/examples/e2e/tests/test-clipboard.spec.ts
  apps/examples/e2e/tests/test-smoke.spec.ts
  apps/examples/src/examples/ShapeMetaExample.tsx
  apps/examples/src/examples/only-editor/MiniSelectTool.ts
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/components/default-components/DefaultSelectionForeground.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/SnapManager.ts
  packages/editor/src/lib/utils/rotation.ts
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.test.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/geo/GeoShapeTool.test.ts
  packages/tldraw/src/lib/shapes/geo/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/text/toolStates/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Crop/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Crop/children/TranslatingCrop.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Cropping.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingCropHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingResizeHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Translating.ts
  packages/tldraw/src/lib/tools/selection-logic/getShouldEnterCropModeOnPointerDown.ts
  packages/tldraw/src/lib/ui/components/ContextMenu.tsx
  packages/tldraw/src/lib/ui/components/DebugPanel.tsx
  packages/tldraw/src/lib/ui/components/EditLinkDialog.tsx
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
  packages/tldraw/src/lib/ui/hooks/useContextMenuSchema.tsx
  packages/tldraw/src/lib/ui/hooks/useHasLinkShapeSelected.ts
  packages/tldraw/src/lib/ui/hooks/useMenuSchema.tsx
  packages/tldraw/src/lib/ui/hooks/useOnlyFlippableShape.ts
  packages/tldraw/src/lib/ui/hooks/useShowAutoSizeToggle.ts
  packages/tldraw/src/test/EraserTool.test.ts
  packages/tldraw/src/test/HighlightShape.test.ts
  packages/tldraw/src/test/SelectTool.test.ts
  packages/tldraw/src/test/arrowBindingsIndex.test.tsx
  packages/tldraw/src/test/arrows-megabus.test.ts
  packages/tldraw/src/test/commands/getInitialMetaForShape.test.ts
  packages/tldraw/src/test/commands/moveShapesToPage.test.ts
  packages/tldraw/src/test/commands/stretch.test.tsx
  packages/tldraw/src/test/flipShapes.test.ts
  packages/tldraw/src/test/frames.test.ts
  packages/tldraw/src/test/paste.test.ts
  packages/tldraw/src/test/select.test.tsx
  packages/tldraw/src/test/selection-omnibus.test.ts
  packages/tldraw/src/test/translating.test.ts
Labels: patch

#2206 No impure getters pt4
  apps/examples/src/examples/OnTheCanvas.tsx
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/editor/src/lib/hooks/useGestureEvents.ts
  packages/editor/src/lib/hooks/useIsEditing.ts
  packages/editor/src/lib/utils/rotation.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/canvas/TldrawHoveredShapeIndicator.tsx
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.test.ts
  packages/tldraw/src/lib/shapes/frame/components/FrameHeading.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/children/Cropping.ts
  packages/tldraw/src/lib/tools/SelectTool/children/EditingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingRotateHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Rotating.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Translating.ts
  packages/tldraw/src/lib/tools/selection-logic/selectOnCanvasPointerUp.ts
  packages/tldraw/src/lib/tools/selection-logic/updateHoveredId.ts
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
  packages/tldraw/src/test/Editor.test.tsx
  packages/tldraw/src/test/SelectTool.test.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/commands/getSvg.test.ts
  packages/tldraw/src/test/commands/moveShapesToPage.test.ts
  packages/tldraw/src/test/commands/nudge.test.ts
  packages/tldraw/src/test/commands/packShapes.test.ts
  packages/tldraw/src/test/duplicate.test.ts
  packages/tldraw/src/test/flipShapes.test.ts
  packages/tldraw/src/test/frames.test.ts
  packages/tldraw/src/test/groups.test.ts
  packages/tldraw/src/test/resizing.test.ts
  packages/tldraw/src/test/rotating.test.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
  packages/tldraw/src/test/translating.test.ts
Labels: patch

#2205 Fix an issue with not being able to group a shape an an arrow.
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/ui/hooks/menuHelpers.ts
Labels: patch

#2210 Revert back to the previous color.
  packages/editor/editor.css
Labels: patch

#2207 [fix] huge images, use downscale for image scaling
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/package.json
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/utils/assets.ts
  public-yarn.lock
Labels: minor

#2201 Update translations from community submissions
  assets/translations/es.json
  assets/translations/ja.json
  assets/translations/ro.json
  assets/translations/ru.json
  assets/translations/uk.json
  assets/translations/zh-cn.json
Labels: patch

#2212 Add prettier caching
  package.json
  packages/tlschema/package.json
  scripts/lint.ts
Labels: internal

#2215 don't overwrite bookmark position if it changed before metadata arrives
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: patch

#2217 VS Code bump 2.0.17
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: internal

#2213 StateNode atoms
  apps/examples/e2e/shared-e2e.ts
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/tools/BaseBoxShapeTool/children/Pointing.ts
  packages/editor/src/lib/editor/tools/RootState.ts
  packages/editor/src/lib/editor/tools/StateNode.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeTool.test.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.test.ts
  packages/tldraw/src/lib/shapes/arrow/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/arrow/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/draw/DrawShapeTool.test.ts
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
  packages/tldraw/src/lib/shapes/frame/FrameShapeTool.test.ts
  packages/tldraw/src/lib/shapes/geo/GeoShapeTool.test.ts
  packages/tldraw/src/lib/shapes/geo/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/geo/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/line/LineShapeTool.test.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.test.ts
  packages/tldraw/src/lib/shapes/line/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/note/NoteShapeTool.test.ts
  packages/tldraw/src/lib/shapes/note/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/EraserTool/children/Erasing.ts
  packages/tldraw/src/lib/tools/EraserTool/children/Pointing.ts
  packages/tldraw/src/lib/tools/HandTool/children/Dragging.ts
  packages/tldraw/src/lib/tools/HandTool/children/Pointing.ts
  packages/tldraw/src/lib/tools/LaserTool/children/Lasering.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Brushing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Cropping.ts
  packages/tldraw/src/lib/tools/SelectTool/children/DraggingHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingCanvas.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingCropHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingResizeHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingRotateHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingSelection.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/ScribbleBrushing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Translating.ts
  packages/tldraw/src/lib/tools/ZoomTool/ZoomTool.ts
  packages/tldraw/src/lib/ui/components/DebugPanel.tsx
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
  packages/tldraw/src/lib/ui/hooks/useRevelantStyles.ts
  packages/tldraw/src/test/Editor.test.tsx
  packages/tldraw/src/test/EraserTool.test.ts
  packages/tldraw/src/test/HandTool.test.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/commands/setSelectedTool.test.ts
  packages/tldraw/src/test/cropping.test.ts
  packages/tldraw/src/test/frames.test.ts
  packages/tldraw/src/test/groups.test.ts
  packages/tldraw/src/test/resizing.test.ts
  packages/tldraw/src/test/select.test.tsx
  packages/tldraw/src/test/selection-omnibus.test.ts
  packages/tldraw/src/test/shapeutils.test.ts
  packages/tldraw/src/test/translating.test.ts
Labels: minor

#2220 No impure getters pt7
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/components/GeometryDebuggingView.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/SnapManager.ts
  packages/tldraw/src/lib/ui/components/BackToContent.tsx
  packages/tldraw/src/lib/ui/components/DebugPanel.tsx
  packages/tldraw/src/lib/ui/components/MoveToPageMenu.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageItemSubmenu.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageMenu.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/edit-pages-shared.ts
  packages/tldraw/src/lib/ui/hooks/usePrint.ts
  packages/tldraw/src/lib/utils/buildFromV1Document.ts
  packages/tldraw/src/test/TLSessionStateSnapshot.test.ts
  packages/tldraw/src/test/commands/createPage.test.ts
  packages/tldraw/src/test/commands/deletePage.test.ts
  packages/tldraw/src/test/commands/duplicatePage.test.ts
  packages/tldraw/src/test/commands/setCurrentPage.test.ts
  packages/tldraw/src/test/renderingShapes.test.tsx
  packages/tldraw/src/test/shapeIdsInCurrentPage.test.ts
Labels: patch

#2222 No impure getters pt9
  apps/examples/src/examples/CustomConfigExample/CardShape/CardShapeUtil.tsx
  apps/examples/src/examples/CustomStylesExample/CardShape.tsx
  apps/examples/src/examples/MetaExample.tsx
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/editor/src/lib/components/default-components/DefaultErrorFallback.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/SnapManager.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
  packages/editor/src/lib/hooks/useIsDarkMode.ts
  packages/editor/src/lib/hooks/usePeerIds.ts
  packages/editor/src/lib/test/user.test.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/draw/DrawShapeUtil.tsx
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/children/DraggingHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Translating.ts
  packages/tldraw/src/lib/ui/components/MobileStylePanel.tsx
  packages/tldraw/src/lib/ui/components/primitives/ButtonPicker.tsx
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
  packages/tldraw/src/lib/ui/hooks/useMenuSchema.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/useLanguages.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/useTranslation.tsx
  packages/tldraw/src/test/Editor.test.tsx
  packages/tldraw/src/test/TLUserPreferences.test.ts
Labels: patch

#2225 Fix the tool lock button.
  packages/tldraw/src/lib/ui.css
Labels: patch

#2229 Add `getSvgAsImage` to exports.
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
Labels: minor

#2234 Also export `TLUiEventMap`
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
Labels: patch

#2248 Lokalise: Translations update
  assets/translations/ro.json
Labels: patch

#2250 Add floaty window example
  apps/examples/src/examples/FloatyExample.tsx
  apps/examples/src/index.tsx
Labels: internal

#2253 Fix "custom UI" example
  apps/examples/src/examples/CustomUiExample/CustomUiExample.tsx
Labels: internal

#2251 Fix missing padding-right in toast
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/DebugPanel.tsx
Labels: patch

#2247 Fixes #2246 Sublibraries example (ExplodedExample.tsx)
  apps/examples/src/examples/ExplodedExample.tsx
Labels: patch

#2231 improves translation into pt-br
  assets/translations/pt-br.json
Labels: patch

#2242 fix typo in useFixSafariDoubleTapZoomPencilEvents.ts
  packages/editor/src/lib/hooks/useFixSafariDoubleTapZoomPencilEvents.ts
Labels: documentation

#2261 Replace getters in examples
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
  packages/state/api/api.json
  packages/state/src/lib/core/Atom.ts
  packages/state/src/lib/core/Computed.ts
  packages/state/src/lib/core/EffectScheduler.ts
  packages/state/src/lib/core/capture.ts
  packages/state/src/lib/core/transactions.ts
  packages/state/src/lib/react/track.ts
  packages/state/src/lib/react/useAtom.ts
  packages/state/src/lib/react/useComputed.ts
  packages/state/src/lib/react/useValue.ts
Labels: documentation

#2219 Removing frames and adding elements to frames
  assets/translations/main.json
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/editor.css
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/tools/BaseBoxShapeTool/BaseBoxShapeTool.ts
  packages/editor/src/lib/editor/tools/BaseBoxShapeTool/children/Pointing.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/frame/FrameShapeTool.ts
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
  packages/tldraw/src/lib/ui/hooks/useContextMenuSchema.tsx
  packages/tldraw/src/lib/ui/hooks/useEventsProvider.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/test/frames.test.ts
Labels: minor
