Repository tldraw/tldraw, pull requests merged in 2023-10, with the labels that each got.

#1977 [fix] Drawing tool touch for first pen mark
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
Labels: patch

#1974 [fix] text shape outline
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
Labels: patch

#1953 Remove focus management
  apps/examples/e2e/tests/test-canvas-events.spec.ts
  apps/examples/e2e/tests/test-focus.spec.ts
  apps/examples/src/BasicExample.tsx
  apps/examples/src/examples/AssetOptionsExample.tsx
  apps/examples/src/examples/CanvasEventsExample.tsx
  apps/examples/src/examples/CustomConfigExample/CustomConfigExample.tsx
  apps/examples/src/examples/CustomStylesExample/CustomStylesExample.tsx
  apps/examples/src/examples/CustomUiExample/CustomUiExample.tsx
  apps/examples/src/examples/ExplodedExample.tsx
  apps/examples/src/examples/HideUiExample.tsx
  apps/examples/src/examples/HostedImagesExample.tsx
  apps/examples/src/examples/MultipleExample.tsx
  apps/examples/src/examples/PersistenceExample.tsx
  apps/examples/src/examples/ScrollExample.tsx
  apps/examples/src/examples/ShapeMetaExample.tsx
  apps/examples/src/examples/SnapshotExample/SnapshotExample.tsx
  apps/examples/src/examples/StoreEventsExample.tsx
  apps/examples/src/examples/UiEventsExample.tsx
  apps/examples/src/examples/end-to-end/end-to-end.tsx
  apps/examples/src/only-editor/OnlyEditor.tsx
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/hooks/useFocusEvents.ts
  packages/editor/src/lib/hooks/useScreenBounds.ts
  packages/tldraw/src/lib/Tldraw.test.tsx
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/defaultSideEffects.ts
  packages/tldraw/src/lib/ui/components/Toolbar/Toolbar.tsx
  packages/tldraw/src/test/Editor.test.tsx
Labels: major

#1980 Fix text-wrapping on Safari
  apps/examples/e2e/tests/test-text.spec.ts
  packages/editor/src/lib/editor/managers/TextManager.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/test/TestEditor.ts
Labels: patch

#1979 [fix] pinch events
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useGestureEvents.ts
Labels: patch

#1981 Sliiiightly darken muted-2 color.
  packages/editor/editor.css
Labels: patch

#1975 [fix] Right click groups
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/test/groups.test.ts
Labels: tests

#1949 fix(docs): update shapes docs add the array of defined shapes
  docs/docs/shapes.mdx
Labels: documentation

#1985 [fix] Hovered indicators shown when coarse pointer
  packages/editor/src/lib/components/Canvas.tsx
Labels: patch

#1986 [fix] Escape key exiting full screen while editing shapes
  packages/editor/src/lib/hooks/useDocumentEvents.ts
Labels: patch

#1997 Fix group opacity
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#1990 [improvement] prevent editing in readonly
  apps/examples/src/examples/ReadOnlyExample.tsx
  apps/examples/src/index.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/arrow/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingShape.ts
Labels: major

#2006 [fix] X box shape arrow intersections
  packages/editor/api-report.md
  packages/editor/src/lib/editor/shapes/shared/arrow/curved-arrow.ts
  packages/editor/src/lib/editor/shapes/shared/arrow/shared.ts
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
Labels: patch

#2008 fix cloud rendering
  packages/tldraw/src/lib/shapes/geo/cloudOutline.ts
  packages/tldraw/src/lib/shapes/geo/components/DashStyleCloud.tsx
Labels: patch

#2004 Fix an issue with arrow creation.
  packages/editor/src/lib/editor/shapes/shared/arrow/curved-arrow.ts
  packages/editor/src/lib/editor/shapes/shared/arrow/straight-arrow.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeTool.test.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/toolStates/Pointing.ts
Labels: patch

#2009 [fix] tool lock button in toolbar
  packages/tldraw/src/lib/ui/components/Toolbar/Toolbar.tsx
Labels: patch

#2003 fix text in geo shapes not causing its container to grow
  apps/examples/e2e/tests/test-text.spec.ts
  packages/editor/editor.css
  packages/editor/src/lib/editor/managers/TextManager.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/default-shape-constants.ts
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/commands/__snapshots__/getSvg.test.ts.snap
Labels: patch

#1999 Contain all the things
  packages/editor/editor.css
  packages/tldraw/src/lib/ui.css
Labels: patch

#2002 [fix] Image size
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
Labels: patch

#2010 Re-focus on focus.
  packages/editor/src/lib/hooks/useFocusEvents.ts
Labels: patch

#2013 [fix] focus events
  packages/editor/src/lib/hooks/useFocusEvents.ts
Labels: patch

#2011 Fix vs code extension. Prepare for new release.
  apps/vscode/README.md
  apps/vscode/editor/src/app.tsx
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: patch

#2012 [fix] Minimap interactions
  packages/tldraw/src/lib/ui/components/NavigationZone/Minimap.tsx
Labels: patch

#2015 [fix] Focus events (actually)
  apps/examples/e2e/tests/test-focus.spec.ts
  apps/examples/src/examples/MultipleExample.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/hooks/useCanvasEvents.ts
  packages/editor/src/lib/hooks/useFocusEvents.ts
  packages/editor/src/lib/hooks/useSelectionEvents.ts
  packages/tldraw/src/lib/defaultSideEffects.ts
  packages/tldraw/src/lib/shapes/frame/components/FrameLabelInput.tsx
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/primitives/Input.tsx
Labels: patch

#2019 [improvement] Refactor curved arrows
  packages/editor/src/lib/editor/shapes/shared/arrow/curved-arrow.ts
  packages/editor/src/lib/primitives/utils.ts
Labels: patch

#2016 frame label fix
  packages/editor/editor.css
  packages/editor/src/lib/components/Shape.tsx
  packages/tldraw/src/lib/shapes/frame/components/FrameHeading.tsx
Labels: patch

#2022 fix screen bounds not updating
  packages/editor/src/lib/hooks/useScreenBounds.ts
Labels: patch

#2026 [fix] Multiple example
  apps/examples/src/examples/MultipleExample.tsx
Labels: patch

#2027 Update readme
  apps/examples/.gitignore
  apps/examples/src/index.tsx
  packages/tldraw/README.md
  vercel.json
Labels: patch

#2030 Remove docs source.
  docs/README.md
  docs/authors.json
  docs/community/contributing.mdx
  docs/community/translations.mdx
  docs/docs/assets.mdx
  docs/docs/collaboration.mdx
  docs/docs/editor.mdx
  docs/docs/persistence.mdx
  docs/docs/shapes.mdx
  docs/docs/tools.mdx
  docs/docs/user-interface.mdx
  docs/getting-started/installation.mdx
  docs/getting-started/introduction.mdx
  docs/getting-started/usage.mdx
  docs/sections.json
Labels: internal

#2034 Publish api.json
  .gitignore
  packages/editor/api/api.json
  packages/state/api/api.json
  packages/store/api/api.json
  packages/tldraw/api/api.json
  packages/tlschema/api/api.json
  packages/utils/api/api.json
  packages/validate/api/api.json
Labels: internal

#2035 Export tools
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeTool.ts
  packages/tldraw/src/lib/shapes/draw/DrawShapeTool.ts
  packages/tldraw/src/lib/shapes/frame/FrameShapeTool.ts
  packages/tldraw/src/lib/shapes/geo/GeoShapeTool.ts
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeTool.ts
  packages/tldraw/src/lib/shapes/line/LineShapeTool.ts
  packages/tldraw/src/lib/shapes/note/NoteShapeTool.ts
  packages/tldraw/src/lib/shapes/text/TextShapeTool.ts
Labels: patch

#2018 Remove topBar prop from <TldrawUi />
  apps/examples/src/examples/ZonesExample.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/Spinner.tsx
  packages/tldraw/src/lib/ui/components/Toasts.tsx
Labels: minor

#2036 [fix] Stylepanel default spacing
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui.css
Labels: patch

#2037 Restore background
  packages/editor/editor.css
  packages/editor/src/lib/hooks/useEditorComponents.tsx
  packages/tldraw/api/api.json
Labels: patch

#2023 prevent hover indicator from showing when pointer isn't over the canvas
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/hooks/useCanvasEvents.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLInstance.ts
Labels: minor

#2038 [fix] migrations for page state
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLPageState.ts
Labels: patch

#2039 Remove dot com ui styles [1/2]
  packages/tldraw/src/lib/ui.css
  packages/tlschema/api/api.json
Labels: minor

#2040 [fix] Page state migration
  packages/tlschema/src/records/TLPageState.ts
Labels: patch

#2041 Remove fixup script
  packages/tlschema/api-report.md
  packages/tlschema/src/fixup.ts
  packages/tlschema/src/index.ts
Labels: internal

#2043 [improvement] Scope `getShapeAtPoint` to rendering shapes only
  apps/examples/src/only-editor/MicroSelectTool.ts
  apps/examples/src/only-editor/MiniSelectTool.ts
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/primitives/Vec2d.ts
  packages/editor/src/lib/primitives/geometry/Circle2d.ts
  packages/editor/src/lib/primitives/geometry/Edge2d.ts
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
  packages/editor/src/lib/primitives/geometry/Polyline2d.ts
  packages/tldraw/src/lib/shapes/arrow/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingSelection.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/children/ScribbleBrushing.ts
  packages/tldraw/src/lib/tools/selection-logic/getHitShapeOnCanvasPointerDown.ts
  packages/tldraw/src/lib/tools/selection-logic/selectOnCanvasPointerUp.ts
  packages/tldraw/src/lib/tools/selection-logic/updateHoveredId.ts
  packages/tldraw/src/test/SelectTool.test.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: minor

#2053 Fix alt + shift keyboard shortcuts
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
Labels: patch

#2059 Fix newlines in text geo shapes
  apps/examples/e2e/tests/export-snapshots.spec.ts
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-leading-line-breaks-1-Mobile-Chrome-darwin.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-leading-line-breaks-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-leading-line-breaks-1-chromium-darwin.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-leading-line-breaks-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-leading-line-breaks-in-dark-mode-1-Mobile-Chrome-darwin.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-leading-line-breaks-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-leading-line-breaks-in-dark-mode-1-chromium-darwin.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-leading-line-breaks-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-trailing-line-breaks-1-Mobile-Chrome-darwin.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-trailing-line-breaks-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-trailing-line-breaks-1-chromium-darwin.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-trailing-line-breaks-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-trailing-line-breaks-in-dark-mode-1-Mobile-Chrome-darwin.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-trailing-line-breaks-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-trailing-line-breaks-in-dark-mode-1-chromium-darwin.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-trailing-line-breaks-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/test-text.spec.ts
  packages/editor/src/lib/editor/managers/TextManager.ts
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
Labels: patch

#2044 fix: proper label for opacity tooltip on hover
  packages/tldraw/src/lib/ui/components/StylePanel/StylePanel.tsx
Labels: patch

#2062 [fix] broken docs link
  packages/tlschema/api/api.json
  packages/tlschema/src/styles/StyleProp.ts
Labels: internal

#2055 Fix shape opacity when erasing
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#2064 Move example into examples folder
  apps/examples/src/examples/only-editor/MicroSelectTool.ts
  apps/examples/src/examples/only-editor/MiniBoxShape.tsx
  apps/examples/src/examples/only-editor/MiniSelectTool.ts
  apps/examples/src/examples/only-editor/OnlyEditor.tsx
  apps/examples/src/index.tsx
Labels: internal

#2066 Update VS Code extension 2.0.13
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: internal

#2067 Cache playwright browsers.
  .github/workflows/playwright.yml
Labels: tests

#2068 Fix ExplodedExample.tsx
  apps/examples/src/examples/ExplodedExample.tsx
Labels: internal

#2073 [fix] locked shape of opacity problem with eraser.pointing
  packages/tldraw/src/lib/tools/EraserTool/children/Pointing.ts
Labels: patch

#2069 [fix] Don't select locked shapes on pointer up
  packages/tldraw/src/lib/tools/selection-logic/selectOnCanvasPointerUp.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: patch

#2071 Same first page id for all editors
  packages/tldraw/src/lib/shapes/line/__snapshots__/LineShapeUtil.test.ts.snap
  packages/tlschema/src/TLStore.ts
Labels: minor

#2070 [fix] reparenting locked shapes
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/groups.test.ts
Labels: patch

#2072 Compact children when updating parents to children.
  packages/editor/src/lib/editor/derivations/parentsToChildren.ts
Labels: patch

#2074 Only upload playwright to S3 if we have the right credentials
  .github/workflows/playwright.yml
  apps/examples/e2e/tests/test-ui.spec.ts
Labels: tests

#2075 [fix] missing border on group shape when unlocked
  packages/editor/src/lib/components/ShapeIndicator.tsx
  packages/editor/src/lib/editor/shapes/group/DashedOutlineBox.tsx
  packages/editor/src/lib/editor/shapes/group/GroupShapeUtil.tsx
Labels: patch

#2076 Add data breakpoint to layout css
  packages/tldraw/src/lib/ui/TldrawUi.tsx
Labels: minor

#2078 bump nanoid
  packages/editor/package.json
  packages/store/package.json
  packages/tlschema/package.json
  public-yarn.lock
Labels: dependencies

#2081 [fix] remove findLast calls
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#2082 Fixed a bug checking translated string keys
  packages/tldraw/src/lib/ui/hooks/useTranslation/translations.ts
Labels: patch

#2083 Add offline indicator (also to top zone example)
  apps/examples/src/examples/ZonesExample.tsx
  assets/icons/icon/status-offline.svg
  assets/icons/icon/status-online.svg
  assets/translations/main.json
  packages/assets/imports.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/OfflineIndicator/OfflineIndicator.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/lib/ui/icon-types.ts
Labels: minor

#2097 fix cropped image size
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
Labels: patch

#2095 Fix not being able to upload massive images
  packages/tldraw/src/lib/utils/assets.ts
Labels: patch

#2099 move imports
  packages/tldraw/src/index.ts
Labels: patch

#2096 Add timestamp to file names
  packages/tldraw/src/lib/ui/hooks/useExportAs.ts
Labels: patch

#2092 Firefox, Touch: Fix not being able to open style dropdowns
  packages/tldraw/src/lib/ui/components/StylePanel/DoubleDropdownPicker.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DropdownPicker.tsx
Labels: patch

#2101 [fix] mobile style panel switching open / closed
  packages/tldraw/src/lib/ui/components/MobileStylePanel.tsx
  packages/tldraw/src/lib/ui/hooks/useMenuIsOpen.ts
  packages/tldraw/src/lib/ui/hooks/useOpenMenuCloser.tsx
Labels: patch

#2109 Remove (optional) from jsdocs
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/utils/reordering/reordering.ts
  packages/state/src/lib/core/HistoryBuffer.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteExcalidrawContent.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteFiles.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteTldrawContent.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteUrl.ts
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/useTranslation.tsx
Labels: documentation

#2113 fix selection fg transform
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
Labels: patch

#2122 Add meta example
  apps/examples/src/examples/MetaExample.tsx
  apps/examples/src/index.tsx
  packages/editor/api/api.json
Labels: documentation

#2102 Tighten up editor ui
  apps/examples/e2e/shared-e2e.ts
  apps/examples/e2e/tests/export-snapshots.spec.ts
  apps/examples/e2e/tests/test-shapes.spec.ts
  apps/examples/e2e/tests/test-smoke.spec.ts
  apps/examples/src/examples/end-to-end/end-to-end.tsx
  assets/icons/icon/checkbox-empty.svg
  assets/translations/main.json
  packages/editor/editor.css
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/ActionsMenu.tsx
  packages/tldraw/src/lib/ui/components/BackToContent.tsx
  packages/tldraw/src/lib/ui/components/ContextMenu.tsx
  packages/tldraw/src/lib/ui/components/DebugPanel.tsx
  packages/tldraw/src/lib/ui/components/DuplicateButton.tsx
  packages/tldraw/src/lib/ui/components/EditLinkDialog.tsx
  packages/tldraw/src/lib/ui/components/EmbedDialog.tsx
  packages/tldraw/src/lib/ui/components/FollowingIndicator.tsx
  packages/tldraw/src/lib/ui/components/HelpMenu.tsx
  packages/tldraw/src/lib/ui/components/LanguageMenu.tsx
  packages/tldraw/src/lib/ui/components/Menu.tsx
  packages/tldraw/src/lib/ui/components/MenuZone.tsx
  packages/tldraw/src/lib/ui/components/MobileStylePanel.tsx
  packages/tldraw/src/lib/ui/components/MoveToPageMenu.tsx
  packages/tldraw/src/lib/ui/components/NavigationZone/NavigationZone.tsx
  packages/tldraw/src/lib/ui/components/NavigationZone/ZoomMenu.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageItemSubmenu.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageMenu.tsx
  packages/tldraw/src/lib/ui/components/PenModeToggle.tsx
  packages/tldraw/src/lib/ui/components/RedoButton.tsx
  packages/tldraw/src/lib/ui/components/StopFollowing.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DoubleDropdownPicker.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DropdownPicker.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/StylePanel.tsx
  packages/tldraw/src/lib/ui/components/Toasts.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/ToggleToolLockedButton.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/Toolbar.tsx
  packages/tldraw/src/lib/ui/components/TrashButton.tsx
  packages/tldraw/src/lib/ui/components/UndoButton.tsx
  packages/tldraw/src/lib/ui/components/primitives/Button.tsx
  packages/tldraw/src/lib/ui/components/primitives/ButtonPicker.tsx
  packages/tldraw/src/lib/ui/components/primitives/Dialog.tsx
  packages/tldraw/src/lib/ui/components/primitives/DropdownMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/Popover.tsx
  packages/tldraw/src/lib/ui/hooks/useMenuIsOpen.ts
  packages/tldraw/src/lib/ui/hooks/useToastsProvider.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/useTranslation.tsx
Labels: minor

#2124 [fix] css for editing page title
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/PageMenu/PageMenu.tsx
Labels: patch

#2126 [fix] Move to page button / toasts styling
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/DebugPanel.tsx
  packages/tldraw/src/lib/ui/components/MoveToPageMenu.tsx
Labels: patch

#2130 [fix] button gaps
  packages/tldraw/src/lib/ui.css
Labels: patch

#2132 [android] Fix text labels and link button getting misaligned
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
Labels: patch
