Repository tldraw/tldraw, pull requests merged in 2023-08, with the labels that each got.

#1784 environment manager
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/EnvironmentManager.ts
  packages/editor/src/lib/hooks/useCoarsePointer.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/defaultStyleDefs.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageMenu.tsx
  packages/tldraw/src/lib/ui/hooks/usePrint.ts
Labels: major

#1785 SideEffectManager
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/HistoryManager.test.ts
  packages/editor/src/lib/editor/managers/HistoryManager.ts
  packages/editor/src/lib/editor/managers/SIdeEffectManager.test.ts
  packages/editor/src/lib/editor/managers/SideEffectManager.ts
  packages/store/api-report.md
  packages/store/src/lib/Store.ts
Labels: major

#1788 Custom rendering margin / don't cull selected shapes
  packages/editor/api-report.md
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/renderingShapes.test.tsx
Labels: patch

#1789 Update setter names, `setXXShapeId` rather than `setXXId`
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/shapes/frame/components/FrameLabelInput.tsx
  packages/tldraw/src/lib/shapes/geo/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/note/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/EraserTool/children/Erasing.ts
  packages/tldraw/src/lib/tools/EraserTool/children/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/SelectTool.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Crop/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Cropping.ts
  packages/tldraw/src/lib/tools/SelectTool/children/EditingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingCropHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Translating.ts
  packages/tldraw/src/lib/tools/selection-logic/updateHoveredId.ts
  packages/tldraw/src/test/Editor.test.tsx
Labels: major

#1791 [fix] CSS reload in dev
  packages/tldraw/package.json
Labels: internal

#1792 [fix] embeds switching / tldraw embed
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
  packages/tldraw/src/lib/ui/hooks/useContextMenuSchema.tsx
  packages/tldraw/src/lib/ui/hooks/useMenuSchema.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/shapes/TLEmbedShape.ts
Labels: patch

#1790 Fix text editing in page menu popover
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/Input.tsx
Labels: patch

#1793 [fix] Don't make arrows shapes to arrows
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
Labels: patch

#1795 remove yjs example
  apps/examples/package.json
  apps/examples/src/examples/UserPresenceExample.tsx
  apps/examples/src/examples/yjs/YjsExample.tsx
  apps/examples/src/examples/yjs/useYjsStore.ts
  docs/docs/collaboration.mdx
  public-yarn.lock
Labels: internal

#1797 [fix] page to screen
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/HistoryManager.test.ts
  packages/editor/src/lib/editor/managers/HistoryManager.ts
  packages/editor/src/lib/editor/types/history-types.ts
  packages/tldraw/src/test/commands/screenToPage.test.ts
  packages/tldraw/src/test/commands/updateViewportPageBounds.test.ts
Labels: patch

#1799 Rendering / cropping side-effects
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/SideEffectManager.ts
  packages/editor/src/lib/editor/shapes/group/GroupShapeUtil.tsx
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/tools/EraserTool/children/Erasing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Crop/children/Idle.ts
  packages/tldraw/src/lib/ui/components/BackToContent.tsx
  packages/tldraw/src/lib/useSideEffects.ts
  packages/tldraw/src/test/EraserTool.test.ts
  packages/tldraw/src/test/cropping.test.ts
  packages/tldraw/src/test/groups.test.ts
  packages/tldraw/src/test/renderingShapes.test.tsx
Labels: major

#1800 Cleanup page state commands
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/group/GroupShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/frame/components/FrameLabelInput.tsx
  packages/tldraw/src/lib/shapes/geo/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/note/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/EraserTool/children/Erasing.ts
  packages/tldraw/src/lib/tools/EraserTool/children/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/DragAndDropManager.ts
  packages/tldraw/src/lib/tools/SelectTool/SelectTool.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Crop/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Cropping.ts
  packages/tldraw/src/lib/tools/SelectTool/children/DraggingHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/EditingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingCropHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Translating.ts
  packages/tldraw/src/lib/tools/selection-logic/selectOnCanvasPointerUp.ts
  packages/tldraw/src/lib/tools/selection-logic/updateHoveredId.ts
  packages/tldraw/src/test/Editor.test.tsx
Labels: major

#1804 [fix] Collaborator scribble on tldraw
  packages/tldraw/src/lib/Tldraw.tsx
Labels: patch

#1806 [improvement] More selection logic
  apps/examples/src/examples/APIExample.tsx
  docs/docs/editor.mdx
  docs/docs/shapes.mdx
  packages/editor/api-report.md
  packages/editor/src/lib/components/GeometryDebuggingView.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/group/GroupShapeUtil.tsx
  packages/editor/src/lib/editor/tools/BaseBoxShapeTool/children/Pointing.ts
  packages/editor/src/lib/primitives/geometry/Group2d.ts
  packages/state/src/lib/core/Atom.ts
  packages/state/src/lib/core/Computed.ts
  packages/state/src/lib/core/__tests__/fuzz.tlstate.test.ts
  packages/state/src/lib/core/capture.ts
  packages/state/src/lib/core/transactions.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeTool.test.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/components/ArrowTextLabel.tsx
  packages/tldraw/src/lib/shapes/arrow/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/shapes/text/toolStates/Idle.ts
  packages/tldraw/src/lib/tools/EraserTool/children/Erasing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Brushing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Crop/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/EditingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/children/ScribbleBrushing.ts
  packages/tldraw/src/lib/tools/selection-logic/getHitShapeOnCanvasPointerDown.ts
  packages/tldraw/src/lib/tools/selection-logic/selectOnCanvasPointerUp.ts
  packages/tldraw/src/lib/tools/selection-logic/selectOnDoubleClick.tsx
  packages/tldraw/src/lib/ui/components/ContextMenu.tsx
  packages/tldraw/src/lib/ui/components/DebugPanel.tsx
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteExcalidrawContent.ts
  packages/tldraw/src/lib/useSideEffects.ts
  packages/tldraw/src/test/Editor.test.tsx
  packages/tldraw/src/test/EraserTool.test.ts
  packages/tldraw/src/test/SelectTool.test.ts
  packages/tldraw/src/test/arrows-megabus.test.ts
  packages/tldraw/src/test/cleanup.test.ts
  packages/tldraw/src/test/commands/alignShapes.test.tsx
  packages/tldraw/src/test/commands/clipboard.test.ts
  packages/tldraw/src/test/commands/distributeShapes.test.ts
  packages/tldraw/src/test/commands/lockShapes.test.ts
  packages/tldraw/src/test/commands/nudge.test.ts
  packages/tldraw/src/test/commands/setSelectedIds.test.ts
  packages/tldraw/src/test/commands/stackShapes.test.ts
  packages/tldraw/src/test/commands/stretch.test.tsx
  packages/tldraw/src/test/commands/zoomToSelection.test.ts
  packages/tldraw/src/test/getShapeAtPoint.test.ts
  packages/tldraw/src/test/groups.test.ts
  packages/tldraw/src/test/select.test.tsx
  packages/tldraw/src/test/selection-omnibus.test.ts
  packages/tldraw/src/test/styles2.test.tsx
Labels: minor

#1808 [fix] Sticky text content / hovered shapes
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/children/EditingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Translating.ts
  packages/tldraw/src/test/SelectTool.test.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
  packages/tldraw/src/test/translating.test.ts
Labels: patch

#1811 Add next cache to clean command
  scripts/clean.sh
Labels: internal

#1814 [fix] style changes
  apps/examples/src/examples/APIExample.tsx
  apps/examples/src/examples/CustomStylesExample/FilterStyleUi.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/ui/components/StylePanel/StylePanel.tsx
  packages/tldraw/src/test/Editor.test.tsx
  packages/tldraw/src/test/commands/createShapes.test.ts
  packages/tldraw/src/test/commands/getSvg.test.ts
  packages/tldraw/src/test/frames.test.ts
  packages/tldraw/src/test/groups.test.ts
  packages/tldraw/src/test/styles2.test.tsx
Labels: major

#1818 [fix] bug with eventemitter3 default export
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#1820 [feature] unlock all action
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
  packages/tldraw/src/lib/ui/hooks/useEventsProvider.tsx
  packages/tldraw/src/lib/ui/hooks/useMenuSchema.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: minor

#1821 [fix] editing video shapes
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: patch

#1822 [fix] Replace `findLast` for browser compat
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#1819 [fix] snapping bug
  packages/editor/src/lib/editor/managers/SnapManager.ts
Labels: patch

#1823 [fix] remove CSS radius calculations
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/components/default-components/DefaultHandle.tsx
  packages/editor/src/lib/hooks/useCoarsePointer.ts
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
Labels: patch

#1825 [fix] Line shape rendering
  packages/editor/src/lib/primitives/geometry/CubicBezier2d.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/components/getLineSvg.ts
  packages/tldraw/src/lib/shapes/line/components/svg.ts
Labels: patch

#1826 [fix] text editing outline when scaled
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
Labels: patch

#1824 [feature] Asset props
  apps/examples/src/examples/AssetOptionsExample.tsx
  apps/examples/src/examples/HostedImagesExample.tsx
  apps/examples/src/index.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/useRegisterExternalContentHandlers.ts
  packages/tldraw/src/lib/utils/assets.ts
Labels: minor

#1827 Add className as prop to Canvas
  packages/editor/api-report.md
  packages/editor/src/lib/components/Canvas.tsx
Labels: minor

#1829 export asset stuff
  apps/examples/src/examples/HostedImagesExample.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/useRegisterExternalContentHandlers.ts
  packages/tldraw/src/lib/utils/assets.ts
Labels: minor

#1831 fix typo
  docs/docs/editor.mdx
Labels: internal

#1830 Fix broken link in docs
  docs/getting-started/usage.mdx
Labels: documentation

#1832 Allow setting `user` as a prop
  packages/editor/api-report.md
  packages/editor/src/lib/TldrawEditor.tsx
Labels: patch
