Repository tldraw/tldraw, pull requests merged in 2023-06, with the labels that each got.

#1418 [2/3] renderer changes to support "sandwich mode" highlighting
  packages/editor/api-report.md
  packages/editor/src/lib/app/App.ts
  packages/editor/src/lib/app/shapeutils/TLFrameUtil/TLFrameUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLHighlightUtil/TLHighlightUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLShapeUtil.ts
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/test/commands/__snapshots__/getSvg.test.ts.snap
  packages/editor/src/lib/test/commands/getSvg.test.ts
  packages/editor/src/lib/test/commands/renderingShapes.test.tsx
  packages/primitives/src/lib/Box2d.ts
Labels: minor

#1496 replace console.log with nicelog
  .eslintrc.js
  apps/docs/content/docs/api.mdx
  apps/docs/package.json
  apps/docs/scripts/generateContent.ts
  apps/examples/e2e/tests/test-shapes.spec.ts
  apps/vscode/extension/src/TldrawDocument.ts
  apps/vscode/extension/src/TldrawEditorProvider.ts
  apps/vscode/extension/src/WebViewMessageHandler.ts
  apps/vscode/extension/src/extension.ts
  apps/vscode/extension/src/file.ts
  apps/vscode/extension/src/utils.ts
  packages/primitives/src/lib/freehand/getStrokeOutlinePoints.ts
  scripts/api-check.ts
  scripts/check-scripts.ts
  scripts/lib/exec.ts
  scripts/lib/file.ts
  scripts/lib/nicelog.ts
  scripts/lib/publishing.ts
  scripts/publish-canary.ts
  scripts/publish-new.ts
  scripts/refresh-assets.ts
  scripts/typecheck.ts
Labels: internal

#1497 VS Code version bump, changelog.
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: patch

#1340 Add support for project names
  apps/examples/src/15-custom-zones/ZonesExample.tsx
  apps/examples/src/index.tsx
  assets/translations/main.json
  packages/editor/api-report.md
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/app/App.ts
  packages/editor/src/lib/config/createTLStore.ts
  packages/editor/src/lib/hooks/useTLStore.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLDocument.ts
  packages/ui/api-report.md
  packages/ui/src/lib/TldrawUi.tsx
  packages/ui/src/lib/components/MenuZone.tsx
  packages/ui/src/lib/components/Toolbar/Toolbar.tsx
  packages/ui/src/lib/components/primitives/Input.tsx
  packages/ui/src/lib/hooks/useTranslation/TLTranslationKey.ts
  packages/ui/src/lib/hooks/useTranslation/defaultTranslation.ts
  packages/ui/ui.css
Labels: major

#1498 [fix] eslint from brivate
  apps/vscode/editor/package.json
  apps/vscode/extension/package.json
  scripts/check-scripts.ts
Labels: internal

#1499 move v1 migration code into file-format
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/file-format/api-report.md
  packages/file-format/package.json
  packages/file-format/src/index.ts
  packages/file-format/src/lib/buildFromV1Document.ts
  packages/file-format/src/lib/file.ts
  packages/file-format/tsconfig.json
  public-yarn.lock
Labels: minor

#1501 Revert 09c36781 & tweak linting
  .prettierignore
  apps/vscode/editor/package.json
  apps/vscode/editor/tsconfig.json
  apps/vscode/extension/package.json
  apps/vscode/extension/tsconfig.json
  public-yarn.lock
  scripts/check-scripts.ts
  scripts/lint.ts
  scripts/package.json
Labels: internal

#1502 Filter out unused assets.
  packages/file-format/src/lib/file.ts
Labels: patch

#1506 TLSchema readme
  packages/tlschema/README.md
Labels: documentation

#1508 Rename tlvalidate to validate
  apps/docs/package.json
  packages/editor/package.json
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/tsconfig.json
  packages/file-format/package.json
  packages/file-format/src/lib/file.ts
  packages/file-format/tsconfig.json
  packages/tlschema/api-report.md
  packages/tlschema/package.json
  packages/tlschema/src/assets/TLBookmarkAsset.ts
  packages/tlschema/src/assets/TLImageAsset.ts
  packages/tlschema/src/assets/TLVideoAsset.ts
  packages/tlschema/src/assets/asset-validation.ts
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/records/TLAsset.ts
  packages/tlschema/src/records/TLCamera.ts
  packages/tlschema/src/records/TLDocument.ts
  packages/tlschema/src/records/TLInstance.ts
  packages/tlschema/src/records/TLInstancePageState.ts
  packages/tlschema/src/records/TLInstancePresence.ts
  packages/tlschema/src/records/TLPage.ts
  packages/tlschema/src/records/TLPointer.ts
  packages/tlschema/src/records/TLUserDocument.ts
  packages/tlschema/src/shapes/TLArrowShape.ts
  packages/tlschema/src/shapes/TLBookmarkShape.ts
  packages/tlschema/src/shapes/TLDrawShape.ts
  packages/tlschema/src/shapes/TLEmbedShape.ts
  packages/tlschema/src/shapes/TLFrameShape.ts
  packages/tlschema/src/shapes/TLGeoShape.ts
  packages/tlschema/src/shapes/TLGroupShape.ts
  packages/tlschema/src/shapes/TLHighlightShape.ts
  packages/tlschema/src/shapes/TLIconShape.ts
  packages/tlschema/src/shapes/TLImageShape.ts
  packages/tlschema/src/shapes/TLLineShape.ts
  packages/tlschema/src/shapes/TLNoteShape.ts
  packages/tlschema/src/shapes/TLTextShape.ts
  packages/tlschema/src/shapes/TLVideoShape.ts
  packages/tlschema/src/shapes/shape-validation.ts
  packages/tlschema/src/ui-types.ts
  packages/tlschema/src/validation.ts
  packages/tlschema/tsconfig.json
  packages/validate/CHANGELOG.md
  packages/validate/LICENSE
  packages/validate/README.md
  packages/validate/api-extractor.json
  packages/validate/api-report.md
  packages/validate/package.json
  packages/validate/src/index.ts
  packages/validate/src/lib/validation.ts
  packages/validate/src/test/validation.test.ts
  packages/validate/tsconfig.json
  public-yarn.lock
Labels: major

#1512 restore styles sets exports
  packages/tlschema/api-report.md
  packages/tlschema/src/index.ts
Labels: internal

#1520 Simplify static cursors
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/lib/app/shapeutils/ShapeUtil.ts
  packages/editor/src/lib/hooks/useCursor.ts
  packages/ui/src/lib/components/DebugPanel.tsx
Labels: internal

#1522 Update examples links to point to examples folder.
  apps/docs/content/docs/api.mdx
  apps/docs/content/docs/persistence.mdx
  apps/docs/content/docs/shapes.mdx
  apps/docs/content/docs/tools.mdx
  apps/docs/content/docs/user-interface.mdx
Labels: documentation

#1524 Reinstate auto
  package.json
  public-yarn.lock
Labels: internal

#1515 Lokalise: Translations update
  assets/translations/gl.json
  assets/translations/it.json
  assets/translations/ro.json
  assets/translations/ru.json
  assets/translations/uk.json
  assets/translations/zh-tw.json
Labels: translations, patch

#1523 ensure that fixed points stay fixed
  packages/editor/src/lib/app/shapeutils/DrawShapeUtil/DrawShapeUtil.tsx
  packages/editor/src/lib/app/tools/DrawShapeTool/children/Drawing.ts
  packages/editor/src/lib/test/tools/__snapshots__/resizing.test.ts.snap
  packages/primitives/api-report.md
  packages/primitives/src/index.ts
  packages/primitives/src/lib/utils.ts
Labels: patch

#1531 Fix being able to undo following
  packages/editor/src/lib/app/Editor.ts
Labels: patch

#1535 [fix] control click on mac
  packages/editor/src/lib/app/Editor.ts
  packages/editor/src/lib/app/tools/SelectTool/children/Idle.ts
Labels: patch

#1536 scale exported canvases when they reach the browsers max size
  packages/editor/package.json
  packages/editor/src/lib/utils/export.ts
  packages/editor/src/lib/utils/getBrowserCanvasMaxSize.tsx
  public-yarn.lock
Labels: patch

#1537 [fix] Shift key code / nudge
  packages/editor/src/lib/app/Editor.ts
  packages/editor/src/lib/app/tools/SelectTool/children/Crop/children/Idle.ts
  packages/editor/src/lib/app/tools/SelectTool/children/Idle.ts
Labels: patch

#1538 Use `"Toggle locked"`
  assets/translations/main.json
  packages/ui/src/lib/hooks/useTranslation/defaultTranslation.ts
Labels: patch

#1539 [feature] add vertical align to note shape
  packages/editor/api-report.md
  packages/editor/src/lib/app/shapeutils/ArrowShapeUtil/ArrowShapeUtil.tsx
  packages/editor/src/lib/app/shapeutils/GeoShapeUtil/GeoShapeUtil.tsx
  packages/editor/src/lib/app/shapeutils/NoteShapeUtil/NoteShapeUtil.tsx
  packages/editor/src/lib/app/shapeutils/shared/getTextLabelSvgElement.ts
  packages/editor/src/lib/app/tools/GeoShapeTool/GeoShapeTool.ts
  packages/editor/src/lib/app/tools/NoteShapeTool/NoteShapeTool.ts
  packages/editor/src/lib/test/commands/__snapshots__/getSvg.test.ts.snap
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/shapes/TLNoteShape.ts
Labels: minor

#1547 update editor tests
  packages/editor/src/lib/config/defaultTools.ts
  packages/editor/src/lib/editor/tools/ArrowShapeTool/ArrowShapeTool.test.ts
  packages/editor/src/lib/editor/tools/DrawShapeTool/DrawShapeTool.test.ts
  packages/editor/src/lib/editor/tools/EraserTool/EraserTool.test.ts
  packages/editor/src/lib/editor/tools/EraserTool/EraserTool.ts
  packages/editor/src/lib/editor/tools/EraserTool/children/Erasing.ts
  packages/editor/src/lib/editor/tools/EraserTool/children/Idle.ts
  packages/editor/src/lib/editor/tools/EraserTool/children/Pointing.ts
  packages/editor/src/lib/editor/tools/FrameShapeTool/FrameShapeTool.test.ts
  packages/editor/src/lib/editor/tools/GeoShapeTool/GeoShapeTool.test.ts
  packages/editor/src/lib/editor/tools/HandTool/HandTool.test.ts
  packages/editor/src/lib/editor/tools/HighlightShapeTool/HighlightShapeTool.test.ts
  packages/editor/src/lib/editor/tools/LaserTool/LaserTool.test.ts
  packages/editor/src/lib/editor/tools/LineShapeTool/LineShapeTool.test.ts
  packages/editor/src/lib/editor/tools/NoteShapeTool/NoteShapeTool.test.ts
  packages/editor/src/lib/editor/tools/SelectTool/SelectTool.test.ts
  packages/editor/src/lib/editor/tools/TextShapeTool/TextShapeTool.test.ts
  packages/editor/src/lib/editor/tools/ZoomTool/ZoomTool.test.ts
  packages/editor/src/lib/test/tools/bookmark-shapes.ts
  packages/editor/src/lib/test/tools/groups.test.ts
Labels: tests

#1548 Use unpkg as a default for serving assets.
  apps/docs/content/docs/installation.mdx
  apps/docs/content/docs/introduction.mdx
  apps/docs/content/docs/usage.mdx
  packages/editor/src/lib/assetUrls.ts
  packages/editor/src/version.ts
  packages/ui/src/lib/assetUrls.ts
  packages/ui/src/version.ts
  scripts/lib/publishing.ts
Labels: major

#1554 [Docs] Change some internal methods to public
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
Labels: documentation

#1553 [Docs] Change some editor properties to methods
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
Labels: documentation

#1555 Misc sync fixes
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/test/commands/setCurrentPage.test.ts
Labels: patch

#1556 Add contributor license agreement.
  CONTRIBUTING.md
  apps/docs/content/community/contributing.mdx
  apps/docs/pages/cla.tsx
Labels: internal

#1550 `ExternalContentManager` for handling external content (files, images, etc)
  apps/vscode/editor/src/app.tsx
  apps/vscode/editor/src/utils/bookmarks.ts
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/ExternalContentManager.ts
  packages/editor/src/lib/editor/shapeutils/BookmarkShapeUtil/BookmarkShapeUtil.tsx
  packages/editor/src/lib/editor/tools/SelectTool/children/Idle.ts
  packages/editor/src/lib/hooks/useCanvasEvents.ts
  packages/editor/src/lib/test/TldrawEditor.test.tsx
  packages/editor/src/lib/utils/assets.ts
  packages/file-format/src/lib/buildFromV1Document.ts
  packages/tldraw/src/lib/Tldraw.test.tsx
  packages/ui/src/lib/TldrawUiContextProvider.tsx
  packages/ui/src/lib/components/EmbedDialog.tsx
  packages/ui/src/lib/hooks/clipboard/pasteFiles.ts
  packages/ui/src/lib/hooks/clipboard/pastePlainText.ts
  packages/ui/src/lib/hooks/clipboard/pasteSvgText.ts
  packages/ui/src/lib/hooks/clipboard/pasteUrl.ts
  packages/ui/src/lib/hooks/useClipboardEvents.ts
  packages/ui/src/lib/hooks/useInsertMedia.ts
Labels: major

#1559 More misc sync fixes
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapeutils/ArrowShapeUtil/arrow/shared.ts
Labels: patch

#1557 Asset improvements
  apps/docs/content/docs/assets.mdx
  apps/docs/content/docs/introduction.mdx
  apps/docs/content/docs/usage.mdx
  packages/assets/imports.d.ts
  packages/assets/imports.js
  packages/assets/package.json
  packages/assets/selfHosted.d.ts
  packages/assets/selfHosted.js
  packages/assets/tsconfig.json
  packages/assets/types.d.ts
  packages/assets/urls.d.ts
  packages/assets/urls.js
  packages/assets/utils.d.ts
  packages/assets/utils.js
  packages/editor/api-report.md
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/assetUrls.ts
  packages/ui/api-report.md
  packages/ui/src/lib/TldrawUiContextProvider.tsx
  packages/ui/src/lib/assetUrls.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/types.ts
  scripts/refresh-assets.ts
Labels: patch

#1560 yjs example
  apps/examples/package.json
  apps/examples/src/index.tsx
  apps/examples/src/yjs/YjsExample.tsx
  apps/examples/src/yjs/useYjsStore.ts
  apps/examples/src/yjs/y.ts
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/config/createTLStore.ts
  public-yarn.lock
Labels: internal

#1486 use the right TLEventHandlers
  packages/editor/src/lib/editor/tools/SelectTool/children/EditingShape.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/Idle.ts
  packages/editor/src/lib/editor/tools/TextShapeTool/children/Idle.ts
Labels: internal

#1570 Update pr template
  .github/pull_request_template.md
Labels: internal

#1572 Lokalise: Translations update
  assets/translations/it.json
  assets/translations/ru.json
  assets/translations/uk.json
Labels: translations, patch

#1564 offset drop point by editor client rect
  packages/editor/src/lib/hooks/useCanvasEvents.ts
Labels: patch

#1571 Add anchor targets to our headings.
  apps/docs/components/mdx-components/generic.tsx
Labels: documentation

#1568 [improvement] bookmark shape logic
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/geo/GeoShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/shared/HyperlinkButton.tsx
  packages/editor/src/lib/test/tools/bookmark-shapes.ts
  packages/editor/src/lib/utils/data.ts
  packages/ui/src/lib/components/EditLinkDialog.tsx
  packages/ui/src/lib/hooks/useActions.tsx
  packages/ui/src/lib/hooks/useContextMenuSchema.tsx
Labels: internal

#1578 [fix] embeds
  packages/editor/src/lib/editor/managers/ExternalContentManager.ts
  packages/ui/src/lib/hooks/useActions.tsx
Labels: patch

#1565 fix: properly remove awareness from store
  apps/examples/src/yjs/y.ts
Labels: documentation

#1579 Add optional generic to `updateShapes` / `createShapes`
  apps/examples/src/2-api/APIExample.tsx
  apps/examples/src/8-error-boundary/ErrorBoundaryExample.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/derivations/arrowBindingsIndex.test.tsx
  packages/editor/src/lib/editor/managers/ExternalContentManager.ts
  packages/editor/src/lib/editor/shapes/arrow/ArrowShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/arrow/toolStates/Pointing.ts
  packages/editor/src/lib/editor/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/draw/toolStates/Drawing.ts
  packages/editor/src/lib/editor/shapes/geo/toolStates/Pointing.ts
  packages/editor/src/lib/editor/shapes/line/toolStates/Pointing.ts
  packages/editor/src/lib/editor/shapes/shared/useEditableText.ts
  packages/editor/src/lib/editor/shapes/text/toolStates/Pointing.ts
  packages/editor/src/lib/editor/tools/BaseBoxShapeTool/children/Pointing.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/Crop/children/Idle.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/Idle.ts
  packages/editor/src/lib/test/commands/createShapes.test.ts
  packages/editor/src/lib/test/commands/updateShapes.test.ts
  packages/file-format/src/lib/buildFromV1Document.ts
Labels: minor

#1582 add presence to yjs example
  apps/examples/src/yjs/YjsExample.tsx
  apps/examples/src/yjs/useYjsStore.ts
  apps/examples/src/yjs/y.ts
Labels: documentation

#1587 [fix] Remove group shape export backgrounds
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#1583 update exports for user presence
  apps/examples/src/yjs/useYjsStore.ts
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/createPresenceStateDerivation.ts
Labels: patch

#1591 remove `ShapeUtil.point`
  packages/editor/api-report.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
Labels: major

#1552 Make sure loading screens use dark mode user preference.
  assets/translations/fa.json
  packages/editor/editor.css
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/DefaultSpinner.tsx
Labels: patch

#1592 Change app to editor in docs
  apps/docs/content/docs/editor.mdx
Labels: documentation

#1589 [refactor] snapping
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/SnapManager.ts
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/editor/src/lib/editor/shapes/arrow/ArrowShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/group/GroupShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/line/LineShapeUtil.tsx
  packages/editor/src/lib/editor/tools/SelectTool/children/DraggingHandle.ts
  packages/editor/src/lib/test/tools/translating.test.ts
  packages/primitives/src/lib/CubicSegment2d.test.ts
  packages/primitives/src/lib/CubicSegment2d.ts
  packages/primitives/src/lib/LineSegment2d.ts
Labels: patch

#1593 [docs] Add barebones note about translations
  apps/docs/content/community/translations.mdx
Labels: documentation

#1487 (1/2) Cursor Chat - Presence
  apps/examples/src/11-user-presence/UserPresenceExample.tsx
  assets/translations/main.json
  packages/editor/editor.css
  packages/editor/src/lib/components/DefaultCursor.tsx
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/createPresenceStateDerivation.ts
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLInstance.ts
  packages/tlschema/src/records/TLPresence.ts
  packages/ui/api-report.md
  packages/ui/src/lib/hooks/useEventsProvider.tsx
  packages/ui/src/lib/hooks/useTranslation/TLUiTranslationKey.ts
  packages/ui/src/lib/hooks/useTranslation/defaultTranslation.ts
  packages/ui/ui.css
Labels: minor

#1594 Explicit shape type checks
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/components/SelectionFg.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/derivations/arrowBindingsIndex.test.tsx
  packages/editor/src/lib/editor/derivations/arrowBindingsIndex.ts
  packages/editor/src/lib/editor/shapes/draw/toolStates/Drawing.ts
  packages/editor/src/lib/editor/shapes/embed/EmbedShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/frame/FrameShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/geo/toolStates/Idle.ts
  packages/editor/src/lib/editor/shapes/group/GroupShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/text/toolStates/Idle.ts
  packages/editor/src/lib/editor/tools/EraserTool/children/Erasing.ts
  packages/editor/src/lib/editor/tools/EraserTool/children/Pointing.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/Brushing.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/Idle.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/PointingShape.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/Resizing.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/ScribbleBrushing.ts
  packages/editor/src/lib/test/duplicate.test.ts
  packages/editor/src/lib/test/tools/translating.test.ts
  packages/editor/src/lib/utils/export.ts
  packages/ui/src/lib/hooks/useActions.tsx
  packages/ui/src/lib/hooks/useOnlyFlippableShape.ts
Labels: internal

#1596 Remove `@tldraw/utils` from the docs site
  apps/docs/package.json
Labels: documentation

#1525 (1/2) Timeout collaborator cursors
  packages/editor/api-report.md
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLInstance.ts
Labels: minor

#1600 Tidy up
  packages/editor/api-report.md
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/derivations/shapeIdsInCurrentPage.test.ts
  packages/editor/src/lib/editor/derivations/shapeIdsInCurrentPage.ts
  packages/editor/src/lib/editor/managers/CameraManager.ts
  packages/editor/src/lib/editor/managers/SnapManager.ts
  packages/editor/src/lib/editor/shapes/line/LineShapeUtil.test.ts
  packages/editor/src/lib/editor/tools/SelectTool/SelectTool.test.ts
  packages/editor/src/lib/hooks/useZoomCss.ts
  packages/editor/src/lib/test/TestEditor.ts
  packages/editor/src/lib/test/commands/createShapes.test.ts
  packages/editor/src/lib/test/commands/moveShapesToPage.test.ts
  packages/editor/src/lib/test/commands/paste.test.ts
  packages/editor/src/lib/test/commands/renderingShapes.test.tsx
  packages/editor/src/lib/test/tools/translating.test.ts
  packages/ui/src/lib/components/NavigationZone/Minimap.tsx
  packages/ui/src/lib/components/NavigationZone/ZoomMenu.tsx
  packages/ui/src/lib/hooks/useContextMenuSchema.tsx
  packages/ui/src/lib/hooks/useCopyAs.ts
  packages/ui/src/lib/hooks/useExportAs.ts
  packages/ui/src/lib/hooks/useMenuSchema.tsx
Labels: major

#1602 [fix] camera culling
  packages/editor/api-report.md
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/CameraManager.ts
Labels: major

#1603 [fix] yjs presence
  apps/examples/src/yjs/YjsExample.tsx
  apps/examples/src/yjs/useYjsStore.ts
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/createPresenceStateDerivation.ts
Labels: minor

#1607 tldraw.css
  .gitignore
  apps/docs/content/docs/collaboration.mdx
  apps/docs/content/docs/installation.mdx
  apps/docs/content/docs/introduction.mdx
  apps/docs/content/docs/usage.mdx
  apps/docs/styles/globals.css
  apps/examples/src/1-basic/BasicExample.tsx
  apps/examples/src/10-custom-components/CustomComponentsExample.tsx
  apps/examples/src/11-user-presence/UserPresenceExample.tsx
  apps/examples/src/12-ui-events/UiEventsExample.tsx
  apps/examples/src/13-store-events/StoreEventsExample.tsx
  apps/examples/src/14-persistence/PersistenceExample.tsx
  apps/examples/src/15-custom-zones/ZonesExample.tsx
  apps/examples/src/16-custom-styles/CustomStylesExample.tsx
  apps/examples/src/2-api/APIExample.tsx
  apps/examples/src/3-custom-config/CustomConfigExample.tsx
  apps/examples/src/4-custom-ui/CustomUiExample.tsx
  apps/examples/src/5-exploded/ExplodedExample.tsx
  apps/examples/src/6-scroll/ScrollExample.tsx
  apps/examples/src/7-multiple/MultipleExample.tsx
  apps/examples/src/8-error-boundary/ErrorBoundaryExample.tsx
  apps/examples/src/9-hide-ui/HideUiExample.tsx
  apps/examples/src/end-to-end/end-to-end.tsx
  apps/examples/src/yjs/YjsExample.tsx
  packages/editor/editor.css
  packages/tldraw/package.json
  packages/tldraw/scripts/copy-css-files.mjs
  packages/ui/ui.css
Labels: major

#1609 Rename `ShapeUtil.render` -> `ShapeUtil.component`
  apps/examples/src/16-custom-styles/CardShape.tsx
  apps/examples/src/3-custom-config/CardShape.tsx
  apps/examples/src/8-error-boundary/ErrorShape.ts
  packages/editor/api-report.md
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/editor/src/lib/editor/shapes/arrow/ArrowShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/draw/DrawShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/embed/EmbedShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/frame/FrameShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/geo/GeoShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/group/GroupShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/highlight/HighlightShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/image/ImageShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/line/LineShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/note/NoteShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/text/TextShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/video/VideoShapeUtil.tsx
  packages/editor/src/lib/test/Editor.test.tsx
  packages/editor/src/lib/test/TldrawEditor.test.tsx
  packages/editor/src/lib/test/tools/translating.test.ts
Labels: major

#1610 Make resizeBox a regular function
  packages/editor/src/lib/editor/shapes/shared/resizeBox.ts
Labels: minor

#1612 Remove on drop override
  packages/editor/api-report.md
  packages/editor/src/lib/components/Canvas.tsx
Labels: major

#1613 Update dependencies
  .prettierrc
  apps/docs/package.json
  apps/examples/package.json
  apps/vscode/README.md
  apps/vscode/editor/package.json
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
  config/package.json
  package.json
  packages/assets/api-report.md
  packages/editor/package.json
  packages/polyfills/api-report.md
  packages/tldraw/api-report.md
  packages/tldraw/package.json
  packages/ui/api-report.md
  packages/ui/package.json
  public-yarn.lock
  scripts/package.json
Labels: dependencies

#1615 [fix] tldraw api report
  packages/tldraw/src/index.ts
Labels: patch

#1616 [fix] tldraw file drop
  packages/editor/src/lib/hooks/useCanvasEvents.ts
Labels: patch

#1619 [docs] Simplify paths for uncategorised pages
  apps/docs/next.config.js
  apps/docs/pages/[sectionId]/[childId]/[articleId].tsx
  apps/docs/pages/[sectionId]/[childId]/index.tsx
Labels: documentation

#1618 Lokalise: Translations update
  assets/translations/zh-cn.json
Labels: translations, patch

#1621 [docs] Tighten up Introduction page
  apps/docs/content/docs/introduction.mdx
Labels: documentation

#1622 [docs] Tighten up Editor page introduction
  apps/docs/content/docs/editor.mdx
Labels: documentation

#1625 [fix] react component runaways, error boundaries
  apps/examples/src/8-error-boundary/ErrorBoundaryExample.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/DefaultShapeErrorFallback.tsx
  packages/editor/src/lib/components/ErrorBoundary.tsx
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/components/ShapeIndicator.tsx
  packages/editor/src/lib/hooks/useEditorComponents.tsx
  packages/editor/src/lib/test/TldrawEditor.test.tsx
  packages/ui/src/lib/components/Toolbar/Toolbar.tsx
  packages/ui/src/lib/components/primitives/Slider.tsx
Labels: major

#1624 [docs] Tighten up wording & structure of Usage page
  apps/docs/content/docs/usage.mdx
Labels: documentation

#1630 [docs] Fix wrong cursor when hovering buttons
  apps/docs/styles/globals.css
Labels: documentation

#1626 [docs] Separate some pages out of the Docs section
  apps/docs/components/Breadcrumb.tsx
  apps/docs/components/Sidebar.tsx
  apps/docs/content/getting-started/installation.mdx
  apps/docs/content/getting-started/introduction.mdx
  apps/docs/content/getting-started/usage.mdx
  apps/docs/content/sections.json
  apps/docs/next.config.js
  apps/docs/pages/[sectionId]/index.tsx
  apps/docs/utils/getSidebarContentList.ts
Labels: documentation

#1633 [docs] Add feedback when you search
  apps/docs/components/Search.tsx
  apps/docs/styles/globals.css
Labels: documentation

#1632 [docs] Allow sidebar to be scrolled on short screens
  apps/docs/styles/globals.css
Labels: documentation

#1643 remove docs (again)
  apps/docs/components/Breadcrumb.tsx
  apps/docs/components/Search.tsx
  apps/docs/components/Sidebar.tsx
  apps/docs/content/getting-started/installation.mdx
  apps/docs/content/getting-started/introduction.mdx
  apps/docs/content/getting-started/usage.mdx
  apps/docs/content/sections.json
  apps/docs/next.config.js
  apps/docs/pages/[sectionId]/index.tsx
  apps/docs/styles/globals.css
  apps/docs/utils/getSidebarContentList.ts
Labels: documentation

#1639 Fix SVG cursors not being used
  packages/editor/editor.css
Labels: patch

#1647 docs: remove not accepting contributions notice
  README.md
Labels: documentation

#1636 Styles API follow-ups
  apps/examples/e2e/shared-e2e.ts
  apps/examples/e2e/tests/export-snapshots.spec.ts
  apps/examples/package.json
  apps/examples/src/15-custom-zones/ZonesExample.tsx
  apps/examples/src/16-custom-styles/CardShape.tsx
  apps/examples/src/3-custom-config/CardShape/CardShapeUtil.tsx
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/setupTests.js
  packages/editor/src/index.ts
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/components/DefaultErrorFallback.tsx
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/editor/src/lib/editor/shapes/arrow/ArrowShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/draw/DrawShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/frame/FrameShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/geo/GeoShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/geo/components/DashStyleEllipse.tsx
  packages/editor/src/lib/editor/shapes/geo/components/DashStyleOval.tsx
  packages/editor/src/lib/editor/shapes/geo/components/DashStylePolygon.tsx
  packages/editor/src/lib/editor/shapes/geo/components/DrawStyleEllipse.tsx
  packages/editor/src/lib/editor/shapes/geo/components/DrawStylePolygon.tsx
  packages/editor/src/lib/editor/shapes/geo/components/SolidStyleEllipse.tsx
  packages/editor/src/lib/editor/shapes/geo/components/SolidStyleOval.tsx
  packages/editor/src/lib/editor/shapes/geo/components/SolidStylePolygon.tsx
  packages/editor/src/lib/editor/shapes/highlight/HighlightShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/line/LineShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/note/NoteShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/shared/ShapeFill.tsx
  packages/editor/src/lib/editor/shapes/shared/SvgExportContext.tsx
  packages/editor/src/lib/editor/shapes/shared/TLExportColors.ts
  packages/editor/src/lib/editor/shapes/shared/TextLabel.tsx
  packages/editor/src/lib/editor/shapes/shared/defaultStyleDefs.tsx
  packages/editor/src/lib/editor/shapes/shared/useColorSpace.tsx
  packages/editor/src/lib/editor/shapes/text/TextShapeUtil.tsx
  packages/editor/src/lib/hooks/usePattern.tsx
  packages/editor/src/lib/test/commands/__snapshots__/getSvg.test.ts.snap
  packages/editor/src/lib/test/commands/getSvg.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/index.ts
  packages/tlschema/src/styles/TLColorStyle.ts
  packages/tlschema/src/styles/TLFontStyle.ts
  packages/ui/src/lib/components/MobileStylePanel.tsx
  packages/ui/src/lib/components/primitives/ButtonPicker.tsx
  public-yarn.lock
Labels: minor

#1641 Styles API docs
  apps/examples/src/3-custom-config/CardShape/card-shape-props.ts
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/utils/SharedStylesMap.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/styles/StyleProp.ts
  scripts/lib/docs/docs-utils.ts
  scripts/lib/docs/generateApiContent.ts
  scripts/lib/docs/getApiMarkdown.ts
Labels: documentation

#1649 Fix text shapes not having colour
  packages/editor/src/lib/editor/shapes/text/TextShapeUtil.tsx
Labels: patch

#1653 [docs] Remove embeds page
  docs/community/embeds.mdx
Labels: documentation

#1652 (1/2) [docs] Restore some missing changes
  docs/getting-started/installation.mdx
  docs/getting-started/introduction.mdx
  docs/getting-started/usage.mdx
  docs/sections.json
Labels: documentation

#1654 (2/2) [docs] Fix links to API.
  docs/docs/editor.mdx
Labels: documentation

#1651 [fix] remove docs scripts
  scripts/lib/docs/docs-types.ts
  scripts/lib/docs/docs-utils.ts
  scripts/lib/docs/generate-on-reload.ts
  scripts/lib/docs/generateApiContent.ts
  scripts/lib/docs/generateContent.ts
  scripts/lib/docs/generateSection.ts
  scripts/lib/docs/getApiMarkdown.ts
  scripts/lib/docs/index.ts
Labels: documentation

#1655 [fix] pen mode touches
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#1659 [tweak] migrate store snapshot arguments
  packages/editor/src/lib/utils/sync/TLLocalSyncClient.ts
  packages/file-format/src/lib/file.ts
  packages/store/api-report.md
  packages/store/src/lib/Store.ts
  packages/store/src/lib/StoreSchema.ts
  packages/store/src/lib/test/migrate.test.ts
Labels: major

#1660 [improvement] custom shapes example
  apps/examples/src/3-custom-config/CardShape/CardShapeUtil.tsx
  apps/examples/src/3-custom-config/custom-shapes.ts
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/shapes/shared/resizeBox.ts
Labels: documentation

#1658 Fix crash when rotating a deleted shape
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/Rotating.ts
  packages/editor/src/lib/test/tools/rotating.test.ts
  packages/editor/src/lib/utils/rotation.ts
Labels: patch

#1662 [chore] bump vscode extension to 2.0.9
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: internal

#1627 [feature] add `meta` property to records
  apps/examples/e2e/tests/export-snapshots.spec.ts
  apps/examples/src/17-shape-meta/ShapeMetaExample.tsx
  apps/examples/src/index.tsx
  apps/vscode/editor/src/utils/bookmarks.ts
  docs/docs/editor.mdx
  packages/editor/api-report.md
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/components/ShapeIndicator.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/ExternalContentManager.ts
  packages/editor/src/lib/editor/shapes/line/__snapshots__/LineShapeUtil.test.ts.snap
  packages/editor/src/lib/test/commands/__snapshots__/packShapes.test.ts.snap
  packages/editor/src/lib/test/commands/__snapshots__/zoomToFit.test.ts.snap
  packages/editor/src/lib/test/commands/getInitialMetaForShape.test.ts
  packages/editor/src/lib/test/tools/__snapshots__/resizing.test.ts.snap
  packages/editor/src/lib/utils/assets.ts
  packages/file-format/src/lib/buildFromV1Document.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
  packages/tlschema/src/assets/TLBaseAsset.ts
  packages/tlschema/src/createPresenceStateDerivation.ts
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLAsset.ts
  packages/tlschema/src/records/TLCamera.ts
  packages/tlschema/src/records/TLDocument.ts
  packages/tlschema/src/records/TLInstance.ts
  packages/tlschema/src/records/TLPage.ts
  packages/tlschema/src/records/TLPageState.ts
  packages/tlschema/src/records/TLPointer.ts
  packages/tlschema/src/records/TLPresence.ts
  packages/tlschema/src/records/TLShape.ts
  packages/tlschema/src/shapes/TLBaseShape.ts
  packages/ui/src/lib/hooks/clipboard/pasteExcalidrawContent.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/json-value.ts
  packages/validate/api-report.md
  packages/validate/src/lib/validation.ts
Labels: minor

#1663 [fix] mutating `snapshot` in `migrateStoreSnapshot`
  packages/store/src/lib/StoreSchema.ts
Labels: patch

#1670 [fix] Shape rendering
  packages/editor/src/lib/components/Shape.tsx
Labels: patch

#1672 [fix] rename `global` in @tldraw/state to avoid collissions
  packages/state/src/lib/core/capture.ts
Labels: patch

#1671 [improvement] export scribble manager
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/managers/ScribbleManager.ts
Labels: minor

#1673 [improvemnet] drop crc, Buffer dependency
  packages/editor/package.json
  packages/editor/src/lib/utils/crc.ts
  packages/editor/src/lib/utils/png.ts
  public-yarn.lock
Labels: patch

#1674 [improvement] add box sizing border box
  packages/editor/editor.css
Labels: patch

#1675 [fix] comma keyboard shortcuts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
Labels: patch

#1677 [fix] Lock shortcut
  apps/examples/e2e/tests/test-kbds.spec.ts
  packages/ui/src/lib/hooks/useActions.tsx
Labels: patch

#1680 Fix VS Code commits failing on bublic?
  .husky/pre-commit
Labels: internal

#1682 [improvement] More nuanced cursor state
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/Editor.ts
Labels: minor

#1681 [docs] Fix the types in the Shapes example
  docs/docs/shapes.mdx
Labels: documentation

#1685 [docs] Update multiple test
  apps/examples/src/7-multiple/MultipleExample.tsx
Labels: documentation

#1687 [infra] use huppy token for publish-new
  .github/workflows/publish-canary.yml
  .github/workflows/publish-manual.yml
  .github/workflows/publish-new.yml
Labels: internal
