Repository tldraw/tldraw, pull requests merged in 2023-09, with the labels that each got.

#1836 [fix] svg overlays when browser zoom is not 100%
  packages/editor/editor.css
Labels: patch

#1841 [fix] line tool bug with tool locked
  packages/tldraw/src/lib/shapes/line/LineShapeTool.test.ts
  packages/tldraw/src/lib/shapes/line/toolStates/Pointing.ts
Labels: patch

#1842 [fix] awful rendering issue
  packages/editor/editor.css
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#1846 [fix] assets and content handlers
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/defaultSideEffects.ts
  packages/tldraw/src/lib/useRegisterExternalContentHandlers.ts
  packages/tldraw/src/lib/useSideEffects.ts
Labels: patch

#1851 update currentPageShapesSorted reference in docs
  docs/docs/editor.mdx
Labels: documentation

#1847 [fix] exit penmode
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
Labels: patch

#1855 [fix] pointer events in shapes
  packages/editor/editor.css
Labels: patch

#1852 Fix indicator transform miscalculation
  packages/editor/editor.css
Labels: patch

#1859 Fix paste transform
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/test/paste.test.ts
Labels: patch

#1858 avoid pixel rounding / transformation miscalc for overlay items
  packages/editor/editor.css
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/hooks/useDPRMultiple.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/tldraw/setupTests.js
Labels: patch

#1860 clamp x-box and check-box lines to stay within box at small scales
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
Labels: patch

#1840 [fix] zero width / height bounds
  packages/editor/api-report.md
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/components/default-components/DefaultBrush.tsx
  packages/editor/src/lib/components/default-components/DefaultSelectionForeground.tsx
  packages/editor/src/lib/primitives/Box2d.ts
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeTool.test.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
Labels: patch

#1856 Add snapshot prop, examples
  apps/examples/e2e/tests/test-routes.spec.ts
  apps/examples/src/examples/SnapshotExample/SnapshotExample.tsx
  apps/examples/src/examples/SnapshotExample/snapshot.json
  apps/examples/src/index.tsx
  apps/examples/tsconfig.json
  packages/editor/api-report.md
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/hooks/useLocalStore.ts
  packages/editor/src/lib/hooks/useTLStore.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/Tldraw.tsx
Labels: minor

#1843 Migrate snapshot
  packages/editor/api-report.md
  packages/editor/src/lib/config/createTLStore.ts
  packages/store/api-report.md
  packages/store/src/lib/Store.ts
  packages/tldraw/src/test/Editor.test.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
Labels: minor

#1848 [fix] iframe losing focus on pointer down
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/editor/src/lib/hooks/useFocusEvents.ts
  packages/tldraw/src/test/Editor.test.tsx
Labels: patch

#1873 [wip] Viewport focus of editing shapes
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#1895 Fix pinch start with toolbar open
  apps/examples/package.json
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
Labels: patch

#1904 Fix line handles
  packages/tldraw/src/lib/shapes/shared/polygon-helpers.ts
Labels: patch

#1891 [fix] right click
  packages/editor/src/lib/hooks/useCanvasEvents.ts
Labels: patch

#1903 Fix highlighter dots not being clickable
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeUtil.tsx
  packages/tldraw/src/test/HighlightShape.test.ts
Labels: patch

#1888 [fix] help menu css
  packages/tldraw/src/lib/ui.css
Labels: patch

#1905 Fix selecting one shape from selection group
  packages/tldraw/src/lib/tools/SelectTool/children/PointingShape.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: patch

#1915 Fix line wobble
  packages/editor/src/lib/components/Shape.tsx
Labels: patch

#1889 Update community translations
  assets/translations/ru.json
  assets/translations/uk.json
  assets/translations/zh-cn.json
Labels: translations, patch

#1919 [fix] id properties of undefined (#1730)
  packages/tldraw/src/lib/ui/components/PageMenu/PageMenu.tsx
Labels: patch

#1886 [fix] Moving group items inside of a frame (dropping)
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/DragAndDropManager.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Translating.ts
  packages/tldraw/src/test/frames.test.ts
Labels: patch

#1912 Fix first handle of line snapping to itself
  packages/tldraw/src/lib/tools/SelectTool/children/DraggingHandle.ts
Labels: patch

#1920 Fix lines being draggable via their background
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: patch

#1930 Use smarter rounding for shape container div width/height
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/hooks/useDPRMultiple.ts
Labels: patch

#1932 Fix shape drag perf
  packages/editor/src/lib/editor/Editor.ts
  packages/store/api-report.md
  packages/store/src/lib/Store.ts
Labels: patch

#1925 [feature] Include `sources` in `TLExternalContent`
  apps/examples/src/examples/ExternalContentSourcesExample.tsx
  apps/examples/src/index.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/external-content.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteFiles.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteUrl.ts
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: minor

#1929 expanded highlighter geometry
  packages/editor/api-report.md
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/components/GeometryDebuggingView.tsx
  packages/editor/src/lib/utils/debug-flags.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/draw/getPath.ts
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeUtil.tsx
  packages/tldraw/src/lib/ui/components/DebugPanel.tsx
Labels: patch

#1934 fix clipping on nested non-intersecting frames
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#1927 [fix] geo shape text label placement
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/index.ts
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/primitives/utils.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/cloudOutline.ts
  packages/tldraw/src/lib/shapes/geo/components/DashStyleEllipse.tsx
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
Labels: patch

#1951 [infra] missing await
  scripts/lib/publishing.ts
Labels: internal

#1957 [improvement] improve arrows (for real)
  packages/editor/src/lib/editor/shapes/shared/arrow/curved-arrow.ts
  packages/editor/src/lib/editor/shapes/shared/arrow/shared.ts
  packages/editor/src/lib/primitives/utils.ts
Labels: patch

#1964 Lokalise: Translations update
  assets/translations/de.json
  assets/translations/gl.json
Labels: patch

#1955 Stop editing frame headers when clicking inside a frame.
  packages/tldraw/src/lib/shapes/frame/components/FrameHeading.tsx
  packages/tldraw/src/lib/tools/SelectTool/children/EditingShape.ts
Labels: patch

#1969 Mark an undo before toggling lock
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
Labels: patch

#1968 Allow right clicking selection backgrounds
  packages/editor/src/lib/hooks/useSelectionEvents.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: patch

#1936 fix line bugs
  packages/tldraw/src/lib/shapes/line/LineShapeTool.test.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/toolStates/Pointing.ts
  packages/tldraw/src/lib/ui/components/Toolbar/Toolbar.tsx
Labels: patch

#1963 Make user preferences optional
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
  packages/tldraw/src/test/Editor.test.tsx
  packages/tldraw/src/test/TLUserPreferences.test.ts
Labels: major

#1962 Remove targeted editing from text
  packages/tldraw/src/lib/shapes/arrow/components/ArrowTextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/shapes/text/toolStates/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/EditingShape.ts
Labels: major

#1976 [fix] Screen bounds offset after editing text
  packages/tldraw/src/lib/tools/SelectTool/children/EditingShape.ts
Labels: patch
