Repository tldraw/tldraw, pull requests merged in 2023-07, with the labels that each got.

#1696 [fix] indicator not updating
  packages/editor/src/lib/components/ShapeIndicator.tsx
Labels: patch

#1686 Update readme
  README.md
Labels: documentation

#1694 Lokalise: Translations update
  assets/translations/fa.json
  assets/translations/ru.json
  assets/translations/uk.json
  assets/translations/zh-cn.json
Labels: translations, patch

#1698 [fix] penmode
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/test/penmode.test.ts
Labels: patch

#1704 Disable styles panel button on mobile when using the laser tool.
  packages/ui/src/lib/components/MobileStylePanel.tsx
Labels: patch

#1701 Firefox: Fix coarse pointer issue
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useCoarsePointer.ts
Labels: patch

#1707 Fix tsdocs for TldrawUi component
  packages/ui/api-report.md
  packages/ui/src/lib/TldrawUi.tsx
  packages/ui/src/lib/TldrawUiContextProvider.tsx
Labels: documentation

#1700 Go back to default cursor when done resizing.
  packages/editor/src/lib/editor/tools/SelectTool/children/Resizing.ts
Labels: patch

#1688 [internal] Add basic list to examples
  apps/examples/e2e/tests/test-routes.spec.ts
  apps/examples/src/6-scroll/ScrollExample.tsx
  apps/examples/src/ExamplesTldrawLogo.tsx
  apps/examples/src/components/ListLink.tsx
  apps/examples/src/index.tsx
  apps/examples/src/styles.css
Labels: internal

#1661 Add API links to all docs pages
  docs/docs/assets.mdx
  docs/docs/editor.mdx
  docs/docs/shapes.mdx
  docs/docs/user-interface.mdx
  docs/getting-started/introduction.mdx
  docs/getting-started/usage.mdx
Labels: documentation

#1717 remove state checks for brush and zoom brush
  packages/editor/src/lib/components/Canvas.tsx
Labels: minor

#1719 Bump vs code version.
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: patch

#1718 [refactor] reordering shapes
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/test/commands/renderingShapes.test.tsx
  packages/editor/src/lib/test/commands/reorderShapes.test.ts
  packages/editor/src/lib/utils/reorderShapes.ts
Labels: major

#1691 [hot take] remove `tool` from shape definition
  apps/examples/src/16-custom-styles/CardShape.tsx
  apps/examples/src/16-custom-styles/CustomStylesExample.tsx
  apps/examples/src/3-custom-config/CardShape/CardShape.ts
  apps/examples/src/3-custom-config/CustomConfigExample.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/config/defaultTools.ts
  packages/editor/src/lib/config/defineShape.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/arrow/ArrowShape.ts
  packages/editor/src/lib/editor/shapes/draw/DrawShape.ts
  packages/editor/src/lib/editor/shapes/frame/FrameShape.ts
  packages/editor/src/lib/editor/shapes/geo/GeoShape.ts
  packages/editor/src/lib/editor/shapes/highlight/HighlightShape.ts
  packages/editor/src/lib/editor/shapes/line/LineShape.ts
  packages/editor/src/lib/editor/shapes/note/NoteShape.ts
  packages/editor/src/lib/editor/shapes/text/TextShape.ts
Labels: major

#1706 Make some missing tsdocs appear on the docs site
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/ui/api-report.md
  packages/ui/src/index.ts
  packages/ui/src/lib/TldrawUi.tsx
  packages/ui/src/lib/TldrawUiContextProvider.tsx
Labels: documentation

#1693 [refactor] reduce dependencies on shape utils in editor
  apps/examples/src/16-custom-styles/CardShape.tsx
  apps/examples/src/3-custom-config/CardShape/CardShapeTool.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/components/SelectionFg.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/derivations/arrowBindingsIndex.test.tsx
  packages/editor/src/lib/editor/derivations/arrowBindingsIndex.ts
  packages/editor/src/lib/editor/managers/ExternalContentManager.ts
  packages/editor/src/lib/editor/managers/SnapManager.ts
  packages/editor/src/lib/editor/shapes/arrow/ArrowShapeTool.ts
  packages/editor/src/lib/editor/shapes/arrow/ArrowShapeUtil.test.ts
  packages/editor/src/lib/editor/shapes/arrow/ArrowShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/arrow/toolStates/Pointing.ts
  packages/editor/src/lib/editor/shapes/draw/DrawShapeTool.ts
  packages/editor/src/lib/editor/shapes/draw/toolStates/Drawing.ts
  packages/editor/src/lib/editor/shapes/embed/EmbedShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/frame/FrameShapeTool.ts
  packages/editor/src/lib/editor/shapes/frame/FrameShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/geo/GeoShapeTool.ts
  packages/editor/src/lib/editor/shapes/geo/toolStates/Idle.ts
  packages/editor/src/lib/editor/shapes/group/GroupShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/highlight/HighlightShapeTool.ts
  packages/editor/src/lib/editor/shapes/line/LineShapeTool.test.ts
  packages/editor/src/lib/editor/shapes/line/LineShapeTool.ts
  packages/editor/src/lib/editor/shapes/note/NoteShapeTool.ts
  packages/editor/src/lib/editor/shapes/text/TextShapeTool.ts
  packages/editor/src/lib/editor/shapes/text/toolStates/Idle.ts
  packages/editor/src/lib/editor/tools/BaseBoxShapeTool/BaseBoxShapeTool.ts
  packages/editor/src/lib/editor/tools/BaseBoxShapeTool/children/Pointing.ts
  packages/editor/src/lib/editor/tools/EraserTool/children/Erasing.ts
  packages/editor/src/lib/editor/tools/EraserTool/children/Pointing.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/Brushing.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/Cropping.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/Idle.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/PointingShape.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/Resizing.ts
  packages/editor/src/lib/editor/tools/SelectTool/children/ScribbleBrushing.ts
  packages/editor/src/lib/editor/tools/StateNode.ts
  packages/editor/src/lib/test/Editor.test.tsx
  packages/editor/src/lib/test/TldrawEditor.test.tsx
  packages/editor/src/lib/test/commands/rotateShapes.test.ts
  packages/editor/src/lib/test/duplicate.test.ts
  packages/editor/src/lib/test/shapeutils.test.ts
  packages/editor/src/lib/test/tools/frames.test.ts
  packages/editor/src/lib/test/tools/groups.test.ts
  packages/editor/src/lib/test/tools/translating.test.ts
  packages/file-format/src/lib/buildFromV1Document.ts
  packages/ui/api-report.md
  packages/ui/src/lib/hooks/menuHelpers.ts
  packages/ui/src/lib/hooks/useActions.tsx
  packages/ui/src/lib/hooks/useClipboardEvents.ts
  packages/ui/src/lib/hooks/useContextMenuSchema.tsx
  packages/ui/src/lib/hooks/useExportAs.ts
  packages/ui/src/lib/hooks/useOnlyFlippableShape.ts
  packages/ui/src/lib/hooks/useShowAutoSizeToggle.ts
Labels: major

#1708 Add cloud shape
  .github/workflows/publish-manual.yml
  apps/examples/e2e/tests/test-shapes.spec.ts
  assets/icons/icon/geo-cloud.svg
  assets/translations/main.json
  packages/assets/imports.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/editor/api-report.md
  packages/editor/src/lib/editor/shapes/frame/FrameShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/frame/components/FrameHeading.tsx
  packages/editor/src/lib/editor/shapes/geo/GeoShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/geo/cloudOutline.ts
  packages/editor/src/lib/editor/shapes/geo/components/DashStyleCloud.tsx
  packages/editor/src/lib/editor/shapes/geo/components/DrawStyleCloud.tsx
  packages/editor/src/lib/editor/shapes/geo/components/SolidStyleCloud.tsx
  packages/editor/src/lib/editor/shapes/geo/toolStates/Pointing.ts
  packages/editor/src/lib/test/tools/resizing.test.ts
  packages/editor/src/lib/utils/rotation.ts
  packages/primitives/api-report.md
  packages/primitives/src/index.ts
  packages/primitives/src/lib/Vec2d.ts
  packages/primitives/src/lib/utils.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/shapes/TLGeoShape.ts
  packages/ui/api-report.md
  packages/ui/src/lib/components/StylePanel/styles.tsx
  packages/ui/src/lib/hooks/useToolbarSchema.tsx
  packages/ui/src/lib/hooks/useTranslation/TLUiTranslationKey.ts
  packages/ui/src/lib/hooks/useTranslation/defaultTranslation.ts
  packages/ui/src/lib/icon-types.ts
  scripts/publish-new.ts
Labels: minor

#1723 tweaks for cloud shape
  packages/editor/src/lib/editor/shapes/geo/cloudOutline.ts
Labels: patch

#1721 (2/2) Add content to Tools docs page.
  docs/docs/editor.mdx
  docs/docs/tools.mdx
  lerna.json
Labels: documentation

#1735 Bump vs code version.
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: patch

#1737 support custom shapes in yjs example
  apps/examples/src/yjs/useYjsStore.ts
Labels: internal

#1733 fix: arrow label dark mode color
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
Labels: patch

#1732 fix: escape eraser tool on escape
  packages/tldraw/src/lib/tools/EraserTool/children/Idle.ts
Labels: patch

#1705 add shapes docs content
  docs/docs/editor.mdx
  docs/docs/shapes.mdx
Labels: documentation

#1744 (chore) bump
  apps/vscode/editor/package.json
  apps/vscode/extension/package.json
  package.json
  packages/editor/src/lib/editor/types/SvgExportContext.tsx
  public-yarn.lock
  scripts/package.json
Labels: dependencies

#1748 Fix e2e test
  apps/examples/e2e/tests/test-kbds.spec.ts
Labels: tests

#1747 [fix]: Fix typo in shapeType declaration
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeTool.ts
Labels: patch

#1750 move some utils into tldraw/utils
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/useRegisterExternalContentHandlers.ts
  packages/tldraw/src/lib/utils/assetUrls.ts
  packages/tldraw/src/lib/utils/assets.ts
  packages/tldraw/src/lib/utils/export.ts
  packages/tldraw/src/lib/utils/file.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/file.ts
  packages/utils/src/lib/media.ts
  packages/utils/src/lib/png.ts
Labels: major

#1749 More cleanup, focus bug fixes
  apps/examples/e2e/tests/test-focus.spec.ts
  apps/examples/src/7-multiple/MultipleExample.tsx
  assets/translations/pt-br.json
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/SnapManager.ts
  packages/editor/src/lib/editor/types/editor-state.ts
  packages/editor/src/lib/hooks/useCanvasEvents.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingSelection.ts
  packages/tldraw/src/lib/tools/SelectTool/children/PointingShape.ts
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/ActionsMenu.tsx
  packages/tldraw/src/lib/ui/components/ContextMenu.tsx
  packages/tldraw/src/lib/ui/components/HelpMenu.tsx
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog.tsx
  packages/tldraw/src/lib/ui/components/Menu.tsx
  packages/tldraw/src/lib/ui/components/MenuZone.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageMenu.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/StylePanel.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/Toolbar.tsx
  packages/tldraw/src/lib/ui/components/TrashButton.tsx
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
  packages/tldraw/src/lib/ui/hooks/useReadOnly.ts
  packages/tldraw/src/lib/ui/hooks/useReadonly.ts
  packages/tldraw/src/test/Editor.test.tsx
  packages/tldraw/src/test/SelectTool.test.ts
  packages/tldraw/src/test/groups.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLInstance.ts
Labels: major

#1756 [fix] arrow snapping bug
  packages/editor/editor.css
  packages/editor/src/lib/components/default-components/DefaultHandle.tsx
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
Labels: minor

#1758 Fix asset urls
  packages/tldraw/src/lib/utils/assetUrls.ts
Labels: patch

#1761 [fix] revert legacy changes to buildFromV1Document.ts
  packages/tldraw/src/lib/utils/buildFromV1Document.ts
Labels: patch

#1763 rename selection page bounds
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.test.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Translating.ts
  packages/tldraw/src/lib/useRegisterExternalContentHandlers.ts
  packages/tldraw/src/test/commands/moveShapesToPage.test.ts
  packages/tldraw/src/test/commands/nudge.test.ts
  packages/tldraw/src/test/flipShapes.test.ts
  packages/tldraw/src/test/resizing.test.ts
  packages/tldraw/src/test/rotating.test.ts
Labels: major

#1764 refactor `parentsToChildrenWithIndexes`
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/derivations/parentsToChildren.ts
Labels: minor

#1765 [fix] restore bg option, fix calculations
  packages/editor/api-report.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/children/Idle.ts
  packages/tldraw/src/lib/tools/selection-logic/selectOnCanvasPointerUp.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: patch

#1767 [fix] arrow rendering safari
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
Labels: patch

#1766 remove `selectionPageCenter`
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/utils/rotation.ts
  packages/tldraw/src/lib/tools/SelectTool/children/Rotating.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/commands/rotateShapes.test.ts
Labels: major

#1771 [fix] shape indicator showing when locked shapes are hovered
  packages/editor/src/lib/components/ShapeIndicator.tsx
Labels: patch

#1774 export `UiEventsProvider`
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/TldrawUiContextProvider.tsx
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  packages/tldraw/src/lib/ui/hooks/useDialogsProvider.tsx
  packages/tldraw/src/lib/ui/hooks/useEventsProvider.tsx
  packages/tldraw/src/lib/ui/hooks/useMenuIsOpen.ts
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
Labels: minor

#1776 Add shapes to exports
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/tools/EraserTool/EraserTool.ts
  packages/tldraw/src/lib/tools/HandTool/HandTool.ts
  packages/tldraw/src/lib/tools/LaserTool/LaserTool.ts
  packages/tldraw/src/lib/tools/SelectTool/SelectTool.ts
  packages/tldraw/src/lib/tools/ZoomTool/ZoomTool.ts
  packages/validate/api-report.md
  packages/validate/src/index.ts
Labels: minor

#1779 [fix] handles updates
  packages/editor/src/lib/components/Canvas.tsx
Labels: patch

#1781 Fix outlines on text shapes
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
Labels: patch

#1777 [feature] Add val town embed
  assets/embed-icons/val_town.png
  packages/assets/imports.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/tlschema/api-report.md
  packages/tlschema/src/shapes/TLEmbedShape.ts
Labels: minor
