Repository tldraw/tldraw, pull requests merged in 2023-05, with the labels that each got.

#1334 [chore] move schema construction to tlschema package
  packages/editor/src/lib/config/TldrawEditorConfig.tsx
  packages/tlschema/api-report.md
  packages/tlschema/package.json
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/defaultDerivePresenceState.ts
  packages/tlschema/src/index.ts
  public-yarn.lock
Labels: patch

#1341 Rework the assets package for strategy-specific imports
  .eslintignore
  .eslintrc.js
  .github/workflows/checks.yml
  apps/examples/src/index.tsx
  apps/vscode/editor/src/app.tsx
  packages/assets/imports.d.ts
  packages/assets/imports.js
  packages/assets/package.json
  packages/assets/src/imports.ts
  packages/assets/src/index.ts
  packages/assets/src/urls.ts
  packages/assets/src/utils.ts
  packages/assets/tsconfig.json
  packages/assets/urls.d.ts
  packages/assets/urls.js
  packages/tlschema/scripts/new-asset.js
  packages/tlschema/scripts/new-record.js
  packages/tlschema/tsconfig.json
  scripts/check-scripts.ts
  scripts/lib/file.ts
  scripts/refresh-assets.ts
Labels: major

#1337 Added initial webdriver tests
  .eslintignore
  .eslintrc.js
  .gitignore
  apps/webdriver/CHANGELOG.md
  apps/webdriver/README.md
  apps/webdriver/package.json
  apps/webdriver/scripts/dev.mjs
  apps/webdriver/src/1-basic/BasicExampleWebdriver.tsx
  apps/webdriver/src/index.css
  apps/webdriver/src/index.tsx
  apps/webdriver/tsconfig.json
  apps/webdriver/www/index.html
  e2e/CHANGELOG.md
  e2e/README.md
  e2e/downloads/README.md
  e2e/package.json
  e2e/screenshots/README.md
  e2e/test-overview-ui.png
  e2e/test/helpers/constants.ts
  e2e/test/helpers/index.ts
  e2e/test/helpers/runtime.ts
  e2e/test/helpers/ui/app.ts
  e2e/test/helpers/ui/canvas.ts
  e2e/test/helpers/ui/help.ts
  e2e/test/helpers/ui/index.ts
  e2e/test/helpers/ui/main.ts
  e2e/test/helpers/ui/minimap.ts
  e2e/test/helpers/ui/props.ts
  e2e/test/helpers/ui/share.ts
  e2e/test/helpers/ui/tools.ts
  e2e/test/helpers/util.ts
  e2e/test/helpers/webdriver.ts
  e2e/test/mocha-ext.ts
  e2e/test/specs/arrange.ts
  e2e/test/specs/camera.ts
  e2e/test/specs/constants.ts
  e2e/test/specs/export.ts
  e2e/test/specs/grouping.ts
  e2e/test/specs/index.ts
  e2e/test/specs/pages.ts
  e2e/test/specs/reorder.ts
  e2e/test/specs/screenshots.ts
  e2e/test/specs/shortcuts.ts
  e2e/test/specs/smoke.ts
  e2e/test/specs/styling.ts
  e2e/test/specs/text.ts
  e2e/test/test-constants.ts
  e2e/tsconfig.json
  e2e/wdio.local.conf.js
  e2e/wdio.nightly.conf.js
  e2e/wdio.remote.conf.js
  lazy.config.ts
  package.json
  public-yarn.lock
  scripts/e2e-run-ci
  scripts/e2e-run-tests
  scripts/e2e-start-server
Labels: tests

#1342 Fix "copy as png" in firefox when `dom.events.asyncClipboard.clipboardItem` is enabled
  packages/ui/src/lib/hooks/useCopyAs.ts
Labels: needs qa, patch

#1323 [fix] tabs in text exports
  packages/editor/src/lib/app/managers/TextManager.ts
  packages/editor/src/lib/app/shapeutils/shared/getTextSvgElement.ts
  packages/editor/src/lib/utils/string.ts
Labels: needs qa

#1326 [feature] ui events
  .ignore
  apps/examples/package.json
  apps/examples/src/12-events/EventsExample.tsx
  apps/examples/src/index.tsx
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/app/App.ts
  packages/editor/src/lib/app/managers/HistoryManager.ts
  packages/editor/src/lib/app/types/emit-types.ts
  packages/editor/src/lib/app/types/reorder-types.ts
  packages/editor/src/lib/test/commands/distributeShapes.test.ts
  packages/editor/src/lib/test/commands/stackShapes.test.ts
  packages/editor/src/lib/test/commands/stretch.test.ts
  packages/editor/src/lib/test/tools/TLArrowTool.test.ts
  packages/editor/src/lib/test/tools/TLFrameTool.test.ts
  packages/editor/src/lib/test/tools/TLGeoTool.test.ts
  packages/editor/src/lib/test/tools/TLLineTool.test.ts
  packages/editor/src/lib/test/tools/TLNoteTool.test.ts
  packages/ui/api-report.md
  packages/ui/src/lib/TldrawUi.tsx
  packages/ui/src/lib/TldrawUiContextProvider.tsx
  packages/ui/src/lib/components/ActionsMenu.tsx
  packages/ui/src/lib/components/BackToContent.tsx
  packages/ui/src/lib/components/ContextMenu.tsx
  packages/ui/src/lib/components/DuplicateButton.tsx
  packages/ui/src/lib/components/EditLinkDialog.tsx
  packages/ui/src/lib/components/HelpMenu.tsx
  packages/ui/src/lib/components/Menu.tsx
  packages/ui/src/lib/components/MoveToPageMenu.tsx
  packages/ui/src/lib/components/NavigationZone/NavigationZone.tsx
  packages/ui/src/lib/components/NavigationZone/ZoomMenu.tsx
  packages/ui/src/lib/components/PenModeToggle.tsx
  packages/ui/src/lib/components/RedoButton.tsx
  packages/ui/src/lib/components/StopFollowing.tsx
  packages/ui/src/lib/components/Toolbar/Toolbar.tsx
  packages/ui/src/lib/components/TrashButton.tsx
  packages/ui/src/lib/components/UndoButton.tsx
  packages/ui/src/lib/hooks/useActions.tsx
  packages/ui/src/lib/hooks/useAppEvents.ts
  packages/ui/src/lib/hooks/useClipboardEvents.ts
  packages/ui/src/lib/hooks/useDialogsProvider.tsx
  packages/ui/src/lib/hooks/useEventsProvider.tsx
  packages/ui/src/lib/hooks/useExportAs.ts
  packages/ui/src/lib/hooks/useKeyboardShortcuts.ts
  packages/ui/src/lib/hooks/useMenuIsOpen.ts
  packages/ui/src/lib/hooks/usePrint.ts
  packages/ui/src/lib/hooks/useTools.tsx
  public-yarn.lock
Labels: major

#1350 [fix] various text
  .eslintignore
  .prettierignore
  e2e/test/specs/text.ts
  packages/editor/src/lib/app/managers/TextManager.ts
  packages/editor/src/lib/app/shapeutils/TLArrowUtil/TLArrowUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLGeoUtil/TLGeoUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLNoteUtil/TLNoteUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLTextUtil/TLTextUtil.tsx
Labels: patch

#1354 [improvement] Ui events followup
  apps/examples/src/12-events/EventsExample.tsx
  packages/editor/src/lib/app/App.ts
  packages/ui/api-report.md
  packages/ui/src/lib/components/ContextMenu.tsx
  packages/ui/src/lib/components/Menu.tsx
  packages/ui/src/lib/components/Toolbar/Toolbar.tsx
  packages/ui/src/lib/hooks/useActions.tsx
  packages/ui/src/lib/hooks/useClipboardEvents.ts
  packages/ui/src/lib/hooks/useDialogsProvider.tsx
  packages/ui/src/lib/hooks/useEventsProvider.tsx
  packages/ui/src/lib/hooks/useKeyboardShortcuts.ts
  packages/ui/src/lib/hooks/useMenuIsOpen.ts
  packages/ui/src/lib/hooks/useTools.tsx
Labels: major

#1358 [improvement] rename onEvent to onUiEvent
  apps/docs/content/docs/user-interface.mdx
  apps/examples/src/12-ui-events/UiEventsExample.tsx
  apps/examples/src/13-store/StoreEventsExample.tsx
  apps/examples/src/index.tsx
  packages/ui/api-report.md
  packages/ui/src/index.ts
  packages/ui/src/lib/TldrawUiContextProvider.tsx
Labels: major

#1361 presence-related fixes
  packages/editor/src/lib/app/App.ts
  packages/editor/src/lib/test/commands/createPage.test.ts
  packages/tlstore/src/lib/Store.ts
  packages/tlstore/src/lib/test/recordStore.test.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/raf.ts
Labels: patch

#1360 Export Events stuff
  packages/ui/api-report.md
  packages/ui/src/index.ts
  packages/ui/src/lib/TldrawUiContextProvider.tsx
Labels: patch

#1362 [perf] make ensureStoreIsUsable scale better
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/index.ts
  packages/tlstore/api-report.md
  packages/tlstore/src/lib/Store.ts
  packages/tlstore/src/lib/StoreSchema.ts
Labels: patch

#1363 enable eslint for test files
  .eslintignore
  .eslintrc.js
  lazy.config.ts
  packages/editor/src/lib/test/App.test.ts
Labels: internal

#1343 Adds CI for webdriver tests
  .github/workflows/webdriver-nightly.yml
  .github/workflows/webdriver-on-demand.yml
  .github/workflows/webdriver.yml
  apps/webdriver/scripts/dev.mjs
  e2e/README.md
  e2e/package.json
  e2e/wdio.browserstack.conf.js
  e2e/wdio.local.conf.js
  e2e/wdio.nightly.conf.js
  e2e/wdio.remote.conf.js
  e2e/wdio.util.js
  package.json
  public-yarn.lock
  scripts/e2e-run-ci
  scripts/e2e-run-tests
  scripts/e2e-start-server
  scripts/e2e/commands/index.ts
  scripts/e2e/commands/selenium-grid.ts
  scripts/e2e/commands/serve.ts
  scripts/e2e/commands/test-browserstack.ts
  scripts/e2e/commands/test-ci.ts
  scripts/e2e/commands/test-local.ts
  scripts/e2e/commands/util.ts
  scripts/e2e/index.ts
Labels: tests

#1356 Update community translations + remove unused translations
  assets/translations/ar.json
  assets/translations/ca.json
  assets/translations/da.json
  assets/translations/de.json
  assets/translations/es.json
  assets/translations/fa.json
  assets/translations/fi.json
  assets/translations/fr.json
  assets/translations/gl.json
  assets/translations/he.json
  assets/translations/hi-in.json
  assets/translations/it.json
  assets/translations/ja.json
  assets/translations/ko-kr.json
  assets/translations/ku.json
  assets/translations/my.json
  assets/translations/ne.json
  assets/translations/no.json
  assets/translations/pl.json
  assets/translations/pt-br.json
  assets/translations/pt-pt.json
  assets/translations/ro.json
  assets/translations/ru.json
  assets/translations/sv.json
  assets/translations/te.json
  assets/translations/th.json
  assets/translations/tr.json
  assets/translations/uk.json
  assets/translations/vi.json
  assets/translations/zh-cn.json
  assets/translations/zh-tw.json
Labels: translations, patch

#1364 avoid lazy race conditions
  .github/workflows/checks.yml
  apps/docs/package.json
  apps/vscode/editor/package.json
  apps/webdriver/package.json
  lazy.config.ts
  package.json
  packages/editor/package.json
  packages/file-format/package.json
  packages/polyfills/package.json
  packages/primitives/package.json
  packages/tldraw/package.json
  packages/tlschema/package.json
  packages/tlstore/package.json
  packages/tlsync-client/package.json
  packages/tlvalidate/package.json
  packages/ui/package.json
  packages/utils/package.json
  scripts/check-scripts.ts
  scripts/prepack.ts
Labels: internal

#1367 remove references to tldraw-lite
  apps/docs/scripts/generateContent.ts
  package.json
  scripts/publish-new.ts
Labels: internal

#1366 Disable nightly/on-demand webdriver scripts
  .github/workflows/webdriver-nightly.yml
  .github/workflows/webdriver-on-demand.yml
Labels: tests

#1365 fix a couple of consistency assumptions
  packages/editor/src/lib/app/App.ts
Labels: patch

#1373 [perf] deleteShapes
  packages/editor/src/lib/app/App.ts
Labels: patch

#1377 Remove commented code in App
  packages/editor/src/lib/app/App.ts
Labels: internal

#1378 [fix] pointer location not updating when moving over editing shape
  packages/editor/src/lib/hooks/useShapeEvents.ts
Labels: minor

#1333 [fix] Allow interactions with embeds in readonly mode
  packages/editor/src/lib/app/statechart/TLSelectTool/children/Idle.ts
  packages/editor/src/lib/test/tools/TLSelectTool.test.ts
Labels: needs qa, patch

#1379 Expand selection outline for single-selected draw shape
  packages/editor/api-report.md
  packages/editor/src/lib/app/shapeutils/TLDrawUtil/TLDrawUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLShapeUtil.ts
  packages/editor/src/lib/components/SelectionFg.tsx
  packages/editor/src/lib/hooks/useTransform.ts
Labels: patch

#1380 Fix selection foreground being misaligned
  packages/editor/editor.css
Labels: patch

#1368 Update codesandbox + example link
  apps/docs/content/docs/introduction.mdx
Labels: documentation

#1386 Fix setting the grid mode.
  packages/editor/src/lib/app/App.ts
Labels: patch

#1384 Delete an empty text shape when clicking on another text shape.
  packages/editor/src/lib/app/statechart/TLSelectTool/children/EditingShape.ts
  packages/editor/src/lib/test/tools/TLSelectTool.test.ts
Labels: needs qa, patch

#1388 fix pasted tabs not getting converted to space
  packages/editor/src/lib/app/shapeutils/shared/useEditableText.ts
Labels: patch

#1396 [fix] Don't synchronize isReadOnly
  lazy.config.ts
  packages/editor/api-report.md
  packages/editor/src/lib/app/App.ts
  packages/editor/src/lib/test/tools/TLSelectTool.test.ts
  packages/editor/src/lib/test/tools/groups.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLUserDocument.ts
  packages/ui/src/lib/components/DebugPanel.tsx
Labels: major

#1399 Snapshot link menu translations
  assets/translations/main.json
  packages/ui/api-report.md
  packages/ui/src/lib/hooks/useTranslation/TLTranslationKey.ts
  packages/ui/src/lib/hooks/useTranslation/defaultTranslation.ts
  packages/ui/ui.css
Labels: minor

#1400 open menus refactor
  assets/icons/icon/clipboard-copied.svg
  packages/assets/imports.d.ts
  packages/assets/imports.js
  packages/assets/urls.d.ts
  packages/assets/urls.js
  packages/ui/api-report.md
  packages/ui/src/lib/components/ContextMenu.tsx
  packages/ui/src/lib/components/HelpMenu.tsx
  packages/ui/src/lib/components/primitives/DropdownMenu.tsx
  packages/ui/src/lib/components/primitives/Popover.tsx
  packages/ui/src/lib/hooks/useMenuIsOpen.ts
  packages/ui/src/lib/icon-types.ts
Labels: minor

#1382 Don't allow the users to use keyboard shortcuts to select tools in readonly mode.
  packages/ui/src/lib/hooks/useKeyboardShortcuts.ts
  packages/ui/src/lib/hooks/useTools.tsx
Labels: needs qa, patch

#1402 remove url state, to private
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/hooks/useUrlState.tsx
Labels: major

#1403 Add stuff for new 'share project' flow
  assets/translations/main.json
  packages/tlstore/api-report.md
  packages/tlstore/src/lib/Store.ts
  packages/ui/api-report.md
  packages/ui/src/lib/hooks/useTranslation/TLTranslationKey.ts
  packages/ui/src/lib/hooks/useTranslation/defaultTranslation.ts
Labels: minor

#1405 Switch to new collaborators component
  packages/editor/api-report.md
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/editor/src/lib/components/LiveCollaboratorsNext.tsx
  packages/editor/src/lib/utils/debug-flags.ts
  packages/ui/src/lib/components/NavigationZone/Minimap.tsx
  packages/ui/src/lib/components/NavigationZone/MinimapManager.ts
Labels: major

#1406 [fix] page menu, drag handle css
  packages/ui/src/lib/components/PageMenu/PageMenu.tsx
  packages/ui/ui.css
Labels: patch

#1411 fix viewport following
  packages/editor/src/lib/app/App.ts
Labels: patch

#1414 Vertical text alignment for geo shapes
  assets/icons/icon/vertical-align-center.svg
  assets/icons/icon/vertical-align-end.svg
  assets/icons/icon/vertical-align-start.svg
  assets/translations/main.json
  packages/assets/imports.d.ts
  packages/assets/imports.js
  packages/assets/urls.d.ts
  packages/assets/urls.js
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/lib/app/shapeutils/TLArrowUtil/TLArrowUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLGeoUtil/TLGeoUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLNoteUtil/TLNoteUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLTextUtil/TLTextUtil.tsx
  packages/editor/src/lib/app/shapeutils/shared/TextLabel.tsx
  packages/editor/src/lib/app/shapeutils/shared/getTextSvgElement.ts
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/test/commands/__snapshots__/packShapes.test.ts.snap
  packages/editor/src/lib/test/props.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/index.ts
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLInstance.ts
  packages/tlschema/src/shapes/TLGeoShape.ts
  packages/tlschema/src/style-types.ts
  packages/tlschema/src/validation.ts
  packages/ui/api-report.md
  packages/ui/src/lib/components/StylePanel/DropdownPicker.tsx
  packages/ui/src/lib/components/StylePanel/StylePanel.tsx
  packages/ui/src/lib/hooks/useTranslation/TLTranslationKey.ts
  packages/ui/src/lib/hooks/useTranslation/defaultTranslation.ts
  packages/ui/src/lib/icon-types.ts
Labels: minor

#1412 [feature] add laser pointer
  apps/docs/styles/globals.css
  assets/icons/icon/tool-laser.svg
  assets/translations/main.json
  packages/assets/imports.d.ts
  packages/assets/imports.js
  packages/assets/urls.d.ts
  packages/assets/urls.js
  packages/editor/editor.css
  packages/editor/src/lib/app/managers/ScribbleManager.ts
  packages/editor/src/lib/app/statechart/RootState.ts
  packages/editor/src/lib/app/statechart/TLEraserTool/children/Erasing.ts
  packages/editor/src/lib/app/statechart/TLLaserTool/TLLaserTool.ts
  packages/editor/src/lib/app/statechart/TLLaserTool/children/Idle.ts
  packages/editor/src/lib/app/statechart/TLLaserTool/children/Lasering.ts
  packages/editor/src/lib/app/statechart/TLSelectTool/children/ScribbleBrushing.ts
  packages/editor/src/lib/components/DefaultScribble.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLInstance.ts
  packages/tlschema/src/records/TLInstancePresence.ts
  packages/tlschema/src/ui-types.ts
  packages/ui/api-report.md
  packages/ui/src/lib/hooks/useToolbarSchema.tsx
  packages/ui/src/lib/hooks/useTools.tsx
  packages/ui/src/lib/hooks/useTranslation/TLTranslationKey.ts
  packages/ui/src/lib/hooks/useTranslation/defaultTranslation.ts
  packages/ui/src/lib/icon-types.ts
Labels: minor

#1419 [improvement] set horizontal position using text alignment
  packages/editor/editor.css
  packages/editor/src/lib/app/shapeutils/TLGeoUtil/TLGeoUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLNoteUtil/TLNoteUtil.tsx
  packages/editor/src/lib/app/shapeutils/shared/TextLabel.tsx
  packages/editor/src/lib/app/shapeutils/shared/getTextSvgElement.ts
Labels: minor

#1421 Bump version.
  apps/vscode/extension/package.json
Labels: patch

#1423 [feature] Add checkbox to toolbar
  packages/ui/src/lib/hooks/useToolbarSchema.tsx
Labels: minor

#1426 Create @tldraw/indices package
  e2e/package.json
  e2e/test/specs/reorder.ts
  e2e/tsconfig.json
  packages/editor/api-report.md
  packages/editor/package.json
  packages/editor/src/index.ts
  packages/editor/src/lib/app/App.ts
  packages/editor/src/lib/app/derivations/parentsToChildrenWithIndexes.test.ts
  packages/editor/src/lib/app/managers/SnapManager.ts
  packages/editor/src/lib/app/shapeutils/TLLineUtil/TLLineUtil.tsx
  packages/editor/src/lib/app/statechart/TLLineTool/children/Pointing.ts
  packages/editor/src/lib/app/statechart/TLSelectTool/children/DraggingHandle.ts
  packages/editor/src/lib/test/tools/groups.test.ts
  packages/editor/src/lib/utils/reordering/reordering.ts
  packages/editor/tsconfig.json
  packages/indices/CHANGELOG.md
  packages/indices/LICENSE
  packages/indices/README.md
  packages/indices/api-extractor.json
  packages/indices/api-report.md
  packages/indices/package.json
  packages/indices/src/index.ts
  packages/indices/src/lib/dgreensp/dgreensp.test.ts
  packages/indices/src/lib/dgreensp/dgreensp.ts
  packages/indices/src/lib/dgreensp/index.ts
  packages/indices/src/lib/reordering.test.ts
  packages/indices/src/lib/reordering.ts
  packages/indices/tsconfig.json
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/sort.ts
  public-yarn.lock
Labels: major

#1427 [chore] remove yarnrc-private.yml
  .github/workflows/publish-new.yml
  .husky/pre-commit
Labels: internal

#1429 [fix] laser pointer
  packages/editor/src/lib/components/DefaultScribble.tsx
  packages/editor/src/lib/components/LiveCollaborators.tsx
Labels: patch

#1397 Measure individual words instead of just line breaks for text exports
  e2e/test/specs/text.ts
  packages/editor/src/lib/app/managers/TextManager.ts
  packages/editor/src/lib/app/shapeutils/TLArrowUtil/TLArrowUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLFrameUtil/TLFrameUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLGeoUtil/TLGeoUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLNoteUtil/TLNoteUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLTextUtil/TLTextUtil.tsx
  packages/editor/src/lib/app/shapeutils/shared/createTextSvgElementFromSpans.ts
  packages/editor/src/lib/app/shapeutils/shared/getTextSvgElement.ts
  packages/editor/src/lib/test/TestApp.ts
  packages/editor/src/lib/test/commands/__snapshots__/getSvg.test.ts.snap
  packages/primitives/api-report.md
  packages/primitives/src/lib/Box2d.ts
  packages/ui/src/lib/hooks/clipboard/pastePlainText.ts
Labels: needs qa, patch

#1430 [refactor] record migrations
  .prettierignore
  packages/editor/src/lib/app/shapeutils/TLArrowUtil/TLArrowUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLBookmarkUtil/TLBookmarkUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLDrawUtil/TLDrawUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLEmbedUtil/TLEmbedUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLFrameUtil/TLFrameUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLGeoUtil/TLGeoUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLGroupUtil/TLGroupUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLImageUtil/TLImageUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLLineUtil/TLLineUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLNoteUtil/TLNoteUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLTextUtil/TLTextUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLVideoUtil/TLVideoUtil.tsx
  packages/editor/src/lib/test/tools/translating.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/package.json
  packages/tlschema/scripts/new-asset.js
  packages/tlschema/scripts/new-record.js
  packages/tlschema/src/assets/TLBookmarkAsset.ts
  packages/tlschema/src/assets/TLImageAsset.ts
  packages/tlschema/src/assets/TLVideoAsset.ts
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/index.ts
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLAsset.ts
  packages/tlschema/src/records/TLCamera.ts
  packages/tlschema/src/records/TLDocument.ts
  packages/tlschema/src/records/TLInstance.ts
  packages/tlschema/src/records/TLInstancePageState.ts
  packages/tlschema/src/records/TLInstancePresence.ts
  packages/tlschema/src/records/TLPage.ts
  packages/tlschema/src/records/TLShape.ts
  packages/tlschema/src/records/TLUser.ts
  packages/tlschema/src/records/TLUserDocument.ts
  packages/tlschema/src/records/TLUserPresence.ts
  packages/tlschema/src/schema.ts
  packages/tlschema/src/shapes/TLArrowShape.ts
  packages/tlschema/src/shapes/TLBookmarkShape.ts
  packages/tlschema/src/shapes/TLDrawShape.ts
  packages/tlschema/src/shapes/TLEmbedShape.ts
  packages/tlschema/src/shapes/TLFrameShape.ts
  packages/tlschema/src/shapes/TLGeoShape.ts
  packages/tlschema/src/shapes/TLGroupShape.ts
  packages/tlschema/src/shapes/TLIconShape.ts
  packages/tlschema/src/shapes/TLImageShape.ts
  packages/tlschema/src/shapes/TLLineShape.ts
  packages/tlschema/src/shapes/TLNoteShape.ts
  packages/tlschema/src/shapes/TLTextShape.ts
  packages/tlschema/src/shapes/TLVideoShape.ts
  packages/tlstore/api-report.md
  packages/tlstore/src/lib/migrate.ts
  packages/tlstore/src/lib/test/defineMigrations.test.ts
  packages/tlstore/src/lib/test/testSchema.v0.ts
  packages/tlstore/src/lib/test/testSchema.v1.ts
Labels: major

#1431 Fix new wobble
  packages/editor/api-report.md
  packages/editor/src/lib/app/App.ts
  packages/editor/src/lib/app/managers/TickManager.ts
  packages/editor/src/lib/app/types/emit-types.ts
Labels: patch

#1432 [refactor] Remove `TLShapeDef`, `getShapeUtilByType`.
  apps/examples/src/3-custom-config/CustomConfigExample.tsx
  apps/examples/src/8-error-boundaries/ErrorBoundaryExample.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/app/App.ts
  packages/editor/src/lib/app/derivations/arrowBindingsIndex.ts
  packages/editor/src/lib/app/managers/SnapManager.ts
  packages/editor/src/lib/app/shapeutils/TLArrowUtil/TLArrowUtil.test.ts
  packages/editor/src/lib/app/shapeutils/TLArrowUtil/TLArrowUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLBookmarkUtil/TLBookmarkUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLDrawUtil/TLDrawUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLEmbedUtil/TLEmbedUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLFrameUtil/TLFrameUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLGeoUtil/TLGeoUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLGroupUtil/TLGroupUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLImageUtil/TLImageUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLLineUtil/TLLineUtil.test.ts
  packages/editor/src/lib/app/shapeutils/TLLineUtil/TLLineUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLNoteUtil/TLNoteUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLShapeUtil.ts
  packages/editor/src/lib/app/shapeutils/TLTextUtil/TLTextUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLVideoUtil/TLVideoUtil.tsx
  packages/editor/src/lib/app/statechart/TLArrowTool/children/Pointing.ts
  packages/editor/src/lib/app/statechart/TLBoxTool/children/Pointing.ts
  packages/editor/src/lib/app/statechart/TLDrawTool/children/Drawing.ts
  packages/editor/src/lib/app/statechart/TLNoteTool/children/Pointing.ts
  packages/editor/src/lib/app/statechart/TLSelectTool/children/Cropping.ts
  packages/editor/src/lib/config/TLShapeDefinition.ts
  packages/editor/src/lib/config/TldrawEditorConfig.tsx
  packages/editor/src/lib/test/commands/flipShapes.test.ts
  packages/editor/src/lib/test/commands/rotateShapes.test.ts
  packages/editor/src/lib/test/resizeBox.test.ts
  packages/editor/src/lib/test/shapeutils.test.ts
  packages/editor/src/lib/test/tools/TLBookmarkUtil.test.ts
  packages/editor/src/lib/test/tools/TLLineTool.test.ts
  packages/editor/src/lib/test/tools/frames.test.ts
  packages/editor/src/lib/test/tools/groups.test.ts
  packages/editor/src/lib/test/tools/translating.test.ts
  packages/editor/src/lib/utils/assets.ts
  packages/editor/src/lib/utils/buildFromV1Document.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/index.ts
  packages/tlschema/src/records/TLShape.ts
  packages/tlstore/api-report.md
  packages/tlstore/src/lib/RecordType.ts
  packages/tlstore/src/lib/StoreSchema.ts
  packages/ui/src/lib/components/EditLinkDialog.tsx
  packages/ui/src/lib/hooks/clipboard/pastePlainText.ts
  packages/ui/src/lib/hooks/menuHelpers.ts
  packages/ui/src/lib/hooks/useActions.tsx
  packages/ui/src/lib/hooks/useClipboardEvents.ts
  packages/ui/src/lib/hooks/useContextMenuSchema.tsx
  packages/ui/src/lib/hooks/useExportAs.ts
  packages/ui/src/lib/hooks/useShowAutoSizeToggle.ts
Labels: major

#1440 [refactor] remove `createTLSchema`
  packages/editor/api-report.md
  packages/editor/src/lib/config/TldrawEditorConfig.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/index.ts
Labels: major

#1416 Add SVG cursors for all cursor types
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/lib/app/statechart/TLSelectTool/children/Idle.ts
  packages/editor/src/lib/hooks/useCursor.ts
  packages/editor/src/lib/utils/debug-flags.ts
  packages/ui/src/lib/components/DebugPanel.tsx
Labels: minor

#1441 Fix cursor shadow getting clipped
  packages/editor/src/lib/hooks/useCursor.ts
Labels: patch

#1444 [refactor] restore createTLSchema
  apps/examples/src/4-custom-ui/CustomUiExample.tsx
  apps/examples/src/5-exploded/ExplodedExample.tsx
  apps/vscode/editor/src/app.tsx
  apps/vscode/extension/src/file.ts
  e2e/test/helpers/ui/app.ts
  packages/editor/api-report.md
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/app/App.ts
  packages/editor/src/lib/app/shapeutils/TLFrameUtil/TLFrameUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLIconUtil/TLIconUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLShapeUtil.ts
  packages/editor/src/lib/app/statechart/TLArrowTool/TLArrowTool.ts
  packages/editor/src/lib/app/statechart/TLArrowTool/children/Pointing.ts
  packages/editor/src/lib/app/statechart/TLLineTool/TLLineTool.ts
  packages/editor/src/lib/app/statechart/TLLineTool/children/Pointing.ts
  packages/editor/src/lib/config/TldrawEditorConfig.tsx
  packages/editor/src/lib/test/TestApp.test.ts
  packages/editor/src/lib/test/TestApp.ts
  packages/editor/src/lib/test/TldrawEditor.test.tsx
  packages/editor/src/lib/utils/buildFromV1Document.ts
  packages/file-format/src/lib/file.ts
  packages/file-format/src/test/file.test.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/index.ts
  packages/tlschema/src/records/TLShape.ts
  packages/tlsync-client/api-report.md
  packages/tlsync-client/src/lib/TLLocalSyncClient.test.ts
  packages/tlsync-client/src/lib/hooks/useLocalSyncClient.ts
Labels: major

#1428 Fix issue template label not getting applied
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: patch

#1443 Add migration for horizontal alignment
  packages/editor/editor.css
  packages/editor/src/lib/app/managers/TextManager.ts
  packages/editor/src/lib/app/shapeutils/TLGeoUtil/TLGeoUtil.tsx
  packages/editor/src/lib/app/shapeutils/TLNoteUtil/TLNoteUtil.tsx
  packages/editor/src/lib/app/shapeutils/shared/TextLabel.tsx
  packages/editor/src/lib/utils/legacy.ts
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/shapes/TLGeoShape.ts
  packages/tlschema/src/shapes/TLNoteShape.ts
  packages/tlschema/src/style-types.ts
  packages/tlschema/src/validation.ts
Labels: needs qa, patch

#1453 update use-gesture
  packages/editor/package.json
  public-yarn.lock
Labels: needs qa, dependencies

#1435 [chore] refactor user preferences
  .github/workflows/webdriver-nightly.yml
  .github/workflows/webdriver-on-demand.yml
  apps/examples/src/11-user-presence/UserPresenceExample.tsx
  apps/examples/src/5-exploded/ExplodedExample.tsx
  apps/vscode/editor/src/ChangeResponder.tsx
  apps/vscode/editor/src/FileOpen.tsx
  apps/vscode/editor/src/app.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/app/App.ts
  packages/editor/src/lib/app/managers/UserPreferencesManager.ts
  packages/editor/src/lib/app/shapeutils/TLLineUtil/TLLineUtil.test.ts
  packages/editor/src/lib/app/shapeutils/TLLineUtil/__snapshots__/TLLineUtil.test.ts.snap
  packages/editor/src/lib/app/shapeutils/shared/ShapeFill.tsx
  packages/editor/src/lib/components/DefaultErrorFallback.tsx
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/config/TldrawEditorConfig.tsx
  packages/editor/src/lib/hooks/useDarkMode.ts
  packages/editor/src/lib/hooks/usePeerIds.ts
  packages/editor/src/lib/hooks/usePresence.ts
  packages/editor/src/lib/test/TestApp.ts
  packages/editor/src/lib/test/TldrawEditor.test.tsx
  packages/editor/src/lib/test/tools/groups.test.ts
  packages/file-format/api-report.md
  packages/file-format/src/lib/file.ts
  packages/file-format/src/test/file.test.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/TLRecord.ts
  packages/tlschema/src/TLStore.ts
  packages/tlschema/src/createPresenceStateDerivation.ts
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/defaultDerivePresenceState.ts
  packages/tlschema/src/index.ts
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLInstance.ts
  packages/tlschema/src/records/TLInstancePresence.ts
  packages/tlschema/src/records/TLPointer.ts
  packages/tlschema/src/records/TLUser.ts
  packages/tlschema/src/records/TLUserDocument.ts
  packages/tlschema/src/records/TLUserPresence.ts
  packages/tlschema/src/schema.ts
  packages/tlschema/src/translations.test.ts
  packages/tlschema/src/translations.ts
  packages/tlschema/src/validation.ts
  packages/tlstore/api-report.md
  packages/tlstore/src/lib/StoreSchema.ts
  packages/tlsync-client/api-report.md
  packages/tlsync-client/src/index.ts
  packages/tlsync-client/src/lib/TLLocalSyncClient.test.ts
  packages/tlsync-client/src/lib/TLLocalSyncClient.ts
  packages/tlsync-client/src/lib/hooks/useLocalSyncClient.ts
  packages/tlsync-client/src/lib/persistence-constants.ts
  packages/ui/src/lib/components/LanguageMenu.tsx
  packages/ui/src/lib/components/NavigationZone/Minimap.tsx
  packages/ui/src/lib/hooks/useMenuSchema.tsx
  packages/ui/src/lib/hooks/useTranslation/useLanguages.tsx
  packages/ui/src/lib/hooks/useTranslation/useTranslation.tsx
Labels: needs qa, major

#1454 change pointer cursor to white
  packages/editor/src/lib/hooks/useCursor.ts
Labels: patch

#1458 Fix positioning of default cursor
  packages/editor/src/lib/hooks/useCursor.ts
Labels: patch

#1461 [fix] page item submenu
  packages/ui/src/lib/components/PageMenu/PageItemSubmenu.tsx
Labels: patch

#1462 [fix] make follow icon visible on iPad
  packages/ui/ui.css
Labels: patch

#1467 Add laser keyboard shortcut.
  packages/ui/src/lib/hooks/useKeyboardShortcutsSchema.tsx
Labels: patch

#1460 [fix] lock option for laser tool
  packages/ui/src/lib/components/Toolbar/ToggleToolLockedButton.tsx
Labels: patch

#1468 [mini-feature] Following indicator
  packages/editor/editor.css
  packages/ui/src/lib/TldrawUi.tsx
  packages/ui/src/lib/components/FollowingIndicator.tsx
Labels: minor

#1471 Fix people menu button border on android
  packages/ui/ui.css
Labels: patch

#1459 Don't allow `g` keyboard shortcut in readonly mode, show laser tool in the toolbar
  e2e/test/helpers/util.ts
  packages/ui/src/lib/components/Toolbar/Toolbar.tsx
  packages/ui/src/lib/hooks/useClipboardEvents.ts
  packages/ui/src/lib/hooks/useCopyAs.ts
  packages/ui/src/lib/hooks/useKeyboardShortcuts.ts
Labels: patch

#1470 remove safari special-casing for paste
  packages/ui/api-report.md
  packages/ui/src/lib/components/ContextMenu.tsx
  packages/ui/src/lib/components/Menu.tsx
  packages/ui/src/lib/hooks/useActions.tsx
  packages/ui/src/lib/hooks/useClipboardEvents.ts
  packages/ui/src/lib/hooks/useContextMenuSchema.tsx
  packages/ui/src/lib/hooks/useMenuSchema.tsx
Labels: patch

#1473 [refactor] update record names
  apps/examples/src/11-user-presence/UserPresenceExample.tsx
  apps/examples/src/5-exploded/ExplodedExample.tsx
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/app/App.ts
  packages/editor/src/lib/app/derivations/shapeIdsInCurrentPage.test.ts
  packages/editor/src/lib/app/derivations/shapeIdsInCurrentPage.ts
  packages/editor/src/lib/app/shapeutils/TLBookmarkUtil/TLBookmarkUtil.tsx
  packages/editor/src/lib/app/statechart/TLSelectTool/children/Translating.ts
  packages/editor/src/lib/config/TldrawEditorConfig.tsx
  packages/editor/src/lib/test/App.test.ts
  packages/editor/src/lib/test/TestApp.ts
  packages/editor/src/lib/test/TldrawEditor.test.tsx
  packages/editor/src/lib/test/commands/createPage.test.ts
  packages/editor/src/lib/test/commands/deletePage.test.ts
  packages/editor/src/lib/test/commands/misc.test.ts
  packages/editor/src/lib/test/commands/moveShapesToPage.test.ts
  packages/editor/src/lib/test/commands/setCurrentPage.test.ts
  packages/editor/src/lib/utils/assets.ts
  packages/editor/src/lib/utils/buildFromV1Document.ts
  packages/file-format/src/test/file.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
  packages/tlschema/src/createPresenceStateDerivation.ts
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/index.ts
  packages/tlschema/src/records/TLAsset.ts
  packages/tlschema/src/records/TLCamera.ts
  packages/tlschema/src/records/TLDocument.ts
  packages/tlschema/src/records/TLInstance.ts
  packages/tlschema/src/records/TLInstancePageState.ts
  packages/tlschema/src/records/TLInstancePresence.ts
  packages/tlschema/src/records/TLPage.ts
  packages/tlschema/src/records/TLPointer.ts
  packages/tlschema/src/records/TLUserDocument.ts
  packages/tlsync-client/src/lib/TLLocalSyncClient.test.ts
  packages/tlsync-client/src/lib/persistence-constants.ts
  packages/ui/src/lib/components/MoveToPageMenu.tsx
  packages/ui/src/lib/components/PageMenu/PageItemSubmenu.tsx
  packages/ui/src/lib/components/PageMenu/PageMenu.tsx
  packages/ui/src/lib/hooks/clipboard/pasteExcalidrawContent.ts
Labels: major

#1481 [minor] Mark tlsync-client internal APIs
  packages/tlsync-client/api-report.md
  packages/tlsync-client/src/index.ts
  packages/tlsync-client/src/lib/TLLocalSyncClient.ts
  packages/tlsync-client/src/lib/alerts.ts
  packages/tlsync-client/src/lib/hardReset.ts
  packages/tlsync-client/src/lib/hooks/useLocalSyncClient.ts
  packages/tlsync-client/src/lib/indexedDb.ts
  packages/tlsync-client/src/lib/persistence-constants.ts
Labels: major

#1482 [tiny] add isPageId
  packages/editor/src/lib/app/App.ts
  packages/editor/src/lib/app/derivations/shapeIdsInCurrentPage.ts
  packages/editor/src/lib/app/statechart/TLSelectTool/children/Translating.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/index.ts
  packages/tlschema/src/records/TLPage.ts
Labels: internal

#1474 Feature flags rework
  apps/examples/vite.config.ts
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/utils/debug-flags.ts
  packages/ui/src/lib/components/DebugPanel.tsx
Labels: patch

#1413 Add DSL to make writing shape-layout test cases much easier
  packages/editor/src/lib/app/derivations/arrowBindingsIndex.test.tsx
  packages/editor/src/lib/test/TestApp.ts
  packages/editor/src/lib/test/commands/alignShapes.test.tsx
  packages/editor/src/lib/test/commands/renderingShapes.test.tsx
  packages/editor/src/lib/test/commands/stretch.test.tsx
  packages/editor/src/lib/test/jsx.tsx
  packages/editor/src/lib/test/tools/select.test.tsx
Labels: tests

#1480 [feature] Easier store persistence API + persistence example
  apps/examples/package.json
  apps/examples/src/14-persistence/PersistenceExample.tsx
  apps/examples/src/index.tsx
  apps/examples/tsconfig.json
  packages/tlstore/api-report.md
  packages/tlstore/src/lib/Store.ts
  packages/tlstore/src/lib/test/recordStore.test.ts
  public-yarn.lock
Labels: minor

#1488 [chore] remove webdriver dependencies / scripts
  .github/workflows/playwright.yml
  package.json
  public-yarn.lock
  scripts/e2e/commands/index.ts
  scripts/e2e/commands/selenium-grid.ts
  scripts/e2e/commands/serve.ts
  scripts/e2e/commands/test-browserstack.ts
  scripts/e2e/commands/test-ci.ts
  scripts/e2e/commands/test-local.ts
  scripts/e2e/commands/util.ts
  scripts/e2e/index.ts
Labels: internal
