Repository tldraw/tldraw, pull requests merged in 2023-12, with the labels that each got.

#2273 Add connecting screen override.
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/default-components/DefaultLoadingScreen.tsx
  packages/editor/src/lib/hooks/useEditorComponents.tsx
Labels: minor

#2265 [improvements] arrows x enclosing shapes x precision.
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/shared/arrow/curved-arrow.ts
  packages/editor/src/lib/editor/shapes/shared/arrow/shared.ts
  packages/editor/src/lib/editor/shapes/shared/arrow/straight-arrow.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeTool.test.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.test.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/DraggingHandle.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteExcalidrawContent.ts
  packages/tldraw/src/test/arrowBindingsIndex.test.tsx
  packages/tldraw/src/test/arrows-megabus.test.ts
  packages/tldraw/src/test/commands/clipboard.test.ts
  packages/tldraw/src/test/commands/deleteShapes.test.ts
  packages/tldraw/src/test/duplicate.test.ts
  packages/tldraw/src/test/flipShapes.test.ts
  packages/tldraw/src/test/translating.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/shapes/TLArrowShape.ts
Labels: minor

#2268 Fix exporting of cropped images.
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/utils/export/copyAs.ts
Labels: needs qa, patch

#2295 Fix an issue with a stale editor reference in shape utils
  packages/editor/src/lib/components/Shape.tsx
Labels: patch

#2275 Add fit to content for frames.
  assets/translations/main.json
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
  packages/tldraw/src/lib/ui/hooks/useContextMenuSchema.tsx
  packages/tldraw/src/lib/ui/hooks/useEventsProvider.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/lib/utils/frames/frames.ts
  packages/tldraw/src/test/frames.test.ts
Labels: minor

#2303 Fix hmr.
  apps/examples/src/index.tsx
Labels: patch

#2293 zoom to affected shapes after undo/redo
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/Editor.test.tsx
Labels: needs qa, patch

#2310 Revert "zoom to affected shapes after undo/redo"
  .github/workflows/checks.yml
  .github/workflows/playwright-update-snapshots.yml
  .github/workflows/playwright.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-manual.yml
  .github/workflows/publish-new.yml
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/Editor.test.tsx
Labels: patch

#2324 VS Code 2.0.19
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: patch

#2322 Use a global singleton for tlstate
  packages/state/api-report.md
  packages/state/api/api.json
  packages/state/src/lib/core/Atom.ts
  packages/state/src/lib/core/Computed.ts
  packages/state/src/lib/core/EffectScheduler.ts
  packages/state/src/lib/core/capture.ts
  packages/state/src/lib/core/index.ts
  packages/state/src/lib/core/isSignal.ts
  packages/state/src/lib/core/transactions.ts
  packages/state/src/lib/core/types.ts
Labels: patch

#2325 Fix downscaling
  packages/tldraw/src/lib/utils/assets/assets.ts
Labels: patch

#2299 Start scrolling if we are dragging close to the window edges.
  assets/translations/main.json
  lerna.json
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/index.ts
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
  packages/editor/src/lib/editor/tools/StateNode.ts
  packages/editor/src/lib/editor/types/event-types.ts
  packages/editor/src/lib/utils/edgeScrolling.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/tools/SelectTool/childStates/Brushing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
  packages/tldraw/src/lib/ui/hooks/useEventsProvider.tsx
  packages/tldraw/src/lib/ui/hooks/useMenuSchema.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/test/TLUserPreferences.test.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/resizing.test.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
  packages/tldraw/src/test/translating.test.ts
Labels: minor

#2327 Fix TSDoc for @tldraw/state
  packages/state/api-report.md
  packages/state/api/api.json
  packages/state/src/lib/core/Atom.ts
  packages/state/src/lib/core/Computed.ts
  packages/state/src/lib/core/EffectScheduler.ts
  packages/state/src/lib/core/__tests__/atom.test.ts
  packages/state/src/lib/core/__tests__/capture.test.ts
  packages/state/src/lib/core/__tests__/computed.test.ts
  packages/state/src/lib/core/capture.ts
  packages/state/src/lib/core/helpers.ts
  packages/state/src/lib/core/index.ts
  packages/state/src/lib/core/isSignal.ts
  packages/state/src/lib/core/transactions.ts
  packages/state/src/lib/core/types.ts
Labels: patch

#2335 Fix indicator radius for bookmarks.
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
Labels: patch

#2332 Call devFreeze on initialData
  packages/store/src/lib/Store.ts
Labels: patch

#2336 Prevent diff mutation
  packages/store/src/lib/Store.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.test.ts
Labels: patch

#2342 Lokalise: Translations update
  assets/translations/cs.json
  assets/translations/de.json
  assets/translations/ko-kr.json
  assets/translations/languages.json
  assets/translations/ru.json
  assets/translations/uk.json
  assets/translations/zh-cn.json
  packages/assets/imports.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/translations/languages.ts
Labels: patch

#2333 Remove deprecated getters
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/HistoryManager.ts
  packages/editor/src/lib/editor/managers/SnapManager.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
  packages/editor/src/lib/editor/tools/StateNode.ts
  packages/editor/src/lib/utils/SharedStylesMap.ts
  packages/state/api-report.md
  packages/state/api/api.json
  packages/state/src/lib/core/Atom.ts
  packages/state/src/lib/core/Computed.ts
  packages/state/src/lib/core/types.ts
Labels: major

#2167 Change licenses to tldraw
  CLA.md
  CONTRIBUTING.md
  LICENSE
  LICENSE.md
  README.md
  TRADEMARKS.md
  apps/examples/LICENSE.md
  apps/examples/README.md
  apps/examples/package.json
  apps/vscode/README.md
  apps/vscode/editor/LICENSE
  apps/vscode/editor/LICENSE.md
  apps/vscode/editor/README.md
  apps/vscode/editor/package.json
  apps/vscode/extension/LICENSE
  apps/vscode/extension/LICENSE.md
  apps/vscode/extension/README.md
  apps/vscode/extension/package.json
  assets/github-hero-light-2.png
  assets/github-hero_dark-2.png
  config/LICENSE
  config/LICENSE.md
  config/package.json
  package.json
  packages/assets/LICENSE
  packages/assets/LICENSE.md
  packages/assets/README.md
  packages/assets/package.json
  packages/editor/LICENSE
  packages/editor/LICENSE.md
  packages/editor/README.md
  packages/editor/package.json
  packages/state/package.json
  packages/store/package.json
  packages/tldraw/LICENSE
  packages/tldraw/LICENSE.md
  packages/tldraw/README.md
  packages/tldraw/package.json
  packages/tlschema/LICENSE
  packages/tlschema/LICENSE.md
  packages/tlschema/README.md
  packages/tlschema/package.json
  packages/utils/LICENSE
  packages/utils/LICENSE.md
  packages/utils/README.md
  packages/utils/package.json
  packages/validate/LICENSE
  packages/validate/LICENSE.md
  packages/validate/README.md
  packages/validate/package.json
  scripts/package.json
Labels: major

#2337 Allow dragging on top of locked shapes.
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: patch

#2330 [bug] Fix for issue #2329
  packages/editor/src/lib/primitives/Matrix2d.ts
Labels: patch

#2345 Fix iconleft padding
  packages/tldraw/src/lib/ui.css
Labels: patch

#2346 Drop edge scrolling adjustment for mobile
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/utils/edgeScrolling.ts
  packages/tldraw/src/test/resizing.test.ts
  packages/tldraw/src/test/translating.test.ts
Labels: patch

#2350 fix png images with pixel ratios <0.5 crashing the app
  packages/utils/src/lib/media.ts
Labels: patch

#2347 Only allow side resizing when we have some shapes that are not aspect ratio locked
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
Labels: patch

#2352 Stop shape text labels being hoverable when context menu is open
  packages/editor/editor.css
Labels: patch

#2358 refactor: Keep hook function convention the same
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/hooks/useEditor.ts
Labels: internal

#2356 fix read only page menu
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/PageMenu/PageMenu.tsx
Labels: patch

#2362 add speech bubble example
  apps/examples/public/speech-bubble.svg
  apps/examples/src/examples/CustomShapeWithHandles/CustomShapeWithHandles.tsx
  apps/examples/src/examples/CustomShapeWithHandles/SpeechBubble/SpeechBubbleTool.tsx
  apps/examples/src/examples/CustomShapeWithHandles/SpeechBubble/SpeechBubbleUtil.tsx
  apps/examples/src/examples/CustomShapeWithHandles/SpeechBubble/helpers.tsx
  apps/examples/src/examples/CustomShapeWithHandles/SpeechBubble/ui-overrides.ts
  apps/examples/src/examples/CustomShapeWithHandles/customhandles.css
  apps/examples/src/index.tsx
Labels: minor

#2364 bump to beta
  lerna.json
  packages/assets/package.json
  packages/editor/package.json
  packages/editor/src/version.ts
  packages/state/package.json
  packages/store/package.json
  packages/tldraw/api/api.json
  packages/tldraw/package.json
  packages/tlschema/package.json
  packages/utils/package.json
  packages/validate/package.json
Labels: major

#2365 Fix license language.
  README.md
Labels: internal

#2366 Another typo fix.
  apps/examples/README.md
  apps/vscode/README.md
  apps/vscode/extension/README.md
  packages/assets/README.md
  packages/editor/README.md
  packages/tldraw/README.md
  packages/tlschema/README.md
  packages/utils/README.md
  packages/validate/README.md
Labels: documentation

#2371 VS Code bump 2.0.20
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: patch

#2370 Adding an image shape from a file the public folder
  apps/examples/public/tldraw.png
  apps/examples/src/examples/HostedImagesExample.tsx
  apps/examples/src/examples/ImagesExamples.tsx
  apps/examples/src/index.tsx
Labels: minor

#2373 Avoid importing `editor.css` twice
  apps/examples/src/examples/only-editor/OnlyEditor.tsx
Labels: patch

#2372 Fix README link typo
  README.md
Labels: documentation

#2378 [fix] polygon bounds
  packages/editor/src/lib/primitives/utils.ts
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
Labels: patch

#2380 Fix trademark links
  apps/examples/README.md
  apps/vscode/README.md
  packages/assets/README.md
  packages/editor/README.md
  packages/tldraw/README.md
  packages/tlschema/README.md
  packages/utils/README.md
  packages/validate/README.md
Labels: documentation

#2389 [fix] Asset versions
  packages/tldraw/setupTests.js
  packages/tldraw/src/lib/ui/version.ts
Labels: patch
