Repository tldraw/tldraw, pull requests merged in 2024-09, with the labels that each got.

#4440 fix context toolbar example container width
  apps/examples/src/examples/context-toolbar/ContextToolbar.tsx
Labels: bugfix

#4441 simplify context toolbar example
  apps/examples/src/examples/context-toolbar/ContextToolbar.tsx
Labels: improvement

#4444 github: start actually closing old issues
  .github/workflows/close-stale-issues.yml
Labels: other

#4442 Rename TLSvgOptions
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/getSvgJsx.tsx
  packages/editor/src/lib/editor/types/misc-types.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/TldrawImage.tsx
  packages/tldraw/src/lib/utils/export/copyAs.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/tldraw/src/lib/utils/export/exportAs.ts
Labels: api

#4435 Allow publishing PR branches to npm for testing
  .github/workflows/publish-branch.yml
  .github/workflows/publish-canary.yml
  scripts/publish-prerelease.ts
Labels: other

#4388 feat(blog): Hook up newsletter form with SendGrid
  apps/docs/components/blog/blog-category-page.tsx
  apps/docs/components/blog/blog-post-page.tsx
  apps/docs/components/common/button.tsx
  apps/docs/components/common/newsletter-signup.tsx
  apps/docs/scripts/submit-newsletter-signup.ts
Labels: feature

#4387 feat(docs): Hook up feedback form with Vercel analytics events
  apps/docs/components/docs/docs-feedback-widget.tsx
Labels: feature

#4445 Update translations
  assets/translations/fa.json
  assets/translations/ru.json
  assets/translations/uk.json
  assets/translations/zh-cn.json
  assets/translations/zh-tw.json
Labels: translations, other

#4448 Rename manually triggered actions
  .github/workflows/publish-manual.yml
  .github/workflows/publish-new.yml
  .github/workflows/trigger-production-build.yml
Labels: other

#4453 Use custom mime types in useInsertMedia hook
  packages/editor/api-report.md
  packages/editor/src/lib/hooks/useIdentity.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/ui/context/TldrawUiContextProvider.tsx
  packages/tldraw/src/lib/ui/hooks/useInsertMedia.ts
Labels: bugfix

#4403 add default <foreignObject> based export for shapes
  apps/docs/content/docs/editor.mdx
  apps/examples/e2e/tests/export-snapshots.spec.tsx
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Bookmarks-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Bookmarks-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Bookmarks-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Bookmarks-light-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Foreign-objects-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Foreign-objects-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Foreign-objects-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Foreign-objects-light-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Images-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Images-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Images-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Images-light-1-chromium-linux.png
  apps/examples/package.json
  apps/examples/public/bonk.webm
  apps/examples/src/examples/ag-grid-shape/DataGridExample.tsx
  apps/examples/src/examples/ag-grid-shape/README.md
  apps/examples/src/misc/end-to-end.tsx
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/getSvgJsx.tsx
  packages/editor/src/lib/editor/types/SvgExportContext.tsx
  packages/editor/src/lib/exports/ExportDelay.tsx
  packages/editor/src/lib/exports/FontEmbedder.ts
  packages/editor/src/lib/exports/StyleEmbedder.ts
  packages/editor/src/lib/exports/domUtils.ts
  packages/editor/src/lib/exports/embedMedia.ts
  packages/editor/src/lib/exports/exportToSvg.tsx
  packages/editor/src/lib/exports/fetchCache.ts
  packages/editor/src/lib/exports/getSvgJsx.tsx
  packages/editor/src/lib/exports/parseCss.test.ts
  packages/editor/src/lib/exports/parseCss.ts
  packages/editor/src/lib/hooks/useContainer.tsx
  packages/editor/src/lib/hooks/useEditorComponents.tsx
  packages/editor/src/lib/options.ts
  packages/editor/src/lib/test/currentToolIdMask.test.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/useAsset.ts
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
  packages/tldraw/src/lib/utils/export/copyAs.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/commands/__snapshots__/getSvgString.test.ts.snap
  packages/tldraw/src/test/commands/getSvgString.test.ts
  packages/utils/api-report.md
  packages/utils/src/lib/media/media.ts
  packages/utils/src/lib/url.ts
  yarn.lock
Labels: improvement

#4432 Fix an issue with firefox
  packages/editor/src/lib/utils/sync/LocalIndexedDb.ts
Labels: bugfix

#4408 Fix an issue with canceling the page name and presence name changes.
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/components/PageMenu/DefaultPageMenu.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageItemInput.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/PeopleMenu.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/UserPresenceEditor.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiInput.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiPopover.tsx
Labels: bugfix

#4458 fix getArcInfo
  packages/tldraw/src/lib/shapes/arrow/curved-arrow.ts
Labels: bugfix

#4455 Serve optimised content from CDN
  .github/workflows/publish-branch.yml
  .gitignore
  packages/tldraw/src/lib/ui/assetUrls.ts
  scripts/lib/upload-static-assets.ts
  scripts/publish-manual.ts
  scripts/publish-new.ts
  scripts/publish-patch.ts
  scripts/publish-prerelease.ts
  scripts/refresh-assets.ts
Labels: other

#4465 Add assetUrls option to TldrawImage
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/TldrawImage.tsx
Labels: api

#4454 Add sleep fn
  .eslintrc.js
  apps/docs/components/docs/docs-feedback-widget.tsx
  apps/docs/utils/ContentVectorDatabase.ts
  apps/examples/e2e/shared-e2e.ts
  apps/examples/e2e/tests/test-camera.spec.ts
  apps/examples/e2e/tests/test-clipboard.spec.ts
  apps/examples/e2e/tests/test-shapes.spec.ts
  apps/examples/e2e/tests/test-smoke.spec.ts
  apps/examples/e2e/tests/test-text.spec.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/exports/ExportDelay.tsx
  packages/editor/src/lib/license/Watermark.tsx
  packages/sync-core/src/lib/ClientWebSocketAdapter.test.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/control.ts
  packages/worker-shared/src/createPersistQueue.ts
Labels: other

#4466 fix bad merge
  apps/docs/components/docs/docs-feedback-widget.tsx
  apps/docs/utils/ContentVectorDatabase.ts
Labels: other

#4467 add deprecation notice to reference docs
  apps/docs/content/docs/sync.mdx
  apps/docs/scripts/functions/getApiMarkdown.ts
Labels: other

#4463 assets: no need for the setTimeout 0 anymore after deep links
  packages/tldraw/src/lib/shapes/shared/useAsset.ts
Labels: bugfix

#4470 Fix escape bug
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/tldraw/src/lib/ui/components/SharePanel/PeopleMenu.tsx
Labels: bugfix

#4472 docs: fix pricing link
  apps/docs/components/navigation/footer.tsx
Labels: other

#4461 csp: turn on; also, add data: for connect-src
  apps/dotcom/scripts/build.ts
  apps/dotcom/src/utils/csp.ts
Labels: other

#4469 File save warning
  apps/dotcom/src/components/LocalEditor.tsx
  packages/tldraw/src/lib/ui.css
Labels: improvement

#4473 docs: nix system theme
  apps/docs/components/common/theme-switch.tsx
Labels: other

#4477 [docs] tighten up header whitespace on desktop
  apps/docs/app/(docs)/[...slug]/page.tsx
  apps/docs/app/legal/[slug]/page.tsx
  apps/docs/components/blog/blog-category-page.tsx
  apps/docs/components/blog/blog-post-header.tsx
  apps/docs/components/blog/blog-post-page.tsx
  apps/docs/components/docs/docs-header.tsx
Labels: other

#4480 [docs] Remove breadcrumbs (for now)
  apps/docs/app/blog/[...slug]/page.tsx
  apps/docs/app/blog/page.tsx
  apps/docs/components/blog/blog-category-page.tsx
  apps/docs/components/blog/blog-post-header.tsx
  apps/docs/components/common/breadcrumbs.tsx
  apps/docs/components/docs/docs-header.tsx
  apps/docs/components/docs/docs-sidebar-menus.tsx
  apps/docs/components/navigation/headings-menu.tsx
Labels: other

#4460 Store bookmark images on our own asset server
  apps/bemo-worker/src/worker.ts
  apps/dotcom-asset-upload/src/worker.ts
  apps/dotcom-worker/package.json
  apps/dotcom-worker/src/routes/extractBookmarkMetadata.tsx
  apps/dotcom-worker/src/types.ts
  apps/dotcom-worker/src/worker.ts
  apps/dotcom/src/utils/createAssetFromUrl.ts
  packages/sync/src/useSyncDemo.ts
  packages/worker-shared/src/bookmarks.ts
  packages/worker-shared/src/handleRequest.ts
  packages/worker-shared/src/index.ts
  packages/worker-shared/src/userAssetUploads.ts
  scripts/deploy-dotcom.ts
Labels: other

#4451 images: dont stop playing a gif on double click
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/test/translating.test.ts
Labels: improvement

#4482 Fix local save warning / watermark
  apps/dotcom/src/components/LocalEditor.tsx
  apps/examples/e2e/tests/test-kbds.spec.ts
  apps/examples/e2e/tests/test-style-panel.spec.ts
  packages/editor/src/lib/license/Watermark.tsx
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/constants.ts
Labels: bugfix

#4483 [docs] improve code block typography
  apps/docs/app/layout.tsx
  apps/docs/components/content/pre.tsx
  apps/docs/tailwind.config.js
Labels: other

#4491 [docs] better icon for 'Reference' nav item
  apps/docs/components/docs/docs-category-menu.tsx
Labels: other

#4492 [docs] remove useless subheadings
  apps/docs/components/marketing/cta-section.tsx
  apps/docs/components/marketing/installation-section.tsx
Labels: other

#4447 Docs tweaks, copy changes
  apps/docs/app/layout.tsx
  apps/docs/app/page.tsx
  apps/docs/components/common/newsletter-signup.tsx
  apps/docs/components/marketing/cta-section.tsx
  apps/docs/components/marketing/details-section.tsx
  apps/docs/components/marketing/installation-section.tsx
  apps/docs/components/marketing/pricing-section.tsx
  apps/docs/components/marketing/request-form.tsx
Labels: other

#4497 Commercial license -> business license
  apps/docs/components/marketing/request-form.tsx
Labels: other

#4498 Lokalise: Translations update
  assets/translations/ko-kr.json
Labels: translations, other

#4500 Delete .github/workflows/publish-canary.yml
  .github/workflows/publish-canary.yml
Labels: other

#4475 Bisect issues using the PR preview links
  apps/dev-tools/LICENSE.md
  apps/dev-tools/package.json
  apps/dev-tools/src/App.tsx
  apps/dev-tools/src/Bisect/Bisect.tsx
  apps/dev-tools/src/Bisect/BisectButton.tsx
  apps/dev-tools/src/Bisect/PrItem.tsx
  apps/dev-tools/src/Bisect/pr-numbers.ts
  apps/dev-tools/src/index.html
  apps/dev-tools/src/main.tsx
  apps/dev-tools/src/styles.css
  apps/dev-tools/src/vite-env.d.ts
  apps/dev-tools/tsconfig.json
  apps/dev-tools/vite.config.ts
  apps/examples/.gitignore
  package.json
  scripts/get-pr-numbers.ts
  yarn.lock
Labels: other

#4502 Fix parsing of older tldraw v2 documents
  packages/tldraw/src/lib/utils/tldr/file.ts
Labels: bugfix

#4489 docs: use permalinks for source urls
  apps/docs/components/docs/docs-header.tsx
  apps/docs/version.ts
  scripts/refresh-assets.ts
Labels: other

#4486 docs: only show edit on github link for docs pages
  apps/docs/components/blog/blog-authors.tsx
  apps/docs/components/blog/blog-post-preview.tsx
  apps/docs/components/docs/docs-article-info.tsx
  apps/docs/components/docs/docs-feedback-widget.tsx
  apps/docs/components/navigation/headings-menu.tsx
  apps/docs/scripts/lib/generateSection.ts
  apps/docs/types/content-types.ts
Labels: other

#4505 fix up privacy policy formatting
  apps/dotcom/PRIVACY_POLICY.md
Labels: other

#4493 Make docs site like 69x faster
  apps/docs/app/(docs)/[...slug]/page.tsx
Labels: other

#4462 paste: fix pasting images from excalidraw
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/external-content.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/__snapshots__/pasteExcalidrawContent.test.tsx.snap
  packages/tldraw/src/lib/ui/hooks/clipboard/excalidraw-test-fixtures/image.json
Labels: bugfix

#4510 Improve loading of files
  packages/store/src/lib/StoreSchema.ts
  packages/store/src/lib/test/upgradeSchema.test.ts
  packages/tldraw/src/lib/utils/tldr/file.ts
Labels: improvement

#4511 hotfix remove bad article
  apps/docs/content/blog/announcing-new-license-and-watermark.mdx
  apps/docs/content/blog/license-update-for-the-tldraw-sdk.mdx
Labels: other

#4513 Fix search on docs
  apps/docs/utils/algolia.ts
Labels: other

#4515 docs: tweak search colors
  apps/docs/components/search/SearchAutocomplete.tsx
Labels: other

#4516 search: use algolia's grouping by section
  apps/docs/components/search/SearchAutocomplete.tsx
  apps/docs/scripts/update-algolia-index.ts
Labels: other

#4517 licenses: add MIT and update GB ones to match US
  apps/docs/LICENSE.md
  apps/examples/LICENSE.md
  packages/state-react/LICENSE.md
  packages/state/LICENSE.md
  packages/store/LICENSE.md
  packages/tlschema/LICENSE.md
  packages/utils/LICENSE.md
  packages/validate/LICENSE.md
  templates/nextjs/LICENSE
  templates/sync-cloudflare/LICENSE
  templates/vite/LICENSE
Labels: other

#4519 search: turn back on in production
  apps/docs/package.json
Labels: other

#4520 docs: fix link
  apps/docs/content/docs/tools.mdx
  apps/docs/types/search-types.ts
Labels: other

#4521 Remove feature flag.
  packages/editor/src/lib/license/LicenseManager.ts
  packages/editor/src/lib/license/Watermark.test.tsx
  packages/editor/src/lib/license/Watermark.tsx
  packages/editor/src/lib/utils/debug-flags.ts
Labels: bugfix

#4501 Use shiki for syntax highlighting in docs
  apps/docs/components/content/code-files.tsx
  apps/docs/components/content/code.tsx
  apps/docs/components/content/index.tsx
  apps/docs/components/content/pre.tsx
  apps/docs/package.json
  yarn.lock
Labels: other

#4524 [fix] container null error
  packages/editor/src/lib/TldrawEditor.tsx
Labels: bugfix

#4525 [fix] build caching i.e. "You have multiple versions of tldraw libraries installed"
  lazy.config.ts
Labels: bugfix

#4508 Add center option to rotateShapesBy
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/utils/rotation.ts
  packages/tldraw/src/test/commands/rotateShapes.test.ts
Labels: api

#4506 Fix a sentry issue with getting arrow bindings
  packages/tldraw/src/lib/bindings/arrow/ArrowBindingUtil.ts
Labels: bugfix

#4535 fix pre-rendering on blog/legal
  apps/docs/app/blog/[...slug]/page.tsx
  apps/docs/app/legal/[slug]/page.tsx
  apps/docs/components/content/embed.tsx
  apps/docs/package.json
  packages/editor/src/lib/exports/FontEmbedder.ts
  yarn.lock
Labels: other

#4545 Add an example of switching to the geo tool.
  apps/examples/src/examples/external-ui-context/ExternalUiContextExample.tsx
  apps/examples/src/examples/external-ui/ExternalUiExample.tsx
Labels: improvement

#4546 Fix footer link in docs.
  apps/docs/components/navigation/footer.tsx
  apps/docs/content/community/license.mdx
  apps/docs/content/legal/tldraw-license.mdx
  apps/docs/scripts/lib/generateSection.ts
Labels: other

#4544 homepage: good wordsmithing
  apps/docs/components/marketing/features-section.tsx
Labels: other

#4549 Fix cloudflare worker error when using tldraw packages
  packages/utils/src/lib/version.ts
Labels: bugfix

#4552 mount sync worker on same domain
  apps/dotcom/client/src/utils/config.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/sync-worker/wrangler.toml
  internal/scripts/deploy-dotcom.ts
Labels: other

#4554 fix simple-server-example
  templates/simple-server-example/.gitignore
  templates/simple-server-example/package.json
  templates/simple-server-example/src/client/App.tsx
  templates/simple-server-example/tsconfig.json
  templates/simple-server-example/yarn.lock
Labels: other

#4553 Serve sync on domain as well as route
  apps/dotcom/sync-worker/wrangler.toml
Labels: other

#4539 Add some additional debugging tools.
  apps/examples/src/hooks/useDebugging.tsx
  apps/examples/src/misc/develop.tsx
  apps/examples/src/misc/diff.ts
Labels: other

#4551 Fix cloudflare sync template deploy
  templates/sync-cloudflare/package.json
  templates/sync-cloudflare/wrangler.toml
  templates/sync-cloudflare/yarn.lock
Labels: bugfix

#4556 fix deploy script
  internal/scripts/lib/deploy.ts
Labels: other

#4557 remove (hopefully) unneeded workers_dev wrangler preview flag
  apps/dotcom/sync-worker/wrangler.toml
Labels: other

#4547 npm: make our React packages consistent
  .yarnrc.yml
  apps/dotcom/client/package.json
  apps/vscode/editor/package.json
  apps/vscode/extension/package.json
  lerna.json
  package.json
  packages/dotcom-shared/package.json
  packages/editor/package.json
  packages/namespaced-tldraw/package.json
  packages/state-react/package.json
  packages/state-react/src/lib/track.test.tsx
  packages/state-react/src/lib/useAtom.test.tsx
  packages/state-react/src/lib/useComputed.test.tsx
  packages/state-react/src/lib/useStateTracking.test.tsx
  packages/state-react/src/lib/useValue.test.tsx
  packages/store/package.json
  packages/sync-core/package.json
  packages/sync/package.json
  packages/tldraw/package.json
  packages/tldraw/src/lib/ui/components/ZoomMenu/DefaultZoomMenu.tsx
  packages/tlschema/package.json
  templates/nextjs/package.json
  templates/sync-cloudflare/package.json
  templates/vite/package.json
  yarn.lock
Labels: other

#4561 Unify licenses.
  apps/vscode/editor/LICENSE.md
  apps/vscode/editor/README.md
  apps/vscode/editor/package.json
  apps/vscode/extension/LICENSE.md
  apps/vscode/extension/README.md
  apps/vscode/extension/package.json
  templates/nextjs/package.json
  templates/simple-server-example/package.json
  templates/sync-cloudflare/package.json
  templates/vite/package.json
Labels: other

#4564 Fix an issue with the dirty state of flags not working after the first change to a file
  apps/vscode/extension/src/WebViewMessageHandler.ts
Labels: bugfix

#4565 Unify links for vs code.
  apps/vscode/editor/src/Links.tsx
  packages/editor/src/lib/license/Watermark.tsx
Labels: improvement

#4559 [sync] Allow doing CRUD directly on the server
  packages/sync-core/api-report.md
  packages/sync-core/src/index.ts
  packages/sync-core/src/lib/TLSocketRoom.ts
  packages/sync-core/src/lib/TLSyncRoom.ts
  packages/sync-core/src/test/TLSyncRoom.test.ts
Labels: feature, api

#4567 hand tool: remove lockable attr
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/tools/HandTool/HandTool.ts
Labels: bugfix

#4446 [feature] isShapeHidden option
  apps/docs/content/docs/editor.mdx
  apps/examples/src/examples/layer-panel/LayerPanelExample.tsx
  apps/examples/src/examples/layer-panel/README.md
  apps/examples/src/examples/layer-panel/ShapeList.tsx
  apps/examples/src/examples/layer-panel/layer-panel.css
  apps/examples/src/examples/layer-panel/snapshot.json
  apps/examples/src/examples/sync-private-content/README.md
  apps/examples/src/examples/sync-private-content/SyncPrivateContentExample.tsx
  apps/examples/src/examples/sync-private-content/Toggle.tsx
  apps/examples/src/examples/sync-private-content/style.css
  apps/examples/src/icons/icons.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/tools/EraserTool/childStates/Erasing.ts
  packages/tldraw/src/lib/tools/EraserTool/childStates/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Brushing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/ScribbleBrushing.ts
  packages/tldraw/src/test/Editor.test.tsx
Labels: feature

#4571 Fix label wrapping
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/arrowLabel.ts
Labels: bugfix

#4580 Fix collaboration shape indicator showing a line through the arrow's label
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
Labels: bugfix

#4584 Add a comment about promise usage for using the clipboard
  apps/dotcom/client/src/utils/clipboard.ts
Labels: other

#4585 [infra] Add get changelog action
  .github/workflows/get-changelog.yml
Labels: other

#4586 fix get-changelog.yml
  .github/workflows/get-changelog.yml
Labels: other

#4587 [infra] try using yarn
  .github/workflows/get-changelog.yml
Labels: other

#4588 [infra] give auto the tags
  .github/workflows/get-changelog.yml
Labels: other

#4590 publish useAsset, tweak docs
  .husky/pre-push
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/options.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/useAsset.ts
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: api

#4591 [sync] tiny perf thing
  packages/sync-core/src/lib/TLSyncRoom.ts
Labels: improvement

#4589 Fix watermark appearance
  packages/editor/src/lib/license/Watermark.tsx
Labels: bugfix

#4593 bug: fix rendering issues on new MacOS 15 / iOS 18
  apps/dotcom/client/styles/globals.css
  apps/examples/src/styles.css
Labels: bugfix

#4594 Update installation.mdx
  apps/docs/content/getting-started/installation.mdx
Labels: other

#4595 Revert "Delete .github/workflows/publish-canary.yml"
  .github/workflows/publish-canary.yml
Labels: other

#4598 fix publish-canary
  .github/workflows/publish-canary.yml
Labels: other

#4601 [botcom] purge prototype leftovers
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/hooks/useShareMenuOpen.ts
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/components/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaErrorPage.tsx
  apps/dotcom/client/src/tla/components/TlaFileGridItem.tsx
  apps/dotcom/client/src/tla/components/TlaFileList.tsx
  apps/dotcom/client/src/tla/components/TlaFileListItem.tsx
  apps/dotcom/client/src/tla/components/TlaListControls.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/unused/TlaDocumentTopZone.tsx
  apps/dotcom/client/src/tla/components/unused/TlaSidebarDebugging.tsx
  apps/dotcom/client/src/tla/hooks/useFileCollaborators.tsx
  apps/dotcom/client/src/tla/hooks/useWorkspace.tsx
  apps/dotcom/client/src/tla/pages/debug.tsx
  apps/dotcom/client/src/tla/pages/drafts.tsx
  apps/dotcom/client/src/tla/pages/file-temp.tsx
  apps/dotcom/client/src/tla/pages/file.tsx
  apps/dotcom/client/src/tla/pages/groups.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  apps/dotcom/client/src/tla/pages/profile.tsx
  apps/dotcom/client/src/tla/pages/shared.tsx
  apps/dotcom/client/src/tla/pages/stars.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  apps/dotcom/client/src/tla/utils/TldrawApp.ts
  apps/dotcom/client/src/tla/utils/schema/TldrawAppFile.ts
  apps/dotcom/client/src/tla/utils/schema/TldrawAppFileEdit.ts
  apps/dotcom/client/src/tla/utils/schema/TldrawAppFileVisit.ts
  apps/dotcom/client/src/tla/utils/schema/TldrawAppGroup.ts
  apps/dotcom/client/src/tla/utils/schema/TldrawAppGroupMembership.ts
  apps/dotcom/client/src/tla/utils/schema/TldrawAppSessionState.ts
  apps/dotcom/client/src/tla/utils/schema/TldrawAppStar.ts
  apps/dotcom/client/src/tla/utils/schema/TldrawAppUser.ts
  apps/dotcom/client/src/tla/utils/schema/TldrawAppWorkspace.ts
  apps/dotcom/client/src/tla/utils/schema/TldrawAppWorkspaceMembership.ts
  apps/dotcom/client/src/tla/utils/schema/TldrawAppWorkspaceVisit.ts
  apps/dotcom/client/src/tla/utils/tldrawAppSchema.ts
  apps/dotcom/client/src/tla/utils/urls.ts
Labels: other

#4602 Remove thumbnail logic
  apps/dotcom/client/src/tla/hooks/useLocalThumbnail.ts
  apps/dotcom/client/src/tla/hooks/useServerThumbnail.ts
  apps/dotcom/thumbnail-server/README.md
  apps/dotcom/thumbnail-server/package.json
  apps/dotcom/thumbnail-server/src/components/ThumbnailEditor.tsx
  apps/dotcom/thumbnail-server/src/index.html
  apps/dotcom/thumbnail-server/src/index.tsx
  apps/dotcom/thumbnail-server/src/routes/file.tsx
  apps/dotcom/thumbnail-server/src/routes/root.tsx
  apps/dotcom/thumbnail-server/src/styles.css
  apps/dotcom/thumbnail-server/tsconfig.json
  apps/dotcom/thumbnail-server/vite.config.ts
  yarn.lock
Labels: other

#4607 docs: fix up horz. scrolling and slow search typing
  apps/docs/app/globals.css
  apps/docs/components/search/index.tsx
Labels: bugfix

#4609 docs: more search fixes on mobile
  apps/docs/components/search/SearchAutocomplete.tsx
  apps/docs/components/search/index.tsx
Labels: bugfix

#4621 [botcom] share menu fixes
  apps/dotcom/client/src/tla/components/TlaIcon/icon.module.css
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/styles/tla.css
Labels: other

#4623 Add canvas mask example
  apps/examples/src/examples/layer-panel/LayerPanelExample.tsx
  apps/examples/src/examples/mask-window/MaskWindowExample.tsx
  apps/examples/src/examples/mask-window/README.md
  apps/examples/src/examples/mask-window/mask-window.css
Labels: other

#4628 [bugfix] respect camera constraints after switching page + setting constraints
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/commands/setCamera.test.ts
  packages/tldraw/src/test/commands/setCurrentPage.test.ts
Labels: bugfix

#4615 Add eslint rule to check that tsdoc params match with function params
  .eslintrc.js
  internal/scripts/lib/eslint-plugin.ts
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/EdgeScrollManager.ts
  packages/editor/src/lib/editor/managers/ScribbleManager.ts
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/state/src/lib/HistoryBuffer.ts
  packages/state/src/lib/transactions.ts
  packages/store/src/lib/RecordType.ts
  packages/store/src/lib/Store.ts
  packages/sync-core/api-report.md
  packages/sync-core/src/lib/TLSyncRoom.ts
  packages/utils/src/lib/file.ts
  packages/utils/src/lib/media/media.ts
Labels: improvement

#4617 [botcom] use tlsync as prototype backend
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/components/RedirectAtRoot.tsx
  apps/dotcom/client/src/tla/components/RequireAuthForUser.tsx
  apps/dotcom/client/src/tla/components/TlaCollaborators/TlaCollaborators.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaFileContent/TlaFileContent.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenuExportPage.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenuSharePage.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/hooks/useAppState.tsx
  apps/dotcom/client/src/tla/hooks/useFileCollaborators.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/pages/auth.tsx
  apps/dotcom/client/src/tla/pages/debug.tsx
  apps/dotcom/client/src/tla/pages/file-temp.tsx
  apps/dotcom/client/src/tla/pages/file.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  apps/dotcom/client/src/tla/pages/profile.tsx
  apps/dotcom/client/src/tla/providers/TlaAppProvider.tsx
  apps/dotcom/client/src/tla/utils/TldrawApp.ts
  apps/dotcom/client/src/tla/utils/local-sync.ts
  apps/dotcom/client/src/tla/utils/urls.ts
  apps/dotcom/sync-worker/dev.sh
  apps/dotcom/sync-worker/migrations/0000_initial_schema.sql
  apps/dotcom/sync-worker/package.json
  apps/dotcom/sync-worker/reset-db.sh
  apps/dotcom/sync-worker/src/TLAppDurableObject.ts
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/r2.ts
  apps/dotcom/sync-worker/src/routes/createRoom.ts
  apps/dotcom/sync-worker/src/routes/createRoomSnapshot.ts
  apps/dotcom/sync-worker/src/routes/getRoomHistory.ts
  apps/dotcom/sync-worker/src/routes/getRoomHistorySnapshot.ts
  apps/dotcom/sync-worker/src/routes/getRoomSnapshot.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/sync-worker/wrangler.toml
  packages/dotcom-shared/package.json
  packages/dotcom-shared/src/index.ts
  packages/dotcom-shared/src/tla-schema/TldrawAppFile.ts
  packages/dotcom-shared/src/tla-schema/TldrawAppFileEdit.ts
  packages/dotcom-shared/src/tla-schema/TldrawAppFileVisit.ts
  packages/dotcom-shared/src/tla-schema/TldrawAppSessionState.ts
  packages/dotcom-shared/src/tla-schema/TldrawAppUser.ts
  packages/dotcom-shared/src/tla-schema/idValidator.ts
  packages/dotcom-shared/src/tla-schema/tldrawAppSchema.ts
  packages/dotcom-shared/tsconfig.json
  packages/sync-core/api-report.md
  packages/sync-core/src/lib/RoomSession.ts
  packages/sync-core/src/lib/TLSyncClient.ts
  packages/sync-core/src/lib/TLSyncRoom.ts
  packages/worker-shared/src/createPersistQueue.ts
  yarn.lock
Labels: other

#4618 chore: refactor safe id
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/exports/getSvgJsx.tsx
  packages/editor/src/lib/hooks/useSafeId.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/utils/export/exportAs.ts
Labels: other

#4630 Fix VS Code `editorPath`
  apps/vscode/extension/src/extension.ts
Labels: bugfix

#4622 Fix watermark link opening twice
  packages/editor/api-report.md
  packages/editor/src/lib/editor/managers/EnvironmentManager.ts
  packages/editor/src/lib/license/Watermark.test.tsx
  packages/editor/src/lib/license/Watermark.tsx
Labels: bugfix

#4616 [botcom] clerk scaffolding
  apps/dotcom/client/package.json
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/components/RequireAuthForUser.tsx
  apps/dotcom/client/src/tla/components/TlaFileContent/TlaFileContent.tsx
  apps/dotcom/client/src/tla/components/TlaFileContent/file.module.css
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenuExportPage.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenuSharePage.tsx
  apps/dotcom/client/src/tla/hooks/useAppState.tsx
  apps/dotcom/client/src/tla/hooks/useAuth.tsx
  apps/dotcom/client/src/tla/hooks/useUser.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/pages/auth.tsx
  apps/dotcom/client/src/tla/pages/debug.tsx
  apps/dotcom/client/src/tla/pages/profile.tsx
  apps/dotcom/client/src/tla/providers/TlaAppLoggedInProvider.tsx
  apps/dotcom/client/src/tla/providers/TlaAppProvider.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  apps/dotcom/client/src/tla/utils/TldrawApp.ts
  apps/dotcom/client/src/utils/csp.ts
  apps/dotcom/sync-worker/package.json
  apps/dotcom/sync-worker/src/utils/auth.ts
  yarn.lock
Labels: other
