Repository tldraw/tldraw, pull requests merged in 2024-08, with the labels that each got.

#4306 [Feature, Example] Text search example and `getText` API
  apps/examples/src/examples/text-search/README.md
  apps/examples/src/examples/text-search/TextSearchExample.tsx
  apps/examples/src/examples/text-search/TextSearchPanel.tsx
  apps/examples/src/examples/text-search/text-search.css
  packages/editor/api-report.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
Labels: feature

#3988 images: show ghost preview image whilst uploading
  apps/dotcom/src/utils/multiplayerAssetStore.ts
  apps/examples/src/examples/hosted-images/HostedImagesExample.tsx
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/lib/editor/Editor.ts
  packages/sync/src/useSyncDemo.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/useAsset.ts
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: improvement, sdk

#4332 fractional indexing: rm the 0 check for indicies, outdated with jitter code
  packages/utils/src/lib/reordering.ts
Labels: bugfix

#4330 bookmark: dont show broken favicon and cleanup HTML entities in title
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/tldraw/src/lib/utils/text/text.ts
Labels: bugfix

#4217 License: add docs
  apps/docs/components/mdx-components/index.ts
  apps/docs/components/mdx-components/license.tsx
  apps/docs/content/getting-started/installation.mdx
  apps/docs/package.json
  apps/docs/tsconfig.json
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/license/LicenseManager.ts
  yarn.lock
Labels: other

#4334 license: allow wildcard to make apex domains also work
  packages/editor/src/lib/license/LicenseManager.test.ts
  packages/editor/src/lib/license/LicenseManager.ts
Labels: improvement

#4340 Fix some broken links in the docs
  apps/docs/content/docs/assets.mdx
  apps/docs/content/docs/sync.mdx
  apps/docs/content/docs/user-interface.mdx
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/examples/src/examples/basic/README.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tlschema/src/records/TLInstance.ts
Labels: other

#4337 Fix flipping of cropped images
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
Labels: bugfix

#4331 Combino fixed text
  packages/tldraw/src/lib/shapes/text/TextShapeTool.test.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Pointing.ts
Labels: bugfix

#4241 Interpolation: draw/highlight points, discrete props
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/tldraw/src/lib/shapes/draw/DrawShapeUtil.tsx
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeUtil.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/interpolate-props.ts
Labels: improvement, api

#4338 video: rm sync that doesn't really work; fix fullscreen rendering
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: bugfix

#4133 Add dialog/toasts example
  apps/examples/src/examples/toasts-and-dialogs/README.md
  apps/examples/src/examples/toasts-and-dialogs/ToastsDialogsExample.tsx
Labels: other

#4348 Disable Pages UI when maxPages === 1
  apps/examples/src/examples/disable-pages/DisablePagesExample.tsx
  apps/examples/src/examples/disable-pages/README.md
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/components/ContextMenu/DefaultContextMenuContent.tsx
  packages/tldraw/src/lib/ui/components/DefaultMenuPanel.tsx
  packages/tldraw/src/lib/ui/hooks/useIsMultiplayer.ts
Labels: api

#4344 Preserve focus search param
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/editor/Editor.ts
Labels: improvement

#4349 Rename `StoreOptions.multiplayerStatus`
  apps/dotcom/src/components/MultiplayerEditor.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/config/createTLStore.ts
  packages/sync/src/useSync.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/components/ContextMenu/DefaultContextMenuContent.tsx
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
  packages/tldraw/src/lib/ui/components/TopPanel/DefaultTopPanel.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/components.tsx
  packages/tldraw/src/lib/ui/hooks/useIsMultiplayer.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
Labels: api

#4345 Gracefully handle deleted tools & actions (remix)
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/docs/tsconfig.json
  apps/dotcom/src/components/FileMenu.tsx
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/components/SnapshotsEditor.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/components/ActionsMenu/DefaultActionsMenuContent.tsx
  packages/tldraw/src/lib/ui/components/HelpMenu/DefaultHelpMenuContent.tsx
  packages/tldraw/src/lib/ui/components/HelperButtons/BackToContent.tsx
  packages/tldraw/src/lib/ui/components/HelperButtons/ExitPenMode.tsx
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
  packages/tldraw/src/lib/ui/components/QuickActions/DefaultQuickActionsContent.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbarContent.tsx
  packages/tldraw/src/lib/ui/components/ZoomMenu/DefaultZoomMenuContent.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuActionCheckboxItem.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuActionItem.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuToolItem.tsx
Labels: improvement

#4356 Make license debug helper return a cleanup function
  apps/examples/src/examples/license-key/LicenseKeyExample.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
Labels: other

#4360 [docs] remove overflow from article body
  apps/docs/app/(docs)/[...slug]/page.tsx
Labels: other

#4361 Hotfix for index keys validation
  packages/utils/src/lib/reordering.ts
Labels: bugfix

#4326 Custom embeds API
  apps/examples/src/examples/custom-embed/CustomEmbedExample.tsx
  apps/examples/src/examples/custom-embed/README.md
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/external-content.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/defaultEmbedDefinitions.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
  packages/tldraw/src/lib/ui/assetUrls.ts
  packages/tldraw/src/lib/ui/components/EmbedDialog.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/useGetEmbedDefinition.ts
  packages/tldraw/src/lib/ui/hooks/useGetEmbedDefinitions.ts
  packages/tldraw/src/lib/utils/embeds/embeds.test.ts
  packages/tldraw/src/lib/utils/embeds/embeds.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/index.ts
  packages/tlschema/src/shapes/TLEmbedShape.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/url.ts
Labels: feature

#4369 feat: Able to pass disable to the Icon when UiMenuContext is in mode 'toolbar'
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuItem.tsx
Labels: bugfix, improvement, feature

#4372 remove bemo worker from dev-app
  package.json
Labels: other

#4373 Remove the document.hasFocus check
  packages/editor/src/lib/TldrawEditor.tsx
Labels: bugfix

#4375 Focus on frames in docs
  apps/docs/components/marketing/demo.tsx
  apps/docs/components/marketing/example.tsx
  apps/docs/components/marketing/features-section.tsx
  apps/docs/scripts/functions/generateSection.ts
Labels: bugfix, improvement

#4376 Event blocking example
  apps/examples/src/examples/event-blocker/EventBlockerExample.tsx
  apps/examples/src/examples/event-blocker/README.md
Labels: other

#4377 Update READMEs.
  CHANGELOG.md
  README.md
  apps/docs/README.md
  apps/examples/README.md
  apps/examples/src/examples/after-create-update-shape/AfterCreateUpdateShapeExample.tsx
  apps/vscode/README.md
  apps/vscode/extension/README.md
  packages/assets/README.md
  packages/editor/CHANGELOG.md
  packages/editor/README.md
  packages/sync-core/src/lib/ClientWebSocketAdapter.ts
  packages/tldraw/CHANGELOG.md
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tlschema/README.md
  packages/utils/README.md
  packages/validate/README.md
  templates/nextjs/LICENSE
  templates/nextjs/README.md
  templates/sync-cloudflare/LICENSE
  templates/sync-cloudflare/README.md
  templates/sync-cloudflare/worker/TldrawDurableObject.ts
  templates/vite/LICENSE
  templates/vite/README.md
Labels: other

#4333 Deep Links
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/dotcom/src/components/ShareMenu.tsx
  apps/dotcom/src/components/SnapshotsEditor.tsx
  apps/dotcom/src/hooks/useLegacyUrlParams.ts
  apps/dotcom/src/hooks/useUrlState.ts
  apps/dotcom/src/utils/sharing.ts
  apps/dotcom/src/utils/useFileSystem.tsx
  apps/examples/src/ExampleWrapper.tsx
  apps/examples/src/examples/deep-links/DeepLinksExample.tsx
  apps/examples/src/examples/deep-links/README.md
  apps/examples/src/examples/sync-custom-shape/SyncDemoShapeExample.tsx
  apps/examples/src/examples/sync-custom-user/SyncCustomUser.tsx
  apps/examples/src/examples/sync-demo/SyncDemoExample.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useScreenBounds.ts
  packages/editor/src/lib/utils/deepLinks.test.ts
  packages/editor/src/lib/utils/deepLinks.ts
  packages/tldraw/src/lib/utils/tldr/file.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/createDeepLink.test.tsx
  packages/tldraw/src/test/handleDeepLink.test.tsx
  packages/tldraw/src/test/registerDeepLinkListener.test.tsx
Labels: improvement, api

#4379 allow loading the sync URI dynamically
  packages/sync/api-report.md
  packages/sync/src/useSync.ts
Labels: api

#4380 Fix cloud rendering with dynamic scale
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/components/GeoShapeBody.tsx
  packages/tldraw/src/lib/shapes/geo/geo-shape-helpers.ts
Labels: bugfix

#4382 fix inky path rendering
  packages/editor/api-report.md
  packages/editor/src/lib/primitives/utils.ts
  packages/tldraw/src/lib/shapes/arrow/curved-arrow.ts
  packages/tldraw/src/lib/shapes/geo/geo-shape-helpers.ts
Labels: bugfix

#4383 Improve some type docs, delete duplicate file
  packages/editor/api-report.md
  packages/editor/src/lib/editor/shapes/shared/resizeBox.ts
  packages/editor/src/lib/editor/types/misc-types.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/resizeBox.ts
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/overrides.ts
Labels: other

#4385 Make rotateShapesBy work on any shapes
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/utils/rotation.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Rotating.ts
  packages/tldraw/src/test/commands/rotateShapes.test.ts
Labels: api

#4384 make arrow labels wrap dynamically
  packages/tldraw/src/lib/shapes/arrow/arrowLabel.ts
Labels: bugfix

#4392 [api] Widen snapshots pit of success
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/config/TLEditorSnapshot.test.ts
  packages/editor/src/lib/config/TLEditorSnapshot.ts
  packages/editor/src/lib/config/TLSessionStateSnapshot.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/TLSessionStateSnapshot.test.ts
  packages/tlschema/src/TLStore.ts
Labels: improvement, api

#4398 Detect multiple installed versions of tldraw packages
  .github/workflows/checks.yml
  package.json
  packages/editor/src/index.ts
  packages/namespaced-tldraw/src/index.ts
  packages/state-react/package.json
  packages/state-react/src/index.ts
  packages/state-react/tsconfig.json
  packages/state/package.json
  packages/state/src/index.ts
  packages/state/tsconfig.json
  packages/store/src/index.ts
  packages/sync-core/src/index.ts
  packages/sync/src/index.ts
  packages/tldraw/src/index.ts
  packages/tlschema/src/index.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/version.test.ts
  packages/utils/src/lib/version.ts
  packages/validate/src/index.ts
  scripts/build-package.ts
  scripts/check-packages.ts
  scripts/check-scripts.ts
  scripts/check-tsconfigs.ts
  scripts/lib/file.ts
  yarn.lock
Labels: api

#4404 fix the box shape tool not exiting the resizing state
  packages/editor/src/lib/editor/tools/BaseBoxShapeTool/children/Pointing.ts
Labels: bugfix

#4397 Fix an error with parsing embed urls.
  packages/tldraw/src/lib/utils/embeds/embeds.ts
Labels: bugfix

#4406 Prevent unhandled promise rejection during strict mode
  apps/examples/src/index.tsx
  packages/editor/src/lib/utils/sync/LocalIndexedDb.ts
Labels: improvement

#4410 inline nanoid
  apps/bemo-worker/package.json
  apps/dotcom-asset-upload/package.json
  apps/dotcom-worker/package.json
  apps/dotcom-worker/src/routes/createRoom.ts
  apps/dotcom-worker/src/routes/createRoomSnapshot.ts
  apps/dotcom/package.json
  apps/images.tldraw.xyz/package.json
  apps/simple-server-example/package.json
  config/jest/node/jest-preset.js
  packages/editor/api-report.md
  packages/editor/package.json
  packages/editor/src/index.ts
  packages/editor/src/lib/config/TLSessionStateSnapshot.ts
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/ClickManager.ts
  packages/editor/src/lib/editor/managers/ScribbleManager.ts
  packages/editor/src/lib/editor/managers/SnapManager/BoundsSnaps.ts
  packages/editor/src/lib/editor/managers/SnapManager/HandleSnaps.ts
  packages/editor/src/lib/utils/uniqueId.ts
  packages/namespaced-tldraw/package.json
  packages/state-react/package.json
  packages/state/package.json
  packages/store/package.json
  packages/store/src/lib/RecordType.ts
  packages/store/src/lib/Store.ts
  packages/sync-core/package.json
  packages/sync-core/src/lib/TLSyncClient.ts
  packages/sync-core/src/test/syncFuzz.test.ts
  packages/sync/package.json
  packages/tldraw/package.json
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.test.tsx
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteExcalidrawContent.test.tsx
  packages/tldraw/src/lib/utils/tldr/buildFromV1Document.test.ts
  packages/tldraw/src/test/groups.test.ts
  packages/tlschema/package.json
  packages/tlschema/src/__tests__/migrationTestUtils.ts
  packages/tlschema/src/records/TLBinding.ts
  packages/tlschema/src/records/TLShape.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/id.ts
  yarn.lock
Labels: improvement

#4409 Improve event tracking
  apps/dotcom/src/components/DocumentName/DocumentName.tsx
  apps/dotcom/src/components/Links.tsx
  apps/dotcom/src/hooks/useOpenUrlAndTrack.ts
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement

#4414 Simplify getting of the text
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: improvement

#4416 chore: license cleanup
  packages/utils/src/lib/id.ts
  packages/utils/src/lib/media/png.ts
Labels: other

#4415 Allow the users to programmatically disable the context menu.
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/components/ContextMenu/DefaultContextMenu.tsx
Labels: improvement

#4412 support tc39 decorators
  apps/apps-script/tsconfig.json
  apps/dotcom/package.json
  apps/dotcom/tsconfig.json
  apps/examples/package.json
  apps/examples/tsconfig.json
  apps/huppy/tsconfig.json
  apps/simple-server-example/package.json
  apps/vscode/editor/tsconfig.json
  apps/vscode/extension/tsconfig.json
  config/tsconfig.base.json
  packages/state/api-report.md
  packages/state/src/lib/Computed.ts
  packages/utils/api-report.md
  packages/utils/src/lib/bind.ts
  packages/utils/src/lib/id.ts
  scripts/build-package.ts
  templates/sync-cloudflare/package.json
  templates/vite/package.json
  yarn.lock
Labels: api

#4424 Fix exports for dark mode frames and flipped images
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Images-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Images-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Images-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Images-light-1-chromium-linux.png
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
Labels: bugfix

#4402 fix: typo in docs
  apps/docs/content/docs/persistence.mdx
Labels: other

#4425 Add custom grid example
  apps/examples/src/examples/custom-grid/CustomGridExample.tsx
  apps/examples/src/examples/custom-grid/README.md
Labels: improvement

#4427 Use base zoom and zoom steps to calculate min and max zoom for pinch gesture
  packages/editor/src/lib/hooks/useGestureEvents.ts
Labels: bugfix

#4433 Fix rendering perf regression
  packages/store/src/lib/Store.ts
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
Labels: bugfix
