Repository tldraw/tldraw, pull requests merged in 2024-11, with the labels that each got.

#4823 error page: have inline icon when offline
  apps/dotcom/client/src/components/ErrorPage/ErrorPage.tsx
Labels: other

#4830 botcom: shareable by default
  packages/dotcom-shared/src/tla-schema/TldrawAppFile.ts
Labels: other

#4833 Call ensureStoreIsUsable after mergeRemoteChanges
  packages/editor/src/lib/utils/sync/TLLocalSyncClient.ts
  packages/store/src/lib/Store.ts
  packages/sync-core/src/lib/TLSyncClient.ts
Labels: improvement

#4842 Try to make the site show up on Google
  apps/dotcom/client/e2e/fixtures/HomePage.ts
  apps/dotcom/client/index.html
  apps/dotcom/client/public/robots.txt
  apps/dotcom/client/public/sitemap.xml
  apps/dotcom/client/src/components/BoardHistoryLog/BoardHistoryLog.tsx
  apps/dotcom/client/src/components/BoardHistorySnapshot/BoardHistorySnapshot.tsx
  apps/dotcom/client/src/main.tsx
  apps/dotcom/client/src/pages/history-snapshot.tsx
  apps/dotcom/client/src/pages/new.tsx
  apps/dotcom/client/src/pages/public-multiplayer.tsx
  apps/dotcom/client/src/pages/public-readonly-legacy.tsx
  apps/dotcom/client/src/pages/public-readonly.tsx
  apps/dotcom/client/src/pages/public-snapshot.tsx
  apps/dotcom/client/src/pages/public-touchscreen-side-panel.tsx
  apps/dotcom/client/src/pages/root.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopRightPanel.tsx
  apps/dotcom/client/styles/core.css
  apps/dotcom/client/styles/globals.css
  apps/dotcom/client/styles/z-board.css
Labels: other

#4844 [botcom] stub more end to end tests
  apps/dotcom/client/e2e/fixtures/tla-test.ts
  apps/dotcom/client/e2e/tests/database.spec.ts
  apps/dotcom/client/e2e/tests/homepage.spec.ts
  apps/dotcom/client/e2e/tests/not-logged-in.spec.ts
  apps/dotcom/client/e2e/tests/sharing.spec.ts
Labels: other

#4795 Better support scale / quality in export utilities
  apps/examples/src/examples/pdf-editor/ExportPdfButton.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/editor/types/misc-types.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/TldrawImage.tsx
  packages/tldraw/src/lib/utils/export/export.ts
Labels: api

#4841 Add option to disable text creation on double click
  packages/editor/api-report.md
  packages/editor/src/lib/options.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
Labels: feature

#4826 dev: restore the loading state for the demo placeholder
  apps/docs/components/marketing/DemoTldraw.tsx
  apps/docs/components/marketing/demo.tsx
Labels: other

#4849 fix id regression
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
Labels: bugfix

#4855 Remove outlines from buttons until we fix radix-ui issues
  packages/editor/editor.css
  packages/tldraw/src/lib/ui.css
Labels: bugfix

#4861 Fix shapes getting stuck in erasing state
  packages/tldraw/src/lib/tools/EraserTool/childStates/Erasing.ts
  packages/tldraw/src/lib/tools/EraserTool/childStates/Pointing.ts
Labels: bugfix

#4834 i18n: wire up strings
  .github/workflows/i18n-download-strings.yml
  .github/workflows/i18n-upload-strings.yml
  .husky/pre-commit
  apps/dotcom/client/package.json
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/components/ErrorPage/ErrorPage.tsx
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/app/i18n.tsx
  apps/dotcom/client/src/tla/components/TlaAccountMenu/TlaAccountMenu.tsx
  apps/dotcom/client/src/tla/components/TlaCloseButton/TlaCloseButton.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopRightPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaPublishEditor.tsx
  apps/dotcom/client/src/tla/components/TlaErrorContent/TlaErrorContent.tsx
  apps/dotcom/client/src/tla/components/TlaFileError/TlaFileError.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaExportTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaInviteTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/file-share-menu-primitives.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSignInButton/TlaSignInButton.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/client/src/tla/hooks/useRaw.ts
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/pages/debug.tsx
  apps/dotcom/client/src/tla/pages/profile.tsx
  apps/dotcom/client/src/tla/pages/settings.tsx
  internal/scripts/i18n-download-strings.ts
  internal/scripts/i18n-upload-strings.ts
  internal/scripts/package.json
  package.json
  yarn.lock
Labels: other

#4870 fonts: fix up preconnect in index.html
  apps/dotcom/client/index.html
Labels: other

#4851 Smart bringForward/sendBackward
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/utils/reorderShapes.ts
  packages/tldraw/src/test/commands/reorderShapes.test.ts
Labels: improvement

#4874 dotcom: use Inter font via a <link> for better Cloudflare optimization
  apps/dotcom/client/index.html
  apps/dotcom/client/styles/globals.css
Labels: other

#4878 Remove dotcom e2e tests for now.
  .github/workflows/playwright-dotcom.yml
Labels: other

#4863 only cache assets from the current deploy
  apps/dotcom/client/package.json
  apps/dotcom/client/scripts/build.ts
  yarn.lock
Labels: other

#4887 Add dev website as an option.
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: improvement

#4885 FE Fixes
  apps/dotcom/client/src/tla/app/zero-polyfill.ts
  apps/dotcom/client/src/tla/components/TlaIcon/TlaIcon.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  apps/dotcom/client/src/tla/utils/urls.ts
Labels: bugfix

#4889 Pin DO and a small refactor
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
Labels: improvement

#4888 Robustify replicator bootup
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/getFetchEverythingSql.ts
  apps/dotcom/zero-cache/docker/000_seed.sql
  apps/dotcom/zero-cache/docker/001_replicator_boot.sql
  apps/dotcom/zero-cache/docker/docker-compose.yml
  apps/dotcom/zero-cache/docker/postgres-logging.conf
  packages/dotcom-shared/src/OptimisticAppStore.ts
  packages/dotcom-shared/src/index.ts
  packages/dotcom-shared/src/tlaSchema.ts
  packages/dotcom-shared/src/types.ts
Labels: other

#4890 Make some keys not updatable.
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/getFetchEverythingSql.ts
  packages/dotcom-shared/src/tlaSchema.ts
Labels: improvement

#4891 fix dev postgres setup
  .prettierignore
  apps/dotcom/sync-worker/wrangler.toml
  apps/dotcom/zero-cache/docker/docker-compose.yml
Labels: other

#4771 make sure copy-as-png comes in at natural size
  apps/examples/e2e/shared-e2e.ts
  apps/examples/e2e/tests/fixtures/fixtures.ts
  apps/examples/e2e/tests/test-clipboard.spec.ts
  apps/examples/e2e/tests/test-context-menu.spec.ts
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuSubmenu.tsx
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteFiles.ts
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  packages/tldraw/src/lib/utils/clipboard.ts
  packages/tldraw/src/lib/utils/export/copyAs.ts
  packages/utils/api-report.md
  packages/utils/src/lib/file.ts
Labels: bugfix

#4899 Remove d1.
  apps/dotcom/sync-worker/dev.sh
  apps/dotcom/sync-worker/migrations/0000_initial_schema.sql
  apps/dotcom/sync-worker/reset-db.sh
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/wrangler.toml
Labels: improvement

#4908 fix postgres setup
  apps/dotcom/zero-cache/.env
  apps/dotcom/zero-cache/.gitignore
  apps/dotcom/zero-cache/package.json
  apps/dotcom/zero-cache/zero.sh
Labels: other

#4875 Snap to grid when creating shapes
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/tools/BaseBoxShapeTool/children/Pointing.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/geo/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/note/NoteShapeTool.test.ts
  packages/tldraw/src/lib/shapes/note/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/test/grid-align-on-create.test.ts
Labels: improvement

#4910 Fix issue.
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
Labels: bugfix

#4911 Make e2e tests run in sequence within a file
  apps/dotcom/client/playwright.config.ts
  apps/examples/e2e/playwright.config.ts
Labels: other

#4913 disable clipboard tests
  apps/examples/e2e/tests/test-clipboard.spec.ts
Labels: other

#4898 Add rate limiting.
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/components/StoreErrorScreen.tsx
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/components/TlaFileError/TlaFileError.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/src/utils/rateLimit.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/sync-worker/wrangler.toml
  packages/dotcom-shared/src/types.ts
  packages/sync-core/api-report.md
  packages/sync-core/src/lib/TLSyncClient.ts
  packages/sync/src/useSync.ts
Labels: improvement

#4872 remove zoom to label
  packages/tldraw/src/lib/shapes/note/noteHelpers.ts
  packages/tldraw/src/lib/tools/SelectTool/selectHelpers.ts
Labels: bugfix

#4925 i18n: disable the debug formatMessage, causing issues with translation at the moment
  apps/dotcom/client/src/tla/app/i18n.tsx
Labels: other

#4930 Permissions example
  apps/examples/src/examples/permissions-example/PermissionsExample.tsx
  apps/examples/src/examples/permissions-example/README.md
Labels: other

#4920 botcom: add react-select for better select menus
  .yarnrc.yml
  apps/dotcom/client/package.json
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaFileError/TlaFileError.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaExportTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaInviteTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/file-share-menu.module.css
  apps/dotcom/client/src/tla/components/TlaSelect/TlaSelect.tsx
  apps/dotcom/client/src/tla/components/TlaSelect/select.module.css
  apps/dotcom/client/src/tla/components/TlaTabs/tabs.module.css
  packages/tldraw/package.json
  yarn.lock
Labels: other

#4852 botcom e2e tests
  .github/workflows/playwright-dotcom.yml
  apps/dotcom/client/e2e/auth.setup.ts
  apps/dotcom/client/e2e/consts.ts
  apps/dotcom/client/e2e/fixtures/Database.ts
  apps/dotcom/client/e2e/fixtures/DeleteFileDialog.ts
  apps/dotcom/client/e2e/fixtures/Editor.ts
  apps/dotcom/client/e2e/fixtures/HomePage.ts
  apps/dotcom/client/e2e/fixtures/ShareMenu.ts
  apps/dotcom/client/e2e/fixtures/Sidebar.ts
  apps/dotcom/client/e2e/fixtures/helpers.ts
  apps/dotcom/client/e2e/fixtures/tla-test.ts
  apps/dotcom/client/e2e/global.setup.ts
  apps/dotcom/client/e2e/tests/database.spec.ts
  apps/dotcom/client/e2e/tests/homepage.spec.ts
  apps/dotcom/client/e2e/tests/not-logged-in.spec.ts
  apps/dotcom/client/e2e/tests/sharing.spec.ts
  apps/dotcom/client/package.json
  apps/dotcom/client/playwright.config.ts
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/scripts/wait-for-docker.sh
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
  apps/dotcom/sync-worker/src/routes/tla/getPublishedFile.ts
  apps/dotcom/zero-cache/dev.sh
  apps/dotcom/zero-cache/package.json
  lazy.config.ts
  package.json
  yarn.lock
Labels: improvement, e2e-tests

#4941 Hubspot form
  apps/docs/app/globals.css
  apps/docs/components/marketing/request-form.tsx
  apps/docs/utils/submit-license-form.ts
Labels: other

#4943 Small cleanup.
  apps/docs/components/marketing/request-form.tsx
Labels: improvement

#4935 Improve panning performance when we have many not shapes and when we are zoomed out
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
Labels: improvement

#4932 Error link blue
  packages/editor/editor.css
  packages/editor/src/lib/components/default-components/DefaultErrorFallback.tsx
Labels: improvement, feature

#4903 fix missing comma in example shape json
  apps/docs/content/docs/shapes.mdx
Labels: bugfix

#4929 Update license references
  templates/nextjs/README.md
  templates/sync-cloudflare/README.md
  templates/vite/README.md
Labels: improvement

#4947 Lokalise: Translations update
  assets/translations/da.json
  assets/translations/ko-kr.json
  assets/translations/languages.json
  assets/translations/so.json
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/editor/api-report.md
  packages/tlschema/api-report.md
  packages/tlschema/src/translations/languages.ts
Labels: improvement

#4865 Examples changes
  apps/examples/src/examples/add-tool-to-toolbar/README.md
  apps/examples/src/examples/custom-ui/README.md
  apps/examples/src/examples/event-blocker/README.md
  apps/examples/src/examples/external-ui-context/README.md
  apps/examples/src/examples/external-ui/README.md
  apps/examples/src/examples/layer-panel/README.md
  apps/examples/src/examples/ui-events/README.md
Labels: improvement

#4950 Clean up what we output.
  apps/dotcom/client/package.json
  apps/dotcom/client/scripts/wait-for-docker.sh
Labels: improvement

#4949 Add jobs to tldraw.dev
  apps/docs/app/jobs/page.tsx
  apps/docs/components/navigation/footer.tsx
Labels: other

#4926 Lazy replicator
  apps/dotcom/client/e2e/fixtures/Database.ts
  apps/dotcom/client/e2e/fixtures/tla-test.ts
  apps/dotcom/client/scripts/wait-for-docker.sh
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/app/zero-polyfill.ts
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/getFetchEverythingSql.ts
  apps/dotcom/sync-worker/src/getPostgres.ts
  apps/dotcom/sync-worker/src/routes/tla/getPublishedFile.ts
  apps/dotcom/sync-worker/src/testRoutes.ts
  apps/dotcom/sync-worker/src/utils/durableObjects.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/zero-cache/docker/002_add_user_id.sql
  internal/scripts/workers/dev.ts
  packages/dotcom-shared/src/OptimisticAppStore.ts
  packages/dotcom-shared/src/tlaSchema.ts
  packages/dotcom-shared/src/types.ts
Labels: other

#4952 Use sign up here.
  apps/dotcom/client/src/tla/components/TlaSignUpButton/TlaSignUpButton.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
Labels: bugfix

#4957 Simplify e2e test running.
  apps/dotcom/client/e2e/fixtures/HomePage.ts
  apps/dotcom/client/package.json
  apps/dotcom/zero-cache/dev.sh
  apps/dotcom/zero-cache/package.json
Labels: improvement

#4956 [botcom] fix sharing defaults
  apps/dotcom/client/e2e/fixtures/ShareMenu.ts
  apps/dotcom/client/e2e/tests/sharing.spec.ts
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaInviteTab.tsx
  apps/dotcom/client/src/tla/components/TlaSelect/TlaSelect.tsx
Labels: other

#4958 Improve the names for duplicated files
  apps/dotcom/client/e2e/tests/homepage.spec.ts
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
Labels: improvement

#4961 [botcom] fix top bar size on desktop
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
Labels: other

#4959 [botcom] fix random remounting
  apps/dotcom/client/e2e/fixtures/Sidebar.ts
  apps/dotcom/client/src/tla/hooks/useUser.tsx
Labels: other

#4963 Make sure the published slugs are unique.
  apps/dotcom/zero-cache/docker/003_make_published_slug_unique.sql
Labels: improvement

#4964 Fix an error when signing out
  apps/dotcom/client/e2e/fixtures/HomePage.ts
  apps/dotcom/client/e2e/fixtures/Sidebar.ts
  apps/dotcom/client/e2e/tests/not-logged-in.spec.ts
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
Labels: bugfix

#4966 [botcom] Nav spacing/typography/alignment fixes
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/styles/tla.css
Labels: other

#4962 Improve the names for files that have no name set
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/app/i18n.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/utils/dates.ts
Labels: improvement

#4976 Increase the wait duration.
  apps/dotcom/client/scripts/wait-for-docker.sh
Labels: improvement

#4978 select: fix up positioning
  apps/dotcom/client/src/tla/components/TlaSelect/TlaSelect.tsx
  apps/dotcom/client/src/tla/components/TlaSelect/select.module.css
Labels: other

#4979 Click / right click on frame headings
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-light-1-chromium-linux.png
  packages/editor/src/lib/editor/Editor.ts
  packages/store/package.json
  packages/store/setupTests.js
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
  packages/tldraw/src/lib/shapes/frame/components/FrameHeading.tsx
  packages/tldraw/src/lib/shapes/frame/frameHelpers.ts
  packages/tldraw/src/lib/shapes/shared/createTextJsxFromSpans.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/test/getShapeAtPoint.test.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: improvement

#4983 Add eslint rule for react-intl.
  apps/dotcom/client/src/components/ErrorPage/ErrorPage.tsx
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaAccountMenu/TlaAccountMenu.tsx
  apps/dotcom/client/src/tla/components/TlaCloseButton/TlaCloseButton.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopRightPanel.tsx
  apps/dotcom/client/src/tla/components/TlaErrorContent/TlaErrorContent.tsx
  apps/dotcom/client/src/tla/components/TlaFileError/TlaFileError.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaExportTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaInviteTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSignInButton/TlaSignInButton.tsx
  apps/dotcom/client/src/tla/components/TlaSignUpButton/TlaSignUpButton.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/utils/dates.ts
  apps/dotcom/client/src/tla/utils/i18n.tsx
  apps/dotcom/client/tsconfig.json
  eslint.config.mjs
Labels: other

#4985 Revert "Add eslint rule for react-intl."
  apps/dotcom/client/src/components/ErrorPage/ErrorPage.tsx
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/app/i18n.tsx
  apps/dotcom/client/src/tla/components/TlaAccountMenu/TlaAccountMenu.tsx
  apps/dotcom/client/src/tla/components/TlaCloseButton/TlaCloseButton.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopRightPanel.tsx
  apps/dotcom/client/src/tla/components/TlaErrorContent/TlaErrorContent.tsx
  apps/dotcom/client/src/tla/components/TlaFileError/TlaFileError.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaExportTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaInviteTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSignInButton/TlaSignInButton.tsx
  apps/dotcom/client/src/tla/components/TlaSignUpButton/TlaSignUpButton.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/utils/dates.ts
  apps/dotcom/client/tsconfig.json
  eslint.config.mjs
Labels: internal

#4965 [botcom] simplify replicator dispatch logic
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/zero-cache/docker/004_guest_column_on_file_state.sql
  packages/dotcom-shared/src/tlaSchema.ts
Labels: other

#4988 Fix invite button on people menu
  apps/dotcom/client/src/components/MultiplayerEditor.tsx
Labels: bugfix

#4968 Fix an issue with rejections not getting sent.
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
Labels: bugfix

#4967 Add a trigger to update the `updatedAt` field when we either update file metadata or the file's contents
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/config.ts
  apps/dotcom/zero-cache/docker/005_update_file_trigger.sql
Labels: improvement

#4973 Use tla user's color and pass it to the editor.
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  packages/dotcom-shared/src/types.ts
Labels: bugfix

#4974 Scroll the sidebar to the top when creating or deleting files
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
Labels: improvement

#4977 Wait for the guest file to be loaded before showing an entry in the sidebar
  apps/dotcom/client/src/tla/app/TldrawApp.ts
Labels: improvement

#4991 Allow custom react providers in SVG exports
  packages/editor/api-report.md
  packages/editor/src/lib/editor/types/SvgExportContext.tsx
  packages/editor/src/lib/options.ts
Labels: api

#4990 [botcom] allow creating rooms quickly
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
Labels: other

#4996 Fix an issue when navigating back to a forgoten file did not restore it.
  apps/dotcom/client/src/tla/app/TldrawApp.ts
Labels: bugfix

#4986 Make sure our tests can test if data was propagated to the server
  apps/dotcom/client/e2e/fixtures/helpers.ts
  apps/dotcom/client/e2e/fixtures/tla-test.ts
  apps/dotcom/client/e2e/tests/homepage.spec.ts
Labels: improvement

#4993 Use partials when mutating
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/app/zero-polyfill.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarRenameInline.tsx
  packages/dotcom-shared/src/OptimisticAppStore.ts
  packages/dotcom-shared/src/tlaSchema.ts
  packages/dotcom-shared/src/types.ts
Labels: bugfix

#4999 Improve mutation rejection toasts
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
Labels: improvement, other

#4994 [botcom] owner info in side bar
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaCollaborator/TlaCollaborator.tsx
  apps/dotcom/client/src/tla/components/TlaCollaborator/collaborator.module.css
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/components/TlaTooltip/TlaTooltip.tsx
  apps/dotcom/client/src/tla/components/TlaTooltip/tooltip.module.css
  apps/dotcom/client/src/tla/components/tla-menu/menu.module.css
  apps/dotcom/client/src/tla/components/tla-menu/tla-menu.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  apps/dotcom/zero-cache/docker/007_update_file_owner_details.sql
  packages/dotcom-shared/src/tlaSchema.ts
Labels: other

#5004 [botcom] Move guest badge to the left
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
Labels: other

#5002 Fix an issue with `firstVisitAt` not getting set
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/app/zero-polyfill.ts
Labels: bugfix

#5006 i18n: better typing and fix tldr file drop
  apps/dotcom/client/src/tla/components/TlaAppMenuGroup/TlaAppMenuGroup.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaExportTab.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/sidebar-shared.ts
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
  apps/dotcom/client/src/tla/utils/i18n.tsx
Labels: other

#5008 Use lower end machines.
  .github/workflows/close-stale-issues.yml
  .github/workflows/dependabot-dedupe.yml
  .github/workflows/deploy-bemo.yml
  .github/workflows/deploy-docs-on-release-edit.yml
  .github/workflows/get-changelog.yml
  .github/workflows/i18n-download-strings.yml
  .github/workflows/i18n-upload-strings.yml
  .github/workflows/playwright-dotcom.yml
  .github/workflows/playwright-update-snapshots.yml
  .github/workflows/prune-preview-deploys.yml
  .github/workflows/publish-templates.yml
  .github/workflows/publish-vscode-extension.yml
  .github/workflows/trigger-production-build.yml
Labels: other

#5013 Fix an issue with drag and dropping the files
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/index.ts
  packages/tlschema/src/records/TLDocument.ts
Labels: bugfix

#5014 [botcom] auto migrations again
  .github/workflows/deploy-dotcom.yml
  .github/workflows/prune-preview-deploys.yml
  apps/docs/package.json
  apps/dotcom/client/package.json
  apps/dotcom/client/playwright.config.ts
  apps/dotcom/client/scripts/wait-for-docker.sh
  apps/dotcom/client/wait-for-postgres.sh
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/getPostgres.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/wrangler.toml
  apps/dotcom/zero-cache/docker/docker-compose.yml
  apps/dotcom/zero-cache/migrate.ts
  apps/dotcom/zero-cache/migrations/000_seed.sql
  apps/dotcom/zero-cache/migrations/001_replicator_boot.sql
  apps/dotcom/zero-cache/migrations/002_add_user_id.sql
  apps/dotcom/zero-cache/migrations/003_make_published_slug_unique.sql
  apps/dotcom/zero-cache/migrations/004_guest_column_on_file_state.sql
  apps/dotcom/zero-cache/migrations/005_update_file_trigger.sql
  apps/dotcom/zero-cache/migrations/006_add_file_soft_delete.sql
  apps/dotcom/zero-cache/migrations/007_update_file_owner_details.sql
  apps/dotcom/zero-cache/package.json
  apps/examples/package.json
  apps/vscode/editor/package.json
  apps/vscode/extension/package.json
  internal/scripts/deploy-dotcom.ts
  internal/scripts/prune-preview-deploys.ts
  package.json
  templates/simple-server-example/package.json
  yarn.lock
Labels: other

#5017 [botcom] undo playwright pipe
  apps/dotcom/client/playwright.config.ts
Labels: other

#5015 Fix the file name flashing with an old value
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/hooks/useAppState.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
Labels: bugfix

#5019 Allow renaming files when pressing enter
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarCreateFileButton.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarRenameInline.tsx
Labels: improvement

#5023 marketing: fix z-index issue with homepage demo
  apps/docs/components/marketing/demo.tsx
Labels: other

#5025 i18n: typing tweak
  apps/dotcom/client/src/tla/utils/i18n.tsx
Labels: other

#5018 Don't trigger navigation if we are already on the correct file page
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
Labels: improvement

#5024 [botcom] add protocol version
  apps/dotcom/client/e2e/fixtures/Database.ts
  apps/dotcom/client/e2e/tests/client-too-old.spec.ts
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/app/zero-polyfill.ts
  apps/dotcom/client/src/tla/components/MaybeForceUserRefresh/MaybeForceUserRefresh.module.css
  apps/dotcom/client/src/tla/components/MaybeForceUserRefresh/MaybeForceUserRefresh.tsx
  apps/dotcom/client/src/tla/hooks/useAppState.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/testRoutes.ts
  apps/dotcom/zero-cache/docker/docker-compose.yml
  packages/dotcom-shared/src/types.ts
Labels: other

#5032 Fix long press bug
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: bugfix

#5033 Hotfix/long press
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: bugfix

#4998 [botcom] Wait 1000s before marking a file as re-visited
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  lerna.json
Labels: other
