Repository tldraw/tldraw, pull requests merged in 2024-06, with the labels that each got.

#3844 Camera Constraints Tests
  packages/tldraw/src/test/commands/setCamera.test.ts
Labels: internal, tests

#3851 npm: improve tldraw package readme
  packages/tldraw/README.md
Labels: internal, dunno

#3830 text labels: address some rendering inconsistencies with the content vs. textarea
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
Labels: bugfix, sdk

#3849 cloudflare: dont cache no-cache headers
  apps/dotcom-asset-upload/src/index.ts
Labels: bugfix, dotcom

#3855 chore: cleanup z-indices so that they're all clearly listed
  packages/editor/editor.css
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/tldraw/src/lib/ui.css
Labels: sdk, chore

#3846 share: make share/fork/copy actions clearer
  apps/dotcom/src/components/DocumentName/DocumentName.tsx
  apps/dotcom/src/components/ShareMenu.tsx
  apps/dotcom/src/utils/sharing.ts
  assets/icons/icon/clipboard-copied.svg
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement, sdk

#3690 Add `select` option to `Editor.groupShapes` and `Editor.ungroupShapes`
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/utils/tldr/buildFromV1Document.ts
  packages/tldraw/src/test/EraserTool.test.ts
  packages/tldraw/src/test/frames.test.ts
  packages/tldraw/src/test/groups.test.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
  packages/tldraw/src/test/translating.test.ts
Labels: improvement, sdk

#3862 [bugfix] Preserve redo stack when selection changes
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix, sdk

#3811 Snapshots pit of success
  apps/docs/content/docs/persistence.mdx
  apps/dotcom/src/components/BoardHistorySnapshot/BoardHistorySnapshot.tsx
  apps/examples/src/examples/image-component/TldrawImageExample.tsx
  apps/examples/src/examples/local-storage/LocalStorageExample.tsx
  apps/examples/src/examples/snapshots/README.md
  apps/examples/src/examples/snapshots/SnapshotExample.tsx
  apps/examples/src/examples/snapshots/snapshot.json
  apps/vscode/extension/src/file.ts
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/config/TLEditorSnapshot.test.ts
  packages/editor/src/lib/config/TLEditorSnapshot.ts
  packages/editor/src/lib/config/TLSessionStateSnapshot.ts
  packages/editor/src/lib/config/createTLStore.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useLocalStore.ts
  packages/editor/src/lib/hooks/useTLStore.ts
  packages/store/api-report.md
  packages/store/src/lib/Store.ts
  packages/store/src/lib/test/recordStore.test.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/TldrawImage.tsx
  packages/tldraw/src/test/Editor.test.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/__tests__/migrationTestUtils.ts
  packages/tlschema/src/index.ts
  packages/tlschema/src/records/TLInstance.ts
Labels: sdk

#3863 Taha/more constraints tests
  packages/tldraw/src/test/commands/setCamera.test.ts
Labels: internal, tests

#3852 editor: register timeouts/intervals/rafs for disposal
  .eslintrc.js
  apps/examples/src/examples/custom-renderer/CustomRenderer.tsx
  apps/examples/src/examples/user-presence/UserPresenceExample.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/editor/src/lib/components/default-components/DefaultErrorFallback.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/ClickManager.ts
  packages/editor/src/lib/editor/managers/TickManager.ts
  packages/editor/src/lib/hooks/useGestureEvents.ts
  packages/editor/src/lib/hooks/useScreenBounds.ts
  packages/editor/src/lib/utils/sync/TLLocalSyncClient.ts
  packages/state/src/lib/core/EffectScheduler.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/TldrawImage.tsx
  packages/tldraw/src/lib/shapes/arrow/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/shared/defaultStyleDefs.tsx
  packages/tldraw/src/lib/tools/SelectTool/DragAndDropManager.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx
  packages/tldraw/src/lib/ui/components/DefaultDebugPanel.tsx
  packages/tldraw/src/lib/ui/components/EditLinkDialog.tsx
  packages/tldraw/src/lib/ui/components/EmbedDialog.tsx
  packages/tldraw/src/lib/ui/components/Minimap/DefaultMinimap.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/DefaultPageMenu.tsx
  packages/tldraw/src/lib/ui/components/Toasts.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiInput.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteTldrawContent.ts
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/tlsync/src/lib/TLSyncClient.ts
  packages/tlsync/src/lib/requestAnimationFrame.polyfill.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/timers.ts
Labels: improvement, sdk

#3870 timeouts: rework effectschedule timeout tracking
  packages/state/src/lib/core/EffectScheduler.ts
  packages/state/src/lib/react/useReactor.ts
Labels: bugfix, sdk

#3832 Add editor notes to the docs
  apps/docs/components/Mdx.tsx
  apps/docs/content/docs/editor.mdx
  apps/docs/package.json
  apps/docs/styles/globals.css
  yarn.lock
Labels: docs, improvement

#3873 Fix drag distance
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/Editor.test.tsx
Labels: bugfix, sdk

#3874 VS Code version bump 2.0.34
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: chore

#3877 Fix pressure
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
Labels: bugfix, sdk

#3879 VS Code 2.0.35
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: chore

#3882 Prevent stale shape data in render
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/components/default-components/DefaultShapeIndicator.tsx
Labels: bugfix, sdk

#3881 security: don't send referrer paths for images and bookmarks
  apps/dotcom/index.html
  apps/dotcom/src/utils/assetUrls.ts
  apps/dotcom/src/utils/createAssetFromFile.ts
  apps/dotcom/src/utils/createAssetFromUrl.ts
  apps/vscode/editor/src/utils/bookmarks.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/defaultStyleDefs.tsx
  packages/tldraw/src/lib/ui/context/asset-urls.tsx
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteFiles.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteUrl.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/tldraw/src/lib/utils/tldr/file.ts
  packages/utils/src/lib/file.ts
  packages/utils/src/lib/media/media.ts
Labels: bugfix, dotcom, sdk

#3875 Editor.blur method
  apps/examples/src/examples/editor-focus/EditorFocusExample.tsx
  apps/examples/src/examples/editor-focus/editor-focus.css
  apps/examples/src/examples/inline-behavior/InlineBehavior.tsx
  apps/examples/src/examples/multiple/MultipleExample.tsx
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/FocusManager.ts
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
Labels: improvement, feature, sdk

#3886 [DX] sensible defaults for createTLStore
  apps/docs/content/docs/persistence.mdx
  apps/examples/src/examples/local-storage/LocalStorageExample.tsx
  apps/vscode/extension/src/file.ts
  packages/editor/api-report.md
  packages/editor/src/lib/config/createTLStore.ts
  packages/tlsync/src/test/TLServer.test.ts
Labels: improvement, sdk

#3876 Add option to navigate to new project from file menu
  apps/dotcom/src/components/FileMenu.tsx
  apps/dotcom/src/pages/new.tsx
  apps/dotcom/src/utils/useFileSystem.tsx
Labels: feature, dotcom

#3871 Bindings onBeforeShapeIsolate?
  apps/examples/src/examples/pin-bindings/PinExample.tsx
  apps/examples/src/examples/sticker-bindings/StickerExample.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/bindings/BindingUtil.ts
  packages/editor/src/lib/editor/derivations/bindingsIndex.ts
  packages/editor/src/lib/options.ts
  packages/tldraw/src/lib/bindings/arrow/ArrowBindingUtil.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/test/bindings.test.tsx
Labels: bugfix, improvement, sdk

#3885 dotcom: desc tweak
  apps/dotcom/index.html
Labels: improvement, dotcom

#3900 Add option for max points per draw shape
  packages/editor/api-report.md
  packages/editor/src/lib/options.ts
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
Labels: feature, sdk

#3898 Open share menu when navigating from create new shared project button
  apps/dotcom/src/components/ShareMenu.tsx
  apps/dotcom/src/hooks/useShareMenuOpen.ts
  apps/dotcom/src/pages/new.tsx
  assets/translations/main.json
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement, dotcom

#3856 bookmark: fix up double request and rework extractor
  apps/dotcom-bookmark-extractor/api/bookmark.ts
  apps/dotcom-bookmark-extractor/lib/unfurl.ts
  apps/dotcom-bookmark-extractor/package.json
  apps/dotcom-bookmark-extractor/tsconfig.json
  apps/dotcom/src/utils/createAssetFromUrl.ts
  apps/vscode/editor/src/utils/bookmarks.ts
  apps/vscode/extension/src/WebViewMessageHandler.ts
  apps/vscode/messages.ts
  package.json
  packages/editor/editor.css
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/HyperlinkButton.tsx
  packages/tldraw/src/lib/shapes/shared/icons-editor.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteUrl.ts
  packages/tldraw/src/test/bookmark-shapes.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/assets/TLBookmarkAsset.ts
  packages/tlschema/src/migrations.test.ts
  yarn.lock
Labels: bugfix, improvement, dotcom

#3906 Fix Content-Security-Policy browser warnings
  apps/dotcom/scripts/build.ts
Labels: bugfix, dotcom

#3907 csp: disable for now
  apps/dotcom/scripts/build.ts
Labels: bugfix, dotcom

#3800 Bindings tests
  apps/examples/src/examples/pin-bindings/PinExample.tsx
  apps/examples/src/examples/sticker-bindings/StickerExample.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/bindings.test.tsx
Labels: tests, sdk

#3891 Cropping undo/redo UX
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/HistoryManager.test.ts
  packages/editor/src/lib/editor/managers/HistoryManager.ts
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/defaultSideEffects.ts
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/SelectTool.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/Crop.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/Cropping.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/PointingCropHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/test/cropping.test.ts
Labels: improvement, sdk

#3910 Fix 'insert media' undo operation
  packages/tldraw/src/lib/ui/hooks/useInsertMedia.ts
Labels: bugfix, sdk

#3914 bookmarks: resolve relative urls
  apps/dotcom-bookmark-extractor/lib/unfurl.ts
  apps/dotcom/src/utils/createAssetFromUrl.ts
  apps/vscode/editor/src/utils/bookmarks.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: bugfix, dotcom

#3918 Add return info to StoreSideEffects methods
  packages/store/src/lib/StoreSideEffects.ts
Labels: sdk, chore

#3919 tests: ugh edit->edit still flaky, skip
  apps/examples/e2e/tests/test-focus.spec.ts
Labels: internal, tests

#3922 VS Code release 2.0.36
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: chore

#3827 assets: make option to transform urls dynamically / LOD
  .github/workflows/deploy.yml
  apps/dotcom/setupTests.js
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/dotcom/src/hooks/useMultiplayerAssets.ts
  apps/dotcom/src/utils/assetHandler.test.ts
  apps/dotcom/src/utils/assetHandler.ts
  apps/dotcom/src/utils/config.ts
  apps/dotcom/src/utils/createAssetFromFile.ts
  apps/dotcom/vite.config.ts
  apps/examples/src/examples/hosted-images/HostedImagesExample.tsx
  apps/examples/src/examples/image-annotator/ImageAnnotationEditor.tsx
  apps/examples/src/examples/local-images/LocalImagesExample.tsx
  apps/examples/src/examples/pdf-editor/PdfEditor.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/misc-types.ts
  packages/state/api-report.md
  packages/state/src/lib/react/index.ts
  packages/state/src/lib/react/useValueDebounced.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/useAsset.ts
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteExcalidrawContent.ts
  packages/tldraw/src/lib/utils/tldr/buildFromV1Document.ts
  packages/tldraw/src/test/Editor.test.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/assets/TLImageAsset.ts
  packages/tlschema/src/assets/TLVideoAsset.ts
  packages/tlschema/src/migrations.test.ts
  scripts/deploy.ts
Labels: feature, sdk

#3911 Fix document name editable in readonly mode
  apps/dotcom/src/components/DocumentName/DocumentName.tsx
Labels: improvement, dotcom

#3924 images: avoid double request for animated images
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/ui/context/asset-urls.tsx
  packages/tldraw/src/lib/utils/export/export.ts
Labels: bugfix, sdk

#3931 Inline documentation links in type excerpts
  apps/docs/components/mdx-components/code.tsx
  apps/docs/components/mdx-components/generic.tsx
  apps/docs/components/mdx-components/index.ts
  apps/docs/scripts/functions/getApiMarkdown.ts
  apps/docs/styles/globals.css
  apps/docs/styles/hljs.css
Labels: docs, improvement

#3935 Generated docs cleanup
  apps/docs/components/ArticleReferenceDocsPage.tsx
  apps/docs/components/mdx-components/api-docs.tsx
  apps/docs/public/icons/code.svg
  apps/docs/scripts/functions/connect.ts
  apps/docs/scripts/functions/generateSection.ts
  apps/docs/scripts/functions/getApiMarkdown.ts
  apps/docs/styles/globals.css
  apps/docs/types/content-types.ts
  apps/docs/utils/addContent.ts
  config/api-extractor.json
Labels: docs, improvement

#3934 image: follow-up fixes for LOD
  apps/dotcom/src/utils/assetHandler.test.ts
  apps/dotcom/src/utils/assetHandler.ts
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/state/api-report.md
  packages/state/src/lib/react/index.ts
  packages/state/src/lib/react/useValueDebounced.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/useAsset.ts
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: bugfix, sdk

#3836 assets: store in indexedDB, not as base64
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/dotcom/src/utils/assetHandler.test.ts
  apps/dotcom/src/utils/assetHandler.ts
  apps/dotcom/src/utils/cloneAssetForShare.ts
  apps/dotcom/src/utils/sharing.ts
  apps/dotcom/src/utils/useFileSystem.tsx
  apps/vscode/editor/src/ChangeResponder.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/misc-types.ts
  packages/tldraw/api-report.md
  packages/tldraw/package.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/AssetBlobStore.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/tldraw/src/lib/utils/tldr/file.ts
  packages/validate/src/lib/validation.ts
  yarn.lock
Labels: improvement, sdk

#3921 Uploading the static assets to R2 bucket
  scripts/publish-canary.ts
  scripts/publish-manual.ts
  scripts/publish-new.ts
  scripts/publish-patch.ts
  scripts/upload-static-assets.ts
Labels: internal, tools

#3941 Fix uploading static assets to r2
  .github/workflows/publish-canary.yml
  .github/workflows/publish-manual.yml
  .github/workflows/publish-new.yml
  .github/workflows/publish-patch.yml
Labels: bugfix, internal

#3933 Flatten shapes to image(s)
  assets/translations/main.json
  packages/editor/api-report.md
  packages/editor/src/lib/options.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/components/ContextMenu/DefaultContextMenuContent.tsx
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useFlatten.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: feature, sdk

#3913 Make ArrowBindingUtil public
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/bindings/arrow/ArrowBindingUtil.ts
Labels: feature, sdk

#3912 [tiny] getSnapshot and loadSnapshot on Editor class
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
Labels: improvement, sdk

#3927 assets: preload fonts
  apps/dotcom/index.html
  apps/dotcom/scripts/build.ts
  apps/examples/src/examples/exploded/ExplodedExample.tsx
  apps/examples/src/examples/local-storage/LocalStorageExample.tsx
  apps/vscode/editor/src/app.tsx
  packages/editor/src/lib/components/default-components/DefaultSpinner.tsx
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/TldrawImage.tsx
Labels: improvement, dotcom

#3953 assets: add crossorigin tag for preloaded fonts
  apps/dotcom/scripts/build.ts
Labels: bugfix, dotcom

#3954 assets: fix up videos with indexedDB
  apps/dotcom/src/utils/assetHandler.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: bugfix, sdk

#3955 bookmark: css tweaks
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
Labels: bugfix, sdk

#3905 Set up automatic VS Code publishing
  .github/workflows/publish-vscode-extension.yml
  apps/vscode/extension/package.json
  scripts/publish-vscode-extension.ts
Labels: tools

#3950 Improve edge scrolling
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/EdgeScrollManager.ts
  packages/editor/src/lib/options.ts
  packages/editor/src/lib/utils/edgeScrolling.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Brushing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/test/commands/setCamera.test.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
  packages/tldraw/src/test/translating.test.ts
Labels: improvement, sdk

#3703 [Experiment] Allow users to use system's appearance (dark / light) mode
  apps/examples/e2e/tests/export-snapshots.spec.ts
  apps/examples/e2e/tests/test-kbds.spec.ts
  apps/examples/src/examples/image-component/TldrawImageExample.tsx
  assets/translations/main.json
  packages/editor/api-report.md
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
  packages/editor/src/lib/test/user.test.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/components/ColorSchemeMenu.tsx
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/lib/utils/tldr/file.ts
  packages/tldraw/src/test/TLUserPreferences.test.ts
Labels: improvement, sdk

#3959 assets: fix copy/paste with missing src
  packages/tldraw/src/lib/shapes/shared/useAsset.ts
Labels: bugfix, sdk

#3962 Fix draw shape indicators for pen-drawn solid shapes
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/examples/src/misc/develop.tsx
  packages/tldraw/src/lib/shapes/draw/getPath.ts
Labels: bugfix, sdk

#3965 Fix asset positions
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: bugfix, sdk

#3963 Fix solid style draw shape.
  packages/tldraw/src/lib/shapes/geo/components/GeoShapeBody.tsx
Labels: bugfix, sdk

#3966 Add fill fill style.
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: feature, sdk

#3967 images: make isAnimated check on shared rooms work better
  apps/dotcom/src/hooks/useMultiplayerAssets.ts
  apps/dotcom/src/utils/createAssetFromFile.ts
Labels: bugfix, sdk

#3968 flattening: use correct id for asset
  packages/tldraw/src/lib/ui/hooks/useFlatten.ts
Labels: bugfix, sdk

#3970 lod: dont resize images that are culled
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/useAsset.ts
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: improvement, sdk

#3972 lod: dont transform SVGs
  apps/dotcom/src/utils/assetHandler.test.ts
  apps/dotcom/src/utils/assetHandler.ts
  packages/utils/api-report.md
  packages/utils/src/lib/media/media.ts
Labels: improvement, dotcom

#3973 Fix edge scrolling at odd browser zoom levels
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix, sdk

#3975 Fix border color for following user
  packages/editor/src/lib/hooks/usePresence.ts
Labels: bugfix, sdk

#3976 Fix vs code publishing
  scripts/publish-vscode-extension.ts
Labels: tools

#3977 Hotfix to publish vs code
  scripts/publish-vscode-extension.ts
Labels: tools

#3981 Add a new environment for publishing
  .github/workflows/publish-vscode-extension.yml
Labels: tests

#3990 Update license in readme of the store package
  packages/store/README.md
Labels: docs, chore

#3991 theme: rename color scheme to theme
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/components/ColorSchemeMenu.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement, sdk

#4001 Fix multiple editor instances issue
  apps/examples/src/index.tsx
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/editor/managers/TextManager.ts
  packages/tldraw/src/test/TldrawEditor.test.tsx
Labels: bugfix, sdk

#4003 clipboard: fix copy/paste on Firefox
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: bugfix, sdk

#4008 clipboard: fix copy/paste bad typo, ugh
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: bugfix, sdk

#4012 better auto-generated docs for Tldraw and TldrawEditor
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/config/createTLStore.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: docs, improvement, sdk

#4007 editing: don't allow editing locked shapes when edit→edit mode.
  packages/tldraw/src/lib/tools/SelectTool/childStates/EditingShape.ts
Labels: bugfix, sdk

#4014 assets: mark assetOptions as internal
  packages/editor/api-report.md
  packages/editor/src/lib/TldrawEditor.tsx
Labels: sdk, chore

#3957 Do a pre-release of the VS code extension for merges to main.
  .github/workflows/publish-vscode-extension.yml
  apps/vscode/extension/package.json
  apps/vscode/extension/scripts/package.ts
  apps/vscode/extension/scripts/publish.ts
  scripts/publish-vscode-extension.ts
Labels: tools

#4015 Better docs search
  apps/docs/app/api/search/route.ts
Labels: docs, improvement

#4016 dx: PR labels re-revamp
  .eslintignore
  .github/pull_request_template.md
  apps/huppy/src/flows/enforcePrLabels.tsx
  scripts/lib/auto-plugin.js
  scripts/lib/labels.ts
Labels: internal, dunno

#3952 csp: add content security policy for dotcom
  .github/workflows/deploy.yml
  apps/dotcom-worker/src/lib/types.ts
  apps/dotcom/scripts/build.ts
  scripts/deploy.ts
Labels: improvement, dotcom

#3979 local assets: make sure hard reset also clears out new asset db
  packages/editor/src/lib/utils/sync/indexedDb.ts
  packages/tldraw/src/lib/AssetBlobStore.ts
Labels: bugfix, sdk

#4024 Fix `<InFrontOfTheCanvas/>`
  packages/editor/editor.css
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/tldraw/src/lib/ui/TldrawUi.tsx
Labels: bugfix, sdk

#4025 Add fog of war example
  apps/examples/src/examples/fog-of-war/FogOfWarExample.tsx
  apps/examples/src/examples/fog-of-war/README.md
Labels: docs, improvement

#4029 csp: report-only for now
  apps/dotcom/scripts/build.ts
Labels: other

#4030 fix dotcom worker bundle size
  packages/tlsync/src/lib/TLSocketRoom.ts
Labels: other

#4020 Cleanup z-indices
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/dotcom/styles/z-board.css
  apps/examples/src/examples/multiple/MultipleExample.tsx
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/index.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/editor/src/lib/hooks/useEditor.ts
  packages/editor/src/lib/hooks/useEditorComponents.tsx
  packages/tldraw/src/lib/ui.css
Labels: bugfix, sdk

#4032 check worker bundle sizes
  .github/workflows/checks.yml
  .gitignore
  apps/dotcom-worker/package.json
  apps/health-worker/package.json
  scripts/check-worker-bundle.ts
  yarn.lock
Labels: other

#4034 Don't select child of selected shape on right click
  apps/dotcom/src/utils/remote-sync/ClientWebSocketAdapter.test.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/test/SelectTool.test.ts
  packages/tldraw/src/test/groups.test.ts
Labels: bugfix

#3974 Improve filled draw shaped in dynamic size mode
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
Labels: improvement, dotcom

#4037 Fix empty edit context menu
  packages/tldraw/src/lib/ui/components/menu-items.tsx
Labels: bugfix

#3996 Layout constraints example
  apps/examples/src/examples/layout-bindings/LayoutExample.tsx
  apps/examples/src/examples/layout-bindings/README.md
  apps/examples/src/examples/layout-bindings/snapshot.json
Labels: docs, feature

#4038 Update pull_request_template.md
  .github/pull_request_template.md
  scripts/lib/labels.ts
  scripts/update-pr-template.ts
Labels: other

#4043 Add shape change examples
  apps/examples/src/examples/prevent-instance-change/PreventInstanceChangeExample.tsx
  apps/examples/src/examples/prevent-instance-change/README.md
  apps/examples/src/examples/prevent-shape-change/PreventShapeChangeExample.tsx
  apps/examples/src/examples/prevent-shape-change/README.md
Labels: other
