Repository tldraw/tldraw, pull requests merged in 2024-12, with the labels that each got.

#5038 Incremental derivation example
  apps/examples/package.json
  apps/examples/src/examples/derived-view/DerivedViewExample.tsx
  apps/examples/src/examples/derived-view/README.md
  apps/examples/tsconfig.json
  yarn.lock
Labels: other

#5044 [dotcom] Handle max connections properly
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/components/StoreErrorScreen.tsx
  apps/dotcom/client/src/tla/components/TlaFileError/TlaFileError.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  packages/sync-core/api-report.md
  packages/sync-core/src/lib/TLSyncClient.ts
Labels: improvement

#5046 Fix the offline indicator
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor.module.css
  apps/dotcom/client/src/tla/styles/tla.css
Labels: bugfix

#5042 [botcom] Set document title from file name
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
Labels: other

#5048 workflow: up checks.yml power
  .github/workflows/checks.yml
Labels: other

#5049 [botcom] Add import / save as tldr file.
  apps/dotcom/client/public/tla/icon-import.svg
  apps/dotcom/client/src/tla/components/TlaAccountMenu/TlaAccountMenu.tsx
  apps/dotcom/client/src/tla/components/TlaAppMenuGroup/TlaAppMenuGroup.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: other

#5050 [botcom] Remove unused overlay CSS
  apps/dotcom/client/src/tla/components/TlaEditor/editor.module.css
Labels: other

#5027 Fix custom embed first render
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
Labels: bugfix

#5053 Don't run on forks.
  .github/workflows/playwright-dotcom.yml
Labels: improvement

#5010 Make sure notes snap to grid after position is updated
  packages/tldraw/src/lib/shapes/note/toolStates/Pointing.ts
Labels: bugfix

#5055 Create a utility type for making undefined properties optional
  packages/tlschema/api-report.md
  packages/tlschema/src/recordsWithProps.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/types.ts
  packages/validate/api-report.md
  packages/validate/src/index.ts
  packages/validate/src/lib/validation.ts
Labels: other

#5054 Simplify.
  .github/workflows/playwright-dotcom.yml
Labels: improvement

#5022 Fix some export bugs
  .github/workflows/playwright-update-snapshots.yml
  apps/examples/e2e/tests/export-snapshots.spec.tsx
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Regressions-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Regressions-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Regressions-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Regressions-light-1-chromium-linux.png
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/editor/src/lib/exports/exportToSvg.tsx
  packages/editor/src/lib/exports/getSvgJsx.tsx
  packages/tldraw/src/lib/shapes/shared/defaultStyleDefs.tsx
Labels: bugfix

#5056 Move to job level.
  .github/workflows/playwright-dotcom.yml
Labels: improvement

#5041 Expand helpers available in actions / toasts overrides.
  apps/examples/src/examples/action-overrides/ActionOverridesExample.tsx
  apps/examples/src/examples/action-overrides/README.md
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
  packages/tldraw/src/lib/ui/overrides.ts
Labels: api

#5061 assets: fix up resolving when copy/pasting multiple items; also, videos
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/shapes/shared/useImageOrVideoAsset.ts
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: bugfix

#5066 tldraw.dev landing page dark mode fixes
  apps/docs/components/marketing/demo.tsx
  apps/docs/components/marketing/watermark-image.tsx
  apps/docs/public/images/ui-placeholder/lg-bc-dark.png
  apps/docs/public/images/ui-placeholder/lg-bc.jpg
  apps/docs/public/images/ui-placeholder/lg-bc.png
  apps/docs/public/images/ui-placeholder/lg-bl-dark.png
  apps/docs/public/images/ui-placeholder/lg-bl.jpg
  apps/docs/public/images/ui-placeholder/lg-bl.png
  apps/docs/public/images/ui-placeholder/lg-tl-dark.png
  apps/docs/public/images/ui-placeholder/lg-tl.jpg
  apps/docs/public/images/ui-placeholder/lg-tl.png
  apps/docs/public/images/ui-placeholder/lg-tr-dark.png
  apps/docs/public/images/ui-placeholder/lg-tr.jpg
  apps/docs/public/images/ui-placeholder/lg-tr.png
  apps/docs/public/images/ui-placeholder/sm-bc-dark.png
  apps/docs/public/images/ui-placeholder/sm-bc.jpg
  apps/docs/public/images/ui-placeholder/sm-bc.png
  apps/docs/public/images/ui-placeholder/sm-tl-dark.png
  apps/docs/public/images/ui-placeholder/sm-tl.jpg
  apps/docs/public/images/ui-placeholder/sm-tl.png
Labels: other

#5068 i18n: cleanup some missings strings; rework automation
  .github/workflows/i18n-download-strings.yml
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaAppMenuGroup/TlaAppMenuGroup.tsx
  apps/dotcom/client/src/tla/components/TlaDebugMenuGroup.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
Labels: other

#5029 fix: Updating shape props to undefined when using editor.updateShape
  packages/editor/src/lib/editor/Editor.test.ts
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix

#5057 Improve rerenedring of the page menu and quick actions
  packages/editor/src/lib/editor/Editor.ts
  packages/store/src/lib/StoreQueries.ts
  packages/tldraw/src/lib/ui/components/QuickActions/DefaultQuickActionsContent.tsx
Labels: improvement

#5028 Add gecko analytics
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/src/utils/analytics.ts
Labels: other

#5075 [botcom] cache file record in file DO
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
Labels: other

#5073 [botcom] retry user requests on connection failure
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/src/utils/retryOnConnectionFailure.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/retry.ts
Labels: other

#5059 [botcom] slurp local files on sign in
  apps/bemo-worker/src/BemoDO.ts
  apps/dotcom/client/public/tla/icon-external.svg
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/ExternalLink/ExternalLink.module.css
  apps/dotcom/client/src/tla/components/ExternalLink/ExternalLink.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/SlurpFailure.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaIcon/TlaIcon.tsx
  apps/dotcom/client/src/tla/components/TlaIcon/icon.module.css
  apps/dotcom/client/src/tla/hooks/useAppState.tsx
  apps/dotcom/client/src/tla/pages/local-file.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  apps/dotcom/client/src/tla/utils/slurping.tsx
  apps/dotcom/client/src/tla/utils/temporary-files.ts
  apps/dotcom/client/src/tla/utils/urls.ts
  apps/dotcom/client/src/utils/multiplayerAssetStore.test.ts
  apps/dotcom/client/src/utils/multiplayerAssetStore.ts
  apps/dotcom/client/src/utils/scratch-persistence-key.ts
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/utils/sync/LocalIndexedDb.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/ExecutionQueue.test.ts
  packages/utils/src/lib/ExecutionQueue.ts
  packages/worker-shared/src/index.ts
Labels: other

#5077 [botcom] fix noop file name edit interaction
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
Labels: other

#5079 Localize `Untitled project`
  apps/dotcom/client/public/tla/locales-compiled/sl.json
  apps/dotcom/client/public/tla/locales/sl.json
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  lazy.config.ts
Labels: bugfix

#5080 [botcom] use editor bg as page bg to make loading states less funky
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/sidebar-layout.module.css
Labels: other

#5072 Update landing page
  apps/docs/app/buy/business/page.tsx
  apps/docs/app/buy/page.tsx
  apps/docs/app/buy/startup-lite/page.tsx
  apps/docs/app/buy/startup/page.tsx
  apps/docs/app/globals.css
  apps/docs/app/page.tsx
  apps/docs/app/pricing/page.tsx
  apps/docs/components/marketing/DisclosureToggle.tsx
  apps/docs/components/marketing/case-studies-section.tsx
  apps/docs/components/marketing/cta-section.tsx
  apps/docs/components/marketing/demo.tsx
  apps/docs/components/marketing/details-section.tsx
  apps/docs/components/marketing/faq-section.tsx
  apps/docs/components/marketing/features-section.tsx
  apps/docs/components/marketing/hero-section.tsx
  apps/docs/components/marketing/installation-section.tsx
  apps/docs/components/marketing/logo-section.tsx
  apps/docs/components/marketing/masked-logo.tsx
  apps/docs/components/marketing/pricing-button.tsx
  apps/docs/components/marketing/pricing-section.tsx
  apps/docs/components/marketing/request-form.tsx
  apps/docs/components/marketing/section.tsx
  apps/docs/components/marketing/testimonials-section.tsx
  apps/docs/components/marketing/watermark-section.tsx
  apps/docs/components/navigation/header.tsx
  apps/docs/public/images/case-studies/legend-keeper-logo.png
  apps/docs/public/images/case-studies/legend-keeper.png
  apps/docs/public/images/logos/autodesk-logo.svg
  apps/docs/public/images/logos/axa-logo.svg
  apps/docs/public/images/logos/bbb-logo.svg
  apps/docs/public/images/logos/bigbluebutton-logo.svg
  apps/docs/public/images/logos/cadchat-logo.svg
  apps/docs/public/images/logos/clickup-logo.svg
  apps/docs/public/images/logos/craft-logo.svg
  apps/docs/public/images/logos/encube-logo.svg
  apps/docs/public/images/logos/fev-logo.svg
  apps/docs/public/images/logos/fevtutor-logo.svg
  apps/docs/public/images/logos/formitize-logo.svg
  apps/docs/public/images/logos/glean-logo.svg
  apps/docs/public/images/logos/jam-logo.svg
  apps/docs/public/images/logos/legendkeeper-logo.svg
  apps/docs/public/images/logos/lex-logo.svg
  apps/docs/public/images/logos/matilda-logo.svg
  apps/docs/public/images/logos/padlet-logo.svg
  apps/docs/public/images/logos/pixelpaper-logo.svg
  apps/docs/public/images/logos/roam-logo.svg
  apps/docs/public/images/testimonials/Kn6-6wdi_400x400.jpg
  apps/docs/public/images/testimonials/matt_palmer.jpg
  apps/docs/public/logos/centricsoftware.jpg
  apps/docs/public/logos/doozy.jpg
  apps/docs/public/logos/gamma.jpg
  apps/docs/public/logos/logo-1.jpg
  apps/docs/public/logos/logo-2.jpg
  apps/docs/public/logos/logo-3.jpg
  apps/docs/public/logos/roam.jpg
  apps/docs/public/logos/switchboard.jpg
Labels: other

#5082 Update landing page x2
  apps/docs/app/not-found.tsx
  apps/docs/components/common/newsletter-signup.tsx
  apps/docs/components/docs/docs-category-menu.tsx
  apps/docs/components/marketing/DisclosureToggle.tsx
  apps/docs/components/marketing/cta-section.tsx
  apps/docs/components/marketing/details-section.tsx
  apps/docs/components/marketing/faq-section.tsx
  apps/docs/components/marketing/features-section.tsx
  apps/docs/components/marketing/hero-section.tsx
  apps/docs/components/marketing/installation-section.tsx
  apps/docs/components/marketing/pricing-section.tsx
  apps/docs/components/marketing/testimonials-section.tsx
  apps/docs/components/marketing/watermark-section.tsx
Labels: other

#5083 Tweak logos
  apps/docs/components/marketing/logo-section.tsx
Labels: other

#5084 Cleanup social images
  README.md
  apps/docs/app/opengraph-image.alt.txt
  apps/docs/app/opengraph-image.jpg
  apps/docs/app/twitter-image.alt.txt
  apps/docs/app/twitter-image.jpg
  apps/dotcom/client/public/humans.txt
  assets/card-repo.png
  assets/card_repo.svg
  assets/github-hero-dark-draw.png
  assets/github-hero-dark.png
  assets/github-hero-light-2.png
  assets/github-hero-light-draw.png
  assets/github-hero-light.png
  assets/github-hero_dark-2.png
Labels: other

#5074 [botcom] resizable sidebar
  apps/dotcom/client/src/tla/components/TlaAvatar/avatar.module.css
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/sidebar-layout.module.css
  apps/dotcom/client/src/tla/utils/local-session-state.ts
Labels: other

#5085 [botcom] Update default title
  apps/dotcom/client/index.html
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
Labels: other

#5086 fix top panel widths
  apps/dotcom/client/src/tla/styles/tla.css
Labels: other

#4825 error page: wordsmith copy again
  apps/dotcom/client/src/tla/components/TlaFileError/TlaFileError.tsx
  assets/translations/da.json
  assets/translations/pl.json
  assets/translations/so.json
  lerna.json
Labels: other

#5078 [botcom] fancypants routes
  apps/dotcom/client/src/routeDefs.ts
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/SlurpFailure.tsx
  apps/dotcom/client/src/tla/components/TlaErrorContent/TlaErrorContent.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaInviteTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarCreateFileButton.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
  apps/dotcom/client/src/tla/layouts/TlaErrorLayout/TlaErrorLayout.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  apps/dotcom/client/src/tla/providers/RequireSignedInUser.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/utils/urls.ts
  apps/dotcom/client/src/utils/sharing.ts
  apps/dotcom/client/src/utils/useFileSystem.tsx
Labels: other

#5093 [botcom] fix sidebar pointer capture release
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/sidebar-layout.module.css
Labels: other

#5088 Delete the link to the discussion page from README.md that is now closed
  README.md
Labels: other

#5070 Fix typo in TldrawEditor example
  apps/examples/src/examples/only-editor/README.md
Labels: other

#5098 alex/missing-space: add spaces
  apps/docs/components/marketing/faq-section.tsx
Labels: other

#5102 [botcom] delete old debug thing
  apps/dotcom/client/src/tla/app/TldrawApp.ts
Labels: other

#5100 Fix sync worker source maps.
  internal/scripts/deploy-dotcom.ts
  internal/scripts/lib/deploy.ts
Labels: bugfix

#5097 Copywriting consolidate on file
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaInviteTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
Labels: other

#5101 [botcom] Clear local session state on sign out
  apps/dotcom/client/src/tla/components/TlaAccountMenu/TlaAccountMenu.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/utils/local-session-state.ts
Labels: other

#5103 alex/forms: form tweaks
  apps/docs/app/buy/business/page.tsx
  apps/docs/app/buy/page.tsx
  apps/docs/app/buy/startup-lite/page.tsx
  apps/docs/app/buy/startup/page.tsx
  apps/docs/app/globals.css
  apps/docs/components/marketing/request-form.tsx
Labels: other

#5105 Landing page copy changes
  apps/docs/components/marketing/pricing-button.tsx
  apps/docs/components/marketing/pricing-section.tsx
Labels: other

#5099 [botcom] move sidebar toggles in to sidebar layout so they're always visible
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarToggleMobile.tsx
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/sidebar-layout.module.css
Labels: other

#5039 Fix popover going off screen
  packages/tldraw/src/lib/ui.css
Labels: bugfix

#5108 Landing page copy
  apps/docs/components/marketing/pricing-button.tsx
  apps/docs/components/marketing/pricing-section.tsx
Labels: other

#5111 Bump the version of the `upload-artifact` action.
  .github/workflows/playwright-dotcom.yml
  .github/workflows/playwright-examples.yml
Labels: other

#5112 alex/banner: banner
  apps/docs/components/marketing/hero-section.tsx
Labels: other

#5116 Update logo-section.tsx
  apps/docs/components/marketing/logo-section.tsx
Labels: other

#5117 fix stale closure in InnerShape
  packages/editor/src/lib/components/Shape.tsx
  packages/state-react/api-report.md
  packages/state-react/src/lib/useStateTracking.ts
Labels: bugfix

#5119 [botcom] Add pinned files
  apps/dotcom/client/e2e/fixtures/Sidebar.ts
  apps/dotcom/client/e2e/tests/homepage.spec.ts
  apps/dotcom/client/e2e/tests/logged-in.spec.ts
  apps/dotcom/client/public/tla/icon-pin-strong.svg
  apps/dotcom/client/public/tla/icon-pin.svg
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaEditor/editor.module.css
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileSection.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarRecentFiles.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/hooks/useIsFilePinned.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  apps/dotcom/zero-cache/migrations/003_make_published_slug_unique.sql
  apps/dotcom/zero-cache/migrations/004_guest_column_on_file_state.sql
  apps/dotcom/zero-cache/migrations/005_update_file_trigger.sql
  apps/dotcom/zero-cache/migrations/006_add_file_soft_delete.sql
  apps/dotcom/zero-cache/migrations/007_update_file_owner_details.sql
  apps/dotcom/zero-cache/migrations/008_add_pinned.sql
  packages/dotcom-shared/src/tlaSchema.ts
Labels: other

#5125 fix hot reload text measurement bug
  packages/editor/api-report.md
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/editor/managers/TextManager.ts
Labels: bugfix

#5071 custom sync presence
  apps/examples/src/examples/sync-custom-presence/README.md
  apps/examples/src/examples/sync-custom-presence/SyncCustomPresence.tsx
  apps/examples/src/examples/user-presence/UserPresenceExample.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useEvent.tsx
  packages/store/api-report.md
  packages/store/src/lib/RecordType.ts
  packages/sync-core/src/test/TLSyncRoom.test.ts
  packages/sync/api-report.md
  packages/sync/src/index.ts
  packages/sync/src/useSync.ts
  packages/sync/src/useSyncDemo.ts
  packages/tldraw/src/lib/ui/components/Minimap/MinimapManager.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/createPresenceStateDerivation.ts
  packages/tlschema/src/index.ts
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLPresence.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/array.ts
Labels: api

#5126 [botcom] stress test fixes
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/testRoutes.ts
  packages/utils/api-report.md
  packages/utils/src/lib/ExecutionQueue.ts
Labels: other

#5128 Close connections
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/zero-cache/migrate.ts
Labels: improvement

#5123 [botcom] Support legacy routes
  apps/dotcom/client/e2e/fixtures/HomePage.ts
  apps/dotcom/client/e2e/tests/legacy.spec.ts
  apps/dotcom/client/e2e/tests/sharing.spec.ts
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/components/BoardHistoryLog/BoardHistoryLog.tsx
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/components/MultiplayerEditor.tsx
  apps/dotcom/client/src/routeDefs.ts
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/components/TlaAppMenuGroup/TlaAppMenuGroup.tsx
  apps/dotcom/client/src/tla/components/TlaCtaButton/TlaCtaButton.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopRightPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorWrapper.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaLegacyFileEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaLegacySnapshotEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaPublishEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor-components/TlaEditorErrorFallback.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor-components/TlaEditorKeyboardShortcutsDialog.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor-components/TlaEditorLegacySharePanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor-components/TlaEditorMenuPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor-components/TlaEditorPublishedSharePanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor-components/TlaEditorSharePanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor-components/TlaEditorTopPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor-messages.ts
  apps/dotcom/client/src/tla/components/TlaEditor/editor.module.css
  apps/dotcom/client/src/tla/components/TlaEditor/sneaky/SneakyFileDropHandler.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/sneaky/SneakyLegacytSetDocumentTitle.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/sneaky/SneakySetDocumentTitle.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
  apps/dotcom/client/src/tla/components/TlaEditor/useFileEditorOverrides.ts
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarUserLink.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/components/TlaSignedOutShareButton/TlaSignedOutShareButton.tsx
  apps/dotcom/client/src/tla/hooks/useUser.tsx
  apps/dotcom/client/src/tla/pages/legacy-history-snapshot.tsx
  apps/dotcom/client/src/tla/pages/legacy-history.tsx
  apps/dotcom/client/src/tla/pages/legacy-readonly-old.tsx
  apps/dotcom/client/src/tla/pages/legacy-readonly.tsx
  apps/dotcom/client/src/tla/pages/legacy-room.tsx
  apps/dotcom/client/src/tla/pages/legacy-snapshot.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
  apps/dotcom/client/src/utils/useFileSystem.tsx
  apps/dotcom/client/styles/globals.css
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
Labels: other

#5120 fix: fix broken bluesky link with old handle name
  apps/docs/components/navigation/footer.tsx
Labels: bugfix

#5129 Add name and timeout params.
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/getPostgres.ts
Labels: improvement

#5133 Execute reactor immediately on listen
  packages/store/src/lib/Store.ts
Labels: bugfix

#5141 Add snow
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/components/MultiplayerEditor.tsx
  apps/dotcom/client/src/components/SnapshotsEditor.tsx
  apps/dotcom/client/src/components/SnowStorm.tsx
  apps/dotcom/client/styles/globals.css
  apps/examples/src/misc/develop.tsx
Labels: other

#5142 Hotfix/add snow
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/components/MultiplayerEditor.tsx
  apps/dotcom/client/src/components/SnapshotsEditor.tsx
  apps/dotcom/client/src/components/SnowStorm.tsx
  apps/dotcom/client/styles/globals.css
  apps/examples/src/misc/develop.tsx
Labels: other

#5148 Reduce snow motion
  apps/dotcom/client/src/components/SnowStorm.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
Labels: other

#5157 add snowstorm example, remove snowstorm from app
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/components/MultiplayerEditor.tsx
  apps/dotcom/client/src/components/SnapshotsEditor.tsx
  apps/dotcom/client/styles/globals.css
  apps/examples/src/examples/snowstorm/README.md
  apps/examples/src/examples/snowstorm/SnowStorm.tsx
  apps/examples/src/examples/snowstorm/SnowStormExample.tsx
  apps/examples/src/examples/snowstorm/snowstorm.css
Labels: other

#5162 Hotfix/remove snow
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/components/MultiplayerEditor.tsx
  apps/dotcom/client/src/components/SnapshotsEditor.tsx
  apps/dotcom/client/styles/globals.css
  apps/examples/src/examples/snowstorm/README.md
  apps/examples/src/examples/snowstorm/SnowStorm.tsx
  apps/examples/src/examples/snowstorm/SnowStormExample.tsx
  apps/examples/src/examples/snowstorm/snowstorm.css
Labels: other
