Repository tldraw/tldraw, pull requests merged in 2024-10, with the labels that each got.

#4569 text: be able to keep tool locked
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/defaultSideEffects.ts
  packages/tldraw/src/lib/shapes/text/TextShapeTool.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/EditingShape.ts
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/getCulledShapes.test.tsx
Labels: improvement

#4629 Disable debug mode in development by default
  apps/docs/components/marketing/DemoTldraw.tsx
  apps/examples/src/examples/image-annotator/ImageAnnotationEditor.tsx
  apps/examples/src/examples/image-component/TldrawImageExample.tsx
  apps/examples/src/examples/inline-behavior/InlineBehavior.tsx
  apps/examples/src/examples/inline/InlineExample.tsx
  apps/examples/src/examples/pdf-editor/PdfEditor.tsx
  packages/tlschema/src/records/TLInstance.ts
Labels: sdk

#4633 github: update stale issues number to be correct
  .github/workflows/close-stale-issues.yml
Labels: other

#4634 Update close-stale-issues.yml
  .github/workflows/close-stale-issues.yml
Labels: other

#4635 Update close-stale-issues.yml
  .github/workflows/close-stale-issues.yml
Labels: other

#4638 Update close-stale-issues.yml
  .github/workflows/close-stale-issues.yml
Labels: other

#4632 text: followup fix to locking text shapes
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
Labels: bugfix

#4643 stale issues: better msg
  .github/workflows/close-stale-issues.yml
Labels: other

#4641 Add 0.0.1 version of translations :joy:
  .eslintrc.js
  apps/dotcom/client/src/tla/components/TlaCloseButton/TlaCloseButton.tsx
  apps/dotcom/client/src/tla/components/TlaErrorContent/TlaErrorContent.tsx
  apps/dotcom/client/src/tla/components/TlaFileContent/TlaFileContent.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenuExportPage.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenuSharePage.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaRenameFileDialog.tsx
  apps/dotcom/client/src/tla/hooks/useAppState.tsx
  apps/dotcom/client/src/tla/hooks/useRaw.ts
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/pages/debug.tsx
  apps/dotcom/client/src/tla/pages/profile.tsx
  apps/dotcom/client/src/tla/pages/settings.tsx
Labels: improvement

#4645 [state] fix error 'cannot change atoms during reaction cycle' bug
  packages/state/src/lib/__tests__/transactions.test.ts
  packages/state/src/lib/transactions.ts
Labels: bugfix

#4647 Prevent some draw shape rerenders when changing the zoom
  packages/tldraw/src/lib/shapes/draw/DrawShapeUtil.tsx
  packages/tldraw/src/lib/shapes/draw/getPath.ts
Labels: improvement

#4639 [botcom] Use auth on backend
  apps/dotcom/client/src/components/StoreErrorScreen.tsx
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaFileContent/TlaFileContent.tsx
  apps/dotcom/client/src/tla/hooks/useAppState.tsx
  apps/dotcom/client/src/tla/pages/file.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  apps/dotcom/client/src/tla/utils/TldrawApp.ts
  apps/dotcom/sync-worker/package.json
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/src/utils/auth.ts
  apps/dotcom/sync-worker/src/utils/getAuth.ts
  apps/dotcom/sync-worker/src/worker.ts
  packages/sync-core/api-report.md
  packages/sync-core/src/lib/ClientWebSocketAdapter.ts
  packages/sync-core/src/lib/TLSyncClient.ts
  packages/sync-core/src/lib/protocol.ts
  packages/sync/src/useSync.ts
Labels: feature

#4644 text: followup to the followup of fix to locking text shapes
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
  packages/tldraw/src/test/strange-tools.test.ts
Labels: bugfix

#4653 auth: add keys
  .github/workflows/deploy-dotcom.yml
  internal/scripts/deploy-dotcom.ts
Labels: other

#4655 auth: add keys to worker as well
  internal/scripts/deploy-dotcom.ts
Labels: other

#4656 watermark: go behind certain elements on the app
  packages/editor/editor.css
  packages/editor/src/lib/license/Watermark.tsx
Labels: improvement

#4570 selection: allow cmd/ctrl to add to selection
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/config/TLSessionStateSnapshot.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/event-types.ts
  packages/editor/src/lib/globals/environment.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/editor/src/lib/hooks/useGestureEvents.ts
  packages/editor/src/lib/utils/getPointerInfo.ts
  packages/editor/src/lib/utils/keyboard.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingArrowLabel.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingCanvas.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingSelection.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingShape.ts
  packages/tldraw/src/lib/tools/selection-logic/selectOnCanvasPointerUp.ts
  packages/tldraw/src/lib/ui/components/Minimap/DefaultMinimap.tsx
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
  packages/tldraw/src/lib/ui/kbd-utils.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/commands/penmode.test.ts
  packages/tldraw/src/test/commands/setCamera.test.ts
  packages/tldraw/src/test/cropping.test.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
  packages/tldraw/src/test/translating.test.ts
Labels: improvement

#4534 [Example] Setting opts in export-canvas-as-image
  apps/examples/src/examples/export-canvas-settings/ExportCanvasImageSettingsExample.tsx
  apps/examples/src/examples/export-canvas-settings/README.md
Labels: feature

#4657 csp: add clerk for new domains
  apps/dotcom/client/src/utils/csp.ts
Labels: other

#4650 Fix an issue with nearest point and lines that start and end at the same point
  packages/editor/src/lib/primitives/geometry/Edge2d.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
Labels: bugfix

#4658 csp: add clerk for new domains, pt 2
  apps/dotcom/client/src/utils/csp.ts
Labels: other

#4646 Arrowhead clipping fix
  apps/examples/e2e/tests/export-snapshots.spec.tsx
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Arrows-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Arrows-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Arrows-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Arrows-light-1-chromium-linux.png
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/arrowheads.ts
Labels: bugfix

#4651 prevent accidental image drops
  packages/editor/src/lib/hooks/useCanvasEvents.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: bugfix

#4661 dotcom top bar / .tldr file drops
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopRightPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor.module.css
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
  apps/dotcom/client/src/tla/components/TlaFileContent/TlaFileContent.tsx
  apps/dotcom/client/src/tla/components/TlaFileContent/file.module.css
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/hooks/usePreventAccidentalDrops.ts
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaCenteredLayout/TlaCenteredLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaErrorLayout/TlaErrorLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaPageLayout/TlaPageLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
  apps/dotcom/client/src/tla/pages/file.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  apps/dotcom/client/src/tla/utils/TldrawApp.ts
  packages/editor/api-report.md
  packages/editor/src/lib/globals/menus.ts
  packages/editor/src/lib/options.ts
Labels: internal, other

#4663 Fix icon button width
  packages/tldraw/src/lib/ui.css
Labels: bugfix

#4664 Fix over-scroll behavior
  apps/dotcom/client/styles/core.css
  apps/examples/src/styles.css
  templates/nextjs/src/app/globals.css
  templates/simple-server-example/src/client/index.css
  templates/sync-cloudflare/client/index.css
  templates/vite/src/index.css
Labels: bugfix

#4662 Pass through wheel events over non-scrolling user interface elements
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/hooks/useLicenseManagerState.ts
  packages/editor/src/lib/hooks/usePassThroughWheelEvents.ts
  packages/editor/src/lib/license/Watermark.test.tsx
  packages/editor/src/lib/license/Watermark.tsx
  packages/tldraw/src/lib/ui/components/ActionsMenu/DefaultActionsMenu.tsx
  packages/tldraw/src/lib/ui/components/DefaultDebugPanel.tsx
  packages/tldraw/src/lib/ui/components/DefaultMenuPanel.tsx
  packages/tldraw/src/lib/ui/components/HelpMenu/DefaultHelpMenu.tsx
  packages/tldraw/src/lib/ui/components/Minimap/DefaultMinimap.tsx
  packages/tldraw/src/lib/ui/components/NavigationPanel/DefaultNavigationPanel.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanel.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbar.tsx
Labels: improvement

#4669 Improve watermark tests
  packages/editor/src/lib/license/Watermark.test.tsx
  packages/editor/src/lib/license/Watermark.tsx
  packages/editor/src/lib/license/useLicenseManagerState.ts
Labels: other

#4670 [botcom] Pass through wheel events in menus
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopRightPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
  apps/dotcom/client/src/tla/utils/TldrawApp.ts
Labels: other

#4673 [sync] Set instance.isReadonly automatically
  apps/dotcom/client/src/components/DocumentName/DocumentName.tsx
  apps/dotcom/client/src/components/MultiplayerEditor.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/config/createTLStore.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/sync-core/api-report.md
  packages/sync-core/src/lib/TLSyncClient.ts
  packages/sync-core/src/lib/TLSyncRoom.ts
  packages/sync-core/src/lib/protocol.ts
  packages/sync-core/src/test/upgradeDowngrade.test.ts
  packages/sync/src/useSync.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/geo/toolStates/Idle.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/PointingCropHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/EditingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingArrowLabel.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingResizeHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingRotateHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingSelection.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingShape.ts
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
  packages/tldraw/src/lib/ui/hooks/useReadonly.ts
  packages/tldraw/src/test/Editor.test.tsx
  packages/tldraw/src/test/SelectTool.test.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
Labels: improvement

#4677 [sync] Expose sessions and individual records on TLSocketRoom
  packages/sync-core/api-report.md
  packages/sync-core/src/lib/TLSocketRoom.ts
Labels: api

#4660 [sync] refine error handling + room.closeSession method
  apps/bemo-worker/src/BemoDO.ts
  apps/dotcom/client/src/components/StoreErrorScreen.tsx
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  packages/sync-core/api-report.md
  packages/sync-core/src/index.ts
  packages/sync-core/src/lib/ClientWebSocketAdapter.test.ts
  packages/sync-core/src/lib/ClientWebSocketAdapter.ts
  packages/sync-core/src/lib/RoomSession.ts
  packages/sync-core/src/lib/ServerSocketAdapter.ts
  packages/sync-core/src/lib/TLRemoteSyncError.ts
  packages/sync-core/src/lib/TLSocketRoom.ts
  packages/sync-core/src/lib/TLSyncClient.ts
  packages/sync-core/src/lib/TLSyncRoom.ts
  packages/sync-core/src/lib/protocol.ts
  packages/sync-core/src/test/TLSyncRoom.test.ts
  packages/sync-core/src/test/TestServer.ts
  packages/sync-core/src/test/TestSocketPair.ts
  packages/sync-core/src/test/syncFuzz.test.ts
  packages/sync-core/src/test/upgradeDowngrade.test.ts
  packages/sync-core/src/test/validation.test.ts
  packages/sync/src/useSync.ts
Labels: improvement, api

#4679 [botcom] Move file update handler, remove tldrawApp.currentEditor
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/utils/TldrawApp.ts
Labels: other

#4680 [botcom] one last logged out fix
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
Labels: other

#4684 Improve .dev demo
  apps/docs/app/demo.css
  apps/docs/app/globals.css
  apps/docs/components/marketing/DemoTldraw.tsx
  apps/docs/components/marketing/demo.tsx
Labels: other

#4685 i18n: fix up lang menu reactivity
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/context/TldrawUiContextProvider.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/useTranslation.tsx
Labels: bugfix, other

#4654 [botcom] sharing
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/components/RedirectAtRoot.tsx
  apps/dotcom/client/src/tla/components/RequireAuthForUser.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor.module.css
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/hooks/useAppState.tsx
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
  apps/dotcom/client/src/tla/pages/file.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  apps/dotcom/client/src/tla/providers/RequireSignedInUser.tsx
  apps/dotcom/client/src/tla/providers/TlaAppLoggedInProvider.tsx
  apps/dotcom/client/src/tla/providers/TlaClerkProvider.tsx
  apps/dotcom/client/src/tla/providers/TlaProvider.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  apps/dotcom/client/src/tla/utils/TldrawApp.ts
  apps/dotcom/sync-worker/src/TLAppDurableObject.ts
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/types.ts
  packages/sync-core/api-report.md
  packages/sync-core/src/lib/TLSocketRoom.ts
Labels: feature

#4687 [botcom] Add event tracking
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenuExportPage.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/context/events.tsx
Labels: other

#4689 Add missing CSS imports to examples
  apps/examples/src/examples/after-delete-shape/AfterDeleteShapeExample.tsx
  apps/examples/src/examples/before-create-update-shape/BeforeCreateUpdateShapeExample.tsx
  apps/examples/src/examples/before-delete-shape/BeforeDeleteShapeExample.tsx
  apps/examples/src/examples/bounds-snapping-shape/BoundsSnappingShape.tsx
  apps/examples/src/examples/image-annotator/ImageAnnotatorExample.tsx
  apps/examples/src/examples/image-annotator/README.md
  apps/examples/src/examples/keyboard-shortcuts/KeyboardShortcutsExample.tsx
  apps/examples/src/examples/keyboard-shortcuts/README.md
  apps/examples/src/examples/layout-bindings/LayoutExample.tsx
  apps/examples/src/examples/only-editor/OnlyEditorExample.tsx
  apps/examples/src/examples/only-editor/README.md
  apps/examples/src/examples/pdf-editor/PdfEditorExample.tsx
  apps/examples/src/examples/pin-bindings/PinExample.tsx
  apps/examples/src/examples/sticker-bindings/StickerExample.tsx
  apps/examples/src/examples/toSvg-method-example/CustomShapeToSvgExample.tsx
Labels: other

#4695 share: fix copy link ux
  apps/dotcom/client/src/components/ShareMenu.tsx
  apps/dotcom/client/src/utils/sharing.ts
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuItem.tsx
Labels: bugfix

#4696 menus: fix up some missing readonlyOk items; rm some ctx menu items in readonly
  packages/tldraw/src/lib/ui/components/ColorSchemeMenu.tsx
  packages/tldraw/src/lib/ui/components/LanguageMenu.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
Labels: bugfix

#4694 make sure DOM IDs are globally unique
  apps/docs/components/marketing/arrow-up.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
  apps/examples/src/misc/end-to-end.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/SVGContainer.tsx
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/components/default-components/DefaultCollaboratorHint.tsx
  packages/editor/src/lib/components/default-components/DefaultCursor.tsx
  packages/editor/src/lib/components/default-components/DefaultErrorFallback.tsx
  packages/editor/src/lib/components/default-components/DefaultGrid.tsx
  packages/editor/src/lib/editor/shapes/group/GroupShapeUtil.tsx
  packages/editor/src/lib/editor/types/SvgExportContext.tsx
  packages/editor/src/lib/exports/exportToSvg.tsx
  packages/editor/src/lib/exports/getSvgJsx.tsx
  packages/editor/src/lib/hooks/useEditor.tsx
  packages/editor/src/lib/hooks/useSafeId.ts
  packages/editor/src/lib/hooks/useSafeId.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/draw/DrawShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeUtil.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/ShapeFill.tsx
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/defaultStyleDefs.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/OverflowingToolbar.tsx
  packages/tldraw/src/test/commands/__snapshots__/getSvgString.test.ts.snap
Labels: bugfix

#4693 Remove v1 migration from dotcom
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/components/SnapshotsEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/utils/migration/DebugMenuItems.tsx
  apps/dotcom/client/src/utils/migration/LocalMigration.tsx
  apps/dotcom/client/src/utils/migration/MigrationAnnouncement.tsx
  apps/dotcom/client/src/utils/migration/migration.tsx
  apps/dotcom/client/src/utils/migration/writeV1ContentsToIdb.tsx
Labels: other

#4701 [fix] Meta key bug
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix

#4697 botcom: prevent pinch-zoom on sidebar
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  packages/editor/src/lib/hooks/useDocumentEvents.ts
Labels: other

#4706 Fix watermark dark mode on tldraw.dev
  apps/docs/components/marketing/pricing-section.tsx
  apps/docs/components/marketing/watermark-image.tsx
  apps/docs/public/watermark-desktop-dark.svg
Labels: other

#4707 ui: suppress aria warning about desc in dialogs
  lerna.json
  packages/tldraw/src/lib/ui/components/Dialogs.tsx
Labels: other

#4712 tla: rename icons without equal sign
  apps/dotcom/client/public/tla/icon-check.svg
  apps/dotcom/client/public/tla/icon-chevron-down-strong.svg
  apps/dotcom/client/public/tla/icon-chevron-down.svg
  apps/dotcom/client/public/tla/icon-chevron-right-strong.svg
  apps/dotcom/client/public/tla/icon-chevron-right.svg
  apps/dotcom/client/public/tla/icon-chevron-up-strong.svg
  apps/dotcom/client/public/tla/icon-chevron-up.svg
  apps/dotcom/client/public/tla/icon-close-strong.svg
  apps/dotcom/client/public/tla/icon-close.svg
  apps/dotcom/client/public/tla/icon-copy-strong.svg
  apps/dotcom/client/public/tla/icon-copy.svg
  apps/dotcom/client/public/tla/icon-doc-strong.svg
  apps/dotcom/client/public/tla/icon-doc.svg
  apps/dotcom/client/public/tla/icon-dots-horizontal-strong.svg
  apps/dotcom/client/public/tla/icon-dots-horizontal.svg
  apps/dotcom/client/public/tla/icon-dots-vertical-strong.svg
  apps/dotcom/client/public/tla/icon-dots-vertical.svg
  apps/dotcom/client/public/tla/icon-draw.svg
  apps/dotcom/client/public/tla/icon-edit-strong.svg
  apps/dotcom/client/public/tla/icon-edit.svg
  apps/dotcom/client/public/tla/icon-export.svg
  apps/dotcom/client/public/tla/icon-group-strong.svg
  apps/dotcom/client/public/tla/icon-group.svg
  apps/dotcom/client/public/tla/icon-home-strong.svg
  apps/dotcom/client/public/tla/icon-home.svg
  apps/dotcom/client/public/tla/icon-info.svg
  apps/dotcom/client/public/tla/icon-link-strong.svg
  apps/dotcom/client/public/tla/icon-link.svg
  apps/dotcom/client/public/tla/icon-more.svg
  apps/dotcom/client/public/tla/icon-plus-strong.svg
  apps/dotcom/client/public/tla/icon-plus.svg
  apps/dotcom/client/public/tla/icon-qr.svg
  apps/dotcom/client/public/tla/icon-question-circle.svg
  apps/dotcom/client/public/tla/icon-sidebar-strong.svg
  apps/dotcom/client/public/tla/icon-sidebar.svg
  apps/dotcom/client/public/tla/icon-spinner.svg
  apps/dotcom/client/public/tla/icon-star-fill.svg
  apps/dotcom/client/public/tla/icon-star-strong-fill.svg
  apps/dotcom/client/public/tla/icon-star-strong.svg
  apps/dotcom/client/public/tla/icon-star.svg
  apps/dotcom/client/public/tla/icon-tldraw.svg
  apps/dotcom/client/src/tla/components/TlaIcon/TlaIcon.tsx
Labels: other

#4682 Lod Perf (effect scheduler)
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/HyperlinkButton.tsx
  packages/tldraw/src/lib/shapes/shared/useAsset.ts
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: improvement, api

#4709 embeds: fix pasting urls giving an error msg always
  packages/tldraw/src/lib/ui/components/EmbedDialog.tsx
Labels: bugfix

#4708 links: fix link indicator on stickies
  packages/editor/editor.css
Labels: bugfix

#4704 drag/drop: followup to accidental img drop pr
  packages/editor/src/lib/hooks/useDocumentEvents.ts
Labels: bugfix

#4659 lod: memoize media assets so that zoom level doesn't re-render constantly
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/HyperlinkButton.tsx
  packages/tldraw/src/lib/shapes/shared/useAsset.ts
  packages/tldraw/src/lib/shapes/shared/useImageOrVideoAsset.ts
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: improvement

#4724 Add labelColor for notes.
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/shapes/TLNoteShape.ts
Labels: feature

#4723 Don't index multiplayer rooms, snapshots, history.
  apps/dotcom/client/public/robots.txt
  apps/dotcom/client/src/pages/noindex.tsx
  apps/dotcom/client/src/routes.tsx
Labels: improvement

#4735 Fix style menu vertical align button
  packages/tldraw/src/lib/ui/components/StylePanel/DropdownPicker.tsx
Labels: bugfix

#4732 refactor: specify type at bbox
  packages/editor/src/lib/exports/getSvgJsx.tsx
Labels: improvement

#4736 Remove .zed folder
  .gitignore
  .zed/settings.json
Labels: other

#4711 [botcom] local session state, logged out view of files
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/components/TlaAppBoundary/TlaAppBoundary.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor.module.css
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenuExportPage.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenuSharePage.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/hooks/useAppState.tsx
  apps/dotcom/client/src/tla/hooks/useFileCollaborators.tsx
  apps/dotcom/client/src/tla/hooks/useFlags.tsx
  apps/dotcom/client/src/tla/hooks/useSessionState.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/anon.module.css
  apps/dotcom/client/src/tla/layouts/TlaCenteredLayout/TlaCenteredLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaCenteredLayout/centered.module.css
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
  apps/dotcom/client/src/tla/pages/debug.tsx
  apps/dotcom/client/src/tla/pages/file.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  apps/dotcom/client/src/tla/providers/RequireSignedInUser.tsx
  apps/dotcom/client/src/tla/providers/TlaProvider.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/utils/TldrawApp.ts
  apps/dotcom/client/src/tla/utils/local-session-state.ts
  apps/dotcom/client/styles/z-board.css
  packages/dotcom-shared/src/tla-schema/TldrawAppUser.ts
  packages/tldraw/src/lib/ui/components/primitives/Button/TldrawUiButton.tsx
Labels: other

#4738 [botcom] Signout route
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/pages/signout.tsx
Labels: other

#4739 drag: passthrough correct event type for drag events
  packages/editor/src/lib/hooks/useDocumentEvents.ts
Labels: bugfix

#4642 menus: rework the open menu logic to be in one consistent place
  apps/docs/content/getting-started/releases-versioning.mdx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/components/MenuClickCapture.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/tools/BaseBoxShapeTool/children/Pointing.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/editor/src/lib/license/Watermark.tsx
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
  packages/tldraw/src/lib/shapes/note/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
  packages/tldraw/src/test/ui/ContextMenu.test.tsx
Labels: improvement

#4710 ui: dont highlight menu triggers that dont have their submenus open
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiDropdownMenu.tsx
Labels: bugfix

#4683 botcom: account menu [bk]
  apps/dotcom/client/package.json
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaAccountMenu/TlaAccountMenu.tsx
  apps/dotcom/client/src/tla/components/TlaAccountMenu/account-menu.module.css
  apps/dotcom/client/src/tla/components/TlaAvatar/TlaAvatar.tsx
  apps/dotcom/client/src/tla/components/TlaAvatar/avatar.module.css
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenuExportPage.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaRenameFileDialog.tsx
  apps/dotcom/client/src/tla/hooks/useAppState.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaCenteredLayout/TlaCenteredLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaCenteredLayout/centered.module.css
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
  apps/dotcom/client/src/tla/pages/signout.tsx
  apps/dotcom/client/src/tla/providers/TlaProvider.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  apps/dotcom/client/src/utils/csp.ts
  packages/dotcom-shared/package.json
  packages/dotcom-shared/src/tla-schema/TldrawAppUser.ts
  packages/dotcom-shared/tsconfig.json
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/hooks/useEditor.tsx
  packages/sync-core/src/lib/TLSyncRoom.ts
  yarn.lock
Labels: other

#4725 botcom: redirect to intended room when signing in
  apps/dotcom/client/src/components/LoginRedirectPage/LoginRedirectPage.tsx
  apps/dotcom/client/src/components/StoreErrorScreen.tsx
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  packages/sync/src/useSync.ts
Labels: other

#4743 Fix copying of snapshot links
  apps/dotcom/client/src/utils/sharing.ts
Labels: bugfix

#4747 Limit the page name length in the move to page menu.
  packages/tldraw/src/lib/ui/components/menu-items.tsx
Labels: improvement

#4749 arrows: fix up label indicator showing up
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
Labels: bugfix

#4751 [botcom] Fix file deletion and creation
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/sync-worker/src/TLAppDurableObject.ts
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  packages/sync-core/src/lib/TLSyncRoom.ts
Labels: other

#4753 botcom: only redirect when logged out and the file is private
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
Labels: other

#4752 [Fix] Colors from Excalidraw when pasting
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteExcalidrawContent.ts
Labels: bugfix

#4750 Improve tooltips in the style panel
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DropdownPicker.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement

#4758 botcom: inline rename
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/components/dialogs/TlaRenameFileDialog.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiInput.tsx
Labels: other

#4745 [Fix] Keyboard events on menus
  apps/examples/e2e/tests/fixtures/fixtures.ts
  apps/examples/e2e/tests/fixtures/menus/MenuClickCapture.ts
  apps/examples/e2e/tests/test-actions-menu.spec.ts
  packages/editor/src/lib/components/MenuClickCapture.tsx
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
Labels: bugfix

#4759 [Fix] Toolbar button outline border radius
  packages/tldraw/src/lib/ui.css
Labels: bugfix

#4762 make options object stable
  packages/editor/src/lib/TldrawEditor.tsx
  packages/tldraw/src/test/TldrawEditor.test.tsx
Labels: api

#4688 [botcom] Publishing
  apps/dotcom/client/public/tla/icon-update.svg
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/pages/not-found.tsx
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaButton/TlaButton.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/SneakyDarkModeSync.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaPublishEditor.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/QrCode.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaExportTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaShareTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaPublishFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/file-share-menu-primitives.tsx
  apps/dotcom/client/src/tla/pages/publish.tsx
  apps/dotcom/client/src/tla/utils/local-session-state.ts
  apps/dotcom/client/src/tla/utils/notFoundError.ts
  apps/dotcom/client/src/tla/utils/urls.ts
  apps/dotcom/client/src/utils/sharing.ts
  apps/dotcom/sync-worker/src/routes/createPublishedRoom.ts
  apps/dotcom/sync-worker/src/routes/deletePublishedRoom.ts
  apps/dotcom/sync-worker/src/routes/getPublishedRoom.ts
  apps/dotcom/sync-worker/src/utils/permissions.ts
  apps/dotcom/sync-worker/src/worker.ts
  packages/dotcom-shared/package.json
  packages/dotcom-shared/src/tla-schema/TldrawAppFile.ts
  packages/dotcom-shared/src/tla-schema/TldrawAppSessionState.ts
  packages/dotcom-shared/src/tla-schema/tldrawAppSchema.ts
  packages/dotcom-shared/tsconfig.json
  yarn.lock
Labels: feature

#4754 [botcom] fix share links
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  apps/dotcom/client/src/tla/utils/urls.ts
Labels: other

#4761 [botcom] Shared file fixes
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaShareTab.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/client/src/tla/hooks/useIsFileOwner.tsx
  apps/dotcom/client/src/tla/utils/local-session-state.ts
Labels: other

#4770 Fix license link
  LICENSE.md
  apps/docs/content/legal/tldraw-license.mdx
Labels: other

#4764 botcom: alternative to multi-menu items
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
Labels: other

#4775 [botcom] fix copy for forbidden state
  apps/dotcom/client/src/components/StoreErrorScreen.tsx
  apps/dotcom/client/src/routes.tsx
Labels: other

#4776 deploy docs when a release is edited
  .github/workflows/deploy-docs-on-release-edit.yml
Labels: other

#4768 [botcom] deep links
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaShareTab.tsx
  apps/dotcom/client/src/tla/pages/file.tsx
Labels: other

#4777 [botcom] sync user name with people menu
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  packages/dotcom-shared/src/tla-schema/TldrawAppUser.ts
Labels: other

#4778 [botcom] add `yarn reset-db` command
  apps/dotcom/sync-worker/package.json
Labels: other

#4766 [botcom] file state
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaCollaborators/TlaCollaborators.tsx
  apps/dotcom/client/src/tla/components/TlaCollaborators/collaborators.module.css
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/hooks/useFileCollaborators.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  packages/dotcom-shared/src/index.ts
  packages/dotcom-shared/src/tla-schema/TldrawAppFileEdit.ts
  packages/dotcom-shared/src/tla-schema/TldrawAppFileState.ts
  packages/dotcom-shared/src/tla-schema/TldrawAppFileVisit.ts
  packages/dotcom-shared/src/tla-schema/TldrawAppUser.ts
  packages/dotcom-shared/src/tla-schema/tldrawAppSchema.ts
  packages/editor/package.json
  packages/editor/src/lib/config/TLSessionStateSnapshot.ts
  yarn.lock
Labels: other

#4774 [infra] bump up skew protection time frame
  internal/scripts/deploy-dotcom.ts
Labels: other

#4781 [infra] limit skew protection to one month
  internal/scripts/deploy-dotcom.ts
Labels: other

#4765 [botcom] Add tooltips / links to Share Menu
  apps/dotcom/client/package.json
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaButton/TlaButton.tsx
  apps/dotcom/client/src/tla/components/TlaButton/button.module.css
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaExportTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaInviteTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/tla-menu/menu.module.css
  apps/dotcom/client/src/tla/components/tla-menu/tla-menu.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  packages/dotcom-shared/src/tla-schema/TldrawAppFile.ts
  yarn.lock
Labels: other

#4783 botcom: signup shouldnt redirect to /user page
  apps/dotcom/client/src/components/LoginRedirectPage/LoginRedirectPage.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
Labels: other

#4784 [botcom] fix file deletion
  apps/bemo-worker/src/BemoDO.ts
  apps/dotcom/sync-worker/src/TLAppDurableObject.ts
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  packages/worker-shared/src/ExecutionQueue.test.ts
  packages/worker-shared/src/ExecutionQueue.ts
  packages/worker-shared/src/createPersistQueue.test.ts
  packages/worker-shared/src/createPersistQueue.ts
  packages/worker-shared/src/index.ts
Labels: other

#4785 [botcom] Fix mobile top bar
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/styles/tla.css
Labels: other

#4760 e2e scaffolding
  .github/workflows/playwright-dotcom.yml
  .github/workflows/playwright-examples.yml
  .gitignore
  apps/dotcom/client/e2e/auth.setup.ts
  apps/dotcom/client/e2e/fixtures/Editor.ts
  apps/dotcom/client/e2e/fixtures/HomePage.ts
  apps/dotcom/client/e2e/fixtures/Sidebar.ts
  apps/dotcom/client/e2e/fixtures/tla-test.ts
  apps/dotcom/client/e2e/tests/homepage.spec.ts
  apps/dotcom/client/e2e/tests/not-logged-in.spec.ts
  apps/dotcom/client/package.json
  apps/dotcom/client/playwright.config.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/vite.config.ts
  package.json
  yarn.lock
Labels: feature

#4794 Fix dragging on frame headings
  packages/tldraw/src/lib/shapes/frame/components/FrameHeading.tsx
Labels: bugfix

#4802 [botcom] Double click sidebar item to edit inline
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
Labels: improvement

#4800 Fix toast spacing
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/Toasts.tsx
Labels: bugfix

#4796 Make default color theme light.
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/dotcom/client/src/components/BoardHistorySnapshot/BoardHistorySnapshot.tsx
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/components/MultiplayerEditor.tsx
  apps/dotcom/client/src/components/SnapshotsEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaPublishEditor.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
Labels: improvement

#4791 kbd shortcuts: fix up wrong size dialog on desktop
  apps/dotcom/client/src/components/LocalEditor.tsx
  packages/tldraw/src/lib/ui.css
Labels: bugfix

#4803 [botcom] Improve UI for file name editing
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
Labels: other

#4808 [infra] disable webhook invocation (temporarily)
  .github/workflows/deploy-bemo.yml
  .github/workflows/deploy-dotcom.yml
Labels: other

#4809 [infra] disable webhook invocation (temporarily) (#4808)
  .github/workflows/deploy-bemo.yml
  .github/workflows/deploy-dotcom.yml
Labels: other

#4789 [botcom] Improve mobile anonymous layout
  apps/dotcom/client/e2e/fixtures/HomePage.ts
  apps/dotcom/client/src/tla/components/TlaButton/TlaButton.tsx
  apps/dotcom/client/src/tla/components/TlaButton/button.module.css
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/anon.module.css
Labels: other

#4798 [botcom] Duplicate / Publish / Create / Delete files on the server
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
  apps/dotcom/client/src/tla/pages/publish.tsx
  apps/dotcom/sync-worker/src/TLAppDurableObject.ts
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/routes/createPublishedRoom.ts
  apps/dotcom/sync-worker/src/routes/deletePublishedRoom.ts
  apps/dotcom/sync-worker/src/routes/getPublishedRoom.ts
  apps/dotcom/sync-worker/src/routes/tla/createFiles.ts
  apps/dotcom/sync-worker/src/routes/tla/deleteFile.ts
  apps/dotcom/sync-worker/src/routes/tla/duplicateFile.ts
  apps/dotcom/sync-worker/src/routes/tla/forwardRoomRequest.ts
  apps/dotcom/sync-worker/src/routes/tla/getPublishedFile.ts
  apps/dotcom/sync-worker/src/routes/tla/publishFile.ts
  apps/dotcom/sync-worker/src/routes/tla/unpublishFile.ts
  apps/dotcom/sync-worker/src/utils/tla/getAuth.ts
  apps/dotcom/sync-worker/src/utils/tla/getCurrentSerializedRoomSnapshot.ts
  apps/dotcom/sync-worker/src/utils/tla/getTldrawAppDurableObject.ts
  apps/dotcom/sync-worker/src/utils/tla/permissions.ts
  apps/dotcom/sync-worker/src/utils/tla/updateRoomSnapshot.ts
  apps/dotcom/sync-worker/src/worker.ts
  packages/dotcom-shared/src/index.ts
  packages/dotcom-shared/src/types.ts
  packages/sync-core/api-report.md
  packages/sync-core/src/lib/TLSocketRoom.ts
Labels: other

#4807 Imported wrong css
  apps/docs/content/getting-started/quick-start.mdx
Labels: bugfix

#4806 [botcom] add max file limit
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
Labels: other

#4811 update vite
  apps/dotcom/client/package.json
  apps/examples/package.json
  internal/dev-tools/package.json
  templates/simple-server-example/package.json
  templates/sync-cloudflare/package.json
  templates/vite/package.json
  yarn.lock
Labels: other

#4786 Organize paths.
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/components/TlaErrorContent/TlaErrorContent.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaErrorLayout/TlaErrorLayout.tsx
  apps/dotcom/client/src/tla/pages/debug.tsx
  apps/dotcom/client/src/tla/providers/RequireSignedInUser.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/utils/urls.ts
Labels: improvement

#4814 Don't pipe out webserver stuff.
  apps/dotcom/client/playwright.config.ts
Labels: improvement

#4813 Fix publishing.
  apps/dotcom/sync-worker/src/routes/tla/getPublishedFile.ts
Labels: bugfix

#4818 docs: fix up NPE on release pages
  apps/docs/components/docs/docs-sidebar-menus.tsx
Labels: bugfix, other

#4819 [botcom] Fix double presence
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
Labels: other

#4805 [botcom] Analytics tracking
  apps/dotcom/client/src/tla/components/TlaAccountMenu/TlaAccountMenu.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopRightPanel.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaInviteTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/client/src/tla/components/tla-menu/tla-menu.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
Labels: feature

#4719 botcom: scaffolding for i18n
  apps/bemo-worker/package.json
  apps/docs/package.json
  apps/dotcom/client/package.json
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales-compiled/fr.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/public/tla/locales/fr.json
  apps/dotcom/client/src/app.d.ts
  apps/dotcom/client/src/tla/app/i18n.tsx
  apps/dotcom/client/src/tla/components/TlaAccountMenu/TlaAccountMenu.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/TlaAnonLayout.tsx
  apps/dotcom/client/src/tla/layouts/TlaAnonLayout/anon.module.css
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
  apps/dotcom/sync-worker/package.json
  apps/vscode/extension/package.json
  eslint.config.mjs
  internal/dev-tools/package.json
  internal/health-worker/package.json
  internal/scripts/package.json
  lerna.json
  package.json
  packages/assets/package.json
  packages/sync-core/package.json
  packages/sync/package.json
  packages/worker-shared/package.json
  templates/simple-server-example/package.json
  yarn.lock
Labels: other

#4817 Isolate tests by resetting the db between each test.
  apps/dotcom/client/e2e/fixtures/Database.ts
  apps/dotcom/client/e2e/fixtures/Sidebar.ts
  apps/dotcom/client/e2e/fixtures/tla-test.ts
  apps/dotcom/client/e2e/tests/database.spec.ts
  apps/dotcom/client/e2e/tests/homepage.spec.ts
  apps/dotcom/client/package.json
  apps/dotcom/client/playwright.config.ts
  apps/dotcom/client/src/tla/app/TldrawApp.ts
Labels: improvement, dotcom

#4824 Sharing tests
  apps/dotcom/client/e2e/fixtures/Editor.ts
  apps/dotcom/client/e2e/fixtures/ErrorPages.ts
  apps/dotcom/client/e2e/fixtures/HomePage.ts
  apps/dotcom/client/e2e/fixtures/ShareMenu.ts
  apps/dotcom/client/e2e/fixtures/helpers.ts
  apps/dotcom/client/e2e/fixtures/tla-test.ts
  apps/dotcom/client/e2e/tests/sharing.spec.ts
  apps/dotcom/client/playwright.config.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaPublishEditor.tsx
Labels: tests, improvement, dotcom
