Repository tldraw/tldraw, pull requests merged in 2024-01, with the labels that each got.

#2379 Fix meta examples
  apps/examples/src/examples/meta-on-change/OnChangeShapeMetaExample.tsx
  apps/examples/src/examples/meta-on-change/README.md
  apps/examples/src/examples/meta-on-create/OnCreateShapeMetaExample.tsx
  apps/examples/src/examples/meta-on-create/README.md
  apps/examples/src/examples/shape-meta/README.md
  apps/examples/src/examples/shape-meta/ShapeMetaExample.tsx
  packages/store/src/lib/Store.ts
Labels: patch

#2394 Refactor speech bubble
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/helpers.tsx
Labels: patch

#2392 Refactor and document speech bubble example
  apps/examples/src/examples/speech-bubble/CustomShapeWithHandles.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleTool.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/helpers.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/ui-overrides.ts
Labels: documentation

#2395 Annotate api example
  apps/examples/src/examples/api/APIExample.tsx
Labels: documentation

#2398 [fix] edge scrolling when component is inside of screen
  packages/editor/src/lib/utils/edgeScrolling.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: patch

#2397 annotate canvas events
  apps/examples/src/examples/canvas-events/CanvasEventsExample.tsx
Labels: documentation

#2399 annotate asset props, correct image/video confusion
  apps/examples/src/examples/asset-props/AssetPropsExample.tsx
Labels: documentation

#2400 Annotate/refactor store events example
  apps/examples/src/examples/store-events/StoreEventsExample.tsx
Labels: documentation

#2402 [example] Changing the default tldraw colors
  apps/examples/src/examples/changing-default-colors/ChangingDefaultColorsExample.tsx
  apps/examples/src/examples/changing-default-colors/README.md
  packages/tldraw/api/api.json
Labels: documentation

#2406 Fix issues with clip paths for frames
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/primitives/intersect.ts
  packages/editor/src/lib/primitives/utils.ts
Labels: patch

#2407 Add descriptions to active examples
  apps/examples/src/HomePage.tsx
  apps/examples/src/components/ListLink.tsx
  apps/examples/src/styles.css
Labels: documentation

#2412 fix example scrolling on ios
  apps/examples/src/styles.css
Labels: documentation

#2410 annotate error boundary example
  apps/examples/src/examples/error-boundary/ErrorBoundaryExample.tsx
Labels: documentation

#2427 [fix] next selected shapes comment
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
Labels: documentation

#2411 refactor copy/export, fix safari copy-as-image being broken
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-none-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-none-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-pattern-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-pattern-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-semi-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-semi-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-solid-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-solid-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-draw-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-draw-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-mono-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-mono-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-sans-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-sans-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-serif-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-serif-in-dark-mode-1-chromium-linux.png
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/utils/export/copyAs.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/tldraw/src/lib/utils/export/exportAs.ts
Labels: needs qa, patch

#2432 Fix decrement button label in OnTheCanvas example component
  apps/examples/src/examples/things-on-the-canvas/OnTheCanvas.tsx
Labels: documentation

#2436 Fix validation when pasting images.
  packages/tlschema/src/assets/TLImageAsset.ts
  packages/tlschema/src/assets/TLVideoAsset.ts
Labels: patch

#2430 annotate meta onchange
  apps/examples/src/examples/meta-on-change/OnChangeShapeMetaExample.tsx
Labels: documentation

#2408 Annotate custom ui example
  apps/examples/src/examples/custom-ui/CustomUiExample.tsx
Labels: documentation

#2420 annotate hide-ui example
  apps/examples/src/examples/hide-ui/HideUiExample.tsx
Labels: documentation

#2413 Annotate exploded example
  apps/examples/src/examples/exploded/ExplodedExample.tsx
Labels: documentation

#2426 annotate meta oncreate example
  apps/examples/src/examples/meta-on-create/OnCreateShapeMetaExample.tsx
Labels: documentation

#2418 Lokalise: Translations update
  assets/translations/hu.json
  assets/translations/tr.json
Labels: patch

#2440 Fix the publish script
  scripts/publish-new.ts
Labels: patch

#2421 annotate force mobile example
  apps/examples/src/examples/force-mobile/ForceBreakpointExample.tsx
Labels: documentation

#2422 annotate hosted images example
  apps/examples/src/examples/hosted-images/HostedImagesExample.tsx
Labels: documentation

#2423 annotate local images example
  apps/examples/src/examples/local-images/LocalImagesExample.tsx
Labels: documentation

#2431 annotate multiple example
  apps/examples/src/examples/multiple/MultipleExample.tsx
Labels: documentation

#2444 Update README
  README.md
  assets/card-repo.png
  assets/card_repo.svg
Labels: documentation

#2414 annotate external sources example
  apps/examples/src/examples/external-content-sources/ExternalContentSourcesExample.tsx
Labels: documentation

#2434 [Minor] change Simplified Chinese label to Chinese
  assets/translations/languages.json
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/translations/languages.ts
Labels: patch

#2442 Don't bother measuring canvas max size for small images
  packages/tldraw/src/lib/shapes/shared/getBrowserCanvasMaxSize.tsx
  packages/tldraw/src/lib/utils/assets/assets.ts
  packages/tldraw/src/lib/utils/export/export.ts
Labels: patch

#2456 [fix] disable vertical edge resizing for text on mobile
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/records/TLInstance.ts
Labels: patch

#2449 Fix bookmark info for VS Code
  apps/vscode/extension/src/WebViewMessageHandler.ts
Labels: patch

#2450 Fix typos and add comments for persistence example
  apps/examples/src/examples/custom-styles/CustomStylesExample.tsx
  apps/examples/src/examples/persistence/PersistenceExample.tsx
Labels: documentation

#2460 annotate ui events example
  apps/examples/src/examples/ui-events/UiEventsExample.tsx
Labels: documentation

#2448 Fix and annotate minimal example
  apps/examples/src/examples/only-editor/MicroSelectTool.ts
  apps/examples/src/examples/only-editor/MiniBoxShape.tsx
  apps/examples/src/examples/only-editor/MiniSelectTool.ts
  apps/examples/src/examples/only-editor/OnlyEditor.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
Labels: documentation

#2454 annotate snapshot example
  apps/examples/src/examples/snapshots/SnapshotExample.tsx
Labels: documentation

#2461 annotate zones example
  apps/examples/src/examples/zones/ZonesExample.tsx
Labels: documentation

#2459 annotate onthecanvas example
  apps/examples/src/examples/things-on-the-canvas/OnTheCanvas.tsx
Labels: documentation

#2463 delete unused duplicated DraggingHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/children/DraggingHandle.ts
Labels: internal

#2462 rename and annotate user presence example
  apps/examples/src/examples/user-presence/README.md
  apps/examples/src/examples/user-presence/UserPresenceExample.tsx
Labels: documentation

#2464 Update README.md
  README.md
Labels: patch

#2468 [improvement] update dark mode
  packages/editor/editor.css
  packages/tldraw/package.json
Labels: minor

#2424 Maintain bindings whilst translating arrows
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.test.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/test/arrows-megabus.test.tsx
Labels: minor

#2469 [tweak] dark mode colors
  package.json
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/ui.css
  public-yarn.lock
  scripts/purge-css.ts
Labels: patch

#2447 Fix validation for local files.
  packages/validate/src/lib/validation.ts
Labels: patch

#2473 fix typo in hideRotateHandle method
  packages/editor/api/api.json
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
Labels: documentation

#2478 [hot take] Make dark mode colours pop more
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-none-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-none-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-pattern-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-pattern-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-semi-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-semi-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-solid-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-solid-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-draw-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-draw-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-mono-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-mono-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-sans-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-sans-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-serif-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-serif-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-draw-fill-none-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-draw-fill-none-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-draw-fill-pattern-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-draw-fill-pattern-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-draw-fill-semi-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-draw-fill-semi-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-draw-fill-solid-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-draw-fill-solid-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-fill-none-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-fill-none-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-fill-pattern-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-fill-pattern-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-fill-semi-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-fill-semi-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-fill-solid-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-fill-solid-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-draw-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-draw-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-mono-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-mono-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-sans-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-sans-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-serif-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-serif-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-draw-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-draw-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-mono-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-mono-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-sans-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-sans-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-serif-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-serif-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-draw-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-draw-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-mono-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-mono-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-sans-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-sans-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-serif-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-serif-in-dark-mode-1-chromium-linux.png
  packages/tlschema/src/styles/TLColorStyle.ts
Labels: patch

#2477 Fix translations link
  apps/docs/.gitignore
  apps/docs/app/layout.tsx
  apps/docs/components/ArticleDetails.tsx
  apps/docs/components/ArticleDocsPage.tsx
  apps/docs/content/community/contributing.mdx
  apps/docs/content/getting-started/installation.mdx
  apps/docs/styles/globals.css
Labels: documentation

#2483 Prevent overlay content disappearing at some browser zoom levels
  packages/editor/editor.css
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/hooks/useDPRMultiple.ts
  packages/editor/src/lib/utils/nearestMultiple.ts
Labels: patch

#2484 Fix the first run of dev script.
  lazy.config.ts
  packages/tldraw/package.json
Labels: patch

#2485 fix geo cloud icon
  assets/icons/icon/geo-cloud.svg
Labels: patch

#2494 add bash scripts for Vercel
  scripts/vercel/build.sh
  scripts/vercel/install.sh
Labels: internal

#2495 use github.ref rather than github.event.ref in deploy.yml
  .github/workflows/deploy.yml
Labels: internal

#2492 Make sure correct dark mode colours get used in exports
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-leading-line-breaks-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-leading-line-breaks-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-trailing-line-breaks-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-trailing-line-breaks-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-semi-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-fill-semi-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-draw-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-draw-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-mono-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-mono-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-sans-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-sans-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-serif-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-serif-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-draw-fill-pattern-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-draw-fill-pattern-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-draw-fill-semi-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-draw-fill-semi-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-fill-pattern-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-fill-pattern-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-fill-semi-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-fill-semi-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-draw-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-draw-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-mono-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-mono-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-sans-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-sans-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-serif-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-serif-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-draw-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-draw-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-mono-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-mono-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-sans-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-sans-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-serif-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-note-font-serif-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-draw-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-draw-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-mono-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-mono-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-sans-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-sans-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-serif-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-serif-in-dark-mode-1-chromium-linux.png
  packages/editor/editor.css
  packages/editor/src/lib/components/Canvas.tsx
  packages/tlschema/src/styles/TLColorStyle.ts
Labels: patch

#2500 VS Code 2.0.22
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: patch

#2498 auto-it/typescript fails the release, patch the problem away while mods are asleep
  .yarn/patches/@auto-it-core-npm-10.46.0-4ce8f196af.patch
  package.json
  yarn.lock
Labels: internal

#2481 Bump Yarn to 4.0.2 and add version constraints
  .github/actions/setup/action.yml
  .github/workflows/checks.yml
  .github/workflows/playwright-update-snapshots.yml
  .github/workflows/playwright.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-manual.yml
  .github/workflows/publish-new.yml
  .yarn/releases/yarn-3.5.0.cjs
  .yarnrc.yml
  apps/docs/package.json
  apps/dotcom-asset-upload/package.json
  apps/dotcom-bookmark-extractor/package.json
  apps/dotcom-worker/package.json
  apps/dotcom/package.json
  apps/dotcom/src/components/ExportMenu.tsx
  apps/dotcom/src/components/PeopleMenu/PeopleMenu.tsx
  apps/dotcom/src/components/PeopleMenu/UserPresenceColorPicker.tsx
  apps/dotcom/src/components/ShareMenu.tsx
  apps/examples/package.json
  apps/huppy/package.json
  apps/vscode/editor/package.json
  apps/vscode/extension/package.json
  config/package.json
  package.json
  packages/editor/package.json
  packages/state/package.json
  packages/store/package.json
  packages/tldraw/package.json
  packages/tlschema/package.json
  packages/tlsync/package.json
  packages/utils/package.json
  packages/validate/package.json
  scripts/package.json
  scripts/vercel/build.sh
  scripts/vercel/install.sh
  yarn.config.cjs
  yarn.lock
Labels: enhancement, dependencies

#2551 add dev / build scripts
  package.json
Labels: internal

#2552 [dotcom] Delete service worker, cache tldraw assets
  .eslintignore
  apps/dotcom/.gitignore
  apps/dotcom/package.json
  apps/dotcom/public/manifest.webmanifest
  apps/dotcom/public/sw.js
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/main.tsx
  apps/dotcom/src/utils/assetUrls.ts
  apps/dotcom/vite.config.ts
  package.json
  packages/assets/imports.vite.d.ts
  packages/assets/imports.vite.js
  packages/assets/package.json
  packages/assets/tsconfig.json
  scripts/refresh-assets.ts
  yarn.lock
Labels: minor

#2567 fix: replaced dead links
  apps/docs/content/docs/assets.mdx
Labels: documentation

#2568 [improvement] better comma control for pointer
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
Labels: minor

#2569 [Internal] Create build-docs.sh
  scripts/vercel/build-docs.sh
Labels: internal

#2561 Use simple example
  apps/docs/content/getting-started/examples.mdx
Labels: documentation

#2599 Replace "original tldraw issue" with docs link.
  .github/ISSUE_TEMPLATE/config.yml
Labels: internal

#2557 arrows: add ability to change label placement
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/index.ts
  packages/editor/src/lib/components/GeometryDebuggingView.tsx
  packages/editor/src/lib/components/default-components/DefaultHandle.tsx
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/editor/src/lib/editor/shapes/shared/arrow/shared.ts
  packages/editor/src/lib/primitives/Box.ts
  packages/editor/src/lib/primitives/Vec.ts
  packages/editor/src/lib/primitives/geometry/Arc2d.ts
  packages/editor/src/lib/primitives/geometry/Circle2d.ts
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
  packages/editor/src/lib/primitives/geometry/Group2d.ts
  packages/editor/src/lib/primitives/utils.ts
  packages/editor/src/lib/utils/debug-flags.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.test.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/arrowLabel.ts
  packages/tldraw/src/lib/shapes/arrow/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/geo/cloudOutline.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/default-shape-constants.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.ts
  packages/tldraw/src/lib/utils/tldr/buildFromV1Document.ts
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/misc/TLHandle.ts
  packages/tlschema/src/shapes/TLArrowShape.ts
  packages/tlsync/src/test/TLSyncRoom.test.ts
Labels: minor

#2615 Fix ios export crash
  packages/tldraw/src/lib/shapes/shared/getBrowserCanvasMaxSize.tsx
Labels: patch

#2558 debug: add FPS counter
  apps/examples/src/components/ListLink.tsx
  apps/examples/src/hooks/useMergedRefs.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/utils/debug-flags.ts
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/DebugPanel.tsx
Labels: minor

#2617 Only actions on selected shapes if we are in select tool.
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
Labels: patch

#2620 Fix yarn clean
  scripts/clean.sh
Labels: internal

#2623 style: fix missing titles on vertical align menu
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: patch

#2625 i18n: sort languages by name, not by locale code
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/translations/languages.ts
  scripts/refresh-assets.ts
Labels: patch

#2624 menus: address several little big things about menu styling
  assets/icons/icon/checkbox-empty.svg
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/hooks/useMenuIsOpen.ts
Labels: patch

#2634 Fix nudge bug
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/commands/nudge.test.ts
Labels: patch

#2630 [draft] Keep editor focus after losing focus of an action button
  packages/tldraw/src/lib/ui/components/DuplicateButton.tsx
  packages/tldraw/src/lib/ui/components/RedoButton.tsx
  packages/tldraw/src/lib/ui/components/TrashButton.tsx
  packages/tldraw/src/lib/ui/components/UndoButton.tsx
  packages/tldraw/src/lib/ui/components/primitives/Button.tsx
Labels: patch

#2644 remove erroneous mount entry from fly.toml
  apps/huppy/fly.toml
Labels: internal

#2628 [Improvement] Share zone styling
  apps/dotcom/src/components/ExportMenu.tsx
  apps/dotcom/src/components/PeopleMenu/PeopleMenu.tsx
  apps/dotcom/src/components/ShareButton.tsx
  apps/dotcom/src/components/ShareMenu.tsx
  apps/dotcom/styles/z-board.css
Labels: patch

#2619 Update layout.tsx
  apps/docs/app/layout.tsx
  apps/docs/components/AutoRefresh.tsx
  apps/docs/public/favicon.ico
  vercel.json
Labels: documentation

#2650 Restore vercel.jsons
  apps/docs/components/Footer.tsx
  apps/dotcom/vercel.json
  apps/examples/vercel.json
Labels: internal

#2594 Update README and examples copy in the docs
  README.md
  apps/examples/src/examples/develop/README.md
Labels: documentation

#2651 Remove repeated word in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#2657 [Fix] Wheel bug
  packages/editor/src/lib/hooks/useGestureEvents.ts
Labels: patch

#2597 Add button to Examples to request an example
  .github/ISSUE_TEMPLATE/example_request.yml
  apps/examples/public/icons/discord.svg
  apps/examples/public/icons/github.svg
  apps/examples/public/icons/twitter.svg
  apps/examples/src/ExamplePage.tsx
  apps/examples/src/components/ListLink.tsx
  apps/examples/src/styles.css
Labels: documentation

#2409 Positional keyboard shortcuts for toolbar
  apps/examples/e2e/tests/test-kbds.spec.ts
  packages/tldraw/src/lib/ui/components/Toolbar/Toolbar.tsx
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
Labels: minor

#2480 Improved duplication
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/tools/SelectTool/SelectTool.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
  packages/tldraw/src/test/duplicate.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/records/TLInstance.ts
  packages/tlsync/src/lib/TLSyncClient.ts
Labels: minor

#2661 [Fix] Missing bend handles on curved arrows
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/components/default-components/DefaultHandle.tsx
  packages/editor/src/lib/constants.ts
Labels: patch

#2663 [Fix] Overlapping non-adjacent handles
  packages/editor/editor.css
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/components/default-components/DefaultHandle.tsx
  packages/editor/src/lib/hooks/useCursor.ts
  packages/tldraw/src/lib/ui.css
Labels: patch

#2670 [Improvement] Text measurement tweaks
  packages/editor/editor.css
  packages/editor/src/lib/editor/managers/TextManager.ts
Labels: patch

#2672 [dx] Add docs to lazy caching.
  lazy.config.ts
  lerna.json
Labels: internal

#2674 [DX] Use tabs in JSON.stringify
  apps/docs/scripts/functions/createApiMarkdown.ts
  apps/examples/src/examples/canvas-events/CanvasEventsExample.tsx
  apps/examples/src/examples/meta-on-change/OnChangeShapeMetaExample.tsx
  apps/examples/src/examples/meta-on-create/OnCreateShapeMetaExample.tsx
  apps/examples/src/examples/shape-meta/ShapeMetaExample.tsx
  apps/huppy/pages/api/dev/simulate.ts
  apps/huppy/pages/deliveries.tsx
  apps/vscode/extension/src/TldrawDocument.ts
  packages/tlsync/src/test/syncFuzz.test.ts
Labels: patch

#2499 Introduce a Cloudflare health worker
  .github/workflows/deploy.yml
  apps/health-worker/.gitignore
  apps/health-worker/README.md
  apps/health-worker/package.json
  apps/health-worker/src/discord.ts
  apps/health-worker/src/index.ts
  apps/health-worker/src/updown_types.ts
  apps/health-worker/tsconfig.json
  apps/health-worker/wrangler.toml
  scripts/deploy.ts
  yarn.lock
Labels: internal

#2585 Grouping examples into categories
  apps/examples/package.json
  apps/examples/src/ExamplePage.tsx
  apps/examples/src/HomePage.tsx
  apps/examples/src/components/ExamplesLink.tsx
  apps/examples/src/components/Icons.tsx
  apps/examples/src/examples.tsx
  apps/examples/src/examples/api/README.md
  apps/examples/src/examples/asset-props/README.md
  apps/examples/src/examples/canvas-events/README.md
  apps/examples/src/examples/changing-default-colors/README.md
  apps/examples/src/examples/context-toolbar/README.md
  apps/examples/src/examples/custom-components/README.md
  apps/examples/src/examples/custom-config/README.md
  apps/examples/src/examples/custom-styles/README.md
  apps/examples/src/examples/custom-ui/README.md
  apps/examples/src/examples/develop/README.md
  apps/examples/src/examples/error-boundary/README.md
  apps/examples/src/examples/exploded/README.md
  apps/examples/src/examples/external-content-sources/README.md
  apps/examples/src/examples/floaty-window/README.md
  apps/examples/src/examples/force-mobile/README.md
  apps/examples/src/examples/hide-ui/README.md
  apps/examples/src/examples/hosted-images/README.md
  apps/examples/src/examples/keyboard-shortcuts/README.md
  apps/examples/src/examples/local-images/README.md
  apps/examples/src/examples/meta-on-change/README.md
  apps/examples/src/examples/meta-on-create/README.md
  apps/examples/src/examples/multiple/README.md
  apps/examples/src/examples/only-editor/README.md
  apps/examples/src/examples/persistence/README.md
  apps/examples/src/examples/readonly/README.md
  apps/examples/src/examples/screenshot-tool/README.md
  apps/examples/src/examples/scroll/README.md
  apps/examples/src/examples/shape-meta/README.md
  apps/examples/src/examples/snapshots/README.md
  apps/examples/src/examples/speech-bubble/README.md
  apps/examples/src/examples/store-events/README.md
  apps/examples/src/examples/things-on-the-canvas/README.md
  apps/examples/src/examples/ui-events/README.md
  apps/examples/src/examples/user-presence/README.md
  apps/examples/src/examples/zones/README.md
  apps/examples/src/index.tsx
  apps/examples/src/styles.css
  apps/examples/vite.config.ts
  yarn.lock
Labels: documentation

#2560 debug: start adding more tooling for debugging when interacting with shapes
  packages/tldraw/src/lib/ui/components/DebugPanel.tsx
Labels: minor

#2627 dev: add test-dev command for easier testing of packages
  apps/dotcom-asset-upload/package.json
  apps/dotcom-worker/package.json
  apps/dotcom/package.json
  package.json
  packages/editor/package.json
  packages/state/package.json
  packages/store/package.json
  packages/tldraw/package.json
  packages/tlschema/package.json
  packages/tlsync/package.json
  packages/utils/package.json
  packages/validate/package.json
Labels: internal

#2678 Remove examples app landing page
  apps/examples/src/HomePage.tsx
  apps/examples/src/index.tsx
Labels: documentation

#2682 check for duplicate dependencies in CI
  .github/workflows/checks.yml
  yarn.lock
Labels: internal

#2676 Fix svg exporting for images with not fully qualified url (`/tldraw.png` or `./tldraw.png`)
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
Labels: patch

#2683 make CI check for yarn install warnings and fix the peer deps ones we have
  .github/workflows/checks.yml
  apps/dotcom-worker/package.json
  apps/dotcom/package.json
  apps/examples/package.json
  apps/huppy/package.json
  apps/vscode/extension/package.json
  config/package.json
  packages/assets/package.json
  packages/store/package.json
  packages/tlschema/package.json
  packages/tlsync/package.json
  scripts/package.json
  yarn.lock
Labels: internal

#2689 remove dotcom's vercel.json
  apps/dotcom/vercel.json
Labels: internal

#2694 [Examples] Add a stupid 404 page
  apps/examples/src/index.tsx
Labels: documentation

#2696 [Fix] Note shape border radius
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
Labels: patch

#2697 reactive context menu overrides
  packages/tldraw/setupTests.js
  packages/tldraw/src/lib/Tldraw.test.tsx
  packages/tldraw/src/lib/shapes/shared/defaultStyleDefs.tsx
  packages/tldraw/src/lib/ui/components/ContextMenu.tsx
  packages/tldraw/src/lib/ui/hooks/useContextMenuSchema.tsx
  packages/tldraw/src/test/TldrawEditor.test.tsx
  packages/tldraw/src/test/testutils/renderTldrawComponent.tsx
  packages/tldraw/src/test/ui/ContextMenu.test.tsx
Labels: patch

#2698 fix prune preview deployment script
  .github/workflows/prune-preview-deploys.yml
  scripts/prune-preview-deploys.ts
Labels: internal

#2691 Update the project to Node 20
  .github/actions/setup/action.yml
  apps/docs/package.json
  apps/health-worker/package.json
  apps/vscode/editor/package.json
  package.json
  packages/editor/src/lib/utils/sync/indexedDb.test.ts
  packages/state/src/lib/react/track.test.tsx
  packages/state/src/lib/react/useStateTracking.test.tsx
  packages/state/src/lib/react/useValue.test.tsx
  packages/store/src/lib/test/migrate.test.ts
  packages/store/src/lib/test/recordStore.test.ts
  packages/tldraw/src/lib/shapes/line/__snapshots__/LineShapeUtil.test.ts.snap
  packages/tldraw/src/test/Editor.test.tsx
  packages/tldraw/src/test/TLSessionStateSnapshot.test.ts
  packages/tldraw/src/test/__snapshots__/groups.test.ts.snap
  packages/tldraw/src/test/__snapshots__/resizing.test.ts.snap
  packages/tldraw/src/test/commands/__snapshots__/packShapes.test.ts.snap
  packages/tldraw/src/test/commands/__snapshots__/zoomToFit.test.ts.snap
  packages/tldraw/src/test/resizing.test.ts
  packages/tldraw/src/test/translating.test.ts
  packages/tlschema/src/migrations.test.ts
  packages/tlsync/src/test/chunk.test.ts
  packages/tlsync/src/test/diff.test.ts
  packages/validate/src/test/validation.test.ts
  scripts/package.json
  yarn.lock
Labels: internal
