Repository tldraw/tldraw, pull requests merged in 2024-04, with the labels that each got.

#3319 Stickies: simplify shadows / DOM elements, add note colors to theme, new colors
  apps/dotcom/package.json
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenuContent.tsx
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/styles/TLColorStyle.ts
  yarn.lock
Labels: improvement, sdk

#2751 [internal] Add license report scripts
  .gitignore
  package.json
  scripts/license-report.ts
  yarn.lock
Labels: internal

#3321 Add white
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/styles/TLColorStyle.ts
Labels: feature, sdk

#3118 squish sync data events before sending them out
  packages/tlsync/package.json
  packages/tlsync/src/lib/TLSyncClient.ts
  packages/tlsync/src/lib/TLSyncRoom.ts
  packages/tlsync/src/lib/diff.ts
  packages/tlsync/src/lib/squish.ts
  packages/tlsync/src/test/squish.test.ts
  yarn.lock
Labels: minor

#3223 Input buffering
  apps/examples/e2e/tests/test-canvas-events.spec.ts
  apps/examples/e2e/tests/test-shapes.spec.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/translating.test.ts
  packages/utils/src/lib/throttle.ts
Labels: improvement, sdk

#3327 Fix text resizing bug
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
Labels: bugfix, sdk

#3332 Revert "Fix text resizing bug (#3327)"
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
Labels: bugfix, sdk

#3333 textfields: fix regression with Text shape and resizing
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
Labels: bugfix, sdk

#3338 Font size adjustment migration
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/shapes/TLNoteShape.ts
Labels: improvement, sdk

#3342 Fix weird text complete
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/shapes/note/noteCloning.test.ts
  packages/tldraw/src/lib/shapes/note/noteHelpers.ts
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
Labels: bugfix, sdk

#3343 Fix blur bug in editable text
  packages/editor/src/lib/editor/Editor.ts
  packages/state/api/api.json
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/test/SelectTool.test.ts
Labels: bugfix, sdk

#3275 Add long press event
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/tools/StateNode.ts
  packages/editor/src/lib/editor/types/event-types.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingCropHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingResizeHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingRotateHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingSelection.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/ScribbleBrushing.ts
Labels: feature, sdk

#3330 Examples: update kbd shortcuts, add actions overrides example
  apps/examples/src/examples/action-overrides/ActionOverridesExample.tsx
  apps/examples/src/examples/action-overrides/README.md
  apps/examples/src/examples/keyboard-shortcuts/KeyboardShortcuts.tsx
  apps/examples/src/examples/keyboard-shortcuts/README.md
  apps/examples/src/examples/keyboard-shortcuts/snapshot.json
Labels: docs, improvement

#3371 Update useFileSystem.tsx
  apps/dotcom/src/utils/useFileSystem.tsx
Labels: feature, sdk

#3291 Display none for culled shapes
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/editor.css
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
  packages/tldraw/src/lib/ui/components/HelperButtons/BackToContent.tsx
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/shapes/TLEmbedShape.ts
Labels: internal, improvement

#3378 put `getCurrentPageId` into a computed
  packages/editor/src/lib/editor/Editor.ts
Labels: improvement, sdk

#3377 [culling] minimal culled diff with webgl
  packages/editor/editor.css
  packages/editor/src/lib/components/CulledShapes.tsx
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
Labels: improvement, sdk

#3380 Fix an issue with layers when moving shapes.
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
Labels: bugfix, sdk

#3384 Remove note parenting
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
Labels: feature, sdk

#3385 Fix typo in Store.ts
  packages/store/src/lib/Store.ts
Labels: docs, chore

#3376 [culling] Improve setting of display none.
  apps/examples/src/examples/custom-renderer/CustomRenderer.tsx
  apps/examples/src/examples/rendering-shape-changes/useRenderingShapesChange.ts
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/components/CulledShapes.tsx
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/getSvgJsx.tsx
  packages/tldraw/src/lib/ui/components/HelperButtons/BackToContent.tsx
  packages/tldraw/src/test/renderingShapes.test.tsx
Labels: internal, improvement

#3401 Perf: (slightly) faster min dist checks
  packages/editor/api-report.md
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/ClickManager.ts
  packages/editor/src/lib/primitives/Vec.ts
  packages/editor/src/lib/primitives/geometry/Arc2d.ts
  packages/editor/src/lib/primitives/geometry/CubicBezier2d.ts
  packages/editor/src/lib/primitives/geometry/CubicSpline2d.ts
  packages/editor/src/lib/primitives/geometry/Ellipse2d.ts
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
  packages/editor/src/lib/primitives/geometry/Group2d.ts
  packages/editor/src/lib/primitives/geometry/Polyline2d.ts
  packages/store/api/api.json
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
Labels: improvement, sdk

#3412 Stickies: Emit `text-select-all` event
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/types/emit-types.ts
  packages/tldraw/src/lib/shapes/note/noteHelpers.ts
  packages/tldraw/src/lib/shapes/shared/TextHelpers.ts
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/text/TextArea.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingShape.ts
Labels: improvement, sdk

#3416 Perf: slightly faster `getShapeAtPoint`
  packages/editor/src/lib/editor/Editor.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/perf.ts
Labels: improvement, sdk

#3418 Perf: block hit tests while moving camera
  packages/editor/editor.css
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
Labels: improvement, sdk

#3423 Fix text bug on iOS
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix, sdk

#3419 Perf: throttle `updateHoveredId`
  packages/tldraw/src/lib/tools/selection-logic/updateHoveredId.ts
Labels: improvement, sdk

#3403 Fix some tests
  packages/editor/src/lib/components/CulledShapes.tsx
  packages/tldraw/src/lib/shapes/shared/defaultStyleDefs.tsx
Labels: tests, sdk

#3429 Perf: Improve text outline performance
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/constants.ts
Labels: improvement, sdk

#3411 Perf: Incremental culled shapes calculation.
  apps/examples/src/examples/rendering-shape-changes/useRenderingShapesChange.ts
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/components/CulledShapes.tsx
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/derivations/notVisibleShapes.ts
  packages/tldraw/src/test/getCulledShapes.test.tsx
  packages/tldraw/src/test/renderingShapes.test.tsx
Labels: improvement, sdk

#3431 Reorder dom elements.
  packages/editor/editor.css
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
Labels: internal, chore

#3430 Update font import URL in quick-start.mdx
  apps/docs/content/getting-started/quick-start.mdx
Labels: docs, bugfix

#3435 Fix cursor chat in context menu.
  apps/dotcom/src/utils/context-menu/CursorChatMenuItem.tsx
Labels: bugfix, dotcom

#3434 Make minimap display sharp rectangles.
  packages/tldraw/src/lib/ui/components/Minimap/MinimapManager.ts
Labels: improvement, sdk

#3438 Remove minimap throttling
  packages/tldraw/src/lib/ui/components/Minimap/MinimapManager.ts
Labels: bugfix, sdk

#3442 VS Code 2.0.27
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: chore

#3446 Fix SVG exports in Next.js
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/getSvgJsx.tsx
  packages/tldraw/src/test/commands/__snapshots__/getSvgString.test.ts.snap
Labels: bugfix, sdk

#3447 Performance measurement tool (for unit tests)
  packages/tldraw/src/test/perf/PerformanceMeasurer.ts
  packages/tldraw/src/test/perf/perf.test.ts
Labels: internal, sdk

#3445 Fix panning.
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix, sdk

#3451 Remove docs for Editor.batch
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix, sdk

#3452 [hotfix] Panning fix for VS Code
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: bugfix

#3454 Faster selection / erasing
  apps/examples/src/examples/exploded/ExplodedExample.tsx
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/editor.css
  packages/editor/src/index.ts
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/components/default-components/DefaultHoveredShapeIndicator.tsx
  packages/editor/src/lib/components/default-components/DefaultShapeIndicator.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/SnapManager/HandleSnaps.ts
  packages/editor/src/lib/editor/shapes/shared/arrow/curved-arrow.ts
  packages/editor/src/lib/editor/shapes/shared/arrow/straight-arrow.ts
  packages/editor/src/lib/editor/tools/StateNode.ts
  packages/editor/src/lib/hooks/useEditorComponents.tsx
  packages/editor/src/lib/primitives/Vec.ts
  packages/editor/src/lib/primitives/geometry/Arc2d.ts
  packages/editor/src/lib/primitives/geometry/Circle2d.ts
  packages/editor/src/lib/primitives/geometry/CubicSpline2d.ts
  packages/editor/src/lib/primitives/geometry/Edge2d.ts
  packages/editor/src/lib/primitives/geometry/Ellipse2d.ts
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
  packages/editor/src/lib/primitives/geometry/Polyline2d.ts
  packages/editor/src/lib/primitives/geometry/Stadium2d.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/canvas/TldrawHoveredShapeIndicator.tsx
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
  packages/tldraw/src/lib/shapes/geo/cloudOutline.ts
  packages/tldraw/src/lib/shapes/line/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/shared/freehand/getStrokePoints.ts
  packages/tldraw/src/lib/tools/EraserTool/childStates/Erasing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Brushing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingArrowLabel.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/ScribbleBrushing.ts
  packages/tldraw/src/test/TldrawEditor.test.tsx
  packages/tldraw/src/test/perf/PerformanceMeasurer.ts
  packages/tldraw/src/test/perf/perf.test.ts
Labels: improvement, sdk

#3457 Don't show edit link for locked shapes.
  packages/tldraw/src/lib/ui/hooks/menu-hooks.ts
Labels: bugfix, sdk

#3456 Only run when shapes change.
  packages/editor/src/lib/editor/derivations/parentsToChildren.ts
Labels: internal, improvement

#3459 Allow users to edit the document title by double clicking it even when editing a shape.
  apps/dotcom/src/components/DocumentName/DocumentName.tsx
Labels: bugfix, dotcom

#3460 Perf: Use a computed cache for masked shape page bounds
  packages/editor/src/lib/editor/Editor.ts
Labels: improvement, sdk

#3453 Perf: Improve perf of `getCurrentPageShapesSorted`
  packages/editor/src/lib/editor/Editor.ts
Labels: internal, improvement

#3461 conditionally use star-history dark theme
  README.md
Labels: docs, improvement

#3462 Cancel pointer velocity while pinching
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/TickManager.ts
Labels: bugfix, sdk

#3466 undo devFreeze unintentional commit
  packages/store/src/lib/devFreeze.ts
Labels: bugfix, sdk

#3439 RBush again?
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/package.json
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/derivations/notVisibleShapes.ts
  packages/editor/src/lib/editor/derivations/spatialIndex.ts
  packages/editor/src/lib/primitives/Box.ts
  packages/tldraw/src/lib/tools/EraserTool/childStates/Erasing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Brushing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/ScribbleBrushing.ts
  packages/tldraw/src/test/getCulledShapes.test.tsx
  packages/tldraw/src/test/selection-omnibus.test.ts
  packages/tldraw/src/test/spatialIndex.test.ts
  yarn.lock
Labels: internal, improvement

#3468 perf: calculate hypoteneuse manually instead of using hypot
  packages/editor/src/lib/editor/shapes/shared/arrow/curved-arrow.ts
  packages/editor/src/lib/primitives/Mat.ts
  packages/editor/src/lib/primitives/Vec.ts
Labels: improvement, sdk

#3471 [perf] faster signia capture
  packages/state/api-report.md
  packages/state/src/lib/core/ArraySet.ts
  packages/state/src/lib/core/Computed.ts
  packages/state/src/lib/core/EffectScheduler.ts
  packages/state/src/lib/core/__tests__/arraySet.test.ts
  packages/state/src/lib/core/__tests__/capture.test.ts
  packages/state/src/lib/core/capture.ts
  packages/state/src/lib/core/types.ts
Labels: improvement, sdk

#3476 [fix] use page point for pointer
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix, sdk

#3480 Revert "[perf] faster signia capture (#3471)"
  packages/state/api-report.md
  packages/state/src/lib/core/ArraySet.ts
  packages/state/src/lib/core/Computed.ts
  packages/state/src/lib/core/EffectScheduler.ts
  packages/state/src/lib/core/__tests__/arraySet.test.ts
  packages/state/src/lib/core/__tests__/capture.test.ts
  packages/state/src/lib/core/capture.ts
  packages/state/src/lib/core/types.ts
Labels: internal

#3481 Revert "RBush again? (#3439)"
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/package.json
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/derivations/notVisibleShapes.ts
  packages/editor/src/lib/editor/derivations/spatialIndex.ts
  packages/editor/src/lib/primitives/Box.ts
  packages/tldraw/src/lib/tools/EraserTool/childStates/Erasing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Brushing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/ScribbleBrushing.ts
  packages/tldraw/src/test/getCulledShapes.test.tsx
  packages/tldraw/src/test/selection-omnibus.test.ts
  packages/tldraw/src/test/spatialIndex.test.ts
  yarn.lock
Labels: bugfix, internal

#3478 stickies: hide clone handles on mobile
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
Labels: bugfix, sdk

#3484 stickies: dont remove selection ranges when edit->edit
  packages/tldraw/src/lib/tools/SelectTool/childStates/EditingShape.ts
Labels: bugfix, sdk

#3487 [perf] faster signia capture (again)
  packages/state/api-report.md
  packages/state/src/lib/core/ArraySet.ts
  packages/state/src/lib/core/Computed.ts
  packages/state/src/lib/core/EffectScheduler.ts
  packages/state/src/lib/core/__tests__/arraySet.test.ts
  packages/state/src/lib/core/__tests__/capture.test.ts
  packages/state/src/lib/core/__tests__/fuzz.tlstate.test.ts
  packages/state/src/lib/core/capture.ts
  packages/state/src/lib/core/types.ts
Labels: improvement, sdk

#3488 Fix alt-duplicating shapes sometimes not working
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingShape.ts
Labels: bugfix, dotcom, sdk

#3485 Only show cursor chat button in select mode
  apps/dotcom/src/utils/context-menu/CursorChatMenuItem.tsx
Labels: bugfix, dotcom

#3493 stickies: a bit of fuzziness when calculating certain text
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
Labels: bugfix, sdk

#3497 css more shapes that need transparent behavior
  RELEASES.md
  packages/editor/editor.css
Labels: bugfix, sdk

#3498 textfields: fix dragging selected shape behind another
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
Labels: bugfix, sdk

#3501 textfields: wait a tick before selecting all to fix iOS
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
Labels: bugfix, sdk

#3467 Add slides example
  apps/examples/src/examples/slides/README.md
  apps/examples/src/examples/slides/SlideShapeTool.tsx
  apps/examples/src/examples/slides/SlideShapeUtil.tsx
  apps/examples/src/examples/slides/SlidesExample.tsx
  apps/examples/src/examples/slides/SlidesPanel.tsx
  apps/examples/src/examples/slides/slides.css
  apps/examples/src/examples/slides/useSlides.tsx
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
Labels: docs, dunno

#3503 Stickies: fix sticky note clipping
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix, sdk

#3486 Color tweaks (light and dark mode)
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-leading-line-breaks-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-leading-line-breaks-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-trailing-line-breaks-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-trailing-line-breaks-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-draw-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-draw-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-mono-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-mono-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-sans-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-sans-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-serif-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-arrow-font-serif-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-draw-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-draw-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-mono-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-mono-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-sans-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-sans-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-serif-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-geo-font-serif-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-draw-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-draw-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-mono-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-mono-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-sans-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-sans-in-dark-mode-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-serif-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-text-font-serif-in-dark-mode-1-chromium-linux.png
  packages/editor/editor.css
  packages/tlschema/src/styles/TLColorStyle.ts
Labels: bugfix, sdk

#3469 textfields: on mobile edit->edit, allow going to empty geo
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/EditingShape.ts
  packages/tldraw/src/lib/tools/selection-logic/getHitShapeOnCanvasPointerDown.ts
Labels: bugfix, sdk

#3507 "Soft preload" icons
  .github/ISSUE_TEMPLATE/bug_report.yml
  config/setupJest.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/ui/context/asset-urls.tsx
  packages/tldraw/src/lib/ui/hooks/usePreloadIcons.ts
Labels: improvement, sdk

#3506 textfields: nix disableTab option; make TextShapes have custom Tab behavior as intended
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/arrow/components/ArrowTextLabel.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
Labels: sdk, chore

#3511 arrows: still use Dist instead of Dist2
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingArrowLabel.ts
Labels: bugfix, sdk

#3513 textfields: fix Safari cursor rendering bug, take 2
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
Labels: bugfix, sdk

#3512 arrows: fix bound arrow labels going over text shape
  packages/tldraw/src/lib/shapes/arrow/arrowLabel.ts
Labels: bugfix, sdk

#3515 VS Code 2.0.29
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: chore

#3517 [fix] allow loading files
  packages/tldraw/src/lib/utils/tldr/file.ts
  packages/validate/api-report.md
  packages/validate/api/api.json
  packages/validate/src/lib/validation.ts
Labels: bugfix, sdk

#3519 VS Code 2.0.30
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: bugfix

#3516 [signia] Smart dirty checking of active computeds
  packages/state/src/lib/core/Computed.ts
  packages/state/src/lib/core/transactions.ts
Labels: improvement, sdk

#3508 Use computed cache for getting the parent child relationships
  packages/editor/src/lib/editor/Editor.ts
Labels: internal, improvement

#3521 Fix version
  apps/dotcom/src/components/IFrameProtector.tsx
Labels: bugfix, dotcom

#3532 Improve back to content
  apps/dotcom/src/components/IFrameProtector.tsx
  packages/tldraw/src/lib/ui/components/HelperButtons/BackToContent.tsx
Labels: enhancement, improvement, sdk

#3510 WebGL Minimap
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/usePeerIds.ts
  packages/editor/src/lib/hooks/usePresence.ts
  packages/editor/src/lib/primitives/Mat.ts
  packages/tldraw/src/lib/ui/components/Minimap/DefaultMinimap.tsx
  packages/tldraw/src/lib/ui/components/Minimap/MinimapManager.ts
  packages/tldraw/src/lib/ui/components/Minimap/getRgba.ts
  packages/tldraw/src/lib/ui/components/Minimap/minimap-webgl-setup.ts
  packages/tldraw/src/lib/ui/components/Minimap/minimap-webgl-shapes.ts
Labels: improvement, sdk

#3464 Perf: minor drawing speedup
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
  packages/tldraw/src/lib/shapes/shared/freehand/svgInk.ts
  packages/tldraw/src/test/__snapshots__/drawing.test.ts.snap
  packages/tldraw/src/test/drawing.data.ts
  packages/tldraw/src/test/drawing.test.ts
  packages/utils/src/lib/perf.ts
Labels: improvement, sdk

#3536 Prevent default on native clipboard events
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: bugfix, sdk

#3545 Expose `usePreloadAssets`
  apps/examples/src/examples/exploded/ExplodedExample.tsx
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/hooks/usePreloadAssets.ts
Labels: docs, bugfix, sdk

#3550 Fix deploy script
  scripts/deploy.ts
  scripts/package.json
  yarn.lock
Labels: internal, tools

#3559 fix document name alignment
  apps/dotcom/styles/z-board.css
Labels: bugfix, dotcom

#3561 Fix transparent colors in the minimap
  packages/tldraw/src/lib/ui/components/Minimap/DefaultMinimap.tsx
  packages/tldraw/src/lib/ui/components/Minimap/MinimapManager.ts
  packages/tldraw/src/lib/ui/components/Minimap/minimap-webgl-setup.ts
Labels: improvement, sdk

#3563 Fix collaborator size with zoom
  packages/tldraw/src/lib/ui/components/Minimap/MinimapManager.ts
Labels: bugfix, sdk

#3564 Add releases section to docs
  apps/docs/api/editor.api.json
  apps/docs/api/store.api.json
  apps/docs/api/tldraw.api.json
  apps/docs/api/tlschema.api.json
  apps/docs/api/validate.api.json
  apps/docs/content/getting-started/installation.mdx
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/docs/content/releases/v2.0.0-alpha.12.mdx
  apps/docs/content/releases/v2.0.0-alpha.13.mdx
  apps/docs/content/releases/v2.0.0-alpha.14.mdx
  apps/docs/content/releases/v2.0.0-alpha.15.mdx
  apps/docs/content/releases/v2.0.0-alpha.16.mdx
  apps/docs/content/releases/v2.0.0-alpha.17.mdx
  apps/docs/content/releases/v2.0.0-alpha.18.mdx
  apps/docs/content/releases/v2.0.0-alpha.19.mdx
  apps/docs/content/releases/v2.0.0-beta.1.mdx
  apps/docs/content/releases/v2.0.0-beta.2.mdx
  apps/docs/content/releases/v2.0.0-beta.3.mdx
  apps/docs/content/releases/v2.0.0-beta.4.mdx
  apps/docs/content/releases/v2.0.0-beta.5.mdx
  apps/docs/content/releases/v2.0.0-beta.6.mdx
  apps/docs/content/releases/v2.0.0-beta.7.mdx
  apps/docs/content/releases/v2.0.0-beta.8.mdx
  apps/docs/content/releases/v2.0.0-beta.9.mdx
  apps/docs/content/releases/v2.0.0.mdx
  apps/docs/content/releases/v2.0.1.mdx
  apps/docs/content/releases/v2.0.2.mdx
  apps/docs/content/sections.json
  apps/docs/scripts/functions/fetchReleases.ts
Labels: docs, feature

#3566 VS Code 2.0.31
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: chore

#3567 longer retries for package publishing
  scripts/lib/publishing.ts
Labels: internal, chore

#3570 increase publish script timeouts
  .github/workflows/publish-canary.yml
  .github/workflows/publish-manual.yml
  .github/workflows/publish-new.yml
  .github/workflows/publish-patch.yml
  .github/workflows/publish-templates.yml
  scripts/lib/publishing.ts
Labels: internal, chore

#3586 fix migration exports
  .eslintrc.js
  apps/dotcom/src/utils/assetUrls.ts
  apps/examples/src/examples/custom-config/CardShape/card-shape-migrations.ts
  apps/examples/src/examples/exploded/ExplodedExample.tsx
  apps/examples/src/examples/image-annotator/ImageAnnotationEditor.tsx
  apps/examples/src/examples/pdf-editor/PdfEditor.tsx
  apps/examples/src/examples/shape-with-migrations/ShapeWithMigrationsExample.tsx
  apps/examples/src/examples/shape-with-tldraw-styles/ShapeWithTldrawStylesExample.tsx
  apps/examples/src/examples/slides/SlideShapeUtil.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
  apps/examples/src/misc/EndToEndApi.tsx
  apps/vscode/editor/src/app.tsx
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/shared/ShapeFill.tsx
  packages/tldraw/src/lib/shapes/shared/getPerfectDashProps.ts
  packages/tldraw/src/lib/ui/constants.ts
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/index.ts
  scripts/lib/eslint-plugin.ts
Labels: bugfix, sdk

#3597 Fix patch release script
  scripts/lib/didAnyPackageChange.ts
Labels: bugfix, internal

#3565 Don't check api.json files into git
  .gitignore
  .husky/pre-commit
  apps/docs/api/editor.api.json
  apps/docs/api/store.api.json
  apps/docs/api/tldraw.api.json
  apps/docs/api/tlschema.api.json
  apps/docs/api/validate.api.json
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/docs/content/releases/v2.0.0.mdx
  apps/docs/content/releases/v2.0.1.mdx
  apps/docs/content/releases/v2.0.2.mdx
  apps/docs/package.json
  apps/docs/scripts/functions/connect.ts
  apps/docs/scripts/functions/refreshContent.ts
  apps/docs/scripts/reset-db.ts
  apps/docs/utils/ContentDatabase.ts
  apps/docs/utils/ContentVectorDatabase.ts
  lazy.config.ts
  lerna.json
  packages/editor/api/api.json
  packages/namespaced-tldraw/api/api.json
  packages/state/api/api.json
  packages/store/api/api.json
  packages/tldraw/api/api.json
  packages/tlschema/api/api.json
  packages/utils/api/api.json
  packages/validate/api/api.json
  scripts/vercel/build-docs.sh
Labels: internal, chore

#3612 Revert "[signia] Smart dirty checking of active computeds (#3516)"
  packages/state/src/lib/core/Computed.ts
  packages/state/src/lib/core/transactions.ts
Labels: bugfix, sdk

#3613 Expose migrations, validators, and versions from tlschema
  packages/tlschema/api-report.md
  packages/tlschema/src/assets/TLBookmarkAsset.ts
  packages/tlschema/src/assets/TLImageAsset.ts
  packages/tlschema/src/assets/TLVideoAsset.ts
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/index.ts
  packages/tlschema/src/misc/TLCursor.ts
  packages/tlschema/src/misc/TLOpacity.ts
  packages/tlschema/src/misc/TLScribble.ts
  packages/tlschema/src/misc/id-validator.ts
  packages/tlschema/src/records/TLAsset.ts
  packages/tlschema/src/records/TLCamera.ts
  packages/tlschema/src/records/TLDocument.ts
  packages/tlschema/src/records/TLInstance.ts
  packages/tlschema/src/records/TLPage.ts
  packages/tlschema/src/records/TLPageState.ts
  packages/tlschema/src/records/TLPointer.ts
  packages/tlschema/src/records/TLPresence.ts
  packages/tlschema/src/records/TLShape.ts
  packages/tlschema/src/shapes/TLArrowShape.ts
  packages/tlschema/src/shapes/TLBookmarkShape.ts
  packages/tlschema/src/shapes/TLDrawShape.ts
  packages/tlschema/src/shapes/TLEmbedShape.ts
  packages/tlschema/src/shapes/TLFrameShape.ts
  packages/tlschema/src/shapes/TLGeoShape.ts
  packages/tlschema/src/shapes/TLGroupShape.ts
  packages/tlschema/src/shapes/TLHighlightShape.ts
  packages/tlschema/src/shapes/TLImageShape.ts
  packages/tlschema/src/shapes/TLLineShape.ts
  packages/tlschema/src/shapes/TLNoteShape.ts
  packages/tlschema/src/shapes/TLTextShape.ts
  packages/tlschema/src/shapes/TLVideoShape.ts
  packages/tlsync/src/lib/schema.ts
Labels: bugfix, sdk

#3615 Bring back `/r`
  apps/dotcom/src/routes.tsx
Labels: improvement, dotcom

#3621 Fix an issue with minimap.
  packages/tldraw/src/lib/ui/components/Minimap/DefaultMinimap.tsx
  packages/tldraw/src/lib/ui/components/Minimap/MinimapManager.ts
Labels: bugfix, sdk

#3617 Fix an issue with the minimap
  packages/tldraw/src/lib/ui/components/Minimap/DefaultMinimap.tsx
  packages/tldraw/src/lib/ui/components/Minimap/MinimapManager.ts
Labels: bugfix, internal

#3624 make route prefixes have a single place where they are defined
  apps/dotcom-worker/src/lib/TLDrawDurableObject.ts
  apps/dotcom-worker/src/lib/routes/forwardRoomRequest.ts
  apps/dotcom-worker/src/lib/routes/joinExistingRoom.ts
  apps/dotcom-worker/src/lib/worker.ts
  apps/dotcom/src/components/BoardHistorySnapshot/BoardHistorySnapshot.tsx
  apps/dotcom/src/components/ShareMenu.tsx
  apps/dotcom/src/pages/history-snapshot.tsx
  apps/dotcom/src/pages/history.tsx
  apps/dotcom/src/pages/new.tsx
  apps/dotcom/src/routes.tsx
  apps/dotcom/src/utils/sharing.ts
  packages/dotcom-shared/src/index.ts
  packages/dotcom-shared/src/routes.ts
Labels: sdk, chore

#3572 Make coarse pointer check dynamic
  packages/editor/src/lib/hooks/useCoarsePointer.ts
Labels: improvement, dotcom

#3606 stickies: make pit/pack distance the same
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/ui/constants.ts
  packages/tldraw/src/lib/ui/context/actions.tsx
Labels: bugfix, sdk

#3625 examples: add filter input
  apps/examples/src/ExamplePage.tsx
  apps/examples/src/styles.css
Labels: docs, improvement

#3608 Add desmos graph embed type
  apps/docs/content/getting-started/releases-versioning.mdx
  assets/embed-icons/desmos.png
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/tldraw/src/lib/utils/embeds/embeds.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/shapes/TLEmbedShape.ts
Labels: tests, feature, dotcom

#3632 Fix text resizing with alt key
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/shapes/text/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
  packages/tldraw/src/test/resizing.test.ts
  packages/tldraw/src/test/text.test.ts
Labels: bugfix, sdk

#3640 Allow embedding tldraw in iframes
  apps/dotcom/src/components/IFrameProtector.tsx
Labels: improvement, dotcom

#3577 textfields: for unfilled geo shapes fix edit->edit
  packages/editor/editor.css
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
Labels: bugfix, sdk

#3623 copy/paste: fix pasting not working from Edit menu
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: bugfix, sdk

#3639 Improve pressure-detection logic in drawing
  apps/docs/content/getting-started/releases-versioning.mdx
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
  packages/tldraw/src/lib/shapes/shared/polygon-helpers.ts
Labels: improvement, sdk

#3609 embed: allow embeds like YouTube to link back to its site
  packages/tlschema/api-report.md
  packages/tlschema/src/shapes/TLEmbedShape.ts
Labels: bugfix, sdk

#3647 3d example
  apps/examples/public/man.png
  apps/examples/public/shadow-man.png
  apps/examples/src/examples/popup-shape/PopupShapeExample.tsx
  apps/examples/src/examples/popup-shape/PopupShapeUtil.tsx
  apps/examples/src/examples/popup-shape/README.md
Labels: docs, improvement

#3646 Update template versions to latest
  templates/nextjs/package.json
  templates/vite/package.json
Labels: bugfix, internal

#3652 Fix missing icon
  packages/tldraw/src/lib/ui/components/primitives/Button/TldrawUiButtonCheck.tsx
Labels: bugfix, sdk

#3653 [bugfix] don't crash if a bound shape doesn't exist
  packages/editor/src/lib/editor/shapes/shared/arrow/shared.ts
Labels: bugfix, dotcom, sdk

#3649 Lokalise: Translations update
  assets/translations/fr.json
  assets/translations/hu.json
  assets/translations/id.json
  assets/translations/ko-kr.json
  assets/translations/languages.json
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/editor/api-report.md
  packages/tlschema/api-report.md
  packages/tlschema/src/translations/languages.ts
Labels: translations

#3654 Fix missing icons
  assets/icons/icon/lock.svg
  assets/icons/icon/share-1.svg
  assets/icons/icon/unlock.svg
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/icon-types.ts
Labels: bugfix, sdk

#3656 fix android long press changing cursor to non-coarse
  packages/editor/src/lib/hooks/useCoarsePointer.ts
Labels: bugfix, dotcom

#3657 Hacky fix safari transparency
  packages/tldraw/src/lib/ui/components/Minimap/MinimapManager.ts
Labels: feature, sdk

#3658 fix undo/redo issues
  apps/dotcom/src/hooks/useUrlState.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/commands/centerOnPoint.test.ts
  packages/tldraw/src/test/commands/pan.test.ts
  packages/tldraw/src/test/commands/resetZoom.test.ts
  packages/tldraw/src/test/commands/setSelectedIds.test.ts
  packages/tldraw/src/test/commands/zoomIn.test.ts
  packages/tldraw/src/test/commands/zoomOut.test.ts
  packages/tldraw/src/test/commands/zoomToBounds.test.ts
  packages/tldraw/src/test/commands/zoomToFit.test.ts
  packages/tldraw/src/test/commands/zoomToSelection.test.ts
Labels: bugfix, sdk

#3659 embed: prevent nested tldraw
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
Labels: bugfix, sdk

#3188 Fix textbox direction when it contains both RTL and LTR languages
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
Labels: bugfix, improvement, dotcom

#3664 VS Code 2.0.32
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: chore
