Repository tldraw/tldraw, pull requests merged in 2024-07, with the labels that each got.

#4044 Add `setDefaultValue` to `StyleProp`
  apps/examples/src/examples/changing-default-style/ChangingDefaultStyleExample.tsx
  apps/examples/src/examples/changing-default-style/README.md
  packages/tlschema/api-report.md
  packages/tlschema/src/styles/StyleProp.ts
Labels: feature

#4050 Fixup staging worker deploys
  apps/dotcom-asset-upload/wrangler.toml
  apps/health-worker/wrangler.toml
  scripts/lib/deploy.ts
Labels: bugfix

#4056 Fix duplicate distance
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/test/duplicate.test.ts
Labels: bugfix

#4052 add workers-shared package and source-maps for dotcom-worker sentry reports
  apps/bemo-worker/package.json
  apps/bemo-worker/src/BemoDO.ts
  apps/bemo-worker/src/sentry.ts
  apps/bemo-worker/src/worker.ts
  apps/bemo-worker/tsconfig.json
  apps/dotcom-asset-upload/wrangler.toml
  apps/dotcom-worker/package.json
  apps/dotcom-worker/src/TLDrawDurableObject.ts
  apps/dotcom-worker/src/types.ts
  apps/dotcom-worker/src/worker.ts
  apps/dotcom-worker/tsconfig.json
  apps/dotcom-worker/wrangler.toml
  packages/worker-shared/package.json
  packages/worker-shared/src/env.ts
  packages/worker-shared/src/index.test.ts
  packages/worker-shared/src/index.ts
  packages/worker-shared/src/sentry.ts
  packages/worker-shared/tsconfig.json
  scripts/deploy-dotcom.ts
  yarn.lock
Labels: other

#4058 asset: targeted fix for loading the initial url quicker, before debouncing
  packages/tldraw/src/lib/shapes/shared/useAsset.ts
Labels: bugfix

#4059 worker fixes
  apps/bemo-worker/src/BemoDO.ts
  apps/bemo-worker/src/worker.ts
  apps/dotcom-asset-upload/package.json
  apps/dotcom-asset-upload/src/worker.ts
  apps/dotcom-asset-upload/wrangler.toml
  apps/dotcom-worker/src/TLDrawDurableObject.ts
  apps/dotcom-worker/src/worker.ts
  packages/worker-shared/src/sentry.ts
  scripts/package.json
  scripts/workers/dev.ts
  yarn.lock
Labels: bugfix

#4055 Demo assets server
  .github/workflows/deploy-dotcom.yml
  apps/bemo-worker/src/types.ts
  apps/bemo-worker/src/worker.ts
  apps/bemo-worker/wrangler.toml
  apps/dotcom-asset-upload/package.json
  apps/dotcom-asset-upload/src/types.ts
  apps/dotcom-asset-upload/src/worker.ts
  apps/dotcom-asset-upload/tsconfig.json
  apps/dotcom-asset-upload/wrangler.toml
  apps/dotcom-worker/src/routes/forwardRoomRequest.ts
  apps/dotcom-worker/src/routes/getRoomHistory.ts
  apps/dotcom-worker/src/routes/getRoomHistorySnapshot.ts
  apps/dotcom-worker/src/routes/getRoomSnapshot.ts
  apps/dotcom-worker/src/routes/joinExistingRoom.ts
  apps/dotcom-worker/src/utils/fourOhFour.ts
  apps/dotcom-worker/src/worker.ts
  packages/worker-shared/src/errors.ts
  packages/worker-shared/src/index.ts
  packages/worker-shared/src/userAssetUploads.ts
  scripts/deploy-dotcom.ts
  yarn.lock
Labels: other

#4064 Add watermark images
  assets/watermark/tldraw-1.svg
  assets/watermark/tldraw-2.svg
  assets/watermark/tldraw-3.svg
Labels: other

#4063 Fix an issue with react router and dev mode for the /new route.
  apps/dotcom/src/pages/new.tsx
Labels: bugfix

#4062 Demo server bookmark unfurl endpoint
  apps/bemo-worker/src/worker.ts
  apps/dotcom-asset-upload/src/worker.ts
  apps/dotcom-worker/src/worker.ts
  apps/dotcom/src/utils/createAssetFromUrl.ts
  packages/tlschema/api-report.md
  packages/validate/api-report.md
  packages/validate/src/lib/validation.ts
  packages/worker-shared/package.json
  packages/worker-shared/src/getUrlMetadata.ts
  packages/worker-shared/src/handleRequest.ts
  packages/worker-shared/src/index.ts
  packages/worker-shared/src/sentry.ts
  packages/worker-shared/tsconfig.json
  yarn.lock
Labels: other

#4053 Allow license keys with additional properties
  packages/editor/src/lib/editor/managers/LicenseManager.ts
Labels: improvement

#4075 Add watermark tests
  packages/editor/src/lib/editor/managers/LicenseManager.ts
  packages/editor/src/lib/editor/managers/WatermarkManager.test.ts
Labels: other

#4071 indicators on the canvas example
  apps/examples/src/examples/indicators-logic/IndicatorsLogicExample.tsx
  apps/examples/src/examples/indicators-logic/README.md
Labels: other

#4083 Add component for `ShapeIndicators`
  apps/examples/src/examples/exploded/ExplodedExample.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/ErrorBoundary.tsx
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/components/default-components/DefaultShapeIndicators.tsx
  packages/editor/src/lib/hooks/useEditorComponents.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/canvas/TldrawShapeIndicators.tsx
  packages/tldraw/src/lib/ui/components/Dialogs.tsx
  packages/tldraw/src/lib/ui/components/Toasts.tsx
Labels: improvement, api

#4079 Share menu improvements
  apps/dotcom/src/components/ShareMenu.tsx
  apps/dotcom/src/utils/sharing.ts
Labels: improvement

#4089 Fix editor remounting when camera options change
  packages/editor/src/lib/TldrawEditor.tsx
  packages/tldraw/src/test/TldrawEditor.test.tsx
Labels: bugfix

#4090 Make arrow sequence not retroactive
  packages/tlschema/src/shapes/TLArrowShape.ts
Labels: bugfix

#4091 Set bemo url in examples app
  apps/examples/src/index.tsx
  apps/examples/vite.config.ts
Labels: other

#4092 Fix two issues with frame headers
  packages/tldraw/src/lib/shapes/frame/components/FrameHeading.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/EditingShape.ts
Labels: bugfix

#4088 Add "paste at cursor" option, which toggles how `cmd + v` and `cmd + shift + v` work
  assets/translations/main.json
  packages/editor/api-report.md
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: feature

#4054 followups to z-index and PR template
  .github/pull_request_template.md
  apps/dotcom/styles/z-board.css
  apps/huppy/src/flows/enforcePrLabels.tsx
  packages/editor/editor.css
  packages/tldraw/src/lib/ui.css
Labels: other

#4105 Allow null origins on dotcom worker requests
  apps/dotcom-worker/src/worker.ts
Labels: bugfix

#4104 Fix paste at point
  packages/editor/api-report.md
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteTldrawContent.ts
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: bugfix

#4107 fix vec docs
  apps/docs/components/mdx-components/code.tsx
Labels: other

#4108 fix input coords while viewport following
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix

#4112 fix vec docs
  apps/docs/components/mdx-components/code.tsx
Labels: other

#4113 Flip images
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/lib/editor/shapes/shared/resizeBox.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/ui/hooks/menu-hooks.ts
  packages/tldraw/src/test/flipShapes.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/shapes/TLImageShape.ts
Labels: improvement

#4117 Add a toast for missing clipboard permissions.
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement

#4114 Add a toast for file upload failures.
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement

#4118 fix bookmark height
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
Labels: bugfix

#4127 Add offline icon back
  assets/icons/icon/status-offline.svg
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/icon-types.ts
Labels: bugfix

#4129 Fix examples URL in docs app
  apps/docs/components/ExampleCodeBlock.tsx
Labels: bugfix

#4125 Export entire canvas as an image
  apps/examples/src/examples/export-canvas-as-image/ExportCanvasImageExample.tsx
  apps/examples/src/examples/export-canvas-as-image/README.md
Labels: other

#4132 use unique IDs for grid instances
  packages/editor/src/lib/components/default-components/DefaultGrid.tsx
  packages/editor/src/lib/utils/sync/TLLocalSyncClient.ts
Labels: bugfix

#4068 [1/4] Blob storage in TLStore
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/dotcom/src/components/SnapshotsEditor.tsx
  apps/dotcom/src/components/TemporaryBemoDevEditor.tsx
  apps/dotcom/src/hooks/useLocalStore.ts
  apps/dotcom/src/hooks/useMultiplayerAssets.ts
  apps/dotcom/src/utils/cloneAssetForShare.ts
  apps/dotcom/src/utils/createAssetFromFile.ts
  apps/dotcom/src/utils/multiplayerAssetStore.test.ts
  apps/dotcom/src/utils/multiplayerAssetStore.ts
  apps/dotcom/src/utils/sharing.ts
  apps/examples/src/examples/hosted-images/HostedImagesExample.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/config/createTLStore.ts
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/misc-types.ts
  packages/editor/src/lib/hooks/useLocalStore.ts
  packages/editor/src/lib/hooks/useRefState.ts
  packages/editor/src/lib/utils/sync/LocalIndexedDb.test.ts
  packages/editor/src/lib/utils/sync/LocalIndexedDb.ts
  packages/editor/src/lib/utils/sync/TLLocalSyncClient.test.ts
  packages/editor/src/lib/utils/sync/TLLocalSyncClient.ts
  packages/editor/src/lib/utils/sync/hardReset.ts
  packages/editor/src/lib/utils/sync/indexedDb.test.ts
  packages/editor/src/lib/utils/sync/indexedDb.ts
  packages/sync-react/src/index.ts
  packages/sync-react/src/useDemoSyncClient.ts
  packages/sync-react/src/useRemoteSyncClient.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/AssetBlobStore.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/utils/tldr/file.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
  packages/tlschema/src/index.ts
Labels: api

#4094 [2/4] Rename sync hooks, add bookmarks to demo
  apps/bemo-worker/wrangler.toml
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/dotcom/src/components/TemporaryBemoDevEditor.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/config/createTLStore.ts
  packages/sync-react/src/index.ts
  packages/sync-react/src/useMultiplayerSync.ts
  packages/sync-react/src/useMutliplayerDemo.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
Labels: api

#4119 [3/5] Automatically enable multiplayer UI when using demo sync
  apps/dotcom/src/components/DocumentName/DocumentName.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/dotcom/src/components/TemporaryBemoDevEditor.tsx
  apps/dotcom/src/utils/context-menu/CursorChatMenuItem.tsx
  apps/dotcom/src/utils/useCursorChat.ts
  apps/dotcom/styles/z-board.css
  apps/examples/src/examples/ui-components-hidden/UiComponentsHiddenExample.tsx
  package.json
  packages/editor/api-report.md
  packages/editor/src/lib/config/createTLStore.ts
  packages/state/api-report.md
  packages/state/src/lib/react/track.ts
  packages/sync-react/src/useMultiplayerSync.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/ContextMenu/DefaultContextMenuContent.tsx
  packages/tldraw/src/lib/ui/components/CursorChatBubble.tsx
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
  packages/tldraw/src/lib/ui/components/OfflineIndicator/OfflineIndicator.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/DefaultSharePanel.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/PeopleMenu.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/PeopleMenuAvatar.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/PeopleMenuItem.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/PeopleMenuMore.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/UserPresenceColorPicker.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/UserPresenceEditor.tsx
  packages/tldraw/src/lib/ui/components/TopPanel/CenteredTopPanelContainer.tsx
  packages/tldraw/src/lib/ui/components/TopPanel/DefaultTopPanel.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/components.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useIsMultiplayer.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
Labels: improvement

#4140 Use shape scale for geo shape min size
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
Labels: bugfix

#4021 sdk: wires up tldraw to have licensing mechanisms
  .github/workflows/deploy-dotcom.yml
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/dotcom/src/components/SnapshotsEditor.tsx
  apps/dotcom/version.ts
  apps/dotcom/vite.config.ts
  apps/examples/e2e/tests/test-help-menu.spec.ts
  apps/examples/package.json
  apps/examples/src/misc/develop.tsx
  apps/examples/src/misc/end-to-end.tsx
  apps/examples/tsconfig.json
  assets/translations/main.json
  assets/watermarks/watermark-desktop-sdk.svg
  assets/watermarks/watermark-desktop.svg
  assets/watermarks/watermark-mobile.svg
  config/jest/node/jest-preset.js
  config/setupJest.ts
  config/svgTransform.js
  lerna.json
  packages/dotcom-shared/src/index.ts
  packages/dotcom-shared/src/license.ts
  packages/editor/api-report.md
  packages/editor/assets/watermarks/watermark-desktop-sdk.svg
  packages/editor/assets/watermarks/watermark-desktop.svg
  packages/editor/assets/watermarks/watermark-mobile.svg
  packages/editor/modules.d.ts
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/LicenseManager.test.ts
  packages/editor/src/lib/editor/managers/LicenseManager.ts
  packages/editor/src/lib/editor/managers/WatermarkManager.test.ts
  packages/editor/src/lib/editor/managers/WatermarkManager.ts
  packages/editor/src/lib/utils/assets.ts
  packages/editor/src/lib/utils/debug-flags.ts
  packages/editor/src/lib/utils/licensing.ts
  packages/editor/src/version.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/TldrawImage.tsx
  packages/tldraw/src/lib/ui/assetUrls.ts
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
  packages/tldraw/src/lib/ui/context/components.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/lib/ui/version.ts
  packages/tldraw/src/lib/utils/static-assets/assetUrls.ts
  scripts/deploy-dotcom.ts
  scripts/refresh-assets.ts
  yarn.lock
Labels: feature, sdk

#4142 Fix `/new` alert bug, make new user data stable
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/utils/sync/TLLocalSyncClient.ts
Labels: bugfix

#4146 [bemo] add analytics to bemo worker
  apps/bemo-worker/src/BemoDO.ts
  apps/bemo-worker/src/types.ts
  apps/bemo-worker/wrangler.toml
  packages/sync-core/src/lib/TLSocketRoom.ts
Labels: feature

#4143 Unify menus. Disable erroring.
  apps/vscode/editor/src/app.tsx
  packages/editor/src/lib/editor/managers/WatermarkManager.ts
Labels: improvement

#4134 Geometry shape example
  apps/examples/src/examples/shape-with-geometry/README.md
  apps/examples/src/examples/shape-with-geometry/ShapeWithGeometry.tsx
Labels: other

#4135 [5/5] Move bemo from dotcom to examples
  apps/bemo-worker/src/BemoDO.ts
  apps/bemo-worker/src/types.ts
  apps/docs/components/ExampleCodeBlock.tsx
  apps/docs/styles/globals.css
  apps/dotcom/src/components/TemporaryBemoDevEditor.tsx
  apps/dotcom/src/pages/temporary-bemo.tsx
  apps/dotcom/src/routes.tsx
  apps/examples/package.json
  apps/examples/src/ExamplePage.tsx
  apps/examples/src/ExampleWrapper.tsx
  apps/examples/src/examples.tsx
  apps/examples/src/examples/multiplayer-demo/MultiplayerDemoExample.tsx
  apps/examples/src/examples/multiplayer-demo/README.md
  apps/examples/src/examples/multiple/MultipleExample.tsx
  apps/examples/src/index.tsx
  apps/examples/src/styles.css
  apps/examples/tsconfig.json
  apps/examples/vite.config.ts
  packages/sync-core/src/lib/ClientWebSocketAdapter.ts
  packages/sync/src/useMultiplayerSync.ts
  packages/sync/src/useMutliplayerDemo.ts
  scripts/workers/dev.ts
  yarn.lock
Labels: other

#4152 [bemo] No public shared rooms in examples app
  apps/docs/components/ExampleCodeBlock.tsx
  apps/examples/src/ExampleWrapper.tsx
  apps/examples/src/examples/multiplayer-demo/README.md
  apps/examples/src/styles.css
Labels: improvement

#4147 State/store example
  apps/examples/src/examples/state-store/README.md
  apps/examples/src/examples/state-store/StateStoreExample.tsx
Labels: other

#4153 [bemo] allow special chars in roomId
  packages/sync/src/useMutliplayerDemo.ts
Labels: improvement

#4156 fix bemo url in examples app
  apps/examples/vite.config.ts
Labels: bugfix

#4158 license: show on dotcom dev mode
  packages/dotcom-shared/src/license.ts
Labels: other

#4160 head: rm mask-icon
  apps/dotcom/index.html
Labels: other

#4155 [sdk] make EffectScheduler and useStateTracking public
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/state/api-report.md
  packages/state/src/lib/react/useStateTracking.ts
Labels: api

#4162 `ShapeUtil.getInterpolatedProps`
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/BaseBoxShapeUtil.tsx
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
Labels: feature, api

#4042 Editor.run, locked shapes improvements
  apps/dotcom/src/hooks/useUrlState.ts
  apps/dotcom/src/utils/useFileSystem.tsx
  apps/examples/src/examples/camera-options/CameraOptionsExample.tsx
  apps/examples/src/examples/image-annotator/ImageAnnotationEditor.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/HistoryManager.test.ts
  packages/editor/src/lib/editor/managers/HistoryManager.ts
  packages/editor/src/lib/editor/managers/ScribbleManager.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/DragAndDropManager.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/Crop.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingShape.ts
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenuContent.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/DefaultPageMenu.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/useMenuIsOpen.ts
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
  packages/tldraw/src/lib/utils/frames/frames.ts
  packages/tldraw/src/lib/utils/tldr/buildFromV1Document.ts
  packages/tldraw/src/lib/utils/tldr/file.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/commands/lockShapes.test.ts
  packages/tldraw/src/test/commands/moveShapesToPage.test.ts
  packages/tldraw/src/test/commands/resizeShape.test.ts
  packages/tldraw/src/test/commands/setCurrentPage.test.ts
Labels: bugfix, feature, api

#4172 Fix sticker example.
  apps/examples/src/examples/sticker-bindings/StickerExample.tsx
Labels: bugfix

#4124 toSvg method example
  apps/examples/src/examples/toSvg-method-example/CustomShapeToSvgExample.tsx
  apps/examples/src/examples/toSvg-method-example/README.md
Labels: other

#4175 publish bemo canaries
  .github/workflows/publish-canary.yml
  .github/workflows/publish-manual.yml
  .github/workflows/publish-new.yml
  .github/workflows/publish-patch.yml
  packages/sync-core/api-report.md
  packages/sync-core/package.json
  packages/sync-core/src/index.ts
  packages/sync-core/src/lib/ClientWebSocketAdapter.ts
  packages/sync-core/src/lib/RoomSession.ts
  packages/sync-core/src/lib/TLSocketRoom.ts
  packages/sync-core/src/lib/TLSyncClient.ts
  packages/sync-core/src/lib/TLSyncRoom.ts
  packages/sync-core/src/lib/chunk.ts
  packages/sync-core/src/lib/diff.ts
  packages/sync-core/src/lib/protocol.ts
  packages/sync/api-report.md
  packages/sync/package.json
  packages/sync/src/useMutliplayerDemo.ts
  scripts/api-check.ts
  scripts/build-package.ts
Labels: other

#4182 Editor.run docs
  apps/docs/content/docs/editor.mdx
  packages/editor/src/lib/editor/Editor.ts
Labels: other

#4183 Shuffle docs order
  apps/examples/src/examples.tsx
  apps/examples/src/examples/camera-options/README.md
  apps/examples/src/examples/editor-focus/README.md
  apps/examples/src/examples/multiplayer-demo/README.md
  apps/examples/src/examples/user-presence/README.md
  apps/examples/src/examples/yjs/README.md
  apps/examples/src/examples/yjs/YjsExample.tsx
Labels: other

#4184 Show checked theme in color scheme menu
  packages/editor/api-report.md
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
  packages/tldraw/src/lib/ui/components/ColorSchemeMenu.tsx
Labels: bugfix

#4180 Fix watermark imports in published packages
  packages/editor/assets/watermarks/watermark-desktop-sdk.svg
  packages/editor/assets/watermarks/watermark-desktop.svg
  packages/editor/assets/watermarks/watermark-mobile.svg
  packages/editor/src/lib/editor/managers/WatermarkManager.ts
  packages/editor/src/lib/editor/managers/watermarks.ts
  scripts/refresh-assets.ts
Labels: bugfix

#4186 fix wrangler config
  apps/bemo-worker/wrangler.toml
Labels: other

#4174 bemo custom shape example
  apps/examples/src/ExampleWrapper.tsx
  apps/examples/src/examples/multiplayer-custom-shape/CounterShape.tsx
  apps/examples/src/examples/multiplayer-custom-shape/MultiplayerDemoExample.tsx
  apps/examples/src/examples/multiplayer-custom-shape/README.md
  apps/examples/src/examples/multiplayer-custom-shape/ui.tsx
  apps/examples/src/styles.css
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/config/createTLStore.ts
  packages/editor/src/lib/hooks/useIdentity.tsx
  packages/editor/src/lib/hooks/useTLStore.ts
  packages/sync/api-report.md
  packages/sync/src/useMultiplayerSync.ts
  packages/sync/src/useMutliplayerDemo.ts
Labels: other

#4171 docs: fix up prev/next for api reference
  apps/docs/utils/ContentDatabase.ts
Labels: other

#4185 Fix color scheme default
  packages/tldraw/src/lib/ui/components/ColorSchemeMenu.tsx
Labels: bugfix

#4191 Explicitly type shape props and defaults
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/defaultBindingUtils.ts
  packages/tldraw/src/lib/defaultShapeTools.ts
  packages/tldraw/src/lib/defaultShapeUtils.ts
  packages/tldraw/src/lib/defaultTools.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/index.ts
  packages/tlschema/src/misc/TLCursor.ts
  packages/tlschema/src/misc/TLScribble.ts
  packages/tlschema/src/misc/geometry-types.ts
  packages/tlschema/src/shapes/TLArrowShape.ts
  packages/tlschema/src/shapes/TLBookmarkShape.ts
  packages/tlschema/src/shapes/TLDrawShape.ts
  packages/tlschema/src/shapes/TLEmbedShape.ts
  packages/tlschema/src/shapes/TLFrameShape.ts
  packages/tlschema/src/shapes/TLGeoShape.ts
  packages/tlschema/src/shapes/TLGroupShape.ts
  packages/tlschema/src/shapes/TLHighlightShape.ts
  packages/tlschema/src/shapes/TLImageShape.ts
  packages/tlschema/src/shapes/TLLineShape.ts
  packages/tlschema/src/shapes/TLNoteShape.ts
  packages/tlschema/src/shapes/TLTextShape.ts
  packages/tlschema/src/shapes/TLVideoShape.ts
Labels: api

#4192 add version attribute
  packages/editor/src/lib/TldrawEditor.tsx
Labels: other

#4190 Relax the params
  packages/editor/api-report.md
  packages/editor/src/lib/hooks/useTLStore.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/TldrawImage.tsx
Labels: improvement

#4159 csp: followup fixes/dx/tweaks
  apps/dotcom/scripts/build.ts
  apps/dotcom/src/components/Head/Head.tsx
  apps/dotcom/src/utils/csp.ts
  apps/vscode/extension/src/unfurl.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useRefState.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteFiles.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteUrl.ts
  packages/worker-shared/src/getUrlMetadata.ts
Labels: other

#4194 docs: fix up typo
  apps/docs/content/docs/editor.mdx
Labels: other

#4199 csp: enable image upload for dev mode
  apps/dotcom/src/utils/csp.ts
Labels: bugfix

#4198 asset lod: fix high-res images
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/utils/assets/assets.ts
Labels: bugfix

#4201 Disable outputs for tests.
  packages/editor/src/lib/editor/managers/LicenseManager.ts
Labels: improvement

#4202 Improve page event tracking.
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/components/PageMenu/DefaultPageMenu.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageItemInput.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageItemSubmenu.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/edit-pages-shared.ts
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
Labels: improvement

#4205 Fix dotcom multiplayer analytics
  apps/dotcom/src/components/MultiplayerEditor.tsx
Labels: bugfix

#4173 Example node + bun server
  .eslintrc.js
  apps/bemo-worker/package.json
  apps/bemo-worker/src/BemoDO.ts
  apps/bemo-worker/src/worker.ts
  apps/dotcom-asset-upload/package.json
  apps/dotcom-asset-upload/src/worker.ts
  apps/dotcom-worker/package.json
  apps/dotcom-worker/src/TLDrawDurableObject.ts
  apps/dotcom-worker/src/worker.ts
  apps/dotcom/package.json
  apps/examples/package.json
  apps/images.tldraw.xyz/package.json
  apps/simple-server-example/.gitignore
  apps/simple-server-example/README.md
  apps/simple-server-example/package.json
  apps/simple-server-example/src/client/App.tsx
  apps/simple-server-example/src/client/index.css
  apps/simple-server-example/src/client/index.html
  apps/simple-server-example/src/client/main.tsx
  apps/simple-server-example/src/client/vite-env.d.ts
  apps/simple-server-example/src/server/assets.ts
  apps/simple-server-example/src/server/rooms.ts
  apps/simple-server-example/src/server/server.bun.ts
  apps/simple-server-example/src/server/server.node.ts
  apps/simple-server-example/src/server/unfurl.ts
  apps/simple-server-example/tsconfig.json
  apps/simple-server-example/vite.config.mts
  package.json
  packages/sync-core/api-report.md
  packages/sync-core/src/index.ts
  packages/sync-core/src/lib/ServerSocketAdapter.ts
  packages/sync-core/src/lib/TLSocketRoom.ts
  packages/sync-core/src/lib/TLSyncRoom.ts
  packages/worker-shared/package.json
  packages/worker-shared/src/handleRequest.ts
  templates/vite/package.json
  yarn.lock
Labels: other

#4209 Fix interactive shape example
  apps/examples/src/examples/interactive-shape/my-interactive-shape-util.tsx
Labels: other

#4196 Watermark II
  assets/watermarks/watermark-desktop-sdk.svg
  assets/watermarks/watermark-desktop.svg
  assets/watermarks/watermark-mobile.svg
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/default-components/DefaultErrorFallback.tsx
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
  packages/editor/src/lib/editor/managers/WatermarkManager.test.ts
  packages/editor/src/lib/editor/managers/WatermarkManager.ts
  packages/editor/src/lib/editor/managers/watermarks.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/editor/src/lib/license/LicenseManager.test.ts
  packages/editor/src/lib/license/LicenseManager.ts
  packages/editor/src/lib/license/LicenseProvider.tsx
  packages/editor/src/lib/license/Watermark.test.tsx
  packages/editor/src/lib/license/Watermark.tsx
  packages/editor/src/lib/watermarks.ts
  packages/tldraw/src/lib/shapes/shared/usePrefersReducedMotion.tsx
  scripts/refresh-assets.ts
Labels: other

#4193 Export default menu panel.
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/components/DefaultMenuPanel.tsx
  packages/tldraw/src/lib/ui/context/components.tsx
Labels: improvement

#4214 Force flag should override isLocked in more cases
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.test.ts
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix, improvement

#4208 Allow custom tools to decide whether they can be lockable or not.
  packages/editor/api-report.md
  packages/editor/src/lib/editor/tools/StateNode.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/draw/DrawShapeTool.ts
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeTool.ts
  packages/tldraw/src/lib/shapes/text/TextShapeTool.ts
  packages/tldraw/src/lib/tools/EraserTool/EraserTool.ts
  packages/tldraw/src/lib/tools/HandTool/HandTool.ts
  packages/tldraw/src/lib/tools/LaserTool/LaserTool.ts
  packages/tldraw/src/lib/tools/SelectTool/SelectTool.ts
  packages/tldraw/src/lib/tools/ZoomTool/ZoomTool.ts
  packages/tldraw/src/lib/ui/components/Toolbar/ToggleToolLockedButton.tsx
Labels: improvement

#4216 Fix watermark after breakpoints
  packages/editor/src/lib/license/Watermark.tsx
Labels: bugfix

#4195 Fix fontStyle assignment
  packages/tldraw/src/lib/shapes/shared/createTextJsxFromSpans.tsx
  packages/tldraw/src/test/commands/__snapshots__/getSvgString.test.ts.snap
Labels: bugfix

#4148 Consolidate menu examples
  apps/examples/src/examples/custom-actions-menu/CustomActionsMenuExample.tsx
  apps/examples/src/examples/custom-actions-menu/README.md
  apps/examples/src/examples/custom-context-menu/CustomContextMenuExample.tsx
  apps/examples/src/examples/custom-context-menu/README.md
  apps/examples/src/examples/custom-debug-menu/CustomDebugMenuExample.tsx
  apps/examples/src/examples/custom-debug-menu/README.md
  apps/examples/src/examples/custom-help-menu/CustomHelpMenuExample.tsx
  apps/examples/src/examples/custom-help-menu/README.md
  apps/examples/src/examples/custom-keyboard-shortcuts-dialog/CustomKeyboardShortcutsDialogExample.tsx
  apps/examples/src/examples/custom-keyboard-shortcuts-dialog/README.md
  apps/examples/src/examples/custom-main-menu/CustomMainMenuExample.tsx
  apps/examples/src/examples/custom-main-menu/README.md
  apps/examples/src/examples/custom-menus/CustomMenusExample.tsx
  apps/examples/src/examples/custom-menus/README.md
  apps/examples/src/examples/custom-navigation-panel/CustomNavigationPanelExample.tsx
  apps/examples/src/examples/custom-navigation-panel/README.md
  apps/examples/src/examples/custom-page-menu/CustomPageMenuExample.tsx
  apps/examples/src/examples/custom-page-menu/README.md
  apps/examples/src/examples/custom-quick-actions/CustomQuickActions.tsx
  apps/examples/src/examples/custom-quick-actions/README.md
  apps/examples/src/examples/custom-style-panel/CustomStylePanelExample.tsx
  apps/examples/src/examples/custom-style-panel/README.md
  apps/examples/src/examples/custom-toolbar/CustomToolbarExample.tsx
  apps/examples/src/examples/custom-toolbar/README.md
  apps/examples/src/examples/custom-zoom-menu/CustomZoomMenuExample.tsx
  apps/examples/src/examples/custom-zoom-menu/README.md
Labels: other

#4212 Finesse sync api
  apps/bemo-worker/src/BemoDO.ts
  apps/dotcom-worker/src/TLDrawDurableObject.ts
  apps/dotcom/src/utils/multiplayerAssetStore.ts
  apps/examples/src/examples/multiplayer-custom-user/MultiplayerCustomUser.tsx
  apps/examples/src/examples/multiplayer-custom-user/README.md
  apps/simple-server-example/src/server/rooms.ts
  apps/simple-server-example/src/server/server.bun.ts
  apps/simple-server-example/src/server/server.node.ts
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/config/createTLStore.ts
  packages/editor/src/lib/config/createTLUser.ts
  packages/editor/src/lib/hooks/useIdentity.tsx
  packages/sync-core/api-report.md
  packages/sync-core/src/index.ts
  packages/sync-core/src/lib/ClientWebSocketAdapter.ts
  packages/sync-core/src/lib/RoomSession.ts
  packages/sync-core/src/lib/ServerSocketAdapter.ts
  packages/sync-core/src/lib/TLRemoteSyncError.ts
  packages/sync-core/src/lib/TLSocketRoom.ts
  packages/sync-core/src/lib/TLSyncClient.ts
  packages/sync-core/src/lib/TLSyncRoom.ts
  packages/sync-core/src/lib/chunk.ts
  packages/sync-core/src/lib/diff.ts
  packages/sync-core/src/lib/protocol.ts
  packages/sync-core/src/lib/server-types.ts
  packages/sync-core/src/test/TLSyncRoom.test.ts
  packages/sync-core/src/test/TestServer.ts
  packages/sync/api-report.md
  packages/sync/package.json
  packages/sync/src/index.ts
  packages/sync/src/useMultiplayerSync.ts
  packages/sync/src/useMutltiplayerDemo.ts
  packages/sync/tsconfig.json
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
  yarn.lock
Labels: api

#4228 Remove bun from deps and run it with npx
  apps/simple-server-example/package.json
  yarn.lock
Labels: other

#4233 Fix snapshots prop
  apps/dotcom/src/components/SnapshotsEditor.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/config/createTLStore.ts
  packages/editor/src/lib/hooks/useTLStore.ts
  packages/tldraw/src/test/TldrawEditor.test.tsx
Labels: bugfix

#4236 Simplify unfurl in simple-server-example
  apps/simple-server-example/package.json
  apps/simple-server-example/src/server/unfurl.ts
  yarn.lock
Labels: improvement

#4188 Interpolated line points
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
Labels: feature, other

#4163 license: add example; fix up example dialog
  LICENSE.md
  apps/examples/src/ExamplePage.tsx
  apps/examples/src/examples/license-key/LicenseKeyExample.tsx
  apps/examples/src/examples/license-key/README.md
  packages/editor/src/lib/license/LicenseManager.ts
Labels: other

#4240 db: add fallback for FF versions < 126
  packages/editor/src/lib/utils/sync/LocalIndexedDb.ts
Labels: bugfix

#4239 Update the templates to include a dropdown to distinguish between dotcom and package bugs / feature requests.
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: other

#4243 Fix indentation.
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: bugfix

#4238 issues: setup bot to auto-close issues over 6 months
  .github/workflows/close-stale-issues.yml
Labels: other

#4231 stickies: make ADJACENT_NOTE_MARGIN match adjacentShapeMargin (again)
  packages/tldraw/src/lib/shapes/note/NoteShapeTool.test.ts
  packages/tldraw/src/lib/shapes/note/noteCloning.test.ts
  packages/tldraw/src/lib/shapes/note/noteHelpers.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingHandle.ts
  packages/tldraw/src/test/translating.test.ts
Labels: bugfix

#4229 Sync docs
  apps/docs/components/mdx-components/code.tsx
  apps/docs/content/docs/assets.mdx
  apps/docs/content/docs/collaboration.mdx
  apps/docs/content/docs/persistence.mdx
  apps/docs/content/docs/sync.mdx
  apps/docs/content/docs/user-interface.mdx
  apps/docs/content/getting-started/quick-start.mdx
  apps/examples/src/examples.tsx
  apps/examples/src/examples/multiplayer-custom-shape/MultiplayerDemoExample.tsx
  apps/examples/src/examples/multiplayer-custom-shape/README.md
  apps/examples/src/examples/multiplayer-custom-user/MultiplayerCustomUser.tsx
  apps/examples/src/examples/multiplayer-custom-user/README.md
  apps/examples/src/examples/multiplayer-demo/MultiplayerDemoExample.tsx
  apps/examples/src/examples/multiplayer-demo/README.md
  apps/examples/src/examples/yjs/README.md
  apps/simple-server-example/README.md
  packages/sync/api-report.md
  packages/sync/src/index.ts
  packages/sync/src/useMutltiplayerDemo.ts
  templates/cloudflare-workers/README.md
Labels: other

#4246 pages: tweak page menu width, fix #1231
  packages/tldraw/src/lib/ui.css
Labels: improvement

#4224 Couple of force flag test additions
  packages/editor/src/lib/editor/Editor.test.ts
Labels: improvement

#4244 Add make real as an option.
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: improvement

#4248 Rename APIs for new sync demo
  .github/workflows/publish-templates.yml
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/examples/src/examples/multiplayer-custom-shape/README.md
  apps/examples/src/examples/multiplayer-demo/MultiplayerDemoExample.tsx
  apps/examples/src/examples/multiplayer-demo/README.md
  apps/examples/src/examples/sync-custom-shape/CounterShape.tsx
  apps/examples/src/examples/sync-custom-shape/README.md
  apps/examples/src/examples/sync-custom-shape/SyncDemoShapeExample.tsx
  apps/examples/src/examples/sync-custom-shape/ui.tsx
  apps/examples/src/examples/sync-custom-user/README.md
  apps/examples/src/examples/sync-custom-user/SyncCustomUser.tsx
  apps/examples/src/examples/sync-demo/README.md
  apps/examples/src/examples/sync-demo/SyncDemoExample.tsx
  apps/simple-server-example/src/client/App.tsx
  packages/sync-core/src/lib/TLSocketRoom.ts
  packages/sync/api-report.md
  packages/sync/src/index.ts
  packages/sync/src/useSync.ts
  packages/sync/src/useSyncDemo.ts
  templates/cloudflare-workers/client/App.tsx
  templates/cloudflare-workers/package.json
Labels: api

#4249 asset: make useAsset @public
  packages/tldraw/src/lib/shapes/shared/useAsset.ts
Labels: other

#4237 focus: fix dbl-click to edit text, when shape is selected, in label geometry hit area
  packages/tldraw/src/lib/tools/SelectTool/childStates/EditingShape.ts
Labels: bugfix

#4252 license: fix up watermark in prod
  packages/editor/src/lib/license/Watermark.tsx
Labels: bugfix

#4254 Load watermark, and fall back to local if it fails or takes too long
  packages/editor/src/lib/license/Watermark.test.tsx
  packages/editor/src/lib/license/Watermark.tsx
Labels: improvement

#4255 supply secrets to template deploys
  .github/workflows/publish-manual.yml
  .github/workflows/publish-new.yml
  .github/workflows/publish-patch.yml
  .github/workflows/publish-templates.yml
Labels: other

#4256 Update docs for dark mode. Add system color scheme docs.
  apps/docs/content/docs/editor.mdx
Labels: other

#4164 Sync docs
  apps/docs/components/mdx-components/code.tsx
  apps/docs/components/mdx-components/generic.tsx
  apps/docs/components/mdx-components/index.ts
  apps/docs/content/docs/assets.mdx
  apps/docs/content/docs/collaboration.mdx
  apps/docs/content/docs/persistence.mdx
  apps/docs/content/docs/sync.mdx
  apps/docs/content/docs/tools.mdx
  apps/docs/content/docs/user-interface.mdx
  apps/docs/content/getting-started/installation.mdx
  apps/docs/content/getting-started/quick-start.mdx
  apps/docs/content/sections.json
  apps/docs/public/images/multiplayer.gif
  apps/docs/public/images/multiplayer_mask.png
  apps/docs/scripts/functions/getApiMarkdown.ts
  apps/docs/scripts/functions/package-list.ts
  apps/docs/styles/globals.css
  apps/docs/styles/hljs.css
  apps/docs/utils/autoLinkDocs.ts
  apps/examples/src/examples.tsx
  apps/examples/src/examples/sync-custom-shape/README.md
  apps/examples/src/examples/sync-custom-user/README.md
  apps/examples/src/examples/sync-demo/README.md
  apps/examples/src/examples/yjs/README.md
  apps/examples/src/examples/yjs/YjsExample.tsx
  apps/simple-server-example/README.md
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/Tldraw.tsx
  templates/cloudflare-workers/README.md
  templates/nextjs/README.md
  templates/vite/README.md
Labels: other

#4247 Fix order of closed menus
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix

#4258 Export helpers for image paste
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: improvement, api

#4262 examples: fix up camera options
  apps/examples/src/examples/camera-options/CameraOptionsExample.tsx
Labels: other

#4264 Address some sync papercuts
  apps/docs/content/docs/sync.mdx
  packages/sync-core/src/lib/ClientWebSocketAdapter.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/warn.ts
  packages/utils/src/lib/warnDeprecatedGetter.ts
  templates/sync-cloudflare/README.md
  templates/sync-cloudflare/client/App.tsx
  templates/sync-cloudflare/client/getBookmarkPreview.tsx
  templates/sync-cloudflare/client/multiplayerAssetStore.tsx
  templates/sync-cloudflare/yarn.lock
Labels: other

#4263 Sync docs, further refinements
  apps/docs/content/docs/sync.mdx
  packages/sync-core/src/lib/ClientWebSocketAdapter.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/warn.ts
  packages/utils/src/lib/warnDeprecatedGetter.ts
  templates/sync-cloudflare/README.md
  templates/sync-cloudflare/client/App.tsx
  templates/sync-cloudflare/client/getBookmarkPreview.tsx
  templates/sync-cloudflare/client/multiplayerAssetStore.tsx
  templates/sync-cloudflare/yarn.lock
Labels: other

#4260 Allow non default z value for scribble points.
  packages/editor/api-report.md
  packages/editor/src/lib/editor/managers/ScribbleManager.test.ts
  packages/editor/src/lib/editor/managers/ScribbleManager.ts
  packages/editor/src/lib/test/TestEditor.ts
Labels: improvement

#4257 Use cloudflare-workers-unfurl
  apps/bemo-worker/src/worker.ts
  apps/dotcom-worker/src/worker.ts
  apps/simple-server-example/package.json
  packages/worker-shared/package.json
  packages/worker-shared/src/getUrlMetadata.ts
  packages/worker-shared/src/index.ts
  templates/sync-cloudflare/package.json
  templates/sync-cloudflare/worker/bookmarkUnfurling.ts
  templates/sync-cloudflare/worker/worker.ts
  templates/sync-cloudflare/yarn.lock
  yarn.lock
Labels: improvement

#4266 Add function property warning.
  scripts/lib/eslint-plugin.ts
Labels: other

#4269 github: make auto-close bot just do stale for now, do close later
  .github/workflows/close-stale-issues.yml
Labels: other

#4271 share: make top/bottom not shrink when a lot of people in the room
  .github/workflows/close-stale-issues.yml
  lerna.json
  packages/tldraw/src/lib/ui.css
Labels: bugfix

#4273 More sync papercuts
  apps/docs/content/docs/sync.mdx
  apps/docs/content/getting-started/releases-versioning.mdx
  packages/editor/api-report.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  templates/sync-cloudflare/README.md
  templates/sync-cloudflare/worker/TldrawDurableObject.ts
Labels: other

#4272 Make it easy to load preexisting snapshots into TLSocketRoom
  apps/docs/content/docs/sync.mdx
  packages/sync-core/api-report.md
  packages/sync-core/src/lib/TLSocketRoom.ts
  packages/sync-core/src/test/TLSocketRoom.test.ts
Labels: feature

#4270 keyboard: list out , as keyboard shortcut
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/lib/ui/kbd-utils.ts
Labels: improvement

#4283 fix assets prop on tldraw component
  packages/editor/src/lib/TldrawEditor.tsx
  packages/tldraw/src/test/TldrawEditor.test.tsx
  packages/tldraw/src/test/testutils/renderTldrawComponent.tsx
Labels: bugfix

#4286 csp: minor update to make sure report-uri isnt added in dev
  apps/dotcom/src/components/Head/Head.tsx
  apps/dotcom/src/utils/csp.ts
Labels: other

#4287 geo: update X icon to reflect the actual shape
  assets/icons/icon/geo-x-box.svg
Labels: bugfix

#4289 theme: fix color scheme (again)
  packages/tldraw/src/lib/ui/components/ColorSchemeMenu.tsx
Labels: bugfix

#4265 Improve arrow label snapping
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/arrowLabel.ts
Labels: improvement

#4275 Steve's sync docs pass
  apps/docs/content/docs/collaboration.mdx
  apps/docs/content/docs/sync.mdx
  apps/docs/content/getting-started/quick-start.mdx
  apps/docs/styles/globals.css
Labels: other

#4292 Address alex's sync docs feedback
  apps/docs/content/docs/collaboration.mdx
  apps/docs/content/docs/sync.mdx
Labels: improvement

#4296 license: add special license option with watermark
  packages/editor/src/lib/license/LicenseManager.test.ts
  packages/editor/src/lib/license/LicenseManager.ts
  packages/editor/src/lib/license/Watermark.test.tsx
  packages/editor/src/lib/license/Watermark.tsx
Labels: other

#4300 support custom delay for laser pointer
  packages/editor/api-report.md
  packages/editor/src/lib/options.ts
  packages/tldraw/src/lib/tools/LaserTool/childStates/Lasering.ts
Labels: improvement

#4308 Add terms of use / privacy policy
  RELEASES.md
  apps/docs/components/SectionDocsPage.tsx
  apps/docs/content/community/license.mdx
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/dotcom/LICENSE.md
  apps/dotcom/PRIVACY_POLICY.md
  apps/dotcom/README.md
  apps/dotcom/TERMS_OF_SERVICE.md
  apps/dotcom/src/components/Links.tsx
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/vscode/editor/src/app.tsx
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: other

#4294 Add option for max pasted / dropped files
  packages/editor/api-report.md
  packages/editor/src/lib/options.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: improvement

#4274 Fix dropdown menus not opening in focus examples
  apps/examples/src/examples/editor-focus/EditorFocusExample.tsx
  apps/examples/src/examples/inline-behavior/InlineBehavior.tsx
Labels: bugfix

#4261 draw: fix dotted line rendering when zoomed out
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/examples/src/examples/slides/SlideShapeUtil.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/shapes/shared/getPerfectDashProps.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/draw/DrawShapeUtil.tsx
  packages/tldraw/src/lib/shapes/draw/getPath.ts
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/components/GeoShapeBody.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/getPerfectDashProps.ts
Labels: bugfix

#4293 text shape: dont make a fixed width unless more intentional drag
  packages/tldraw/src/lib/shapes/text/TextShapeTool.test.ts
  packages/tldraw/src/lib/shapes/text/toolStates/Pointing.ts
Labels: improvement

#4316 Fix duplication of shapes.
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix

#4317 tweak cf template
  templates/sync-cloudflare/worker/TldrawDurableObject.ts
  templates/sync-cloudflare/yarn.lock
Labels: other

#4318 Fix an issue with minimap
  apps/dotcom/src/utils/multiplayerAssetStore.test.ts
  packages/editor/src/lib/editor/managers/SnapManager/HandleSnaps.ts
  packages/editor/src/lib/editor/tools/BaseBoxShapeTool/children/Pointing.ts
  packages/tldraw/src/lib/shapes/frame/FrameShapeTool.ts
  packages/tldraw/src/lib/ui/components/Minimap/MinimapManager.ts
Labels: bugfix

#4320 remove onEditorMount prop
  packages/editor/api-report.md
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/config/createTLStore.ts
  packages/sync/api-report.md
  packages/sync/src/useSync.ts
  packages/sync/src/useSyncDemo.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
Labels: api

#4322 fix broken links
  apps/docs/content/docs/collaboration.mdx
Labels: other

#4323 Add missing bits to exploded example
  apps/examples/src/examples/exploded/ExplodedExample.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/defaultSideEffects.ts
Labels: bugfix

#4312 shape ordering: upgrade fractional indexing to use jitter, avoid conflicts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeTool.test.ts
  packages/utils/api-report.md
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/lib/reordering.ts
  packages/utils/src/lib/reordering/IndexKey.ts
  packages/utils/src/lib/reordering/dgreensp/dgreensp.test.ts
  packages/utils/src/lib/reordering/dgreensp/dgreensp.ts
  packages/utils/src/lib/reordering/reordering.ts
  yarn.lock
Labels: bugfix
