Repository tldraw/tldraw, pull requests merged in 2024-05, with the labels that each got.

#3672 Fix className.includes bug
  packages/editor/src/lib/hooks/useCanvasEvents.ts
Labels: bugfix, sdk

#3679 don't render the minimap if it fails to initialize the gl context
  packages/tldraw/src/lib/ui/components/Minimap/DefaultMinimap.tsx
Labels: bugfix, sdk

#3665 Lokalise: Translations update
  assets/translations/sl.json
Labels: chore

#3681 Fix viewport following
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix, sdk

#3683 delete stray error screen css import
  apps/dotcom/src/components/StoreErrorScreen.tsx
Labels: bugfix, dotcom

#3687 [VS Code] Version 2.0.33
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: chore

#3663 Prevent unnecessary fetching of readonly slugs
  apps/dotcom/src/components/ShareMenu.tsx
  apps/dotcom/src/utils/sharing.ts
Labels: improvement, dotcom

#3680 textfields: fix RTL layout for SVG exports
  apps/examples/e2e/tests/export-snapshots.spec.ts
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-mixed-RTL-in-dark-mode-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.ts-snapshots/Export-snapshots-Exports-with-Exports-geo-text-with-mixed-RTL-in-dark-mode-1-chromium-linux.png
  packages/editor/src/lib/editor/managers/TextManager.ts
  packages/tldraw/src/lib/shapes/shared/createTextJsxFromSpans.tsx
  packages/tldraw/src/test/commands/__snapshots__/getSvgString.test.ts.snap
Labels: bugfix, sdk

#3692 Prevent duplicate from creating any shapes if we reach max allowed shapes
  packages/editor/src/lib/editor/Editor.ts
Labels: improvement, sdk

#3701 Camera options followups
  apps/dotcom/package.json
  apps/examples/package.json
  apps/examples/src/examples/camera-options/CameraOptionsExample.tsx
  apps/examples/src/examples/editor-focus/EditorFocusExample.tsx
  apps/examples/src/examples/image-annotator/ImageAnnotationEditor.tsx
  apps/examples/src/examples/pdf-editor/PdfEditor.tsx
  apps/examples/src/examples/slideshow/README.md
  apps/examples/src/examples/slideshow/SlideShowExample.tsx
  apps/examples/src/examples/slideshow/SlidesManager.tsx
  apps/examples/tsconfig.json
  apps/examples/vite.config.ts
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/test/commands/setCamera.test.ts
  packages/utils/api-report.md
  packages/utils/src/lib/reordering/reordering.ts
  templates/vite/package.json
  yarn.lock
Labels: improvement, sdk

#3708 Fix background color for patterned shapes.
  packages/tldraw/src/lib/shapes/shared/defaultStyleDefs.tsx
Labels: bugfix, sdk

#3689 Add asset pruning when importing files
  packages/tldraw/src/lib/utils/tldr/file.ts
Labels: improvement, sdk

#3693 Move storing of snapshots to R2
  apps/dotcom-worker/src/lib/TLDrawDurableObject.ts
  apps/dotcom-worker/src/lib/r2.ts
  apps/dotcom-worker/src/lib/routes/createRoomSnapshot.ts
  apps/dotcom-worker/src/lib/routes/getRoomSnapshot.ts
  apps/dotcom-worker/src/lib/types.ts
  apps/dotcom-worker/wrangler.toml
  apps/dotcom/src/pages/public-snapshot.tsx
  apps/dotcom/src/utils/sharing.ts
  packages/dotcom-shared/src/types.ts
Labels: improvement, dotcom

#3472 Measure action durations and fps for our interactions
  apps/examples/src/hooks/usePerformance.ts
  apps/examples/src/misc/develop.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/tools/StateNode.ts
  packages/editor/src/lib/utils/debug-flags.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/PerformanceTracker.ts
  packages/utils/src/lib/perf.ts
Labels: internal, tools

#3685 Incremental bindings index
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/derivations/bindingsIndex.ts
  packages/tldraw/src/test/bindingsIndex.test.tsx
Labels: performance

#3726 fix link
  apps/docs/content/docs/editor.mdx
Labels: docs, bugfix

#3721 Move arrow helpers from editor to tldraw
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/utils/WeakMapCache.ts
  packages/store/api-report.md
  packages/store/src/index.ts
  packages/store/src/lib/Store.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/bindings/arrow/ArrowBindingUtil.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeTool.test.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.test.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/arrow-types.ts
  packages/tldraw/src/lib/shapes/arrow/arrowLabel.ts
  packages/tldraw/src/lib/shapes/arrow/arrowheads.ts
  packages/tldraw/src/lib/shapes/arrow/arrowpaths.ts
  packages/tldraw/src/lib/shapes/arrow/curved-arrow.ts
  packages/tldraw/src/lib/shapes/arrow/shared.ts
  packages/tldraw/src/lib/shapes/arrow/straight-arrow.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingArrowLabel.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingHandle.ts
  packages/tldraw/src/lib/ui/hooks/menu-hooks.ts
  packages/tldraw/src/lib/utils/tldr/buildFromV1Document.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/arrows-megabus.test.tsx
  packages/tldraw/src/test/cleanup.test.ts
  packages/tldraw/src/test/commands/clipboard.test.ts
  packages/tldraw/src/test/commands/deleteShapes.test.ts
  packages/tldraw/src/test/duplicate.test.ts
  packages/tldraw/src/test/flipShapes.test.ts
  packages/tldraw/src/test/frames.test.ts
  packages/tldraw/src/test/groups.test.ts
  packages/tldraw/src/test/translating.test.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/cache.ts
Labels: improvement, sdk

#3741 Update READMEs, add form link
  README.md
  apps/docs/README.md
  apps/docs/content/community/license.mdx
  apps/examples/README.md
  apps/vscode/README.md
  apps/vscode/extension/README.md
  packages/assets/README.md
  packages/editor/README.md
  packages/tldraw/README.md
  packages/tlschema/README.md
  packages/utils/README.md
  packages/validate/README.md
Labels: internal, chore

#3742 Fix imports in Astro
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: bugfix, sdk

#3730 assets: rework mime-type detection to be consistent/centralized; add support for webp/webm, apng, avif
  apps/dotcom/src/hooks/useMultiplayerAssets.ts
  apps/dotcom/src/utils/createAssetFromFile.ts
  apps/examples/src/examples/hosted-images/HostedImagesExample.tsx
  apps/examples/src/examples/image-annotator/ImagePicker.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/Idle.ts
  packages/tldraw/src/lib/ui/hooks/useInsertMedia.ts
  packages/tldraw/src/lib/utils/assets/assets.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/media/apng.ts
  packages/utils/src/lib/media/avif.ts
  packages/utils/src/lib/media/gif.ts
  packages/utils/src/lib/media/media.ts
  packages/utils/src/lib/media/png.ts
  packages/utils/src/lib/media/webp.ts
Labels: improvement, sdk

#3732 Fix readonly fetching happening too often.
  apps/dotcom/src/components/ShareMenu.tsx
Labels: improvement, dotcom

#3746 ban using `@internal` items in examples
  .eslintrc.js
  apps/examples/src/examples/context-toolbar/ContextToolbar.tsx
  apps/examples/src/examples/pdf-editor/ExportPdfButton.tsx
  apps/examples/src/examples/pdf-editor/PdfEditor.tsx
  apps/examples/src/examples/pdf-editor/PdfPicker.tsx
  apps/examples/src/examples/slideshow/SlideShowExample.tsx
  apps/examples/src/hooks/usePerformance.ts
  apps/examples/src/index.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/utils/static-assets/assetUrls.ts
  scripts/lib/eslint-plugin.ts
Labels: docs, bugfix, tools

#3748 Store-level "operation end" event
  apps/examples/src/examples/pin-bindings/PinExample.tsx
  apps/examples/src/examples/pin-bindings/README.md
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/bindings/BindingUtil.ts
  packages/editor/tsconfig.json
  packages/store/api-report.md
  packages/store/src/index.ts
  packages/store/src/lib/Store.ts
  packages/store/src/lib/StoreSideEffects.test.ts
  packages/store/src/lib/StoreSideEffects.ts
  packages/store/src/lib/test/recordStore.test.ts
  packages/store/src/lib/test/recordStoreFuzzing.test.ts
Labels: feature, sdk

#3750 No defaults for contexts
  packages/editor/api-report.md
  packages/editor/src/lib/hooks/useEditor.ts
  packages/editor/src/lib/hooks/useEditorComponents.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuContext.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/breakpoints.tsx
  packages/tldraw/src/lib/ui/context/components.tsx
  packages/tldraw/src/lib/ui/context/dialogs.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/context/toasts.tsx
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/useTranslation.tsx
Labels: improvement, sdk

#3761 [bindings] beforeUnbind/afterUnbind to replace beforeDelete/afterDelete
  apps/examples/src/examples/pin-bindings/PinExample.tsx
  apps/examples/src/examples/sticker-bindings/StickerExample.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/bindings/BindingUtil.ts
  packages/tldraw/src/lib/bindings/arrow/ArrowBindingUtil.ts
  packages/tldraw/src/test/bindings.test.tsx
Labels: improvement, sdk

#3718 focus: rework and untangle existing focus management logic in the sdk
  apps/dotcom/src/components/BoardHistorySnapshot/BoardHistorySnapshot.tsx
  apps/dotcom/src/components/CursorChatBubble.tsx
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/dotcom/src/components/PeopleMenu/UserPresenceEditor.tsx
  apps/dotcom/src/components/SnapshotsEditor.tsx
  apps/examples/e2e/tests/test-focus.spec.ts
  apps/examples/src/examples/external-content-sources/ExternalContentSourcesExample.tsx
  apps/examples/src/examples/multiple/MultipleExample.tsx
  apps/examples/src/examples/scroll/ScrollExample.tsx
  apps/vscode/editor/src/app.tsx
  packages/editor/api-report.md
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/FocusManager.ts
  packages/editor/src/lib/hooks/useCanvasEvents.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/editor/src/lib/hooks/useFocusEvents.ts
  packages/editor/src/lib/hooks/useSafariFocusOutFix.ts
  packages/store/src/lib/RecordType.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/defaultSideEffects.ts
  packages/tldraw/src/lib/shapes/frame/components/FrameHeading.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/text/TextArea.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingShape.ts
  packages/tldraw/src/lib/ui/components/EditLinkDialog.tsx
  packages/tldraw/src/lib/ui/components/EmbedDialog.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageItemInput.tsx
  packages/tldraw/src/lib/ui/components/primitives/Button/TldrawUiButton.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiButtonPicker.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiInput.tsx
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
  packages/tldraw/src/test/Editor.test.tsx
  packages/tldraw/src/test/TldrawEditor.test.tsx
Labels: improvement, sdk

#3768 docs: smaller snapshot so it doesnt crash
  apps/examples/src/examples/snapshots/snapshot.json
  apps/examples/src/styles.css
Labels: docs, bugfix

#3769 Allow DefaultErrorFallback to be used independently
  packages/editor/src/lib/components/default-components/DefaultErrorFallback.tsx
Labels: bugfix, dotcom, sdk

#3772 export DefaultNavigationPanel
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
Labels: bugfix, sdk

#3747 E2E camera tests
  apps/examples/e2e/tests/fixtures/menus/Toolbar.ts
  apps/examples/e2e/tests/test-camera.spec.ts
Labels: internal, tests

#3716 Bump max shapes to 4000
  packages/editor/api-report.md
  packages/editor/src/lib/constants.ts
Labels: improvement, sdk

#3695 Prevent wobble during viewport following
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/tlsync/src/lib/TLSyncClient.ts
  packages/tlsync/src/lib/TLSyncRoom.ts
  packages/tlsync/src/lib/protocol.ts
Labels: bugfix, sdk

#3725 Prevent pressing escape when editing document name to bubble up to the editor
  apps/dotcom/src/components/DocumentName/DocumentName.tsx
Labels: improvement, dotcom

#3777 delete old todo comment
  packages/tlsync/src/lib/TLSyncClient.ts
Labels: internal, dunno

#3778 add missing spline icons
  assets/icons/icon/spline-cubic.svg
  assets/icons/icon/spline-line.svg
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/icon-types.ts
Labels: bugfix, sdk

#3771 [bugfix?] End interactions before switching page
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/commands/setCurrentPage.test.ts
Labels: bugfix, sdk

#3765 google meet: add hardware whiteboard integration
  apps/apps-script/.gitignore
  apps/apps-script/appsscript.json
  apps/apps-script/build-workspace-app.ts
  apps/apps-script/package.json
  apps/apps-script/tsconfig.json
  apps/dotcom/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/src/components/IFrameProtector.tsx
  apps/dotcom/src/pages/public-touchscreen-app.tsx
  apps/dotcom/src/pages/public-touchscreen-side-panel.tsx
  apps/dotcom/src/routes.tsx
  yarn.lock
Labels: internal, feature

#3782 Move InFrontOfTheCanvas
  packages/editor/src/lib/TldrawEditor.tsx
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiIcon.tsx
  packages/tldraw/src/lib/ui/context/toasts.tsx
Labels: bugfix, sdk

#3786 touchscreen: whoops, fix up script tag
  apps/dotcom/src/pages/public-touchscreen-side-panel.tsx
Labels: bugfix, sdk

#3788 touchscreen: fix env var name
  apps/dotcom/src/pages/public-touchscreen-side-panel.tsx
Labels: bugfix, sdk

#3789 touchscreen: just add a fallback, figure out env later
  apps/dotcom/src/pages/public-touchscreen-side-panel.tsx
Labels: bugfix, sdk

#3792 [bugfix] Cleanup input state after middle-click-to-pan
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/Editor.test.tsx
Labels: bugfix, sdk

#3790 touchscreen: wrong url argh
  apps/dotcom/src/pages/public-touchscreen-side-panel.tsx
Labels: bugfix, sdk

#3791 Fix spacebar/mmb panning bug.
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix, sdk

#3779 toolbar: rework overflow css logic
  packages/tldraw/src/lib/styles.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbarContent.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/OverflowingToolbar.tsx
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteTldrawContent.ts
Labels: improvement, sdk

#3798 Tighten up zoom to fit padding
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/ZoomTool.test.ts
  packages/tldraw/src/test/commands/__snapshots__/zoomToFit.test.ts.snap
  packages/tldraw/src/test/commands/zoomToBounds.test.ts
Labels: improvement, sdk

#3324 Update validation.ts
  packages/validate/src/lib/validation.ts
Labels: docs, chore

#3795 fix coarse pointer detection
  apps/dotcom-worker/src/lib/routes/createRoom.ts
  apps/dotcom-worker/src/lib/worker.ts
  apps/dotcom-worker/wrangler.toml
  apps/dotcom/scripts/build.ts
  apps/dotcom/vite.config.ts
  packages/editor/src/lib/hooks/useCoarsePointer.ts
Labels: bugfix, sdk

#3802 touchscreen: just create a new room
  apps/dotcom/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/src/components/IFrameProtector.tsx
  apps/dotcom/src/pages/public-touchscreen-app.tsx
  apps/dotcom/src/pages/public-touchscreen-side-panel.tsx
  apps/dotcom/src/routes.tsx
Labels: improvement, sdk

#3805 touchscreen: allow meet.google.com origin
  apps/dotcom-worker/src/lib/worker.ts
Labels: bugfix, sdk

#3806 touchscreen: improve the side panel, fix deploy env var, create room programmatically
  .github/workflows/deploy.yml
  apps/dotcom/src/pages/public-touchscreen-side-panel.tsx
Labels: bugfix, dotcom

#3808 Remove unneeded worker IS_LOCAL check
  apps/dotcom-worker/src/lib/worker.ts
Labels: bugfix, dotcom

#3801 fix pattern fill lods
  packages/tldraw/src/lib/shapes/shared/ShapeFill.tsx
  packages/tldraw/src/lib/shapes/shared/defaultStyleDefs.tsx
  packages/tldraw/src/test/commands/__snapshots__/getSvgString.test.ts.snap
Labels: bugfix, sdk

#3814 Add unit tests for the camera
  packages/tldraw/src/test/commands/setCamera.test.ts
Labels: internal, tests

#3818 Update README.md
  README.md
Labels: docs, improvement

#3813 Fix markdown list rendering on docs site
  .yarn/patches/@microsoft-tsdoc-npm-0.14.2-9988282153.patch
  apps/docs/package.json
  package.json
  yarn.lock
Labels: docs, bugfix

#3821 Fix broken files
  packages/tldraw/src/lib/utils/tldr/file.ts
Labels: bugfix, sdk

#3822 fix excalidraw paste
  packages/tldraw/src/lib/ui/hooks/clipboard/__snapshots__/pasteExcalidrawContent.test.tsx.snap
  packages/tldraw/src/lib/ui/hooks/clipboard/excalidraw-test-fixtures/bound-arrows.json
  packages/tldraw/src/lib/ui/hooks/clipboard/excalidraw-test-fixtures/line-drawing.json
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteExcalidrawContent.test.tsx
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteExcalidrawContent.ts
Labels: bugfix, sdk

#3787 Add heart geo shape
  apps/examples/e2e/tests/test-shapes.spec.ts
  assets/icons/icon/geo-heart.svg
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/primitives/Vec.test.ts
  packages/editor/src/lib/primitives/Vec.ts
  packages/editor/src/lib/primitives/geometry/Arc2d.ts
  packages/editor/src/lib/primitives/geometry/Circle2d.ts
  packages/editor/src/lib/primitives/geometry/CubicBezier2d.ts
  packages/editor/src/lib/primitives/geometry/CubicSpline2d.ts
  packages/editor/src/lib/primitives/geometry/Edge2d.ts
  packages/editor/src/lib/primitives/geometry/Ellipse2d.ts
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
  packages/editor/src/lib/primitives/geometry/Group2d.ts
  packages/editor/src/lib/primitives/geometry/Point2d.ts
  packages/editor/src/lib/primitives/geometry/Polyline2d.ts
  packages/editor/src/lib/primitives/geometry/Rectangle2d.ts
  packages/editor/src/lib/primitives/geometry/Stadium2d.ts
  packages/editor/src/lib/primitives/utils.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/arrowLabel.ts
  packages/tldraw/src/lib/shapes/arrow/curved-arrow.ts
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/cloudOutline.ts
  packages/tldraw/src/lib/shapes/geo/components/DashStyleCloud.tsx
  packages/tldraw/src/lib/shapes/geo/components/DashStyleEllipse.tsx
  packages/tldraw/src/lib/shapes/geo/components/DashStyleOval.tsx
  packages/tldraw/src/lib/shapes/geo/components/DashStylePolygon.tsx
  packages/tldraw/src/lib/shapes/geo/components/DrawStyleCloud.tsx
  packages/tldraw/src/lib/shapes/geo/components/DrawStyleEllipse.tsx
  packages/tldraw/src/lib/shapes/geo/components/DrawStylePolygon.tsx
  packages/tldraw/src/lib/shapes/geo/components/GeoShapeBody.tsx
  packages/tldraw/src/lib/shapes/geo/components/SolidStyleCloud.tsx
  packages/tldraw/src/lib/shapes/geo/components/SolidStyleEllipse.tsx
  packages/tldraw/src/lib/shapes/geo/components/SolidStyleOval.tsx
  packages/tldraw/src/lib/shapes/geo/components/SolidStylePolygon.tsx
  packages/tldraw/src/lib/shapes/geo/geo-shape-helpers.ts
  packages/tldraw/src/lib/shapes/geo/helpers.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/components/getLinePath.ts
  packages/tldraw/src/lib/shapes/line/components/svg.ts
  packages/tldraw/src/lib/shapes/line/line-helpers.ts
  packages/tldraw/src/lib/shapes/shared/getPerfectDashProps.ts
  packages/tldraw/src/lib/styles.tsx
  packages/tldraw/src/lib/ui/components/DefaultDebugPanel.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbarContent.tsx
  packages/tldraw/src/lib/ui/icon-types.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/shapes/TLGeoShape.ts
Labels: feature, sdk

#3833 Remove alpha mention in installation for static assets
  apps/docs/content/getting-started/installation.mdx
Labels: docs, chore

#3828 [fix] setCamera animates to constrained viewport
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/commands/setCamera.test.ts
Labels: bugfix, sdk

#3810 security: add recommended OWASP settings; also Zoom apps require them
  apps/dotcom/scripts/build.ts
Labels: improvement, dotcom

#3819 toolbar: disable items that dont work when not in select mode
  apps/dotcom/src/components/DocumentName/DocumentName.tsx
  packages/tldraw/src/lib/ui/components/ActionsMenu/DefaultActionsMenuContent.tsx
  packages/tldraw/src/lib/ui/components/MenuZone.tsx
  packages/tldraw/src/lib/ui/components/QuickActions/DefaultQuickActionsContent.tsx
  packages/tldraw/src/lib/ui/hooks/menu-hooks.ts
Labels: bugfix, sdk

#3837 Fix cropped image export
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
Labels: bugfix, dotcom, sdk

#3847 asset upload: nix list and delete commands
  apps/dotcom-asset-upload/src/index.ts
Labels: bugfix, dotcom

#3829 tests: fix camera scroll flakiness
  apps/examples/e2e/tests/test-camera.spec.ts
Labels: internal, tests

#3850 tests: fix edit→edit flakiness
  apps/examples/e2e/tests/test-focus.spec.ts
Labels: internal, tests

#3854 test: disable camera pinch test for now, too flaky
  apps/examples/e2e/tests/test-camera.spec.ts
Labels: internal, tests
