Repository tldraw/tldraw, pull requests merged in 2024-02, with the labels that each got.

#2699 return 404 on missing docs content instead of 500
  apps/docs/app/[...id]/page.tsx
Labels: internal

#2702 docs: more cleanup following restructure
  apps/docs/api/editor.api.json
  apps/docs/api/tldraw.api.json
  apps/docs/api/tlschema.api.json
  apps/docs/components/Sidebar.tsx
  apps/docs/components/mdx-components/generic.tsx
  apps/docs/content/docs/editor.mdx
  apps/docs/content/sections.json
  apps/docs/next.config.js
  apps/docs/scripts/functions/createApiMarkdown.ts
  apps/docs/scripts/functions/getApiMarkdown.ts
  apps/docs/styles/globals.css
  apps/docs/types/content-types.ts
  apps/docs/utils/ContentDatabase.ts
Labels: documentation

#2700 fix(docs): fix user-interface.mdx
  apps/docs/content/docs/user-interface.mdx
Labels: documentation

#2706 [Docs] Tweak sidebar titles
  .ignore
  apps/docs/components/Sidebar.tsx
  apps/docs/styles/globals.css
Labels: documentation

#2681 Examples tweaks
  apps/examples/e2e/tests/test-focus.spec.ts
  apps/examples/e2e/tests/test-routes.spec.ts
  apps/examples/package.json
  apps/examples/public/tldraw_dev_dark.png
  apps/examples/public/tldraw_dev_dark.svg
  apps/examples/public/tldraw_dev_light.png
  apps/examples/public/tldraw_dev_light.svg
  apps/examples/src/ExamplePage.tsx
  apps/examples/src/components/ExamplesLink.tsx
  apps/examples/src/components/ExamplesTldrawLogo.tsx
  apps/examples/src/components/Icons.tsx
  apps/examples/src/components/Markdown.tsx
  apps/examples/src/components/Spinner.tsx
  apps/examples/src/examples/api/README.md
  apps/examples/src/examples/basic/BasicExample.tsx
  apps/examples/src/examples/basic/README.md
  apps/examples/src/examples/changing-default-colors/ChangingDefaultColorsExample.tsx
  apps/examples/src/examples/develop/README.md
  apps/examples/src/examples/force-mobile/ForceBreakpointExample.tsx
  apps/examples/src/examples/force-mobile/README.md
  apps/examples/src/examples/hide-ui/README.md
  apps/examples/src/examples/infer-dark-mode/InferDarkModeExample.tsx
  apps/examples/src/examples/infer-dark-mode/README.md
  apps/examples/src/examples/inset/InsetExample.tsx
  apps/examples/src/examples/inset/README.md
  apps/examples/src/examples/meta-on-create/OnCreateShapeMetaExample.tsx
  apps/examples/src/examples/multiple/README.md
  apps/examples/src/examples/peristence-key/PersistenceKeyExample.tsx
  apps/examples/src/examples/peristence-key/README.md
  apps/examples/src/examples/persistence/README.md
  apps/examples/src/examples/readonly/README.md
  apps/examples/src/examples/readonly/ReadOnlyExample.tsx
  apps/examples/src/examples/scroll/README.md
  apps/examples/src/examples/scroll/ScrollExample.tsx
  apps/examples/src/examples/yjs/README.md
  apps/examples/src/index.tsx
  apps/examples/src/misc/develop.tsx
  apps/examples/src/misc/end-to-end.tsx
  apps/examples/src/styles.css
  apps/examples/vite.config.ts
  packages/tldraw/package.json
  yarn.lock
Labels: documentation

#2715 [fix] Debug panel text overflow
  packages/tldraw/src/lib/ui.css
Labels: patch

#2716 Bump jest to fix weird prettier bug
  apps/dotcom-worker/src/lib/AlarmScheduler.test.ts
  package.json
  packages/editor/src/lib/utils/reordering/dgreensp/dgreensp.test.ts
  packages/store/src/lib/test/defineMigrations.test.ts
  packages/store/src/lib/test/recordStore.test.ts
  packages/store/src/lib/test/validate.test.ts
  packages/tldraw/src/test/commands/createShapes.test.ts
  packages/tldraw/src/test/commands/putContent.test.ts
  packages/tldraw/src/test/commands/updateShapes.test.ts
  packages/utils/src/lib/debounce.test.ts
  yarn.lock
Labels: tests

#2719 [Fix] Camera coordinate issues
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/event-types.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/editor/src/lib/utils/edgeScrolling.ts
  packages/tldraw/src/test/commands/zoomIn.test.ts
Labels: major

#2721 [fix] VSCode keyboard shortcuts while editing text
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
Labels: patch

#2723 docs: rework search UI
  apps/docs/api/store.api.json
  apps/docs/api/validate.api.json
  apps/docs/app/api/ai/route.ts
  apps/docs/app/api/search/route.ts
  apps/docs/app/search-results/page.tsx
  apps/docs/components/Autocomplete.css
  apps/docs/components/Autocomplete.tsx
  apps/docs/components/Header.tsx
  apps/docs/components/Search.tsx
  apps/docs/components/Sidebar.tsx
  apps/docs/components/Spinner.tsx
  apps/docs/content/releases/v2.0.0-alpha.12.mdx
  apps/docs/content/releases/v2.0.0-alpha.13.mdx
  apps/docs/content/releases/v2.0.0-alpha.14.mdx
  apps/docs/content/releases/v2.0.0-alpha.15.mdx
  apps/docs/content/releases/v2.0.0-alpha.16.mdx
  apps/docs/content/releases/v2.0.0-alpha.17.mdx
  apps/docs/content/releases/v2.0.0-alpha.18.mdx
  apps/docs/content/releases/v2.0.0-alpha.19.mdx
  apps/docs/content/releases/v2.0.0-beta.1.mdx
  apps/docs/content/releases/v2.0.0-beta.2.mdx
  apps/docs/next.config.js
  apps/docs/package.json
  apps/docs/styles/globals.css
  apps/docs/types/content-types.ts
  apps/docs/types/search-types.ts
  apps/docs/utils/search-api.ts
  yarn.lock
Labels: minor

#2712 [dotcom] `TLSyncRoom` tidy
  packages/tlsync/src/lib/TLSyncRoom.ts
Labels: internal

#2729 [dx] use Biome instead of Prettier, part 1
  .github/workflows/checks.yml
  .ignore
  .prettierignore
  .prettierrc
  .vscode/extensions.json
  apps/docs/package.json
  biome.json
  package.json
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/tlschema/package.json
  scripts/lint.ts
  yarn.lock
Labels: minor

#2731 [dx] use Biome instead of Prettier, part 2
  .github/workflows/checks.yml
  apps/docs/app/api/search/route.ts
  apps/docs/scripts/functions/generateSection.ts
  apps/docs/utils/ContentDatabase.ts
  apps/docs/utils/ContentVectorDatabase.ts
  apps/dotcom-worker/src/lib/AlarmScheduler.test.ts
  apps/dotcom/src/components/BoardHistorySnapshot/BoardHistorySnapshot.tsx
  apps/dotcom/src/components/PeopleMenu/PeopleMenuItem.tsx
  apps/dotcom/src/components/ShareMenu.tsx
  apps/dotcom/src/pages/public-snapshot.tsx
  apps/dotcom/src/utils/migration/LocalMigration.tsx
  apps/dotcom/src/utils/useFileSystem.tsx
  apps/examples/src/examples/api/APIExample.tsx
  apps/examples/src/examples/user-presence/UserPresenceExample.tsx
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/editor/src/lib/config/createTLStore.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/SnapManager.ts
  packages/editor/src/lib/primitives/easings.ts
  packages/editor/src/lib/utils/getIncrementedName.ts
  packages/state/docs-ordering.json
  packages/store/src/lib/StoreSchema.ts
  packages/store/src/lib/migrate.ts
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/arrowLabel.ts
  packages/tldraw/src/lib/shapes/arrow/arrowheads.ts
  packages/tldraw/src/lib/shapes/draw/getPath.ts
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/cloudOutline.ts
  packages/tldraw/src/lib/shapes/geo/components/DashStyleCloud.tsx
  packages/tldraw/src/lib/shapes/geo/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/createTextSvgElementFromSpans.ts
  packages/tldraw/src/lib/shapes/shared/freehand/getStrokeOutlinePoints.ts
  packages/tldraw/src/lib/shapes/shared/freehand/setStrokePointRadii.ts
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingSelection.ts
  packages/tldraw/src/lib/ui/components/ActionsMenu.tsx
  packages/tldraw/src/lib/ui/components/DebugPanel.tsx
  packages/tldraw/src/lib/ui/components/Menu.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/StylePanel.tsx
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteExcalidrawContent.ts
  packages/tldraw/src/lib/ui/hooks/useActions.tsx
  packages/tldraw/src/lib/ui/hooks/useActionsMenuSchema.tsx
  packages/tldraw/src/lib/ui/overrides.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tlschema/src/records/TLAsset.ts
  packages/tlschema/src/records/TLInstance.ts
  packages/tlschema/src/records/TLShape.ts
  packages/tlschema/src/shapes/TLArrowShape.ts
  packages/utils/src/lib/object.ts
  packages/validate/src/lib/validation.ts
  scripts/publish-canary.ts
  scripts/publish-new.ts
Labels: minor

#2735 docs: add full-text search
  apps/docs/app/api/ai/route.ts
  apps/docs/app/api/search/route.ts
  apps/docs/components/Autocomplete.tsx
  apps/docs/components/Search.tsx
  apps/docs/scripts/functions/refreshContent.ts
  apps/docs/styles/globals.css
  apps/docs/utils/addContent.ts
Labels: patch

#2740 docs: disable ai search for now
  apps/docs/components/Search.tsx
Labels: documentation

#2748 Fix pinch zooming
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#2742 arrows: update cursor only when in Select mode
  packages/editor/editor.css
  packages/editor/src/lib/editor/shapes/shared/arrow/curved-arrow.ts
  packages/editor/src/lib/editor/shapes/shared/arrow/straight-arrow.ts
  packages/editor/src/lib/primitives/Vec.test.ts
  packages/tldraw/src/lib/shapes/arrow/arrowheads.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingArrowLabel.ts
Labels: patch

#2756 VS Code 2.0.23
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: patch

#2747 Split snap manager into ShapeBoundsSnaps and HandleSnaps
  apps/examples/src/examples/custom-components/CustomComponentsExample.tsx
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/editor.css
  packages/editor/src/index.ts
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/components/default-components/DefaultSnapIndictor.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/SnapManager/BoundsSnaps.ts
  packages/editor/src/lib/editor/managers/SnapManager/HandleSnaps.ts
  packages/editor/src/lib/editor/managers/SnapManager/SnapManager.ts
  packages/editor/src/lib/hooks/useEditorComponents.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
  packages/tldraw/src/lib/shapes/line/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/test/frames.test.ts
  packages/tldraw/src/test/getSnapLines.ts
  packages/tldraw/src/test/groups.test.ts
  packages/tldraw/src/test/resizing.test.ts
  packages/tldraw/src/test/testutils/getSnapLines.ts
  packages/tldraw/src/test/translating-snapping.test.ts
  packages/tldraw/src/test/translating.test.ts
  packages/utils/api-report.md
  packages/utils/api/api.json
  packages/utils/src/index.ts
  packages/utils/src/lib/number.ts
Labels: major

#2753 arrows: account for another NaN
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/primitives/Vec.ts
  packages/tldraw/src/lib/shapes/arrow/arrowheads.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingArrowLabel.ts
Labels: patch

#2774 hello@tldraw.com -> sales@tldraw.com
  README.md
Labels: internal

#2775 Fix infinite cursor chat issue by partially reverting "reactive context menu overrides (#2697)"
  packages/tldraw/src/lib/ui/hooks/useContextMenuSchema.tsx
  packages/tldraw/src/test/ui/ContextMenu.test.tsx
Labels: patch

#2778 i18n: add HR 🇭🇷
  assets/translations/hr.json
  assets/translations/languages.json
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/translations/languages.ts
Labels: patch

#2738 error reporting: rm ids from msgs for better Sentry grouping
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
  packages/validate/src/lib/validation.ts
  packages/validate/src/test/validation.test.ts
Labels: patch

#2739 rearrange export / import from tldraw to help builds
  packages/tldraw/src/index.ts
Labels: patch

#2730 Fixed actions menu opening in wrong direction on mobile (and add an inline layout example)
  apps/examples/src/examples/inline/InlineExample.tsx
  apps/examples/src/examples/inline/README.md
  packages/tldraw/src/lib/ui/components/ActionsMenu.tsx
Labels: patch

#2770 examples: clean up Canvas/Store events and make UiEvents have code snippets
  apps/examples/package.json
  apps/examples/src/ExamplePage.tsx
  apps/examples/src/examples/canvas-events/CanvasEventsExample.tsx
  apps/examples/src/examples/store-events/StoreEventsExample.tsx
  apps/examples/src/examples/ui-events/UiEventsExample.tsx
  apps/examples/src/examples/ui-events/codeSnippets.ts
  apps/examples/src/styles.css
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui/components/StopFollowing.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/StylePanel.tsx
  packages/tldraw/src/lib/ui/hooks/useEventsProvider.tsx
  yarn.lock
Labels: internal

#2758 Style UI based on component size instead of window size
  apps/examples/src/examples/inline/InlineExample.tsx
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/primitives/Kbd.tsx
Labels: patch

#2768 Remove Geometry2d.isSnappable
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/primitives/geometry/Edge2d.ts
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
Labels: major

#2791 docs: fix scrolling issue with sidebar
  apps/docs/components/Sidebar.tsx
  apps/docs/styles/globals.css
Labels: documentation

#2785 menu: just have an empty space for checked menuitems
  assets/icons/icon/checkbox-empty.svg
Labels: patch

#2788 docs: rm ... from some examples and fix up inset example
  apps/examples/src/examples/basic/README.md
  apps/examples/src/examples/infer-dark-mode/README.md
  apps/examples/src/examples/inset/InsetExample.tsx
  apps/examples/src/examples/peristence-key/README.md
Labels: documentation

#2801 docs: better code snippets
  apps/docs/components/ExampleCodeBlock.tsx
  apps/docs/components/Mdx.tsx
  apps/docs/components/Sidebar.tsx
  apps/docs/components/mdx-components/code.tsx
  apps/docs/components/mdx-components/generic.tsx
  apps/docs/components/mdx-components/index.ts
  apps/docs/content/docs/persistence.mdx
  apps/docs/content/getting-started/installation.mdx
  apps/docs/styles/globals.css
Labels: documentation

#2798 Use canvas bounds for viewport bounds
  apps/dotcom/src/hooks/useUrlState.ts
  apps/dotcom/src/utils/useFileSystem.tsx
  apps/examples/src/examples/inset-canvas/InsetCanvasExample.tsx
  apps/examples/src/examples/inset-canvas/README.md
  apps/examples/src/examples/inset-canvas/inset-canvas.css
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/editor.css
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/Canvas.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useScreenBounds.ts
  packages/tldraw/src/lib/defaultSideEffects.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/EditingShape.ts
  packages/tldraw/src/lib/utils/tldr/buildFromV1Document.ts
  packages/tldraw/src/lib/utils/tldr/file.ts
  packages/tldraw/src/test/Editor.test.tsx
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/commands/updateViewportPageBounds.test.ts
Labels: major

#2806 [fix] overlays, custom brush example
  apps/examples/src/examples/custom-components/CustomComponentsExample.tsx
  packages/editor/editor.css
Labels: patch

#2805 [docs] Small style changes
  apps/docs/components/Autocomplete.css
  apps/docs/components/Header.tsx
  apps/docs/components/Search.tsx
  apps/docs/content/sections.json
  apps/docs/styles/globals.css
Labels: documentation

#2816 VS Code 2.0.24
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: patch

#2818 Fix camera.
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#2814 emojis! 🧑‍🎨 🎨 ✏️
  .yarn/patches/emoji-mart-npm-5.5.2-10ed58131e.patch
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/primitives/geometry/Group2d.ts
  packages/editor/src/lib/utils/debug-flags.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/package.json
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/default-shape-constants.ts
  packages/tldraw/src/lib/shapes/shared/emojis/EmojiDialog.tsx
  packages/tldraw/src/lib/shapes/shared/emojis/index.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/shared/useEmojis.ts
  packages/tldraw/src/lib/ui/components/Dialogs.tsx
  packages/tldraw/src/lib/ui/hooks/useDialogsProvider.tsx
  yarn.lock
Labels: minor

#2822 Revert "emojis! 🧑‍🎨 🎨 ✏️ (#2814)"
  .yarn/patches/emoji-mart-npm-5.5.2-10ed58131e.patch
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/primitives/geometry/Group2d.ts
  packages/editor/src/lib/utils/debug-flags.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/package.json
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/default-shape-constants.ts
  packages/tldraw/src/lib/shapes/shared/emojis/EmojiDialog.tsx
  packages/tldraw/src/lib/shapes/shared/emojis/index.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/shared/useEmojis.ts
  packages/tldraw/src/lib/ui/components/Dialogs.tsx
  packages/tldraw/src/lib/ui/hooks/useDialogsProvider.tsx
  yarn.lock
Labels: internal

#2824 Remove pointer check for arrow labels
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
Labels: minor

#2828 [docs] Fix missing Persistence page
  apps/docs/utils/addContent.ts
  apps/docs/watcher.ts
  apps/examples/e2e/tests/test-routes.spec.ts
  apps/examples/src/examples/local-storage/LocalStorageExample.tsx
  apps/examples/src/examples/local-storage/README.md
Labels: documentation

#2830 Lokalise: Translations update
  assets/translations/languages.json
  assets/translations/sl.json
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/translations/languages.ts
Labels: minor

#2834 docs: tweak search kbd placement to match loupe
  apps/docs/styles/globals.css
Labels: patch

#2836 [fix] sticky note bug
  packages/editor/editor.css
Labels: patch

#2835 Improve signia error handling
  packages/state/api-report.md
  packages/state/api/api.json
  packages/state/src/lib/core/Atom.ts
  packages/state/src/lib/core/Computed.ts
  packages/state/src/lib/core/__tests__/errors.test.ts
  packages/state/src/lib/core/capture.ts
  packages/state/src/lib/core/helpers.ts
  packages/state/src/lib/core/types.ts
Labels: patch

#2833 Readonly defaults to the hand tool
  apps/dotcom/src/components/MultiplayerEditor.tsx
Labels: minor

#2773 dev: swap yarn test and test-dev for better dx
  .github/workflows/checks.yml
  CONTRIBUTING.md
  apps/dotcom-asset-upload/package.json
  apps/dotcom-worker/package.json
  apps/dotcom/package.json
  lazy.config.ts
  package.json
  packages/editor/package.json
  packages/state/package.json
  packages/store/package.json
  packages/tldraw/package.json
  packages/tlschema/package.json
  packages/tlsync/package.json
  packages/utils/package.json
  packages/validate/package.json
  scripts/check-scripts.ts
Labels: internal

#2827 [Snapping 1/5] Validation & strict types for fractional indexes
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/derivations/parentsToChildren.ts
  packages/editor/src/lib/utils/reorderShapes.ts
  packages/editor/src/lib/utils/sync/TLLocalSyncClient.test.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeTool.test.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.test.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/toolStates/Pointing.ts
  packages/tldraw/src/lib/ui/components/PageMenu/edit-pages-shared.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteExcalidrawContent.ts
  packages/tldraw/src/test/SelectTool.test.ts
  packages/tldraw/src/test/commands/moveShapesToPage.test.ts
  packages/tldraw/src/test/commands/reparentShapesById.test.ts
  packages/tldraw/src/test/commands/setCurrentPage.test.ts
  packages/tldraw/src/test/test-jsx.tsx
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/TLStore.ts
  packages/tlschema/src/misc/TLHandle.ts
  packages/tlschema/src/records/TLPage.ts
  packages/tlschema/src/shapes/TLBaseShape.ts
  packages/tlsync/src/lib/TLSyncRoom.ts
  packages/tlsync/src/test/TLSyncRoom.test.ts
  packages/utils/api-report.md
  packages/utils/api/api.json
  packages/utils/src/index.ts
  packages/utils/src/lib/reordering/IndexKey.ts
  packages/utils/src/lib/reordering/dgreensp/dgreensp.test.ts
  packages/utils/src/lib/reordering/dgreensp/dgreensp.ts
  packages/utils/src/lib/reordering/reordering.ts
  packages/validate/api-report.md
  packages/validate/api/api.json
  packages/validate/src/lib/validation.ts
  packages/validate/src/test/validation.test.ts
Labels: patch

#2831 [Snapping 2/5] Fix line-handle mid-point snapping
  packages/editor/src/lib/editor/managers/SnapManager/HandleSnaps.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/line/LineShapeTool.test.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.test.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/__snapshots__/LineShapeUtil.test.tsx.snap
  packages/tldraw/src/lib/shapes/line/toolStates/Pointing.ts
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/misc/TLHandle.ts
  packages/tlschema/src/shapes/TLLineShape.ts
Labels: needs qa, major

#2842 ✋ humans.txt
  apps/dotcom/public/humans.txt
Labels: internal

#2817 seo: take 2
  apps/dotcom/index.html
  apps/dotcom/public/sitemap.txt
  apps/examples/src/index.html
  packages/editor/src/lib/hooks/useScreenBounds.ts
Labels: patch

#2844 errors: improve msg in dialog when error happens
  packages/editor/editor.css
  packages/editor/src/lib/components/default-components/DefaultErrorFallback.tsx
Labels: patch

#2793 [Snapping 3/5] Custom snapping API
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/managers/SnapManager/BoundsSnaps.ts
  packages/editor/src/lib/editor/managers/SnapManager/HandleSnaps.ts
  packages/editor/src/lib/editor/managers/SnapManager/SnapManager.ts
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/editor/src/lib/primitives/Box.ts
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.test.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/test/customSnapping.test.tsx
  packages/tldraw/src/test/test-jsx.tsx
  packages/tldraw/src/test/translating-snapping.test.ts
Labels: minor

#2841 [Snapping 4/5] Add handle-point snapping
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/managers/SnapManager/HandleSnaps.ts
  packages/editor/src/lib/editor/shapes/BaseBoxShapeUtil.tsx
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.test.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/test/customSnapping.test.tsx
Labels: minor

#2845 [Snapping 5/5] Better handle snapping for geo shapes
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.test.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
Labels: minor

#2843 ui: refactor breakpoints to fit in an enum
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/ActionsMenu/DefaultActionsMenu.tsx
  packages/tldraw/src/lib/ui/components/ActionsMenu/DefaultActionsMenuContent.tsx
  packages/tldraw/src/lib/ui/components/HelpMenu/DefaultHelpMenu.tsx
  packages/tldraw/src/lib/ui/components/MenuZone.tsx
  packages/tldraw/src/lib/ui/components/NavigationPanel/DefaultNavigationPanel.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/DefaultPageMenu.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbar.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/ToggleToolLockedButton.tsx
  packages/tldraw/src/lib/ui/components/ZoomMenu/DefaultZoomMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/Kbd.tsx
  packages/tldraw/src/lib/ui/constants.ts
  packages/tldraw/src/lib/ui/context/breakpoints.tsx
  packages/tldraw/src/lib/ui/overrides.ts
Labels: patch

#2849 fix typo(examples/hosted-images)
  apps/examples/src/examples/hosted-images/HostedImagesExample.tsx
Labels: internal

#2850 [fix] pointer capture logging when debug flag is off
  packages/editor/src/lib/utils/dom.ts
Labels: patch

#2804 Add component for viewing an image of a snapshot
  apps/examples/src/examples/image-component/README.md
  apps/examples/src/examples/image-component/TldrawImageExample.tsx
  apps/examples/src/examples/image-component/snapshot.json
  apps/examples/src/examples/inline/README.md
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/SvgExportContext.tsx
  packages/editor/src/lib/hooks/useEditor.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/TldrawImage.tsx
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/draw/DrawShapeUtil.tsx
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/tools/ZoomTool/childStates/ZoomBrushing.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/tldraw/src/lib/utils/tldr/buildFromV1Document.ts
  packages/tldraw/src/lib/utils/tldr/file.ts
Labels: minor

#2851 fix frame style panel
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanel.tsx
Labels: patch

#2709 E2e tests for the toolbar
  apps/examples/e2e/playwright.config.ts
  apps/examples/e2e/tests/fixtures/fixtures.ts
  apps/examples/e2e/tests/fixtures/menus/StylePanel.ts
  apps/examples/e2e/tests/fixtures/menus/Toolbar.ts
  apps/examples/e2e/tests/test-mobile-style-panel.spec.ts
  apps/examples/e2e/tests/test-shapes.spec.ts
  apps/examples/e2e/tests/test-smoke.spec.ts
  apps/examples/e2e/tests/test-toolbar.spec.ts
  apps/examples/e2e/tests/test-ui.spec.ts
  lerna.json
  packages/tldraw/src/lib/ui/components/MobileStylePanel.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/DefaultPageMenu.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbar.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/ToggleToolLockedButton.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiButtonPicker.tsx
Labels: tests

#2858 [fix] grid, other insets
  packages/editor/editor.css
  packages/editor/src/lib/components/Canvas.tsx
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
Labels: patch

#2722 Fix some problem under Windows OS development enviroment
  scripts/refresh-assets.ts
Labels: internal

#2685 Allow users to set document name and use it for exporting / saving
  apps/dotcom/src/components/DocumentName/DocumentName.tsx
  apps/dotcom/src/components/ExportMenu.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/dotcom/src/components/ShareMenu.tsx
  apps/dotcom/src/utils/useFileSystem.tsx
  apps/dotcom/styles/z-board.css
  apps/examples/src/examples/screenshot-tool/ScreenshotTool/childStates/Dragging.ts
  assets/translations/main.json
  packages/editor/src/lib/utils/debug-flags.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useExportAs.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/lib/utils/export/exportAs.ts
Labels: major

#2862 Roundup fixes
  apps/examples/src/examples/custom-style-panel/CustomStylePanelExample.tsx
  apps/examples/src/examples/custom-toolbar/CustomToolbarExample.tsx
  apps/examples/src/examples/exploded/ExplodedExample.tsx
  apps/examples/src/index.tsx
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/LiveCollaborators.tsx
  packages/editor/src/lib/components/default-components/DefaultBackground.tsx
  packages/editor/src/lib/components/default-components/DefaultBrush.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/components/default-components/DefaultCollaboratorHint.tsx
  packages/editor/src/lib/components/default-components/DefaultCursor.tsx
  packages/editor/src/lib/components/default-components/DefaultErrorFallback.tsx
  packages/editor/src/lib/components/default-components/DefaultGrid.tsx
  packages/editor/src/lib/components/default-components/DefaultHandle.tsx
  packages/editor/src/lib/components/default-components/DefaultHandles.tsx
  packages/editor/src/lib/components/default-components/DefaultHoveredShapeIndicator.tsx
  packages/editor/src/lib/components/default-components/DefaultInFrontOfTheCanvas.tsx
  packages/editor/src/lib/components/default-components/DefaultLoadingScreen.tsx
  packages/editor/src/lib/components/default-components/DefaultOnTheCanvas.tsx
  packages/editor/src/lib/components/default-components/DefaultScribble.tsx
  packages/editor/src/lib/components/default-components/DefaultSelectionBackground.tsx
  packages/editor/src/lib/components/default-components/DefaultSelectionForeground.tsx
  packages/editor/src/lib/components/default-components/DefaultShapeIndicator.tsx
  packages/editor/src/lib/components/default-components/DefaultSnapIndictor.tsx
  packages/editor/src/lib/components/default-components/DefaultSpinner.tsx
  packages/editor/src/lib/components/default-components/DefaultSvgDefs.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useEditorComponents.tsx
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/Tldraw.test.tsx
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/canvas/TldrawCropHandles.tsx
  packages/tldraw/src/lib/canvas/TldrawHandles.tsx
  packages/tldraw/src/lib/canvas/TldrawHoveredShapeIndicator.tsx
  packages/tldraw/src/lib/canvas/TldrawScribble.tsx
  packages/tldraw/src/lib/canvas/TldrawSelectionBackground.tsx
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/ContextMenu/DefaultContextMenu.tsx
  packages/tldraw/src/lib/ui/components/MobileStylePanel.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanel.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiDropdownMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuGroup.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuSubmenu.tsx
  packages/tldraw/src/lib/ui/hooks/useRevelantStyles.ts
  packages/tldraw/src/test/TldrawEditor.test.tsx
  packages/tldraw/src/test/commands/lockShapes.test.ts
  packages/tldraw/src/test/testutils/renderTldrawComponent.tsx
  packages/tldraw/src/test/ui/ContextMenu.test.tsx
Labels: patch

#2870 Fix some incorrect translation keys
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenu.tsx
  packages/tldraw/src/lib/ui/components/EditLinkDialog.tsx
  packages/tldraw/src/lib/ui/components/EmbedDialog.tsx
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialog.tsx
Labels: patch

#2873 Fix dialog title styles
  packages/tldraw/src/lib/ui/components/EditLinkDialog.tsx
  packages/tldraw/src/lib/ui/components/EmbedDialog.tsx
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialog.tsx
Labels: patch

#2853 Editable shape example
  apps/examples/src/examples/custom-config/CustomConfigExample.tsx
  apps/examples/src/examples/editable-shape/EditableShapeExample.tsx
  apps/examples/src/examples/editable-shape/README.md
  apps/examples/src/examples/editable-shape/my-shape/my-shape-tool.tsx
  apps/examples/src/examples/editable-shape/my-shape/my-shape-util.tsx
  apps/examples/src/examples/editable-shape/ui-overrides.tsx
Labels: documentation

#2871 Update Hungarian and Korean
  assets/translations/hu.json
  assets/translations/ko-kr.json
Labels: translations, patch

#2856 [handles] Line shape handles -> points
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.test.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeTool.test.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.test.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/__snapshots__/LineShapeUtil.test.tsx.snap
  packages/tldraw/src/lib/shapes/line/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingHandle.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/customSnapping.test.tsx
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/shapes/TLLineShape.ts
Labels: minor

#2869 [Snapping 6/6] Self-snapping API
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/SnapManager/HandleSnaps.ts
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/editor/src/lib/primitives/geometry/CubicBezier2d.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.test.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx
  packages/tldraw/src/test/customSnapping.test.tsx
Labels: minor

#2848 Faster validations + record reference stability at the same time
  apps/dotcom-asset-upload/package.json
  apps/examples/src/examples/context-toolbar/ContextToolbar.tsx
  apps/examples/src/examples/custom-styles/FilterStyleUi.tsx
  package.json
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/utils/SharedStylesMap.ts
  packages/store/api-report.md
  packages/store/api/api.json
  packages/store/src/lib/RecordType.ts
  packages/store/src/lib/Store.ts
  packages/store/src/lib/StoreSchema.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DoubleDropdownPicker.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DropdownPicker.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiButtonPicker.tsx
  packages/tldraw/src/lib/ui/hooks/useRevelantStyles.ts
  packages/tldraw/src/lib/utils/tldr/file.ts
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/assets/TLBaseAsset.ts
  packages/tlschema/src/createTLSchema.ts
  packages/tlschema/src/index.ts
  packages/tlschema/src/shapes/TLBaseShape.ts
  packages/tlschema/src/styles/StyleProp.ts
  packages/validate/api-report.md
  packages/validate/api/api.json
  packages/validate/package.json
  packages/validate/src/lib/validation.ts
  packages/validate/src/test/validation.fuzz.test.ts
  packages/validate/src/test/validation.test.ts
  yarn.lock
Labels: patch

#2883 docs: fix scroll position and theming issue for code snippets
  apps/docs/components/mdx-components/code.tsx
  apps/docs/styles/globals.css
Labels: documentation

#2886 Fix 'style panel doesn't always disappear if you switch to the hand/laser tools'
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/components/MobileStylePanel.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanel.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DoubleDropdownPicker.tsx
  packages/tldraw/src/lib/ui/hooks/useRelevantStyles.ts
Labels: patch

#2890 Add line IDs & fractional indexes
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.test.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeTool.test.ts
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.test.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/__snapshots__/LineShapeUtil.test.tsx.snap
  packages/tldraw/src/lib/shapes/line/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx
  packages/tldraw/src/test/customSnapping.test.tsx
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/shapes/TLLineShape.ts
Labels: major

#2787 [experiment] paste: show little puff when pasting to denote something happened
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteTldrawContent.ts
Labels: patch

#2897 Fix object validator
  packages/validate/src/lib/validation.ts
Labels: patch

#2891 Check tsconfig "references" arrays
  .github/workflows/checks.yml
  apps/dotcom-worker/tsconfig.json
  apps/dotcom/tsconfig.json
  apps/examples/tsconfig.json
  apps/health-worker/tsconfig.json
  apps/huppy/tsconfig.json
  apps/vscode/editor/tsconfig.json
  apps/vscode/extension/tsconfig.json
  package.json
  packages/assets/tsconfig.json
  packages/editor/tsconfig.json
  packages/state/tsconfig.json
  packages/store/tsconfig.json
  packages/tldraw/tsconfig.json
  packages/tlschema/tsconfig.json
  packages/tlsync/tsconfig.json
  packages/validate/tsconfig.json
  scripts/check-tsconfigs.ts
Labels: internal

#2906 Fix some menu issues on mobile
  packages/tldraw/src/lib/ui.css
Labels: patch

#2902 menu fixes: add company links in general; add tracking to lang menu
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
  packages/tldraw/src/lib/ui/components/LanguageMenu.tsx
Labels: patch

#2914 docs: add star history and contributor list to README.
  README.md
Labels: documentation

#2911 VS Code 2.0.25
  apps/vscode/extension/CHANGELOG.md
  apps/vscode/extension/package.json
Labels: patch

#2912 Better example intros
  apps/docs/components/ExampleDocsPage.tsx
  apps/docs/styles/globals.css
Labels: documentation

#2908 Lokalise: Translations update
  assets/translations/ar.json
  assets/translations/ca.json
  assets/translations/cs.json
  assets/translations/da.json
  assets/translations/de.json
  assets/translations/es.json
  assets/translations/fa.json
  assets/translations/fi.json
  assets/translations/fr.json
  assets/translations/gl.json
  assets/translations/hi-in.json
  assets/translations/hr.json
  assets/translations/hu.json
  assets/translations/it.json
  assets/translations/ja.json
  assets/translations/ko-kr.json
  assets/translations/ne.json
  assets/translations/ro.json
  assets/translations/ru.json
  assets/translations/sl.json
  assets/translations/th.json
  assets/translations/tr.json
  assets/translations/uk.json
  assets/translations/vi.json
  assets/translations/zh-cn.json
  assets/translations/zh-tw.json
Labels: internal

#2920 examples: let people copy out code
  apps/examples/src/examples/canvas-events/CanvasEventsExample.tsx
  apps/examples/src/examples/store-events/StoreEventsExample.tsx
  apps/examples/src/examples/ui-events/UiEventsExample.tsx
Labels: internal

#2926 Export history hooks
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
Labels: minor

#2928 Fix frames not preserving shape order
  packages/tldraw/src/lib/shapes/frame/FrameShapeTool.ts
  packages/tldraw/src/test/frames.test.ts
Labels: patch

#2931 Fix an issue with publishing canary
  package.json
  yarn.lock
Labels: internal

#2932 Add custom static assets example, extract preloadFont
  apps/examples/public/ComicMono.woff
  apps/examples/public/custom-arrow-icon.svg
  apps/examples/src/examples/basic/BasicExample.tsx
  apps/examples/src/examples/static-assets/README.md
  apps/examples/src/examples/static-assets/StaticAssetsExample.tsx
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/hooks/usePreloadAssets.ts
  packages/tldraw/src/lib/utils/assets/preload-font.ts
Labels: minor

#2933 Fix undo/redo for Opacity Slider + Style dropdowns.
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/components/MobileStylePanel.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanel.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DropdownPicker.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiSlider.tsx
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteTldrawContent.ts
Labels: patch

#2878 E2E Style Panel Tests
  apps/examples/e2e/playwright.config.ts
  apps/examples/e2e/tests/fixtures/menus/StylePanel.ts
  apps/examples/e2e/tests/fixtures/menus/Toolbar.ts
  apps/examples/e2e/tests/test-mobile-style-panel.spec.ts
  apps/examples/e2e/tests/test-style-panel.spec.ts
  apps/examples/e2e/tests/test-toolbar.spec.ts
Labels: tests

#2919 Remove template references
  apps/docs/content/getting-started/quick-start.mdx
Labels: documentation

#2846 Add example for external UI
  apps/examples/src/examples/external-ui-context/ExternalUiContextExample.tsx
  apps/examples/src/examples/external-ui-context/README.md
  apps/examples/src/examples/external-ui-context/external-ui.css
  apps/examples/src/examples/external-ui/ExternalUiExample.tsx
  apps/examples/src/examples/external-ui/README.md
  apps/examples/src/examples/external-ui/external-ui.css
  apps/examples/src/examples/image-component/TldrawImageExample.tsx
Labels: documentation

#2940 [fix] Corejs imports
  packages/editor/src/index.ts
Labels: patch

#2948 Expand props
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/TldrawEditor.tsx
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/Tldraw.tsx
Labels: patch

#2949 bump typescript / api-extractor
  apps/docs/package.json
  apps/dotcom-bookmark-extractor/package.json
  apps/dotcom-worker/package.json
  apps/health-worker/package.json
  apps/vscode/extension/package.json
  package.json
  packages/assets/package.json
  packages/editor/api/api.json
  packages/state/api/api.json
  packages/store/api/api.json
  packages/tldraw/api/api.json
  packages/tlschema/api/api.json
  packages/tlsync/package.json
  packages/utils/api/api.json
  packages/validate/api/api.json
  scripts/package.json
  yarn.lock
Labels: dependencies

#2946 [fix] fit to content shown on groups
  packages/tldraw/src/lib/ui/components/menu-items.tsx
Labels: patch

#2952 Update auto
  .yarn/patches/@auto-it-core-npm-10.46.0-4ce8f196af.patch
  package.json
  scripts/package.json
  scripts/publish-new.ts
  yarn.lock
Labels: internal

#2956 [examples] Log out the 'after' values of changes in StoreEventsExample
  apps/examples/src/examples/store-events/StoreEventsExample.tsx
Labels: internal

#2958 [docs] content
  apps/docs/api/editor.api.json
  apps/docs/api/store.api.json
  apps/docs/api/tldraw.api.json
  apps/docs/api/tlschema.api.json
  apps/docs/api/validate.api.json
  apps/docs/content/getting-started/installation.mdx
  apps/docs/content/releases/v2.0.0-alpha.12.mdx
  apps/docs/content/releases/v2.0.0-alpha.13.mdx
  apps/docs/content/releases/v2.0.0-alpha.14.mdx
  apps/docs/content/releases/v2.0.0-alpha.15.mdx
  apps/docs/content/releases/v2.0.0-alpha.16.mdx
  apps/docs/content/releases/v2.0.0-alpha.17.mdx
  apps/docs/content/releases/v2.0.0-alpha.18.mdx
  apps/docs/content/releases/v2.0.0-alpha.19.mdx
  apps/docs/content/releases/v2.0.0-beta.1.mdx
  apps/docs/content/releases/v2.0.0-beta.2.mdx
  apps/docs/content/releases/v2.0.0-beta.3.mdx
  apps/docs/content/releases/v2.0.0-beta.4.mdx
Labels: documentation

#2961 [docs] Fix mailtos
  apps/docs/app/cla/page.tsx
  apps/docs/app/license/page.tsx
  apps/docs/content/community/license.mdx
Labels: documentation

#2963 [fix] double spinner
  packages/editor/src/lib/TldrawEditor.tsx
Labels: patch

#2964 Fix transparency toggle
  packages/tldraw/src/lib/ui/components/menu-items.tsx
Labels: patch

#2968 menu: export followup with different semantics for file menu
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: patch

#2959 Show toast on upload error
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: patch

#2973 export default ui items
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/components/ActionsMenu/DefaultActionsMenuContent.tsx
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenuContent.tsx
  packages/tldraw/src/lib/ui/components/HelpMenu/DefaultHelpMenuContent.tsx
  packages/tldraw/src/lib/ui/components/LanguageMenu.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageItemInput.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageItemSubmenu.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
Labels: minor

#2971 migrate shapes / assets as a store on `putContent`
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#2966 Open iframe production links in new tab
  apps/dotcom/src/components/IFrameProtector.tsx
Labels: internal

#2976 license: make them not be scrubbed out in code munging
  packages/tldraw/src/lib/shapes/shared/TextHelpers.ts
  packages/tldraw/src/lib/utils/assets/is-gif-animated.ts
Labels: internal

#2983 Make exportToBlob public
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/tldraw/src/lib/utils/export/exportAs.ts
Labels: minor

#2975 speech bubble handle -> tail
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/helpers.tsx
Labels: documentation

#2986 husky: add +x chmod flag
  .husky/post-merge
Labels: patch

#2887 Add external dialog example
  apps/examples/src/examples/external-dialog/ExternalDialog.tsx
  apps/examples/src/examples/external-dialog/README.md
  apps/examples/src/examples/external-dialog/external-dialog.css
Labels: documentation

#2987 Setup papercuts
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/createTLSchema.ts
Labels: patch

#2992 Don't allow edge scrolling when camera is frozen.
  packages/editor/src/lib/utils/edgeScrolling.ts
Labels: patch

#2938 [feature] wrap mode
  assets/translations/main.json
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Brushing.ts
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: minor

#2996 Implement new package publish process
  .github/workflows/publish-new.yml
  scripts/package.json
  scripts/publish-new.ts
  yarn.lock
Labels: internal

#2999 unbork publish-new
  .github/workflows/publish-new.yml
Labels: internal

#2954 Adding a single E2E test per menu
  apps/examples/e2e/tests/fixtures/fixtures.ts
  apps/examples/e2e/tests/fixtures/menus/ActionsMenu.ts
  apps/examples/e2e/tests/fixtures/menus/HelpMenu.ts
  apps/examples/e2e/tests/fixtures/menus/MainMenu.ts
  apps/examples/e2e/tests/fixtures/menus/NavigationPanel.ts
  apps/examples/e2e/tests/fixtures/menus/PageMenu.ts
  apps/examples/e2e/tests/test-actions-menu.spec.ts
  apps/examples/e2e/tests/test-clipboard.spec.ts
  apps/examples/e2e/tests/test-context-menu.spec.ts
  apps/examples/e2e/tests/test-help-menu.spec.ts
  apps/examples/e2e/tests/test-main-menu.spec.ts
  apps/examples/e2e/tests/test-navigation-panel.spec.ts
  apps/examples/e2e/tests/test-page-menu.spec.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui/components/ActionsMenu/DefaultActionsMenu.tsx
  packages/tldraw/src/lib/ui/components/HelpMenu/DefaultHelpMenu.tsx
  packages/tldraw/src/lib/ui/components/HelpMenu/DefaultHelpMenuContent.tsx
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenu.tsx
  packages/tldraw/src/lib/ui/components/Minimap/DefaultMinimap.tsx
  packages/tldraw/src/lib/ui/components/NavigationPanel/DefaultNavigationPanel.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/DefaultPageMenu.tsx
  packages/tldraw/src/lib/ui/components/ZoomMenu/DefaultZoomMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiDropdownMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuContext.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuSubmenu.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
Labels: tests

#3003 unbork "unbork publish-new"
  .github/workflows/publish-manual.yml
  .github/workflows/publish-new.yml
Labels: internal

#2995 Don't add editor / app to window.
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/dotcom/src/components/SnapshotsEditor.tsx
  apps/examples/src/misc/develop.tsx
  apps/examples/src/misc/end-to-end.tsx
  packages/editor/src/lib/TldrawEditor.tsx
Labels: major

#3006 fix publishing scripts
  scripts/lib/publishing.ts
  scripts/publish-canary.ts
  scripts/publish-new.ts
Labels: internal

#3008 Fix publishing scripts
  apps/dotcom/version.ts
  packages/editor/src/version.ts
  packages/tldraw/src/lib/ui/version.ts
  scripts/lib/publishing.ts
Labels: internal

#3009 fix setAllVersions
  scripts/lib/publishing.ts
Labels: internal

#3010 Fix publish script one more time
  apps/dotcom/version.ts
  packages/editor/src/version.ts
  packages/tldraw/src/lib/ui/version.ts
  scripts/publish-canary.ts
  scripts/publish-new.ts
Labels: internal
