Repository tldraw/tldraw, pull requests merged in 2024-03, with the labels that each got.

#3015 Selection UI example (plus fixes to pageToScreen)
  apps/examples/src/examples/selection-ui/README.md
  apps/examples/src/examples/selection-ui/SelectionUiExample.tsx
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
Labels: minor

#2990 Show a broken image for files without assets
  lerna.json
  packages/editor/editor.css
  packages/editor/src/lib/editor/Editor.ts
  packages/namespaced-tldraw/tldraw.css
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/BrokenAssetIcon.tsx
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: patch

#3022 [fix] Routes check on e2e tests
  apps/docs/scripts/functions/createApiMarkdown.ts
  apps/examples/e2e/tests/test-routes.spec.ts
  packages/editor/api/api.json
  packages/tlschema/api/api.json
Labels: tests

#3023 A few more async routes
  apps/examples/src/index.tsx
  packages/editor/api/api.json
Labels: internal

#3037 [fix] Missing element crash (rare) on video shapes.
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: patch

#3039 Expose `getStyleForNextShape`
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
Labels: patch

#2994 Custom shape examples
  apps/docs/tsconfig.json
  apps/examples/src/examples/custom-config/README.md
  apps/examples/src/examples/custom-shape/CustomShapeExample.tsx
  apps/examples/src/examples/custom-shape/README.md
  apps/examples/src/examples/editable-shape/EditableShapeExample.tsx
  apps/examples/src/examples/editable-shape/EditableShapeUtil.tsx
  apps/examples/src/examples/editable-shape/README.md
  apps/examples/src/examples/editable-shape/my-shape/my-shape-tool.tsx
  apps/examples/src/examples/editable-shape/my-shape/my-shape-util.tsx
  apps/examples/src/examples/editable-shape/ui-overrides.tsx
  apps/examples/src/examples/interactive-shape/InteractiveShapeExample.tsx
  apps/examples/src/examples/interactive-shape/README.md
  apps/examples/src/examples/interactive-shape/my-interactive-shape-util.tsx
Labels: documentation

#3048 [infra] fix canary dist tag
  scripts/lib/publishing.ts
  scripts/publish-canary.ts
Labels: internal

#2980 Configure dependabot.
  .github/dependabot.yml
  .github/workflows/dependabot-dedupe.yml
Labels: internal

#3057 Remove dependabot config since it only controls version updates?
  .github/dependabot.yml
  packages/tlschema/api/api.json
Labels: internal

#3046 Fix broken link for shape example
  apps/docs/content/docs/shapes.mdx
Labels: documentation

#3042 Fix cursor chat bubble position.
  apps/dotcom/src/components/CursorChatBubble.tsx
Labels: internal

#2974 [terrible] Firefox: Allow scrolling on keyboard shortcuts dialog
  packages/tldraw/src/lib/ui.css
Labels: patch

#3049 Lokalise: Translations update
  assets/translations/hu.json
Labels: translations, patch

#3061 children: any -> children: ReactNode
  apps/docs/app/providers.tsx
  apps/docs/components/AutoRefresh.tsx
  apps/dotcom/src/components/IFrameProtector.tsx
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/default-components/DefaultHandles.tsx
  packages/editor/src/lib/hooks/useEditorComponents.tsx
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui/components/ActionsMenu/DefaultActionsMenu.tsx
  packages/tldraw/src/lib/ui/components/ContextMenu/DefaultContextMenu.tsx
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenu.tsx
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenuContent.tsx
  packages/tldraw/src/lib/ui/components/HelpMenu/DefaultHelpMenu.tsx
  packages/tldraw/src/lib/ui/components/HelperButtons/DefaultHelperButtons.tsx
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialog.tsx
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenu.tsx
  packages/tldraw/src/lib/ui/components/QuickActions/DefaultQuickActions.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanel.tsx
  packages/tldraw/src/lib/ui/components/ZoomMenu/DefaultZoomMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/Button/TldrawUiButtonLabel.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiDialog.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiDropdownMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiInput.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuGroup.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuSubmenu.tsx
  packages/tldraw/src/lib/ui/context/TldrawUiContextProvider.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/breakpoints.tsx
  packages/tldraw/src/lib/ui/context/components.tsx
  packages/tldraw/src/lib/ui/context/dialogs.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/context/toasts.tsx
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/useTranslation.tsx
Labels: patch

#3063 Revert "Protect local storage calls (#3043)"
  .eslintrc.js
  apps/dotcom/src/utils/scratch-persistence-key.ts
  apps/dotcom/src/utils/userPreferences.ts
  apps/examples/src/examples/local-storage/LocalStorageExample.tsx
  package.json
  packages/editor/src/lib/config/TLSessionStateSnapshot.ts
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/utils/debug-flags.ts
  packages/editor/src/lib/utils/sync/hardReset.ts
  packages/editor/src/lib/utils/sync/indexedDb.test.ts
  packages/editor/src/lib/utils/sync/indexedDb.ts
  packages/tldraw/src/lib/ui/hooks/useLocalStorageState.ts
  packages/utils/api-report.md
  packages/utils/api/api.json
  packages/utils/src/index.ts
  packages/utils/src/lib/local-storage.ts
  packages/utils/src/lib/session-storage.ts
  yarn.lock
Labels: patch

#3066 Wrap local/session storage calls in try/catch (take 2)
  .eslintrc.js
  apps/dotcom/src/utils/scratch-persistence-key.ts
  apps/dotcom/src/utils/userPreferences.ts
  packages/editor/src/lib/config/TLSessionStateSnapshot.ts
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/utils/debug-flags.ts
  packages/editor/src/lib/utils/sync/hardReset.ts
  packages/editor/src/lib/utils/sync/indexedDb.test.ts
  packages/editor/src/lib/utils/sync/indexedDb.ts
  packages/tldraw/src/lib/ui/hooks/useLocalStorageState.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/storage.tsx
Labels: patch

#3047 Fix an issue where the video size was not drawn correctly
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: patch

#3041 Shorten url state
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/dotcom/src/hooks/useUrlState.ts
Labels: internal

#2960 Better websocket reconnection handling
  apps/dotcom/.eslintignore
  apps/dotcom/jestResolver.js
  apps/dotcom/package.json
  apps/dotcom/src/utils/remote-sync/ClientWebSocketAdapter.test.ts
  apps/dotcom/src/utils/remote-sync/ClientWebSocketAdapter.ts
  apps/dotcom/tsconfig.json
  yarn.lock
Labels: patch

#3068 Remove namespaced-tldraw/tldraw.css
  .gitignore
  packages/namespaced-tldraw/tldraw.css
Labels: internal

#3071 Add tests for Vec.Average
  packages/editor/src/lib/primitives/Vec.test.ts
Labels: tests

#3079 Fix viewport params for pages.
  apps/dotcom/src/hooks/useUrlState.ts
Labels: patch

#3078 Shape with Migrations
  apps/examples/src/examples/bounds-snapping-shape/README.md
  apps/examples/src/examples/shape-with-migrations/README.md
  apps/examples/src/examples/shape-with-migrations/ShapeWithMigrationsExample.tsx
  apps/examples/src/examples/shape-with-migrations/snapshot.json
Labels: documentation

#3091 Custom renderer example
  apps/examples/src/examples/custom-renderer/CustomRenderer.tsx
  apps/examples/src/examples/custom-renderer/CustomRendererExample.tsx
  apps/examples/src/examples/custom-renderer/README.md
Labels: documentation

#3088 Fix typo in useValue comment
  packages/state/src/lib/react/useValue.ts
Labels: documentation

#3093 [fix] Rotated crop handle
  packages/tldraw/src/lib/tools/SelectTool/childStates/Cropping.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingCropHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingResizeHandle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingRotateHandle.ts
Labels: patch

#3095 [infra] Fix patch release script
  scripts/lib/publishing.ts
  scripts/publish-patch.ts
Labels: internal

#2977 Performance improvements
  apps/examples/package.json
  packages/state/package.json
  packages/state/src/lib/react/useStateTracking.ts
  packages/state/src/lib/react/useValue.ts
  packages/state/tsconfig.json
  packages/store/src/lib/Store.ts
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Brushing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Cropping.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Rotating.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/ScribbleBrushing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/drawing.test.ts
  packages/tldraw/src/test/translating.test.ts
  packages/tlsync/src/lib/TLSyncClient.ts
  packages/utils/api-report.md
  packages/utils/src/index.ts
  packages/utils/src/lib/raf.ts
  packages/utils/src/lib/throttle.ts
  yarn.lock
Labels: major

#3012 Debounce/aggregate tlsync messages
  apps/dotcom/src/utils/remote-sync/ClientWebSocketAdapter.ts
  packages/tlsync/src/index.ts
  packages/tlsync/src/lib/RoomSession.ts
  packages/tlsync/src/lib/ServerSocketAdapter.ts
  packages/tlsync/src/lib/TLSyncClient.ts
  packages/tlsync/src/lib/TLSyncRoom.ts
  packages/tlsync/src/lib/protocol.ts
  packages/tlsync/src/lib/serializeMessage.ts
  packages/tlsync/src/test/TestServer.ts
  packages/tlsync/src/test/TestSocketPair.ts
  packages/tlsync/src/test/syncFuzz.test.ts
  packages/tlsync/src/test/upgradeDowngrade.test.ts
Labels: internal

#3116 Don't import package.json in scripts/refresh-assets.ts, just read it
  scripts/refresh-assets.ts
Labels: internal

#3115 Menu updates / fix flip / add export / remove Shape menu
  apps/dotcom/src/components/FileMenu.tsx
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
  apps/examples/e2e/tests/test-kbds.spec.ts
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/components/ContextMenu/DefaultContextMenuContent.tsx
  packages/tldraw/src/lib/ui/components/LanguageMenu.tsx
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/menu-hooks.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/useLanguages.tsx
Labels: major

#3106 Make the custom menu examples a bit clearer
  apps/examples/src/examples/custom-actions-menu/CustomActionsMenuExample.tsx
  apps/examples/src/examples/custom-actions-menu/README.md
  apps/examples/src/examples/custom-context-menu/CustomContextMenuExample.tsx
  apps/examples/src/examples/custom-context-menu/README.md
  apps/examples/src/examples/custom-debug-menu/CustomDebugMenuExample.tsx
  apps/examples/src/examples/custom-debug-menu/README.md
  apps/examples/src/examples/custom-help-menu/CustomHelpMenuExample.tsx
  apps/examples/src/examples/custom-help-menu/README.md
  apps/examples/src/examples/custom-keyboard-shortcuts-dialog/CustomKeyboardShortcutsDialogExample.tsx
  apps/examples/src/examples/custom-keyboard-shortcuts-dialog/README.md
  apps/examples/src/examples/custom-main-menu/CustomMainMenuExample.tsx
  apps/examples/src/examples/custom-main-menu/README.md
  apps/examples/src/examples/custom-navigation-panel/CustomNavigationPanelExample.tsx
  apps/examples/src/examples/custom-navigation-panel/README.md
  apps/examples/src/examples/custom-page-menu/CustomPageMenuExample.tsx
  apps/examples/src/examples/custom-page-menu/README.md
  apps/examples/src/examples/custom-quick-actions/CustomQuickActions.tsx
  apps/examples/src/examples/custom-style-panel/CustomStylePanelExample.tsx
  apps/examples/src/examples/custom-zoom-menu/CustomZoomMenuExample.tsx
  apps/examples/src/examples/custom-zoom-menu/README.md
Labels: docs

#3126 Restore export menu content
  apps/dotcom/src/components/LocalEditor.tsx
  apps/dotcom/src/components/MultiplayerEditor.tsx
Labels: internal

#3111 docs: fix missing API entries
  apps/docs/api/editor.api.json
  apps/docs/api/store.api.json
  apps/docs/api/tldraw.api.json
  apps/docs/api/tlschema.api.json
  apps/docs/api/validate.api.json
  apps/docs/content/releases/v2.0.0-alpha.12.mdx
  apps/docs/content/releases/v2.0.0-alpha.13.mdx
  apps/docs/content/releases/v2.0.0-alpha.14.mdx
  apps/docs/content/releases/v2.0.0-alpha.15.mdx
  apps/docs/content/releases/v2.0.0-alpha.16.mdx
  apps/docs/content/releases/v2.0.0-alpha.17.mdx
  apps/docs/content/releases/v2.0.0-alpha.18.mdx
  apps/docs/content/releases/v2.0.0-alpha.19.mdx
  apps/docs/content/releases/v2.0.0-beta.1.mdx
  apps/docs/content/releases/v2.0.0-beta.2.mdx
  apps/docs/content/releases/v2.0.0-beta.3.mdx
  apps/docs/content/releases/v2.0.0-beta.4.mdx
  apps/docs/content/releases/v2.0.0-beta.5.mdx
  apps/docs/content/releases/v2.0.0-beta.6.mdx
  apps/docs/content/releases/v2.0.0-beta.7.mdx
  apps/docs/content/releases/v2.0.0-beta.8.mdx
  apps/docs/content/releases/v2.0.0-beta.9.mdx
  apps/docs/content/releases/v2.0.0.mdx
  apps/docs/content/sections.json
  apps/docs/scripts/functions/createApiMarkdown.ts
  apps/docs/scripts/functions/fetchApiSource.ts
  apps/docs/scripts/functions/fetchReleases.ts
  apps/docs/scripts/refresh-embeddings.ts
  apps/docs/scripts/utils.ts
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/TldrawImage.tsx
  packages/tldraw/src/lib/ui/TldrawUi.tsx
Labels: docs, internal

#3129 Revert throttling of useValue and useStateTracking.
  packages/state/package.json
  packages/state/src/lib/react/useStateTracking.ts
  packages/state/src/lib/react/useValue.ts
  packages/state/tsconfig.json
  yarn.lock
Labels: bugfix

#3112 [DX] PR labels revamp
  .github/pull_request_template.md
  .github/workflows/checks.yml
  apps/huppy/README.md
  apps/huppy/src/flows/enforcePrLabels.tsx
  package.json
  scripts/lib/labels.ts
  scripts/package.json
  scripts/publish-new.ts
  scripts/publish-patch.ts
  scripts/update-pr-template.ts
  yarn.lock
Labels: internal

#3067 Component-based toolbar customisation API
  apps/examples/e2e/tests/test-focus.spec.ts
  apps/examples/e2e/tests/test-kbds.spec.ts
  apps/examples/e2e/tests/test-shapes.spec.ts
  apps/examples/src/examples/add-tool-to-toolbar/ToolInToolbarExample.tsx
  apps/examples/src/examples/bounds-snapping-shape/ui-overrides.tsx
  apps/examples/src/examples/custom-config/ui-overrides.tsx
  apps/examples/src/examples/custom-toolbar/CustomToolbarExample.tsx
  apps/examples/src/examples/screenshot-tool/ScreenshotToolExample.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/ui-overrides.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/hooks/useSafeId.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbar.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbarContent.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/OverflowingToolbar.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuContext.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuItem.tsx
  packages/tldraw/src/lib/ui/context/TldrawUiContextProvider.tsx
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
  packages/tldraw/src/lib/ui/hooks/useToolbarSchema.tsx
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
  packages/tldraw/src/lib/ui/overrides.ts
Labels: major

#3130 fixup file helpers
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/defaultStyleDefs.tsx
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/tldraw/src/lib/utils/tldr/file.ts
  packages/utils/api-report.md
  packages/utils/api/api.json
  packages/utils/src/lib/file.ts
  packages/utils/src/lib/media.ts
Labels: bugfix, sdk

#3138 Updated exploded example link from installation page.
  apps/docs/content/getting-started/installation.mdx
Labels: docs, dunno

#3150 Enable document name
  apps/dotcom/src/components/MultiplayerEditor.tsx
  packages/editor/src/lib/utils/debug-flags.ts
Labels: feature, dotcom

#3153 [docs] Sync docs deploy with npm deploy
  scripts/lib/didAnyPackageChange.ts
  scripts/package.json
  scripts/publish-new.ts
  scripts/publish-patch.ts
  scripts/vercel/should-build-docs.sh
  yarn.lock
Labels: docs, tools

#3156 Fix release eliding
  scripts/lib/didAnyPackageChange.ts
  scripts/publish-patch.ts
Labels: docs, tools

#3169 [fix] Cleanup text measures
  packages/editor/src/lib/editor/managers/TextManager.ts
Labels: bugfix, sdk

#3171 [tiny] remove unused shape indicator equality checker
  packages/editor/src/lib/components/default-components/DefaultShapeIndicator.tsx
Labels: improvement, sdk

#3172 [fix] Handles extra renders
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
Labels: bugfix, sdk

#3173 [sync] allow connections from v4 clients
  packages/tlsync/src/lib/RoomSession.ts
  packages/tlsync/src/lib/TLSyncClient.ts
  packages/tlsync/src/lib/TLSyncRoom.ts
  packages/tlsync/src/lib/protocol.ts
  packages/tlsync/src/test/upgradeDowngrade.test.ts
Labels: bugfix, dotcom

#3174 [example] culling
  apps/examples/src/examples/rendering-shape-changes/README.md
  apps/examples/src/examples/rendering-shape-changes/RenderingShapesChangeExample.tsx
  apps/examples/src/examples/rendering-shape-changes/useRenderingShapesChange.ts
Labels: docs, improvement

#3177 [fix] handles
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
Labels: bugfix, sdk

#3178 [tiny] Slightly more efficient selection rotated page bounds / page bounds
  packages/editor/src/lib/editor/Editor.ts
Labels: improvement, sdk

#3158 Add release docs
  RELEASES.md
Labels: internal

#3170 [tiny] lift theme in style panel
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiButtonPicker.tsx
Labels: improvement, sdk

#3176 [tinyish] Simplify / skip some work in Shape
  packages/editor/editor.css
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/utils/dom.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
Labels: improvement, sdk

#3183 Skip the random ID for regular history entries
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/managers/HistoryManager.ts
  packages/editor/src/lib/editor/types/history-types.ts
Labels: improvement, sdk

#3181 [fix] Batch tick events
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/ScribbleManager.ts
  packages/editor/src/lib/editor/tools/StateNode.ts
  packages/editor/src/lib/editor/types/event-types.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/tools/SelectTool/childStates/Brushing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
Labels: bugfix, sdk

#3187 Remove access token logic.
  apps/dotcom/src/hooks/useRemoteSyncClient.ts
  apps/dotcom/src/utils/remote-sync/remote-sync.ts
Labels: dotcom, chore

#3198 Fix jpg export and tests
  apps/examples/e2e/tests/export-snapshots.spec.ts
  apps/examples/e2e/tests/fixtures/fixtures.ts
  apps/examples/e2e/tests/test-api.spec.ts
  apps/examples/src/misc/EndToEndApi.tsx
  apps/examples/src/misc/end-to-end.tsx
  packages/tldraw/src/lib/Tldraw.test.tsx
  packages/tldraw/src/lib/utils/export/export.ts
Labels: bugfix, sdk

#3197 Update the document title to include the document name.
  apps/dotcom/src/components/DocumentName/DocumentName.tsx
Labels: improvement, dotcom

#3201 fix docs build
  apps/docs/components/Search.tsx
  apps/docs/scripts/functions/fetchApiSource.ts
  apps/docs/scripts/functions/fetchReleases.ts
  scripts/vercel/build-docs.sh
Labels: docs, bugfix

#3186 Fix lag while panning + translating at the same time
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/TickManager.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/translating.test.ts
  packages/utils/api-report.md
  packages/utils/src/lib/throttle.ts
Labels: bugfix, sdk

#3166 use native structuredClone on node, cloudflare workers, and in tests
  .eslintignore
  .eslintrc.js
  .github/workflows/checks.yml
  apps/docs/app/api/ai/route.ts
  apps/docs/app/api/search/route.ts
  apps/docs/package.json
  apps/docs/tsconfig.json
  apps/dotcom/package.json
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
  packages/editor/package.json
  packages/editor/src/lib/editor/Editor.ts
  packages/namespaced-tldraw/package.json
  packages/store/src/lib/devFreeze.ts
  packages/tldraw/package.json
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.test.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/crop_helpers.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Cropping.ts
  packages/tlschema/src/shapes/TLLineShape.ts
  packages/tlsync/package.json
  packages/tlsync/src/lib/TLSyncRoom.ts
  packages/utils/api-report.md
  packages/utils/api/api.json
  packages/utils/package.json
  packages/utils/patchedJestJsDom.js
  packages/utils/src/index.ts
  packages/utils/src/lib/object.ts
  packages/utils/src/lib/value.ts
  packages/validate/src/lib/validation.ts
  scripts/prepack.ts
  yarn.lock
Labels: improvement, dotcom, sdk, chore

#3147 Add image annotator example
  apps/docs/scripts/functions/generateExamplesContent.ts
  apps/examples/e2e/tests/test-routes.spec.ts
  apps/examples/src/examples.tsx
  apps/examples/src/examples/context-toolbar/ContextToolbar.tsx
  apps/examples/src/examples/image-annotator/ImageAnnotationEditor.tsx
  apps/examples/src/examples/image-annotator/ImageAnnotator.tsx
  apps/examples/src/examples/image-annotator/ImageExport.tsx
  apps/examples/src/examples/image-annotator/ImagePicker.tsx
  apps/examples/src/examples/image-annotator/README.md
  apps/examples/src/examples/image-annotator/assets/anakin.jpeg
  apps/examples/src/examples/image-annotator/assets/distracted-bf.jpeg
  apps/examples/src/examples/image-annotator/assets/expanding-brain.png
  apps/examples/src/examples/image-annotator/image-annotator.css
  apps/examples/src/examples/image-annotator/types.tsx
  apps/examples/src/examples/screenshot-tool/ScreenshotToolExample.tsx
  apps/examples/src/examples/things-on-the-canvas/OnTheCanvas.tsx
  apps/examples/src/index.tsx
  apps/examples/src/styles.css
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useGestureEvents.ts
  packages/tldraw/src/lib/Tldraw.tsx
Labels: docs, feature, sdk

#3159 PDF editor example
  apps/examples/e2e/tests/test-routes.spec.ts
  apps/examples/package.json
  apps/examples/src/examples/image-annotator/ImageAnnotationEditor.tsx
  apps/examples/src/examples/pdf-editor/ExportPdfButton.tsx
  apps/examples/src/examples/pdf-editor/PdfEditor.tsx
  apps/examples/src/examples/pdf-editor/PdfEditorExample.tsx
  apps/examples/src/examples/pdf-editor/PdfPicker.tsx
  apps/examples/src/examples/pdf-editor/README.md
  apps/examples/src/examples/pdf-editor/assets/tldraw.pdf
  apps/examples/src/examples/pdf-editor/pdf-editor.css
  apps/examples/vite.config.ts
  package.json
  yarn.lock
Labels: docs, feature

#3209 docs: work around browser bug with input+scrolling
  apps/docs/styles/globals.css
Labels: docs, bugfix

#3205 top bar design tweaks
  apps/dotcom/styles/z-board.css
Labels: bugfix, dotcom

#3210 tooling: prettier ignore pr template
  .prettierignore
Labels: bugfix, internal

#3218 Add yarn immutable check to pre-commit.
  .husky/pre-commit
Labels: internal, tools

#3182 Don't double squash
  packages/store/src/lib/Store.ts
Labels: improvement, sdk

#3227 fix docs slugs
  apps/docs/scripts/utils.ts
Labels: docs, bugfix

#3217 Revert perf changes
  apps/examples/package.json
  packages/editor/src/lib/components/Shape.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/state/api-report.md
  packages/state/package.json
  packages/state/src/lib/core/EffectScheduler.ts
  packages/state/src/lib/react/index.ts
  packages/state/src/lib/react/useLayoutReaction.ts
  packages/state/src/lib/react/useStateTracking.ts
  packages/state/src/lib/react/useTrackedScheduler.ts
  packages/state/src/lib/react/useValue.ts
  packages/state/tsconfig.json
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Brushing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Cropping.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Rotating.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/ScribbleBrushing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/drawing.test.ts
  packages/tldraw/src/test/translating.test.ts
  yarn.lock
Labels: internal, chore

#3228 docs: make header fixed instead of sticky
  apps/docs/styles/globals.css
Labels: docs, bugfix

#3244 toolbar: fix missing title attributes
  apps/dotcom/src/utils/migration/DebugMenuItems.tsx
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuItem.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
Labels: bugfix, sdk

#3101 stickies: new icon
  assets/icons/icon/tool-note.svg
Labels: improvement

#3113 Add inline behaviour example
  apps/examples/src/examples/inline-behavior/InlineBehavior.tsx
  apps/examples/src/examples/inline-behavior/README.md
  apps/examples/src/examples/multiple/MultipleExample.tsx
Labels: docs

#3261 Allow hiding debug panel.
  apps/examples/src/examples/ui-components-hidden/UiComponentsHiddenExample.tsx
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/DefaultDebugPanel.tsx
  packages/tldraw/src/lib/ui/context/components.tsx
Labels: feature, sdk

#3263 fix document name overflow
  apps/dotcom/src/components/DocumentName/DocumentName.tsx
  apps/dotcom/styles/z-board.css
Labels: bugfix, dotcom

#3222 Stickies: shadows
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
Labels: improvement, sdk

#3269 Update romanian translations
  assets/translations/ro.json
Labels: translations, dotcom

#3264 fix export preview size
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
Labels: bugfix, internal

#3258 side effects reference docs & examples
  apps/docs/content/docs/editor.mdx
  apps/docs/scripts/functions/generateSection.ts
  apps/examples/src/examples/after-create-update-shape/AfterCreateUpdateShapeExample.tsx
  apps/examples/src/examples/after-create-update-shape/README.md
  apps/examples/src/examples/after-delete-shape/AfterDeleteShapeExample.tsx
  apps/examples/src/examples/after-delete-shape/README.md
  apps/examples/src/examples/before-create-update-shape/BeforeCreateUpdateShapeExample.tsx
  apps/examples/src/examples/before-create-update-shape/README.md
  apps/examples/src/examples/before-delete-shape/BeforeDeleteShapeExample.tsx
  apps/examples/src/examples/before-delete-shape/README.md
  packages/editor/api-report.md
  packages/editor/api/api.json
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/SideEffectManager.ts
Labels: docs, improvement

#3050 textfields [1 of 3]: add text into speech bubble; also add rich text example
  apps/examples/src/examples/speech-bubble/README.md
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/helpers.tsx
  apps/examples/src/examples/speech-bubble/customhandles.css
  packages/editor/editor.css
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/components/ArrowTextLabel.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/default-shape-constants.ts
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/text/TextArea.tsx
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
Labels: minor

#2988 ui: make toasts look more toasty
  apps/dotcom/src/components/SneakyOnDropOverride.ts
  apps/dotcom/src/utils/sharing.ts
  apps/dotcom/src/utils/useFileSystem.tsx
  assets/icons/icon/check-circle.svg
  assets/icons/icon/cross-circle.svg
  assets/icons/icon/error.svg
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/editor/editor.css
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenuContent.tsx
  packages/tldraw/src/lib/ui/components/Toasts.tsx
  packages/tldraw/src/lib/ui/context/toasts.tsx
  packages/tldraw/src/lib/ui/hooks/useCopyAs.ts
  packages/tldraw/src/lib/ui/hooks/useEditorEvents.ts
  packages/tldraw/src/lib/ui/hooks/useExportAs.ts
  packages/tldraw/src/lib/ui/icon-types.ts
  packages/tldraw/src/lib/utils/tldr/file.ts
Labels: bugfix

#3271 styling: make dotcom and examples site have consistent font styling
  apps/docs/content/getting-started/installation.mdx
  apps/dotcom/styles/core.css
  apps/dotcom/styles/globals.css
  apps/examples/src/styles.css
  apps/vscode/editor/public/index.css
  packages/tldraw/src/lib/ui.css
  templates/nextjs/src/app/globals.css
  templates/vite/src/index.css
Labels: bugfix, sdk

#3274 log message size in worker analytics
  apps/dotcom-worker/src/lib/TLDrawDurableObject.ts
  apps/dotcom-worker/src/lib/types.ts
  packages/tlsync/src/index.ts
  packages/tlsync/src/lib/ServerSocketAdapter.ts
  packages/tlsync/src/lib/TLServer.ts
  scripts/deploy.ts
Labels: internal, chore

#3242 stickies: resize font-size _only_ if we hit long words
  apps/examples/e2e/tests/test-text.spec.ts
  packages/editor/src/lib/editor/managers/TextManager.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/test/TestEditor.ts
  packages/tlschema/api-report.md
  packages/tlschema/api/api.json
  packages/tlschema/src/shapes/TLNoteShape.ts
Labels: improvement, sdk

#3099 stickies: edit on type
  packages/editor/api-report.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.md
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/test/SelectTool.test.ts
Labels: bugfix

#3137 editing: stay in edit mode across shape editing
  packages/tldraw/src/lib/tools/SelectTool/childStates/EditingShape.ts
  packages/tldraw/src/test/SelectTool.test.ts
Labels: improvement, sdk

#3132 stickies: edit on type, part 2: place cursor at intended position in general
  packages/editor/editor.css
  packages/tldraw/api/api.json
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/TextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/useEditableText.ts
  packages/tldraw/src/lib/shapes/text/TextArea.tsx
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/EditingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingArrowLabel.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingShape.ts
  packages/tldraw/src/lib/utils/frames/frames.ts
  packages/tldraw/src/lib/utils/shapes/shapes.ts
  packages/tldraw/src/test/SelectTool.test.ts
Labels: feature, sdk

#3272 Improve performance of culling
  packages/editor/src/lib/constants.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useScreenBounds.ts
Labels: improvement, sdk

#3283 Decrease the number of rendered dom nodes for geo shape and arrows
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
Labels: improvement, sdk

#3298 stickies: disable indicator whilst editing
  apps/dotcom-worker/src/lib/TLDrawDurableObject.ts
  apps/dotcom-worker/src/lib/types.ts
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/tlsync/src/index.ts
  packages/tlsync/src/lib/ServerSocketAdapter.ts
  packages/tlsync/src/lib/TLServer.ts
  scripts/deploy.ts
Labels: improvement, sdk

#3277 [chore] Bump browser-fs-access.
  apps/dotcom/package.json
  apps/dotcom/src/utils/useFileSystem.tsx
  yarn.lock
Labels: internal, chore

#3306 Fix typo.
  packages/store/src/lib/StoreQueries.ts
Labels: sdk, chore

#3318 Fix count shapes and nodes
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenuContent.tsx
Labels: bugfix, sdk
