Repository tldraw/tldraw, pull requests merged in 2025-04, with the labels that each got.

#5551 Zero spike
  .github/workflows/deploy-dotcom.yml
  .gitignore
  apps/dotcom/client/e2e/fixtures/Sidebar.ts
  apps/dotcom/client/e2e/tests/homepage.spec.ts
  apps/dotcom/client/index.html
  apps/dotcom/client/package.json
  apps/dotcom/client/setupTests.js
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/app/zero-polyfill.ts
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/hooks/useAppState.tsx
  apps/dotcom/client/src/utils/config.ts
  apps/dotcom/client/src/utils/csp.ts
  apps/dotcom/client/src/utils/multiplayerAssetStore.ts
  apps/dotcom/client/vite.config.ts
  apps/dotcom/sync-worker/package.json
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/getFetchEverythingSql.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/zero-cache/.env
  apps/dotcom/zero-cache/.gitignore
  apps/dotcom/zero-cache/clean.sh
  apps/dotcom/zero-cache/migrations/015_full_replicas.sql
  apps/dotcom/zero-cache/migrations/016_zero_publication.sql
  apps/dotcom/zero-cache/package.json
  internal/scripts/deploy-dotcom.ts
  package.json
  packages/dotcom-shared/package.json
  packages/dotcom-shared/src/tlaSchema.ts
  sst.config.ts
  yarn.lock
Labels: other, preview-sst-zero-deploy-please

#5786 Limit the label gating to previews.
  internal/scripts/deploy-dotcom.ts
Labels: improvement

#5787 Fix domain name generation
  sst.config.ts
Labels: bugfix

#5788 Update the production zero domain
  sst.config.ts
Labels: bugfix

#5790 fix error pasting shapes from Miro
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: bugfix

#5778 Disable currently broken docs links
  apps/docs/content/getting-started/releases-versioning.mdx
  packages/editor/src/lib/TldrawEditor.tsx
  packages/state-react/src/lib/useValue.ts
  packages/state/src/lib/Computed.ts
  packages/state/src/lib/EffectScheduler.ts
  packages/state/src/lib/types.ts
Labels: other, docs-hotfix-please

#5784 Better no results page
  apps/docs/components/search/SearchAutocomplete.tsx
Labels: other

#5785 Docs: Add slash keyboard shortcut to open search
  apps/docs/components/search/SearchButton.tsx
Labels: other

#5800 Make image pasting atomic
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: improvement

#5795 Fly for preview deploys.
  .github/workflows/deploy-dotcom.yml
  .github/workflows/prune-preview-deploys.yml
  apps/dotcom/zero-cache/flyio.template.toml
  internal/scripts/deploy-dotcom.ts
  internal/scripts/prune-preview-deploys.ts
Labels: improvement

#5805 Prune sst stages based on the active amazon clusters.
  .github/workflows/prune-preview-deploys.yml
  internal/scripts/prune-preview-deploys.ts
  package.json
  yarn.lock
Labels: improvement

#5791 fix github workflow sometimes using sh instead of bash
  .github/workflows/close-stale-issues.yml
  .github/workflows/dependabot-dedupe.yml
  .github/workflows/deploy-docs-on-release-edit.yml
  .github/workflows/get-changelog.yml
  .github/workflows/i18n-download-strings.yml
  .github/workflows/i18n-upload-strings.yml
  .github/workflows/publish-canary.yml
  .github/workflows/publish-manual.yml
  .github/workflows/publish-new.yml
  .github/workflows/publish-patch.yml
  .husky/post-checkout
Labels: other

#5762 isShapeHidden => getShapeVisibility, to allow children of hidden shapes to be visible
  apps/docs/content/docs/editor.mdx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/examples/src/examples/layer-panel/LayerPanelExample.tsx
  apps/examples/src/examples/layer-panel/ShapeList.tsx
  apps/examples/src/examples/sync-private-content/SyncPrivateContentExample.tsx
  packages/editor/api-report.api.md
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/Editor.test.tsx
Labels: other

#5792 Fix unexpected artefacts showing up in exports when the page includes tailwind
  packages/editor/src/lib/exports/StyleEmbedder.ts
  packages/editor/src/lib/exports/cssRules.ts
  packages/editor/src/lib/exports/parseCss.ts
Labels: bugfix

#5789 images: fix not being able to insert SVGs into Firefox
  packages/tldraw/src/lib/utils/assets/assets.ts
  packages/utils/api-report.api.md
  packages/utils/src/lib/media/media.ts
Labels: bugfix

#5761 a11y: navigable shapes
  .prettierrc
  apps/examples/e2e/tests/test-kbds.spec.ts
  assets/translations/main.json
  packages/editor/api-report.api.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/editor/src/lib/editor/shapes/group/GroupShapeUtil.tsx
  packages/editor/src/lib/editor/types/selection-types.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/editor/src/lib/license/Watermark.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/draw/DrawShapeUtil.tsx
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/noteHelpers.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/A11y.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/test/navigation.test.ts
Labels: feature

#5801 Store.atomic and Store.mergeRemoteChanges fixes
  packages/store/api-report.api.md
  packages/store/src/lib/Store.ts
  packages/store/src/lib/test/recordStore.test.ts
Labels: improvement

#5812 Include assetUrls in ExplodedExample
  apps/examples/src/examples/exploded/ExplodedExample.tsx
Labels: bugfix

#5817 Increase the preview pruning timout
  .github/workflows/prune-preview-deploys.yml
Labels: improvement

#5825 A11y focus button fixes
  assets/translations/main.json
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/A11y.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: bugfix, improvement

#5835 Rename useIsMultiplayer.ts to useCollaborationStatus [#5833]
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/components/ContextMenu/DefaultContextMenuContent.tsx
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
  packages/tldraw/src/lib/ui/components/TopPanel/DefaultTopPanel.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/components.tsx
  packages/tldraw/src/lib/ui/hooks/useCollaborationStatus.ts
Labels: improvement

#5836 Update quick-start.mdx
  apps/docs/content/getting-started/quick-start.mdx
Labels: other, docs-hotfix-please

#5837 a11y: fix focus ring on share menu/embed dialog; also slider/watermark
  apps/dotcom/client/src/tla/components/TlaButton/TlaButton.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/file-share-menu.module.css
  apps/dotcom/client/src/tla/components/TlaSwitch/TlaSwitch.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  packages/editor/src/lib/license/Watermark.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiSlider.tsx
Labels: other

#5774 Fix typo in Local Images example
  apps/examples/src/examples/local-images/LocalImagesExample.tsx
Labels: improvement

#5773 a11y: announce shapes as they're visited
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  assets/translations/main.json
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
  packages/tldraw/src/lib/ui/components/A11y.tsx
  packages/tldraw/src/lib/ui/context/a11y.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/lib/utils/excalidraw/__snapshots__/putExcalidrawContent.test.tsx.snap
  packages/tldraw/src/test/A11y.test.tsx
  packages/tlschema/api-report.api.md
  packages/tlschema/src/migrations.test.ts
  packages/tlschema/src/shapes/TLImageShape.ts
  packages/tlschema/src/shapes/TLVideoShape.ts
Labels: feature

#5840 a11y: add axe to be able to do audits
  apps/dotcom/client/e2e/fixtures/HomePage.ts
  apps/dotcom/client/src/tla/components/TlaIcon/TlaIcon.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarWorkspaceLink.tsx
  apps/dotcom/client/src/tla/components/TlaSignedOutShareButton/TlaSignedOutShareButton.tsx
  apps/examples/src/ExamplePage.tsx
  apps/examples/src/styles.css
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/package.json
  packages/tldraw/src/lib/canvas/TldrawCropHandles.tsx
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/A11y.tsx
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenuContent.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanel.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbar.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiSlider.tsx
  yarn.lock
Labels: feature

#5843 fix examples
  apps/examples/src/examples/image-annotator/ImageAnnotationEditor.tsx
  apps/examples/src/examples/image-annotator/image-annotator.css
  apps/examples/src/examples/pdf-editor/pdf-editor.css
Labels: other, docs-hotfix-please

#5846 a11y: move audit to just /develop
  apps/examples/package.json
  apps/examples/src/misc/a11y.tsx
  apps/examples/src/misc/develop.tsx
  packages/tldraw/package.json
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenuContent.tsx
  yarn.lock
Labels: other

#5834 Fix flyio app prunning and deployment.
  internal/scripts/deploy-dotcom.ts
  internal/scripts/prune-preview-deploys.ts
Labels: bugfix

#5848 a11y: fix up watermark regression
  packages/editor/src/lib/license/Watermark.tsx
Labels: bugfix

#5847 a11y: more role updates, more semantic html5 tags
  apps/dotcom/client/e2e/fixtures/ShareMenu.ts
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileSection.tsx
  apps/dotcom/client/src/tla/components/TlaSwitch/TlaSwitch.tsx
  apps/dotcom/client/src/tla/components/TlaTabs/TlaTabs.tsx
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  apps/examples/src/ExamplePage.tsx
  assets/translations/main.json
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/ContextMenu/DefaultContextMenu.tsx
  packages/tldraw/src/lib/ui/components/DefaultDebugPanel.tsx
  packages/tldraw/src/lib/ui/components/DefaultMenuPanel.tsx
  packages/tldraw/src/lib/ui/components/NavigationPanel/DefaultNavigationPanel.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/PeopleMenu.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbar.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/OverflowingToolbar.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiContextualToolbar.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiDropdownMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuGroup.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement, other

#5851 [dotcom] Fix indicator/selection skew at some browser zoom levels.
  apps/dotcom/client/styles/globals.css
Labels: other

#5863 Fix jobs link.
  apps/docs/content/blog/announcing-tldraw-series-a.mdx
Labels: bugfix

#5852 a11y: add keyboard shortcut items; fix up focus ring in dotcom menus
  apps/dotcom/client/src/tla/components/tla-form/tla-form.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  assets/translations/main.json
  packages/editor/src/lib/editor/managers/FocusManager.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/lib/ui/kbd-utils.ts
Labels: improvement

#5849 Fix `useIsToolSelected`, add remove tool example
  apps/examples/src/examples/remove-tool/README.md
  apps/examples/src/examples/remove-tool/RemoveToolExample.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbarContent.tsx
Labels: bugfix, other

#5865 fix: install corepack from npm
  .github/actions/setup/action.yml
  README.md
  internal/scripts/clean.sh
Labels: other

#5605 kbd: rework keyboard shortcut mapping symbols to be more intuitive
  apps/docs/content/docs/user-interface.mdx
  apps/dotcom/client/src/tla/components/TlaEditor/useFileEditorOverrides.ts
  apps/examples/src/examples/action-overrides/ActionOverridesExample.tsx
  apps/examples/src/examples/keyboard-shortcuts/KeyboardShortcutsExample.tsx
  apps/examples/src/examples/lock-camera-zoom/LockCameraZoomExample.tsx
  apps/examples/src/examples/text-search/TextSearchExample.tsx
  apps/examples/src/hooks/useDebugging.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiKbd.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/useKeyboardShortcuts.ts
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
  packages/tldraw/src/lib/ui/kbd-utils.ts
Labels: improvement

#5867 Fix case sensitive gif
  apps/docs/content/blog/jam.mdx
  apps/docs/public/images/case-studies/jam-long-2.gif
Labels: docs-hotfix-please

#5826 a11y: add resize kbd shortcut
  apps/examples/e2e/tests/test-kbds.spec.ts
  assets/translations/main.json
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement

#5868 Fix landing page issues
  apps/docs/components/common/button.tsx
  apps/docs/components/content/video.tsx
  apps/docs/components/marketing/cta-section.tsx
  apps/docs/components/marketing/installation-section.tsx
  apps/docs/components/marketing/section.tsx
  apps/docs/components/navigation/header.tsx
Labels: docs-hotfix-please

#5873 Update clickup case study
  apps/docs/content/blog/clickup.mdx
Labels: docs-hotfix-please

#5874 rich text: export some of our custom extensions
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/utils/text/richText.ts
  packages/tldraw/src/lib/utils/text/textDirection.ts
Labels: api

#5876 Fix custom mutators deploy
  apps/dotcom/zero-cache/flyio.template.toml
  internal/scripts/deploy-dotcom.ts
  sst.config.ts
Labels: other, preview-sst-zero-deploy-please

#5879 Add vs code option.
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: other

#5853 Add ShapeUtil.configure example
  apps/examples/src/examples/configure-shape-util/ConfigureShapeUtilExample.tsx
  apps/examples/src/examples/configure-shape-util/README.md
Labels: other

#5893 youtube: fix up timestamp
  packages/tldraw/src/lib/defaultEmbedDefinitions.ts
  packages/tldraw/src/lib/utils/embeds/embeds.test.ts
Labels: bugfix

#5896 fix error pasting shapes from Miro, pt 2
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: bugfix

#5900 a11y: add null check for bookmark asset descriptor
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
Labels: bugfix

#5904 Fix bad arrow bindings to text shapes (#5902)
  packages/editor/api-report.api.md
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
Labels: bugfix

#5908 stickies: make sure our custom tab behavior takes over the rich text behavior
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/RichTextLabel.tsx
  packages/tldraw/src/lib/shapes/text/RichTextArea.tsx
  packages/utils/src/lib/media/media.ts
Labels: bugfix

#5913 docs: should be a nav, not aside
  apps/docs/components/blog/blog-sidebar.tsx
  apps/docs/components/blog/blog-table-of-contents.tsx
  apps/docs/components/common/navigation.tsx
  apps/docs/components/docs/docs-sidebar.tsx
  apps/docs/components/docs/docs-table-of-contents.tsx
Labels: other

#5839 [INT-1278] Move Import file under File menu
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaAccountMenu/TlaAccountMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
Labels: improvement

#5885 Deploy zero on demand.
  .github/workflows/deploy-dotcom.yml
  internal/scripts/deploy-dotcom.ts
Labels: improvement

#5915 Bump zero version.
  apps/dotcom/client/package.json
  apps/dotcom/sync-worker/package.json
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/zero-cache/package.json
  packages/dotcom-shared/package.json
  sst.config.ts
  yarn.lock
Labels: improvement, preview-sst-zero-deploy-please

#5924 Fix user following chains + add loop support
  packages/editor/src/lib/editor/Editor.ts
Labels: other

#5923 Optimize query.
  apps/dotcom/client/src/tla/app/TldrawApp.ts
Labels: improvement, preview-flyio-zero-deploy-please

#5928 Fix getSelectedShapes caching
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix

#5919 Move license key docs to docs site
  apps/docs/components/content/index.tsx
  apps/docs/components/content/side-by-side-images.tsx
  apps/docs/components/marketing/pricing-section.tsx
  apps/docs/content/community/license.mdx
  apps/docs/content/legal/tldraw-license.mdx
  apps/docs/public/images/with-watermark.png
  apps/docs/public/images/without-watermark.png
Labels: other, docs-hotfix-please

#5939 Stop sending `first-connect-duration` event
  apps/dotcom/client/src/tla/app/zero-polyfill.ts
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
Labels: improvement, preview-flyio-zero-deploy-please

#5912 a11y: add rich text shortcuts to dialog; add shortcut for links
  assets/translations/main.json
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultRichTextToolbarContent.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement

#5941 a11y: fix up select dropdown in share; also error dialog
  apps/dotcom/client/src/tla/components/TlaSelect/TlaSelect.tsx
  apps/dotcom/client/src/tla/components/TlaSelect/select.module.css
  apps/dotcom/client/src/tla/styles/tla.css
  packages/editor/editor.css
  packages/editor/src/lib/components/default-components/DefaultErrorFallback.tsx
Labels: improvement, preview-flyio-zero-deploy-please

#5940 license: allow ability to do VS code extensions
  apps/vscode/editor/src/app.tsx
  packages/editor/src/lib/license/LicenseManager.test.ts
  packages/editor/src/lib/license/LicenseManager.ts
Labels: api

#5947 INT-1266 Remove GitHub CTA from SDK error dialogs
  packages/editor/src/lib/components/default-components/DefaultErrorFallback.tsx
Labels: improvement

#5949 templates: Fix simple server node example dropping messages on initial connection
  templates/simple-server-example/package.json
  templates/simple-server-example/src/server/server.node.ts
Labels: other

#5953 Bump zero
  apps/dotcom/client/package.json
  apps/dotcom/sync-worker/package.json
  apps/dotcom/zero-cache/package.json
  packages/dotcom-shared/package.json
  yarn.lock
Labels: improvement, preview-flyio-zero-deploy-please

#5872 a11y: make toolbars more compliant with keyboard navigation
  apps/examples/e2e/tests/test-focus.spec.ts
  apps/examples/e2e/tests/test-shapes.spec.ts
  assets/translations/main.json
  packages/editor/api-report.api.md
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/default-components/DefaultSpinner.tsx
  packages/editor/src/lib/options.ts
  packages/editor/src/lib/utils/dom.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/package.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/A11y.tsx
  packages/tldraw/src/lib/ui/components/ActionsMenu/DefaultActionsMenu.tsx
  packages/tldraw/src/lib/ui/components/DefaultMenuPanel.tsx
  packages/tldraw/src/lib/ui/components/LoadingScreen.tsx
  packages/tldraw/src/lib/ui/components/NavigationPanel/DefaultNavigationPanel.tsx
  packages/tldraw/src/lib/ui/components/Spinner.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanel.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DoubleDropdownPicker.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DropdownPicker.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultRichTextToolbar.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultRichTextToolbarContent.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbar.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/OverflowingToolbar.tsx
  packages/tldraw/src/lib/ui/components/ZoomMenu/DefaultZoomMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiButtonPicker.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiContextualToolbar.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiToolbar.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuItem.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  yarn.lock
Labels: improvement

#5958 a11y: better embed interaction
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
Labels: improvement

#5951 Fix flickering when rotating arrow
  packages/editor/api-report.api.md
  packages/editor/src/lib/utils/rotation.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Rotating.ts
Labels: bugfix

#5957 a11y: dont go into edit mode when moving to canvas content
  packages/tldraw/src/lib/shapes/geo/GeoShapeTool.test.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/test/SelectTool.test.ts
  packages/tldraw/src/test/TestEditor.ts
  packages/tldraw/src/test/commands/setCurrentPage.test.ts
Labels: bugfix

#5972 Bump again.
  apps/dotcom/client/package.json
  apps/dotcom/sync-worker/package.json
  apps/dotcom/sync-worker/src/postgres.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/zero-cache/flyio.template.toml
  apps/dotcom/zero-cache/package.json
  packages/dotcom-shared/package.json
  sst.config.ts
  yarn.lock
Labels: bugfix, preview-sst-zero-deploy-please

#5980 Increase view syncer cpu.
  sst.config.ts
Labels: improvement

#5967 ENG 3023 Add double-click to fit frame to content on edges and corners
  apps/docs/content/getting-started/releases-versioning.mdx
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/lib/utils/frames/frames.ts
Labels: feature
