Repository tldraw/tldraw, pull requests merged in 2025-01, with the labels that each got.

#5167 Update docs.
  apps/dotcom/client/README.md
Labels: improvement

#5169 Create SECURITY.md
  SECURITY.md
Labels: other

#5172 Fix relative CSS import rules failing to be fetched
  packages/editor/src/lib/exports/FontEmbedder.ts
Labels: bugfix

#5168 Allow expandSelectionOutlinePx to return a Box
  packages/editor/api-report.md
  packages/editor/src/lib/components/default-components/DefaultSelectionForeground.tsx
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
Labels: api

#5176 Fix max image dimension prop not getting applied.
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: bugfix

#5143 embeds: fix Gist; fix Val Town; add support for <iframe>
  apps/dotcom/client/src/utils/csp.ts
  packages/tldraw/src/lib/defaultEmbedDefinitions.ts
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  packages/tldraw/src/lib/utils/embeds/embeds.test.ts
Labels: bugfix, improvement

#5170 Gist embed: restrict the url to a more strict format
  packages/tldraw/src/lib/defaultEmbedDefinitions.ts
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
  packages/tldraw/src/lib/utils/embeds/embeds.test.ts
Labels: bugfix

#5140 Move to kysely
  apps/dotcom/sync-worker/package.json
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/getFetchEverythingSql.ts
  apps/dotcom/sync-worker/src/getPostgres.ts
  apps/dotcom/sync-worker/src/postgres.ts
  internal/scripts/check-worker-bundle.ts
  internal/scripts/workers/dev.ts
  packages/dotcom-shared/src/tlaSchema.ts
  yarn.lock
Labels: improvement

#5161 Provided an ability to select multiple arrow labels using ctrl/cmd key
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingArrowLabel.ts
Labels: bugfix

#5182 Fix lint.
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingArrowLabel.ts
Labels: bugfix

#5171 Fix some video issues on the blog
  apps/docs/components/content/video.tsx
  apps/docs/content/blog/make-real-the-story-so-far.mdx
  apps/docs/content/blog/release-notes-20240418.mdx
Labels: other

#5189 remove huppy-bot
  internal/huppy/.gitignore
  internal/huppy/Dockerfile
  internal/huppy/README.md
  internal/huppy/fly.toml
  internal/huppy/next.config.js
  internal/huppy/package.json
  internal/huppy/pages/_app.tsx
  internal/huppy/pages/api/dev/getDelivery.ts
  internal/huppy/pages/api/dev/redeliver.ts
  internal/huppy/pages/api/dev/simulate.ts
  internal/huppy/pages/api/github-event.ts
  internal/huppy/pages/api/on-release.ts
  internal/huppy/pages/deliveries.tsx
  internal/huppy/src/Queue.ts
  internal/huppy/src/comment.tsx
  internal/huppy/src/config.tsx
  internal/huppy/src/ctx.tsx
  internal/huppy/src/flow.tsx
  internal/huppy/src/flows/collectClaSignatures.tsx
  internal/huppy/src/flows/enforcePrLabels.tsx
  internal/huppy/src/flows/index.tsx
  internal/huppy/src/flows/standaloneExamplesBranch.tsx
  internal/huppy/src/getCtxForOrg.tsx
  internal/huppy/src/octokit.ts
  internal/huppy/src/repo.ts
  internal/huppy/src/reportError.tsx
  internal/huppy/src/requestWrapper.tsx
  internal/huppy/src/utils.ts
  internal/huppy/tsconfig.json
  internal/scripts/publish-new.ts
  internal/scripts/publish-patch.ts
  yarn.lock
Labels: other

#5135 pass custom migrations to useLocalStore
  packages/editor/src/lib/TldrawEditor.tsx
Labels: bugfix

#5180 Show quick actions panel above toolbar when not logged in.
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
Labels: bugfix

#5204 Sdk hotfix: pass custom migrations to useLocalStore (#5135)
  packages/editor/src/lib/TldrawEditor.tsx
Labels: bugfix

#5184 [botcom] Translation tweaks
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaErrorContent/TlaErrorContent.tsx
  apps/dotcom/client/src/tla/utils/i18n.tsx
Labels: other

#5206 add latest strings
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
Labels: other

#5208 i18n: augment the list so that we hit the top 40 languages
  assets/translations/bn.json
  assets/translations/el.json
  assets/translations/gu.json
  assets/translations/km.json
  assets/translations/kn.json
  assets/translations/languages.json
  assets/translations/ml.json
  assets/translations/mr.json
  assets/translations/ms.json
  assets/translations/nl.json
  assets/translations/pa.json
  assets/translations/ta.json
  assets/translations/tl.json
  assets/translations/ur.json
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/editor/api-report.md
  packages/tlschema/api-report.md
  packages/tlschema/src/translations/languages.ts
Labels: feature

#5212 i18n: rename two locale codes
  assets/translations/gu-in.json
  assets/translations/km-kh.json
  assets/translations/languages.json
  assets/translations/main.json
  packages/assets/imports.js
  packages/assets/imports.vite.js
  packages/assets/selfHosted.js
  packages/assets/types.d.ts
  packages/assets/urls.js
  packages/editor/api-report.md
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/translations/languages.ts
Labels: bugfix

#5213 strings: rm some old ones, use nice apostrophes
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: other

#5207 [botcom] Use clerk cookie to control routing
  apps/dotcom/client/e2e/fixtures/HomePage.ts
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/pages/tla-opt-in.tsx
  apps/dotcom/client/src/pages/tla-override.tsx
  apps/dotcom/client/src/routeDefs.ts
  apps/dotcom/client/src/routes.test.tsx
  apps/dotcom/client/src/routes.tsx
Labels: other

#5181 Allow slurping of legacy multiplayer routes.
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopRightPanel.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarCreateFileButton.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/client/src/tla/pages/file.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  packages/dotcom-shared/src/types.ts
Labels: improvement

#5216 send extra data to sentry properly
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
Labels: other

#5214 close sockets on 'close' event
  packages/sync-core/src/lib/RoomSession.ts
  packages/sync-core/src/lib/TLSyncRoom.ts
Labels: improvement

#5217 [botcom] save document name on blur in side bar
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarRenameInline.tsx
Labels: other

#5223 fix clipboard file upload
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: bugfix

#5220 Set up posthog
  .github/workflows/deploy-dotcom.yml
  apps/dotcom/README.md
  apps/dotcom/client/package.json
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/components/Links.tsx
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/components/MultiplayerEditor.tsx
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaAppMenuGroup/TlaAppMenuGroup.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarCookieConsent.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarUserLink.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/components/TlaSwitch/TlaSwitch.tsx
  apps/dotcom/client/src/tla/components/TlaSwitch/switch.module.css
  apps/dotcom/client/src/tla/components/dialogs/TlaManageCookiesDialog.tsx
  apps/dotcom/client/src/tla/components/dialogs/dialogs.module.css
  apps/dotcom/client/src/tla/components/tla-menu/tla-menu.tsx
  apps/dotcom/client/src/tla/hooks/useUser.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
  apps/dotcom/client/src/tla/utils/i18n.tsx
  apps/dotcom/client/src/utils/posthog.tsx
  apps/dotcom/client/src/utils/trackAnalyticsEvent.ts
  apps/dotcom/sync-worker/src/config.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/zero-cache/migrations/009_add_allow_analytics_cookie.sql
  packages/dotcom-shared/src/tlaSchema.ts
  yarn.lock
Labels: other

#5219 worker debug logging
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/pages/worker-debug-tail.tsx
  apps/dotcom/sync-worker/src/Logger.ts
  apps/dotcom/sync-worker/src/TLLoggerDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/testRoutes.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/src/utils/durableObjects.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/sync-worker/wrangler.toml
  packages/worker-shared/src/sentry.ts
Labels: other

#5229 improve cookie microcopy
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarCookieConsent.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaManageCookiesDialog.tsx
Labels: other

#5230 [botcom] don't broadcast mutation rejections
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
Labels: other

#5201 Added toast instead of throwing an error for the case when the amount…
  assets/translations/main.json
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: bugfix

#5221 error logging: add more context for errors
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
Labels: improvement

#5234 i18n: fix download workflow
  .github/workflows/i18n-download-strings.yml
Labels: other

#5237 i18n: fix workflow perms
  .github/workflows/i18n-download-strings.yml
Labels: other

#5233 Always override session state on initial load
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  packages/editor/src/lib/config/createTLStore.ts
  packages/editor/src/lib/utils/sync/TLLocalSyncClient.ts
Labels: bugfix

#5236 Rename files in window.prompt on mobile
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/client/src/tla/utils/getIsCoarsePointer.tsx
Labels: other

#5114 Exports DX pass
  .yarn/patches/canvas-size-npm-2.0.0-822398a242.patch
  apps/docs/content/docs/editor.mdx
  apps/dotcom/client/e2e/tests/sharing.spec.ts
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaExportTab.tsx
  apps/dotcom/client/src/utils/multiplayerAssetStore.ts
  apps/examples/e2e/tests/test-api.spec.ts
  apps/examples/src/examples/basic/BasicExample.tsx
  apps/examples/src/examples/export-canvas-as-image/ExportCanvasImageExample.tsx
  apps/examples/src/examples/export-canvas-as-image/README.md
  apps/examples/src/examples/export-canvas-settings/ExportCanvasImageSettingsExample.tsx
  apps/examples/src/examples/export-canvas-settings/README.md
  apps/examples/src/examples/image-annotator/ImageAnnotationEditor.tsx
  apps/examples/src/examples/pdf-editor/ExportPdfButton.tsx
  apps/examples/src/examples/screenshot-tool/ScreenshotTool/childStates/Dragging.ts
  apps/examples/src/misc/end-to-end.tsx
  apps/examples/vite.config.ts
  assets/translations/main.json
  eslint.config.mjs
  lerna.json
  package.json
  packages/editor/api-report.md
  packages/editor/package.json
  packages/editor/src/index.ts
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/SvgExportContext.tsx
  packages/editor/src/lib/editor/types/misc-types.ts
  packages/editor/src/lib/exports/exportToSvg.tsx
  packages/editor/src/lib/exports/getSvgAsImage.ts
  packages/editor/src/lib/exports/getSvgJsx.tsx
  packages/editor/src/lib/utils/browserCanvasMaxSize.ts
  packages/sync/src/useSyncDemo.ts
  packages/tldraw/api-report.md
  packages/tldraw/package.json
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/TldrawImage.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/useImageOrVideoAsset.ts
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/useCopyAs.ts
  packages/tldraw/src/lib/ui/hooks/useExportAs.ts
  packages/tldraw/src/lib/ui/hooks/useFlatten.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/lib/utils/assets/assets.ts
  packages/tldraw/src/lib/utils/export/copyAs.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/tldraw/src/lib/utils/export/exportAs.ts
  packages/tldraw/src/test/commands/__snapshots__/getSvgString.test.ts.snap
  packages/tldraw/src/test/commands/getSvgString.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
  yarn.lock
Labels: api

#5242 i18n: workaround Lokalise's broken plural system
  .github/workflows/i18n-download-strings.yml
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
Labels: other

#5249 i18n: fix up locale messup for lokalise
  assets/translations/gu-in.json
  assets/translations/gu_IN.json
  assets/translations/hi-in.json
  assets/translations/hi_IN.json
  assets/translations/km-kh.json
  assets/translations/km_KH.json
  assets/translations/ko-kr.json
  assets/translations/ko_KR.json
  assets/translations/pt-br.json
  assets/translations/pt-pt.json
  assets/translations/pt_BR.json
  assets/translations/pt_PT.json
  assets/translations/zh-cn.json
  assets/translations/zh-tw.json
  assets/translations/zh_CN.json
  assets/translations/zh_TW.json
Labels: other

#5252 Use sign up button on /preview
  apps/dotcom/client/src/pages/tla-opt-in.tsx
Labels: other

#5218 Asset uploads
  apps/dotcom/client/src/components/MultiplayerEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaLegacyFileEditor.tsx
  apps/dotcom/client/src/tla/utils/slurping.tsx
  apps/dotcom/client/src/utils/cloneAssetForShare.ts
  apps/dotcom/client/src/utils/config.ts
  apps/dotcom/client/src/utils/multiplayerAssetStore.test.ts
  apps/dotcom/client/src/utils/multiplayerAssetStore.ts
  apps/dotcom/image-resize-worker/src/worker.ts
  apps/dotcom/image-resize-worker/wrangler.toml
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/routes/tla/uploads.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/src/utils/tla/getAuth.ts
  apps/dotcom/sync-worker/src/utils/tla/permissions.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/sync-worker/wrangler.toml
  apps/dotcom/zero-cache/migrations/010_add_asset_info.sql
  apps/examples/src/examples/hosted-images/HostedImagesExample.tsx
  internal/scripts/deploy-dotcom.ts
  internal/scripts/lib/deploy.ts
  packages/dotcom-shared/src/tlaSchema.ts
  packages/editor/api-report.md
  packages/editor/src/lib/config/createTLStore.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useLocalStore.ts
  packages/sync-core/src/lib/TLSocketRoom.ts
  packages/sync/src/useSyncDemo.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/TLStore.ts
Labels: improvement

#5253 Focus file input on create/duplicate
  apps/dotcom/client/e2e/fixtures/HomePage.ts
  apps/dotcom/client/e2e/fixtures/Sidebar.ts
  apps/dotcom/client/e2e/tests/homepage.spec.ts
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarCreateFileButton.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarRenameInline.tsx
  apps/dotcom/client/src/tla/hooks/useUser.tsx
  apps/dotcom/client/src/tla/providers/FileInputFocusProvider.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiInput.tsx
Labels: other

#5260 Remove unused env vars
  apps/dotcom/client/scripts/dev-app.ts
  apps/dotcom/sync-worker/src/types.ts
  internal/scripts/deploy-dotcom.ts
Labels: improvement

#5262 Fix the blue text color on mobile
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
Labels: bugfix

#5261 Improve focus mode button position and focus mode interaction with the sidebar
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarToggle.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarToggleMobile.tsx
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
  apps/dotcom/client/src/tla/pages/file.tsx
  apps/dotcom/client/src/tla/pages/legacy-history-snapshot.tsx
  apps/dotcom/client/src/tla/pages/legacy-history.tsx
  apps/dotcom/client/src/tla/pages/legacy-readonly-old.tsx
  apps/dotcom/client/src/tla/pages/legacy-readonly.tsx
  apps/dotcom/client/src/tla/pages/legacy-room.tsx
  apps/dotcom/client/src/tla/pages/legacy-snapshot.tsx
  apps/dotcom/client/src/tla/styles/tla.css
  apps/dotcom/client/src/tla/utils/local-session-state.ts
Labels: improvement

#5263 Welcome dialog for preview users
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/hooks/usePromise.ts
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaEditor/PreviewWelcomeDialog.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/utils/local-session-state.ts
  apps/dotcom/client/src/tla/utils/slurping.tsx
  apps/examples/src/examples/ui-components-hidden/UiComponentsHiddenExample.tsx
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/Dialogs.tsx
  packages/tldraw/src/lib/ui/components/Toasts.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiDialog.tsx
  packages/tldraw/src/lib/ui/context/components.tsx
  packages/tldraw/src/lib/ui/context/dialogs.tsx
  packages/tldraw/src/lib/ui/context/toasts.tsx
Labels: api

#5266 fixes
  apps/dotcom/client/package.json
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/pages/tla-opt-in.tsx
Labels: other

#5269 Fix sentry error
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
Labels: other

#5270 Fix an issue with legacy assets not getting their urls changed when they get slurped.
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/types.ts
  internal/scripts/deploy-dotcom.ts
Labels: bugfix

#5271 Make the bottom padding the same as other ones.
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
Labels: improvement

#5272 Prevent slurping for some cases.
  apps/dotcom/client/src/tla/components/TlaEditor/PreviewWelcomeDialog.tsx
Labels: improvement

#5268 Use sign in instead of sign up.
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
Labels: improvement

#5255 Move examples from CodeSandbox to StackBlitz
  .github/ISSUE_TEMPLATE/bug_report.yml
  apps/docs/content/blog/announcing-tldraw-sync.mdx
  apps/docs/content/blog/release-notes-20230324.mdx
  apps/docs/content/docs/collaboration.mdx
  apps/docs/content/getting-started/quick-start.mdx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
Labels: other

#5276 Fix url
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
Labels: bugfix

#5277 fix bottom padding again
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
Labels: other

#5278 Update link
  apps/dotcom/client/src/tla/components/TlaAppMenuGroup/TlaAppMenuGroup.tsx
Labels: other

#5279 hard code context id for dialogs
  packages/tldraw/src/lib/ui/context/TldrawUiContextProvider.tsx
Labels: other

#5211 Fix for resizing snapshot bug
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
Labels: bugfix

#5280 David/int 677 guests see slurp failure modal
  apps/dotcom/client/src/components/LoginRedirectPage/LoginRedirectPage.tsx
  apps/dotcom/client/src/main.tsx
  apps/dotcom/client/src/pages/tla-opt-in.tsx
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/PreviewWelcomeDialog.tsx
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/utils/slurping.tsx
Labels: other

#5158 Style changing duration reduced from 2 to 1 second
  packages/editor/src/lib/editor/Editor.ts
Labels: improvement

#5287 Tooltip tweaks
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/components/TlaTooltip/TlaTooltip.tsx
  apps/dotcom/client/src/tla/components/TlaTooltip/tooltip.module.css
  apps/dotcom/client/src/tla/styles/tla.css
Labels: other

#5286 Update editor.mdx
  apps/docs/content/docs/editor.mdx
Labels: other

#5274 edit menu: don't disable if not in select tool
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
Labels: bugfix

#5288 Move account menu side to end
  apps/dotcom/client/src/tla/components/TlaAccountMenu/TlaAccountMenu.tsx
Labels: other

#5290 fix 2 bad translations from Lokalise
  apps/dotcom/client/public/tla/locales-compiled/ar.json
  apps/dotcom/client/public/tla/locales-compiled/bn.json
  apps/dotcom/client/public/tla/locales-compiled/ca.json
  apps/dotcom/client/public/tla/locales-compiled/cs.json
  apps/dotcom/client/public/tla/locales-compiled/da.json
  apps/dotcom/client/public/tla/locales-compiled/de.json
  apps/dotcom/client/public/tla/locales-compiled/el.json
  apps/dotcom/client/public/tla/locales-compiled/es.json
  apps/dotcom/client/public/tla/locales-compiled/fa.json
  apps/dotcom/client/public/tla/locales-compiled/fi.json
  apps/dotcom/client/public/tla/locales-compiled/fr.json
  apps/dotcom/client/public/tla/locales-compiled/gl.json
  apps/dotcom/client/public/tla/locales-compiled/gu-in.json
  apps/dotcom/client/public/tla/locales-compiled/he.json
  apps/dotcom/client/public/tla/locales-compiled/hi-in.json
  apps/dotcom/client/public/tla/locales-compiled/hr.json
  apps/dotcom/client/public/tla/locales-compiled/hu.json
  apps/dotcom/client/public/tla/locales-compiled/id.json
  apps/dotcom/client/public/tla/locales-compiled/it.json
  apps/dotcom/client/public/tla/locales-compiled/ja.json
  apps/dotcom/client/public/tla/locales-compiled/km-kh.json
  apps/dotcom/client/public/tla/locales-compiled/kn.json
  apps/dotcom/client/public/tla/locales-compiled/ko-kr.json
  apps/dotcom/client/public/tla/locales-compiled/ml.json
  apps/dotcom/client/public/tla/locales-compiled/mr.json
  apps/dotcom/client/public/tla/locales-compiled/ms.json
  apps/dotcom/client/public/tla/locales-compiled/ne.json
  apps/dotcom/client/public/tla/locales-compiled/nl.json
  apps/dotcom/client/public/tla/locales-compiled/no.json
  apps/dotcom/client/public/tla/locales-compiled/pa.json
  apps/dotcom/client/public/tla/locales-compiled/pl.json
  apps/dotcom/client/public/tla/locales-compiled/pt-br.json
  apps/dotcom/client/public/tla/locales-compiled/pt-pt.json
  apps/dotcom/client/public/tla/locales-compiled/ro.json
  apps/dotcom/client/public/tla/locales-compiled/ru.json
  apps/dotcom/client/public/tla/locales-compiled/sl.json
  apps/dotcom/client/public/tla/locales-compiled/so.json
  apps/dotcom/client/public/tla/locales-compiled/sv.json
  apps/dotcom/client/public/tla/locales-compiled/ta.json
  apps/dotcom/client/public/tla/locales-compiled/te.json
  apps/dotcom/client/public/tla/locales-compiled/th.json
  apps/dotcom/client/public/tla/locales-compiled/tl.json
  apps/dotcom/client/public/tla/locales-compiled/tr.json
  apps/dotcom/client/public/tla/locales-compiled/uk.json
  apps/dotcom/client/public/tla/locales-compiled/ur.json
  apps/dotcom/client/public/tla/locales-compiled/vi.json
  apps/dotcom/client/public/tla/locales-compiled/zh-cn.json
  apps/dotcom/client/public/tla/locales-compiled/zh-tw.json
  apps/dotcom/client/public/tla/locales/gl.json
  apps/dotcom/client/public/tla/locales/so.json
Labels: other

#5297 e2e: fix tests now that it has a translations
  apps/dotcom/client/e2e/fixtures/Editor.ts
  apps/dotcom/client/e2e/fixtures/Sidebar.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarUserLink.tsx
Labels: other

#5292 Revert "Fix for resizing snapshot bug (#5211)"
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
Labels: other

#5137 Add an onCrop handler to ShapeUtil
  apps/examples/e2e/tests/export-snapshots.spec.tsx
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/shared/crop.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/Cropping.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/TranslatingCrop.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/crop_helpers.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/crop-constants.ts
  packages/tldraw/src/test/crop.test.ts
  packages/tldraw/src/test/cropping.test.ts
  packages/tlschema/api-report.md
  packages/tlschema/src/index.ts
  packages/tlschema/src/shapes/ShapeWithCrop.ts
  packages/tlschema/src/shapes/TLImageShape.ts
Labels: api

#5296 Fix an error when embed util is not present.
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/ui/hooks/useGetEmbedDefinition.ts
Labels: bugfix

#5273 Add editor option to allow sticky note resizing by scale
  apps/examples/src/examples/resize-note/README.md
  apps/examples/src/examples/resize-note/ResizeNoteExample.tsx
  packages/editor/api-report.md
  packages/editor/editor.css
  packages/editor/src/index.ts
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/shared/resizeScaled.ts
  packages/editor/src/lib/options.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/resizeScaled.ts
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingHandle.ts
  packages/tldraw/src/test/resizing.test.ts
Labels: api

#5300 Use the uncropped width when requesting an image shape asset
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/crop.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/crop_helpers.ts
Labels: bugfix

#5302 Prevent radix dialog warning
  apps/dotcom/client/src/tla/components/TlaEditor/PreviewWelcomeDialog.tsx
Labels: other

#5303 fix pasting text/plain with keyboard shortcut
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: bugfix

#5304 fix copy/export as PNG
  apps/dotcom/client/src/utils/csp.ts
Labels: other

#5306 post release backend error handling
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/types.ts
Labels: other

#5307 hotfix backend error handling
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/types.ts
Labels: other

#5309 Fix images in preview builds
  internal/scripts/deploy-dotcom.ts
Labels: bugfix

#5310 Don't nullify cache
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/PreviewWelcomeDialog.tsx
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
Labels: bugfix

#5311 Cmd+click on active file opens in new tab
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
Labels: other

#5314 Add `/new` route for file creation.
  apps/dotcom/client/src/pages/tla-new.tsx
  apps/dotcom/client/src/routeDefs.ts
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
Labels: improvement

#5316 tweak pricing copy
  apps/docs/components/marketing/pricing-section.tsx
  package.json
Labels: other

#5319 Emit a before-event from Editor
  packages/editor/api-report.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/emit-types.ts
Labels: api

#5298 separately export default external content/asset handlers
  apps/dotcom/client/src/components/SneakyOnDropOverride.ts
  apps/dotcom/client/src/tla/components/TlaEditor/sneaky/SneakyFileDropHandler.tsx
  apps/examples/src/examples/exploded/ExplodedExample.tsx
  apps/examples/src/examples/external-content-sources/ExternalContentSourcesExample.tsx
  apps/vscode/editor/src/utils/bookmarks.ts
  package.json
  packages/editor/api-report.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/external-content.ts
  packages/tldraw/api-report.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: api

#5322 Unify the menus (logged in vs not logged in).
  apps/dotcom/client/src/tla/components/TlaAppMenuGroup/TlaAppMenuGroup.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
Labels: improvement

#5323 Fix the border around the guest icon in Safari
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/client/styles/globals.css
Labels: bugfix

#5324 Public preview opt-in
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/components/MultiplayerEditor.tsx
  apps/dotcom/client/src/components/preview-stuff.tsx
Labels: other

#5331 add analytics event for clicking the preview button
  apps/dotcom/client/src/components/preview-stuff.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
Labels: other

#5329 Disable rename dialog on file create on mobile
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarCreateFileButton.tsx
  apps/dotcom/client/src/tla/utils/local-session-state.ts
Labels: other

#5325 Combined sign in/up for dotcom
  apps/dotcom/client/package.json
  apps/dotcom/client/src/components/preview-stuff.tsx
  apps/dotcom/client/src/main.tsx
  apps/dotcom/client/src/pages/tla-opt-in.tsx
  apps/dotcom/client/src/routes.test.tsx
  yarn.lock
Labels: other

#5328 prettier: reformat with new package updates
  assets/translations/ar.json
  assets/translations/bn.json
  assets/translations/ca.json
  assets/translations/cs.json
  assets/translations/da.json
  assets/translations/de.json
  assets/translations/el.json
  assets/translations/es.json
  assets/translations/fa.json
  assets/translations/fi.json
  assets/translations/fr.json
  assets/translations/gl.json
  assets/translations/gu-in.json
  assets/translations/he.json
  assets/translations/hi-in.json
  assets/translations/hr.json
  assets/translations/hu.json
  assets/translations/id.json
  assets/translations/it.json
  assets/translations/ja.json
  assets/translations/km-kh.json
  assets/translations/kn.json
  assets/translations/ko-kr.json
  assets/translations/ml.json
  assets/translations/mr.json
  assets/translations/ms.json
  assets/translations/ne.json
  assets/translations/nl.json
  assets/translations/no.json
  assets/translations/pa.json
  assets/translations/pl.json
  assets/translations/pt-br.json
  assets/translations/pt-pt.json
  assets/translations/ro.json
  assets/translations/ru.json
  assets/translations/sl.json
  assets/translations/so.json
  assets/translations/sv.json
  assets/translations/ta.json
  assets/translations/te.json
  assets/translations/th.json
  assets/translations/tl.json
  assets/translations/tr.json
  assets/translations/uk.json
  assets/translations/ur.json
  assets/translations/vi.json
  assets/translations/zh-cn.json
  assets/translations/zh-tw.json
Labels: other

#5327 Fix vscode publishing.
  apps/vscode/extension/package.json
Labels: bugfix

#5334 only accept socket connections when upgrade header is set
  apps/dotcom/sync-worker/src/worker.ts
Labels: bugfix

#5333 fix duplicating + publishing rooms with big snapshots
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/utils/durableObjects.ts
  apps/dotcom/sync-worker/src/utils/tla/getCurrentSerializedRoomSnapshot.ts
Labels: bugfix

#5335 Make sure that pinned files don't take precedence.
  apps/dotcom/client/src/tla/app/TldrawApp.ts
Labels: bugfix
