Repository tldraw/tldraw, pull requests merged in 2025-03, with the labels that each got.

#5523 fix file extension for downloads
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
Labels: other

#5524 disable full-fat copy-as-svg on chrome
  packages/tldraw/src/lib/utils/clipboard.ts
Labels: other

#5530 Fix guest files.
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
Labels: bugfix

#5533 pull writing image/svg to clipboard
  packages/tldraw/src/lib/utils/clipboard.ts
Labels: bugfix

#5531 Add a tests for guest files
  apps/dotcom/client/e2e/tests/sharing.spec.ts
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
Labels: improvement

#5544 remove import from core-js
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix

#5545 fix pasting files in safari
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: bugfix

#5549 algolia: add analytics
  apps/docs/components/search/SearchAutocomplete.tsx
  apps/docs/components/search/index.tsx
Labels: other

#5525 media: extract base64 assets from .tldr files
  packages/editor/src/lib/utils/browserCanvasMaxSize.ts
  packages/tldraw/src/lib/utils/tldr/file.ts
  packages/utils/src/lib/bind.ts
Labels: improvement

#5553 Revert "Revert "Fix for resizing snapshot bug (#5211)" (#5292)"
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
Labels: bugfix

#5532 Make better use of replicator history
  apps/dotcom/sync-worker/package.json
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/getFetchEverythingSql.ts
  yarn.lock
Labels: other

#5548 setup pgbouncer for local dev (fix flaky e2e tests?)
  apps/dotcom/client/e2e/fixtures/Database.ts
  apps/dotcom/client/e2e/fixtures/Sidebar.ts
  apps/dotcom/client/playwright.config.ts
  apps/dotcom/client/src/tla/app/zero-polyfill.ts
  apps/dotcom/sync-worker/wrangler.toml
  apps/dotcom/zero-cache/.env
  apps/dotcom/zero-cache/clean.sh
  apps/dotcom/zero-cache/docker/docker-compose.yml
  apps/dotcom/zero-cache/docker/pgbouncer.ini
  apps/dotcom/zero-cache/docker/userlist.txt
  apps/dotcom/zero-cache/package.json
Labels: bugfix

#5562 [dotcom] fix data leaking between preview branches
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/types.ts
Labels: other

#5565 fix reparentshapes preserve order
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/commands/reparentShapesById.test.ts
Labels: bugfix

#5563 Add some randomness to prevent this happening in sync for online users.
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
Labels: improvement

#5568 rich text: fix links getting in the way of some tools and android selection
  apps/examples/e2e/tests/test-rich-text.spec.ts
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/shared/RichTextLabel.tsx
  packages/tldraw/src/lib/shapes/text/RichTextArea.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/LinkEditor.tsx
Labels: bugfix

#5557 Migrate newsletter form to hubspot
  apps/docs/components/common/newsletter-signup.tsx
  apps/docs/scripts/submit-newsletter-signup.ts
Labels: improvement

#5569 Hotfix: Migrate newsletter form to hubspot (#5557)
  apps/docs/components/common/newsletter-signup.tsx
  apps/docs/scripts/submit-newsletter-signup.ts
Labels: improvement

#5536 i18n: add validation and auto-placing of orders
  .github/workflows/i18n-download-strings.yml
  internal/scripts/i18n-upload-strings.ts
  package.json
  yarn.lock
Labels: other

#5571 i18n: fix up latest upload pipeline missing env vars
  .github/workflows/i18n-upload-strings.yml
  internal/scripts/i18n-upload-strings.ts
Labels: other

#5552 Display BrokenAssetIcon when file upload fails
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/shared/useImageOrVideoAsset.ts
Labels: bugfix

#5573 Whats new blog post
  apps/docs/content/authors.json
  apps/docs/content/blog/whats-new-2025.mdx
  apps/docs/content/blog/whats-new-in-tldraw.mdx
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/docs/public/images/blog/whats-new/arrow-padding.gif
  apps/docs/public/images/blog/whats-new/bring-forward.gif
  apps/docs/public/images/blog/whats-new/coming-soon.gif
  apps/docs/public/images/blog/whats-new/drag-bookmark.gif
  apps/docs/public/images/blog/whats-new/dynamic-arrow-labels.gif
  apps/docs/public/images/blog/whats-new/export.gif
  apps/docs/public/images/blog/whats-new/flip-image.gif
  apps/docs/public/images/blog/whats-new/hero.gif
  apps/docs/public/images/blog/whats-new/last-geo-tool.gif
  apps/docs/public/images/blog/whats-new/lock-text.gif
  apps/docs/public/images/blog/whats-new/multi-select.gif
  apps/docs/public/images/blog/whats-new/paste-at-point.gif
  apps/docs/public/images/blog/whats-new/publish.gif
  apps/docs/public/images/blog/whats-new/rich-text-toolbar.gif
  apps/docs/public/images/blog/whats-new/rich-text.gif
  apps/docs/public/images/blog/whats-new/share.gif
  apps/docs/public/images/blog/whats-new/sidebar.gif
  apps/docs/public/images/blog/whats-new/smart-layout.gif
  apps/docs/public/images/blog/whats-new/snap-to-grid.gif
  apps/docs/public/images/blog/whats-new/space-bar.gif
  apps/docs/public/images/blog/whats-new/tiny-text.gif
  apps/docs/public/images/blog/whats-new/x-box.png
Labels: other

#5575 Fixes to the new blog post
  apps/docs/content/blog/whats-new-2025.mdx
Labels: other

#5579 Fix broken people menu
  apps/examples/src/styles.css
Labels: bugfix

#5593 export: fix style embedding for foreignObjects in Firefox
  packages/editor/src/lib/exports/StyleEmbedder.ts
  packages/tldraw/src/test/commands/__snapshots__/getSvgString.test.ts.snap
Labels: bugfix

#5542 CTA analytics
  FAQ.md
  README.md
  apps/bemo-worker/README.md
  apps/docs/README.md
  apps/docs/components/blog/blog-post-header.tsx
  apps/docs/components/blog/blog-table-of-contents.tsx
  apps/docs/content/blog/announcing-tldraw-sync.mdx
  apps/docs/content/blog/make-real-the-story-so-far.mdx
  apps/docs/content/blog/release-notes-20230331.mdx
  apps/docs/content/blog/release-notes-20230414.mdx
  apps/docs/content/blog/release-notes-20240118.mdx
  apps/docs/content/blog/release-notes-20240208.mdx
  apps/docs/content/blog/release-notes-20240314.mdx
  apps/docs/content/blog/release-notes-20240502.mdx
  apps/docs/content/blog/release-notes-20240620.mdx
  apps/docs/content/blog/tldraw-raised-another-2m.mdx
  apps/docs/content/blog/whats-new-in-tldraw.mdx
  apps/docs/content/community/license.mdx
  apps/dotcom/asset-upload-worker/README.md
  apps/dotcom/client/README.md
  apps/dotcom/client/src/components/Links.tsx
  apps/dotcom/client/src/tla/components/TlaAppMenuGroup/TlaAppMenuGroup.tsx
  apps/dotcom/image-resize-worker/README.md
  apps/dotcom/sync-worker/README.md
  apps/examples/README.md
  apps/examples/src/ExamplePage.tsx
  apps/vscode/README.md
  apps/vscode/editor/README.md
  apps/vscode/extension/README.md
  internal/apps-script/README.md
  internal/dev-tools/README.md
  internal/health-worker/README.md
  packages/assets/README.md
  packages/dotcom-shared/README.md
  packages/editor/README.md
  packages/editor/src/lib/license/Watermark.tsx
  packages/namespaced-tldraw/README.md
  packages/state-react/README.md
  packages/state/README.md
  packages/store/README.md
  packages/sync-core/README.md
  packages/sync/README.md
  packages/tldraw/README.md
  packages/tlschema/README.md
  packages/utils/README.md
  packages/validate/README.md
  packages/worker-shared/README.md
  templates/nextjs/README.md
  templates/simple-server-example/README.md
  templates/sync-cloudflare/README.md
  templates/vite/README.md
Labels: other

#5594 Redirect FAQ to notion page
  FAQ.md
Labels: other

#5591 Add state packages to reference
  apps/docs/content/sections.json
  apps/docs/scripts/lib/createApiMarkdown.ts
  apps/docs/scripts/lib/package-list.ts
Labels: other

#5598 Fix header width
  apps/docs/components/marketing/hero-section.tsx
Labels: other

#5587 Add eslint rule for "whilst"
  eslint.config.mjs
  internal/scripts/lib/eslint-plugin.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/exports/ExportDelay.tsx
Labels: other

#5567 Use ImmutableMap inside AtomMap
  packages/store/src/lib/AtomMap.ts
  packages/store/src/lib/ImmutableMap.ts
  packages/store/src/lib/test/AtomMap.test.ts
  packages/tldraw/src/test/bindings.test.tsx
Labels: bugfix

#5602 Example: create arrow between shapes
  apps/examples/src/examples/create-arrow/CreateArrowExample.tsx
  apps/examples/src/examples/create-arrow/README.md
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/Editor.ts
Labels: other

#5606 Fix API links for state packages
  packages/state-react/src/lib/useAtom.ts
  packages/state-react/src/lib/useComputed.ts
  packages/state-react/src/lib/useValue.ts
  packages/state/src/lib/Atom.ts
  packages/state/src/lib/Computed.ts
  packages/state/src/lib/EffectScheduler.ts
  packages/state/src/lib/types.ts
Labels: other

#5616 debug: move hard reset option to avoid fat finger
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenuContent.tsx
Labels: other

#5617 docs: fix sorting for release history
  apps/docs/content/getting-started/releases-versioning.mdx
  apps/docs/scripts/lib/fetchReleases.ts
Labels: other

#5607 security: provide a way to pass through `nonce` to the editor
  apps/dotcom/client/src/utils/csp.ts
  packages/editor/api-report.api.md
  packages/editor/src/lib/exports/getSvgJsx.tsx
  packages/editor/src/lib/license/Watermark.tsx
  packages/editor/src/lib/options.ts
  packages/store/src/lib/ImmutableMap.ts
  packages/tldraw/src/lib/ui/components/Toolbar/OverflowingToolbar.tsx
Labels: feature

#5618 fix header truncation on safari
  apps/dotcom/client/src/tla/styles/tla.css
Labels: other

#5624 toolbar: tweak selected color
  packages/tldraw/src/lib/ui.css
Labels: other

#5626 fonts: fix up invalid google font url
  templates/simple-server-example/src/client/index.css
  templates/sync-cloudflare/client/index.css
  templates/vite/src/index.css
Labels: bugfix

#5627 template: fix Bun server image uploads
  templates/simple-server-example/src/server/server.bun.ts
  templates/simple-server-example/yarn.lock
Labels: bugfix

#5614 'New user' -> 'Guest user' (dotcom only)
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaEditor/editor-messages.ts
  apps/dotcom/client/src/tla/components/TlaEditor/useFileEditorOverrides.ts
  assets/translations/main.json
  packages/editor/api-report.api.md
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/SharePanel/PeopleMenu.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/PeopleMenuAvatar.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/PeopleMenuItem.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/UserPresenceEditor.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/test/TLUserPreferences.test.ts
  packages/tlschema/src/createPresenceStateDerivation.ts
Labels: improvement

#5630 embeds: add support for google maps satellite mode
  packages/tldraw/src/lib/defaultEmbedDefinitions.ts
  packages/tldraw/src/lib/utils/embeds/embeds.test.ts
Labels: improvement

#5633 fix trigger-sdk-hotfix script?
  .github/workflows/trigger-sdk-hotfix.yml
  internal/scripts/trigger-sdk-hotfix.ts
  package.json
Labels: other, docs-hotfix-please

#5635 fix checkout step
  .github/workflows/trigger-sdk-hotfix.yml
Labels: other, docs-hotfix-please

#5636 debug trigger-sdk-hotfix
  .github/workflows/trigger-sdk-hotfix.yml
  internal/scripts/trigger-sdk-hotfix.ts
Labels: other, docs-hotfix-please

#5632 a11y: make toolbar button labels better; fix missing str
  assets/translations/main.json
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiButtonPicker.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuItem.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: bugfix

#5637 fetch-depth 0 again?
  .github/workflows/trigger-sdk-hotfix.yml
Labels: other

#5638 Use correct punctuation in comments in sync.mdx
  apps/docs/content/docs/sync.mdx
Labels: other, docs-hotfix-please

#5640 trigger-sdk-hotfix refresh assets
  internal/scripts/trigger-sdk-hotfix.ts
Labels: other

#5641 Add a dot (test new docs deployment thing)
  apps/docs/content/docs/user-interface.mdx
Labels: other, docs-hotfix-please

#5643 Track embedded examples on docs site
  apps/docs/components/content/example.tsx
Labels: other

#5639 error logging for i18n-upload-strings
  internal/scripts/i18n-upload-strings.ts
Labels: other

#5647 i18n: temporarily patch order placement to avoid Lokalise bug
  internal/scripts/i18n-upload-strings.ts
Labels: other

#5648 use discord steps for trigger-sdk-hotfix script
  internal/scripts/trigger-sdk-hotfix.ts
Labels: other

#5625 Track Enter key to accept search query
  apps/docs/components/search/SearchAutocomplete.tsx
Labels: other

#5649 rich text: add `textOptions` to `<TldrawImage />`
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/TldrawImage.tsx
Labels: bugfix, sdk-hotfix-please

#5650 fonts: update outdated static assets example
  apps/examples/src/examples/static-assets/StaticAssetsExample.tsx
Labels: other

#5656 [Fix] Use adjacent shape margin option in stackShapes, packShapes
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenuContent.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/test/commands/__snapshots__/packShapes.test.ts.snap
  packages/tldraw/src/test/commands/packShapes.test.ts
  packages/tldraw/src/test/commands/stackShapes.test.ts
Labels: improvement, api

#5654 [Fix] indicators hideAll / showAll
  apps/examples/src/examples/indicators-logic/IndicatorsLogicExample.tsx
  packages/editor/api-report.api.md
  packages/editor/src/index.ts
  packages/editor/src/lib/components/default-components/DefaultShapeIndicator.tsx
  packages/editor/src/lib/components/default-components/DefaultShapeIndicators.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/canvas/TldrawShapeIndicators.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
Labels: bugfix

#5570 Don't show dismissible elements until we are sure of their status
  apps/docs/app/analytics.tsx
  apps/docs/components/common/newsletter-signup.tsx
  apps/docs/components/docs/docs-feedback-widget.tsx
  apps/docs/utils/storage.ts
  lerna.json
Labels: improvement, docs-hotfix-please

#5326 Allow embedding other multiplayer routes and also tldraw app routes
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
  apps/dotcom/client/src/tla/pages/file.tsx
  apps/examples/src/examples/interactive-shape/InteractiveShapeExample.tsx
  packages/tldraw/src/lib/defaultEmbedDefinitions.ts
Labels: improvement

#5669 Fix readme images
  templates/nextjs/README.md
  templates/vite/README.md
Labels: other

#5677 examples: make nav not do full page reload
  apps/examples/src/ExamplePage.tsx
Labels: other

#5678 script: add pretty cmd for current diff
  package.json
Labels: other

#5679 Tiny fixes to focus example guides
  apps/examples/src/examples/editor-focus/EditorFocusExample.tsx
  apps/examples/src/examples/scroll/ScrollExample.tsx
Labels: other

#5676 exports: fix Inter being embedded; reduce excessive styling
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-light-1-chromium-linux.png
  packages/editor/src/lib/exports/StyleEmbedder.ts
  packages/editor/src/lib/exports/parseCss.ts
  packages/tldraw/src/lib/shapes/shared/RichTextLabel.tsx
  packages/tldraw/src/test/commands/__snapshots__/getSvgString.test.ts.snap
Labels: bugfix, sdk-hotfix-please

#5685 fix sentry csp
  apps/dotcom/client/src/utils/csp.ts
Labels: other

#5687 upgrade yarn to 4.7
  .github/workflows/checks.yml
  apps/dotcom/sync-worker/package.json
  apps/examples/package.json
  apps/vscode/extension/package.json
  package.json
  packages/dotcom-shared/package.json
  packages/editor/package.json
  packages/namespaced-tldraw/package.json
  packages/state-react/package.json
  packages/sync-core/package.json
  packages/sync/package.json
  packages/tldraw/package.json
  packages/tlschema/package.json
  yarn.lock
Labels: other

#5695 [dotcom] Fix qr code links
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/QrCode.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaAnonCopyLinkTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaInviteTab.tsx
  apps/dotcom/client/src/tla/hooks/useDeepLink.tsx
Labels: other

#5690 templates: rm yarn.lock files
  templates/.gitignore
  templates/nextjs/yarn.lock
  templates/simple-server-example/yarn.lock
  templates/sync-cloudflare/yarn.lock
  templates/vite/yarn.lock
Labels: other

#5700 rich text: add RichTextSVG to exports
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
Labels: bugfix

#5703 i18n: download the tldraw project as well automatically
  .github/workflows/i18n-download-strings.yml
  internal/scripts/i18n-download-strings.ts
Labels: other

#5689 text: fix editing for React 19/StrictMode
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/shapes/text/RichTextArea.tsx
Labels: bugfix

#5709 rich text: tweak numbered list padding depending on # of items
  packages/editor/editor.css
Labels: bugfix

#5705 style panel: be able to hit Enter to continue editing after selection
  apps/examples/e2e/tests/test-focus.spec.ts
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiButtonPicker.tsx
Labels: bugfix

#5710 update export snapshots
  packages/editor/editor.css
Labels: other

#5713 style panel: be able to hit Enter to continue editing after selection, pt 2
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiButtonPicker.tsx
Labels: bugfix

#5714 Improve search config
  apps/docs/content/getting-started/installation.mdx
  apps/docs/content/getting-started/quick-start.mdx
  apps/docs/scripts/update-algolia-index.ts
  apps/examples/src/examples/basic/README.md
Labels: other

#5707 [dotcom] fix deep link handling for previously-seen files
  apps/dotcom/client/e2e/fixtures/Editor.ts
  apps/dotcom/client/e2e/tests/sharing.spec.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/PageMenu/DefaultPageMenu.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/PageItemInput.tsx
Labels: other

#5712 [dotcom] Create admin UI for hard deleting files
  apps/dotcom/client/src/pages/admin.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/adminRoutes.ts
  lerna.json
Labels: other

#5701 Tweak example code snippet sizing
  apps/docs/components/content/code-files.tsx
Labels: other

#5688 Generate `llms.txt` files
  apps/docs/.gitignore
  apps/docs/package.json
  apps/docs/scripts/create-llms-txt.ts
  apps/docs/scripts/lib/generateLllmsTxt.ts
  apps/docs/scripts/lib/refreshContent.ts
  apps/docs/scripts/lib/utils.ts
Labels: other

#5696 Add & fix missing state docs
  apps/docs/package.json
  packages/state-react/api-report.api.md
  packages/state-react/src/lib/useAtom.ts
  packages/state-react/src/lib/useComputed.ts
  packages/state-react/src/lib/useStateTracking.ts
  packages/state-react/src/lib/useValue.ts
  packages/state/src/lib/EffectScheduler.ts
  packages/state/src/lib/transactions.ts
Labels: other

#5722 Use pg message bus for requesting lsn update
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/types.ts
Labels: other

#5724 Revert "examples: make nav not do full page reload (#5677)"
  apps/examples/src/ExamplePage.tsx
Labels: other

#5726 embed: youtube support time and loop
  packages/tldraw/src/lib/defaultEmbedDefinitions.ts
  packages/tldraw/src/lib/utils/embeds/embeds.test.ts
Labels: improvement

#5580 Fix Group2d `getSvgPathData()` missing move markers
  packages/editor/src/lib/primitives/geometry/Group2d.ts
Labels: bugfix

#5734 When editing a text shape, don't mount the text editor for non-editing empty shapes unless they're hovered
  packages/editor/editor.css
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/PlainTextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/RichTextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/useEditablePlainText.ts
  packages/tldraw/src/lib/ui.css
Labels: bugfix

#5738 Dot dev: Fix menu bar overlapping content
  apps/docs/app/(docs)/[...slug]/page.tsx
Labels: other

#5735 Cache the fonts extracted from rich text.
  packages/editor/src/lib/components/Shape.tsx
Labels: improvement

#5739 [dotcom backend] Wrap writeDataPoint in try/catch to make it safe
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/utils/analytics.ts
Labels: other

#5741 ease timeouts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
Labels: other

#5744 Copy changes from hotfixes branch
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/utils/analytics.ts
Labels: other

#5747 prevent boot concurrency again
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
Labels: other

#5753 people menu: fix overflow and follow buttons
  packages/tldraw/src/lib/ui.css
Labels: bugfix

#5736 Not preload empty `embedIcons`
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/assetUrls.ts
  packages/tldraw/src/lib/ui/context/asset-urls.tsx
Labels: improvement

#5763 Don't include json files in llms.txt outputs
  apps/docs/scripts/lib/generateLllmsTxt.ts
Labels: other, docs-hotfix-please

#5554 events: explore using getCoalescedEvents
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/tools/StateNode.ts
  packages/editor/src/lib/hooks/useCanvasEvents.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/draw/DrawShapeTool.ts
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeTool.ts
Labels: improvement

#5634 a11y: add a live region to announce selected tools
  .prettierignore
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/examples/e2e/tests/test-rich-text-toolbar.spec.ts
  apps/examples/src/examples/ui-components-hidden/UiComponentsHiddenExample.tsx
  packages/editor/api-report.api.md
  packages/editor/src/lib/utils/debug-flags.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/A11y.tsx
  packages/tldraw/src/lib/ui/context/TldrawUiContextProvider.tsx
  packages/tldraw/src/lib/ui/context/a11y.tsx
  packages/tldraw/src/lib/ui/context/components.tsx
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
Labels: improvement

#5771 fix zoom speed for pinch gestures
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/hooks/useGestureEvents.ts
  packages/tldraw/src/test/commands/setCamera.test.ts
Labels: bugfix
