Repository tldraw/tldraw, pull requests merged in 2025-06, with the labels that each got.

#6136 Fix shift key opening link
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/HyperlinkButton.tsx
Labels: bugfix

#6130 Improve arrow performance
  packages/editor/api-report.api.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/primitives/Box.ts
  packages/editor/src/lib/utils/areShapesContentEqual.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/arrowLabel.ts
  packages/tldraw/src/lib/shapes/arrow/shared.ts
Labels: bugfix

#6168 Add modal explaining the upcoming changes.
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaEditor/SneakyLegacyModal.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaLegacyFileEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/sneaky-legacy-modal.module.css
Labels: improvement

#6185 Remove autodesk from announcement
  apps/docs/content/blog/announcing-tldraw-series-a.mdx
Labels: other, docs-hotfix-please

#6171 Fix overscroll on docs
  apps/docs/app/globals.css
  apps/docs/content/docs/editor.mdx
  apps/docs/content/getting-started/releases-versioning.mdx
Labels: other, docs-hotfix-please

#6197 [hotfix] history UI scroll
  apps/dotcom/client/styles/globals.css
Labels: other

#6200 Move file history to debug menu, allow for anybody with write access
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/routes/getRoomHistory.ts
  apps/dotcom/sync-worker/src/routes/getRoomHistorySnapshot.ts
  apps/dotcom/sync-worker/src/utils/tla/getAuth.ts
Labels: other

#6201 hotfix history fixes
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/routes/getRoomHistory.ts
  apps/dotcom/sync-worker/src/routes/getRoomHistorySnapshot.ts
  apps/dotcom/sync-worker/src/utils/tla/getAuth.ts
Labels: other

#6198 Improve page menu interactions
  apps/dotcom/client/e2e/fixtures/Editor.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/examples/e2e/tests/fixtures/menus/PageMenu.ts
  apps/examples/e2e/tests/test-page-menu.spec.ts
  packages/tldraw/src/lib/ui/components/PageMenu/DefaultPageMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/Button/TldrawUiButtonCheck.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiIcon.tsx
Labels: improvement

#6202 Remove `getShapePageGeometry`
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/utils/reorderShapes.ts
  packages/tldraw/src/lib/shapes/arrow/elbow/elbowArrowSnapLines.tsx
Labels: bugfix, improvement

#6207 Sort shapes at point
  packages/editor/src/lib/editor/Editor.test.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Brushing.ts
Labels: improvement

#6208 Reverse sorted shapes
  packages/editor/src/lib/editor/Editor.test.ts
  packages/editor/src/lib/editor/Editor.ts
Labels: improvement

#6209 Tidy up notVisibleShapes
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/Editor.ts
Labels: other

#6211 Fix minor typo in effect scheduler tests
  packages/state/src/lib/__tests__/EffectScheduler.test.ts
Labels: codex

#6212 Await result at the end of executionqueue test
  packages/utils/src/lib/ExecutionQueue.test.ts
Labels: codex

#6210 Fix icon preload crossOrigin handling
  packages/tldraw/src/lib/ui/context/asset-urls.tsx
Labels: codex

#6213 Fix typo in TldrawImage documentation
  packages/tldraw/src/lib/TldrawImage.tsx
Labels: codex

#6219 Don't allow dragging of sidebar items
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
Labels: improvement

#6217 Fix renaming from the main menu.
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
Labels: bugfix

#6222 Add dark mode toggle example
  apps/examples/src/examples/dark-mode-toggle/DarkModeToggleExample.tsx
  apps/examples/src/examples/dark-mode-toggle/README.md
  apps/examples/src/examples/layer-panel/README.md
Labels: codex

#6223 Add local video shape example
  apps/examples/public/fluid.mp4
  apps/examples/src/examples/local-images/LocalImagesExample.tsx
  apps/examples/src/examples/local-images/README.md
  apps/examples/src/examples/local-videos/LocalVideosExample.tsx
  apps/examples/src/examples/local-videos/README.md
  apps/examples/src/examples/text-search/README.md
Labels: codex

#6225 Update custom menus example
  apps/examples/src/examples/custom-menus/README.md
Labels: codex

#6231 Truncate long page names on dotcom
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
  apps/dotcom/client/src/tla/styles/tla.css
Labels: bugfix

#6235 Fix needing to undo twice to undo sticky tab creation
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
Labels: bugfix

#6237 Prevent multiple shape selection example
  apps/examples/src/examples/prevent-instance-change/README.md
  apps/examples/src/examples/prevent-multi-shape-selection/PreventMultiShapeSelectionExample.tsx
  apps/examples/src/examples/prevent-multi-shape-selection/README.md
Labels: improvement

#6241 Add url to feedback form
  apps/dotcom/client/src/tla/components/dialogs/SubmitFeedbackDialog.tsx
  apps/dotcom/sync-worker/src/routes/submitFeedback.ts
  packages/dotcom-shared/src/types.ts
Labels: improvement

#6244 Add focus mode example.
  apps/examples/src/examples/focus-mode/FocusModeExample.tsx
  apps/examples/src/examples/focus-mode/README.md
Labels: improvement

#6220 Minor housekeeping, CSS cleanup
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/examples/e2e/tests/test-rich-text-toolbar.spec.ts
  packages/editor/editor.css
  packages/tldraw/src/lib/shapes/shared/PlainTextLabel.tsx
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/ContextMenu/DefaultContextMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/Button/TldrawUiButton.tsx
Labels: internal

#6243 Stroke and font size customization example.
  apps/examples/src/examples/custom-stroke-and-font-sizes/CustomStrokeAndFontSizes.tsx
  apps/examples/src/examples/custom-stroke-and-font-sizes/README.md
Labels: improvement

#6221 Allow downloading of the original image / video
  assets/translations/main.json
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: feature

#6248 Redact the url.
  apps/dotcom/client/src/tla/components/dialogs/SubmitFeedbackDialog.tsx
Labels: improvement

#6218 Default to draw tool if the page is empty
  apps/dotcom/client/e2e/fixtures/Editor.ts
  apps/dotcom/client/e2e/fixtures/HomePage.ts
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaHistorySnapshotEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaLegacyFileEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaLegacySnapshotEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaPublishEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/sneaky/SneakyDarkModeSync.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/sneaky/SneakyLegacyModal.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/sneaky/SneakyToolSwitcher.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/sneaky/sneaky-legacy-modal.module.css
  apps/dotcom/client/src/tla/pages/local.tsx
Labels: improvement

#6251 Massively speed up 'fetch everything' query
  apps/dotcom/sync-worker/src/fetchEverythingSql.snap.ts
  apps/dotcom/sync-worker/src/fetchEverythingSql.test.ts
Labels: other

#6259 a11y: fix up some random things; add auditor to dotcom
  apps/dotcom/client/package.json
  apps/dotcom/client/src/tla/components/TlaEditor/TlaDebug.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaIcon/TlaIcon.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileSection.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/styles/tla.css
  packages/tldraw/src/lib/ui.css
  yarn.lock
Labels: other

#6184 Replicator topics graph
  .github/actions/setup/action.yml
  apps/docs/package.json
  apps/docs/scripts/lib/generateSection.ts
  apps/dotcom/asset-upload-worker/package.json
  apps/dotcom/client/package.json
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/image-resize-worker/package.json
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/UserChangeCollator.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/replicator/ChangeCollator.test.ts
  apps/dotcom/sync-worker/src/replicator/ChangeCollator.ts
  apps/dotcom/sync-worker/src/replicator/Subscription.test.ts
  apps/dotcom/sync-worker/src/replicator/Subscription.ts
  apps/dotcom/sync-worker/src/replicator/getResumeType.test.ts
  apps/dotcom/sync-worker/src/replicator/getResumeType.ts
  apps/dotcom/sync-worker/src/replicator/pruneTopicSubscriptions.test.ts
  apps/dotcom/sync-worker/src/replicator/pruneTopicSubscriptions.ts
  apps/dotcom/sync-worker/src/replicator/replicatorMigrations.test.ts
  apps/dotcom/sync-worker/src/replicator/replicatorMigrations.ts
  apps/dotcom/sync-worker/src/replicator/replicatorTypes.ts
  apps/dotcom/sync-worker/src/replicator/test-helpers.ts
  apps/dotcom/zero-cache/migrations/018_file_state_replica_identity_all.sql
  apps/vscode/editor/package.json
  internal/health-worker/package.json
  internal/scripts/package.json
  package.json
  packages/dotcom-shared/src/mutators.ts
  yarn.lock
Labels: other

#6260 css: restore some text-shape-label code
  packages/editor/editor.css
Labels: bugfix

#6261 kbd: on non-Mac, output the kbd shortcuts correctly
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiKbd.tsx
  packages/tldraw/src/lib/ui/kbd-utils.ts
Labels: bugfix

#6262 examples: put filter value into url
  apps/examples/src/ExamplePage.tsx
Labels: other

#6263 workflow: fix up template publishing
  .github/workflows/publish-templates.yml
Labels: other

#6264 video: add contextual toolbar, replace, download, alt text
  apps/examples/e2e/tests/test-image-toolbar.spec.ts
  apps/examples/e2e/tests/test-video-toolbar.spec.ts
  apps/examples/src/examples/ui-components-hidden/UiComponentsHiddenExample.tsx
  assets/translations/main.json
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/AltTextEditor.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultImageToolbar.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultImageToolbarContent.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultVideoToolbar.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultVideoToolbarContent.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/components.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/lib/ui/overrides.ts
Labels: feature

#6268 Fix drawing bug
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
Labels: bugfix

#6276 image: make sure replace respects mime types, file size, dimensions
  packages/editor/api-report.api.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/external-content.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/ui/overrides.ts
Labels: bugfix

#6277 image: make sure toolbar moves with sidebar; dont hide on move
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiContextualToolbar.tsx
Labels: bugfix

#6275 Prevent duplication of locked shapes, and unlock pasted locked shapes
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/test/duplicate.test.ts
Labels: bugfix

#6284 Create a drag and drop tray
  apps/examples/src/examples/drag-and-drop-tray/DragAndDropTrayExample.tsx
  apps/examples/src/examples/drag-and-drop-tray/README.md
  apps/examples/src/examples/drag-and-drop-tray/drag-and-drop-tray.css
  apps/examples/src/examples/drag-and-drop-tray/trayitems.ts
  drag-and-drop-tray-summary.md
Labels: other

#6287 Ellipse crop geometry / indicator
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultImageToolbarContent.tsx
  packages/tldraw/src/test/ImageShapeUtil.test.ts
Labels: improvement

#6274 Batch prune script errors
  internal/scripts/prune-preview-deploys.ts
Labels: other

#6295 Fix note shape growY
  packages/editor/src/lib/editor/managers/TextManager/TextManager.ts
Labels: bugfix

#6298 Use our app to commit and push.
  .github/workflows/publish-vscode-extension.yml
  internal/scripts/publish-vscode-extension.ts
Labels: bugfix

#6300 Fix for now.
  .github/workflows/publish-vscode-extension.yml
  internal/scripts/publish-vscode-extension.ts
Labels: bugfix

#6294 Shift key when cropping
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/src/lib/shapes/shared/crop.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/Cropping.ts
  packages/tldraw/src/test/crop.test.ts
Labels: feature

#6303 Skip ci actions after we commit the extension
  .github/workflows/publish-vscode-extension.yml
  internal/scripts/publish-vscode-extension.ts
Labels: bugfix

#6310 Only records stats in production
  apps/dotcom/sync-worker/src/utils/durableObjects.ts
Labels: improvement

#6308 Use wrangler for deletions.
  .github/workflows/prune-preview-deploys.yml
  internal/scripts/prune-preview-deploys.ts
Labels: improvement

#6302 app: old browsers error page
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
Labels: other

#6314 Fix keyboard shortcuts while cropping
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultImageToolbarContent.tsx
Labels: bugfix

#6315 Prevent crash when creating shapes when max shapes is reached
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/managers/HistoryManager/HistoryManager.ts
  packages/editor/src/lib/editor/tools/BaseBoxShapeTool/children/Pointing.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/arrow/toolStates/Pointing.tsx
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
  packages/tldraw/src/lib/shapes/geo/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/line/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/note/toolStates/Pointing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/lib/ui/components/DebugMenu/DefaultDebugMenuContent.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
Labels: bugfix

#6318 Show max shapes alert in more places
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/geo/toolStates/Pointing.ts
  packages/tldraw/src/lib/shapes/line/toolStates/Pointing.ts
Labels: other

#6330 Fix tool overrides
  packages/tldraw/src/lib/Tldraw.test.tsx
  packages/tldraw/src/lib/Tldraw.tsx
  packages/utils/src/lib/array.test.ts
Labels: bugfix, sdk-hotfix-please

#6348 videos: fix up tiny controls
  packages/editor/editor.css
Labels: bugfix

#6352 Fix spelling mistakes
  CHANGELOG.md
  apps/docs/content/docs/tools.mdx
  apps/dotcom/client/playwright.config.ts
  apps/examples/src/examples/prevent-shape-change/README.md
  apps/examples/src/examples/snapshots/SnapshotExample.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/CHANGELOG.md
  packages/tldraw/src/test/Editor.test.tsx
  packages/tldraw/src/test/groups.test.tsx
  packages/tldraw/src/test/translating.test.ts
  templates/ai/README.md
Labels: bugfix
