Repository tldraw/tldraw, pull requests merged in 2025-05, with the labels that each got.

#5989 don't lint .schema.js
  eslint.config.mjs
Labels: other

#5992 a11y: fix some dotcom issues
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/file-share-menu.module.css
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
Labels: other, preview-flyio-zero-deploy-please

#5974 Fix gradients / hovers for open submenus
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/StylePanel/DropdownPicker.tsx
Labels: bugfix

#5993 Export custom bg color for single frame exports
  packages/editor/src/lib/exports/getSvgJsx.tsx
Labels: bugfix

#5969 Fix hover buttons
  packages/tldraw/src/lib/ui.css
Labels: bugfix

#5998 Fix mask window example
  apps/examples/src/examples/mask-window/MaskWindowExample.tsx
Labels: other

#5821 Indicators perf
  packages/editor/src/lib/components/default-components/DefaultShapeIndicator.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
Labels: improvement

#5997 disable auto flyio deploy since it's broken
  .github/workflows/deploy-dotcom.yml
Labels: other

#5996 Better error reporting for sync worker
  apps/dotcom/sync-worker/src/routes/tla/createFiles.ts
  apps/dotcom/sync-worker/src/routes/tla/getPublishedFile.ts
  apps/dotcom/sync-worker/src/worker.ts
Labels: other

#5985 Fix spacing and baseline on top right area
  apps/dotcom/client/src/tla/components/TlaCtaButton/cta-button.module.css
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
  apps/dotcom/client/styles/globals.css
Labels: improvement

#6006 Fix export images bug
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/file-share-menu.module.css
Labels: bugfix

#6007 Fix clickable area on form rows
  apps/dotcom/client/src/tla/components/tla-menu/menu.module.css
  apps/dotcom/client/src/tla/components/tla-menu/tla-menu.tsx
Labels: bugfix

#6004 Select offscreen shapes
  packages/tldraw/src/lib/tools/SelectTool/childStates/Brushing.ts
  packages/tldraw/src/test/selection-omnibus.test.ts
Labels: bugfix

#6005 Bump zero to the release v19
  apps/dotcom/client/package.json
  apps/dotcom/sync-worker/package.json
  apps/dotcom/sync-worker/src/postgres.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/zero-cache/flyio.template.toml
  apps/dotcom/zero-cache/package.json
  packages/dotcom-shared/package.json
  yarn.lock
Labels: improvement

#5956 [VSCode] Allow users to drag files from the sidebar.
  apps/vscode/editor/src/app.tsx
  apps/vscode/editor/src/utils/externalUrlContentHandler.ts
  apps/vscode/editor/src/utils/rpc.ts
  apps/vscode/extension/src/WebViewMessageHandler.ts
  apps/vscode/extension/src/media.ts
  apps/vscode/messages.ts
  packages/utils/api-report.api.md
  packages/utils/src/index.ts
  packages/utils/src/lib/media/media.ts
Labels: bugfix

#5979 Fix simple server example
  templates/simple-server-example/src/client/App.tsx
  templates/sync-cloudflare/client/multiplayerAssetStore.tsx
Labels: other

#6014 text: be able to add other styling to measure by if applicable
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/managers/TextManager.ts
Labels: improvement, api

#6013 rich text: fix up styling of empty lines and lists
  packages/editor/editor.css
Labels: bugfix

#6024 Fix inconsistent panning.
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/commands/setCamera.test.ts
Labels: bugfix

#6023 Improve performance of a programatically rotating shape when it is selected
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
Labels: improvement

#6028 Elbow arrow fixes
  apps/examples/e2e/tests/export-snapshots.spec.tsx
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Weird-elbow-arrows-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Weird-elbow-arrows-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Weird-elbow-arrows-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Weird-elbow-arrows-light-1-chromium-linux.png
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/arrow/arrowLabel.ts
  packages/tldraw/src/lib/shapes/arrow/arrowTargetState.ts
  packages/tldraw/src/lib/shapes/arrow/elbow/getElbowArrowInfo.tsx
  packages/tldraw/src/lib/shapes/arrow/elbow/routes/elbowArrowRoutes.tsx
  packages/tldraw/src/lib/shapes/arrow/elbow/routes/routeArrowWithAutoEdgePicking.tsx
  packages/tldraw/src/lib/shapes/arrow/shared.ts
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/EditingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingArrowLabel.ts
Labels: bugfix

#6032 always call on edit end
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix

#6033 Bump memory.
  sst.config.ts
Labels: bugfix

#6030 Fix disposing order
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix

#6035 fix: no tasks found matching build-package
  package.json
Labels: bugfix

#6036 Set retroactive to true for props migrators
  packages/tlschema/src/recordsWithProps.ts
Labels: bugfix

#6037 Revert "Export menu improvements"
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaExportTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/file-share-menu.module.css
Labels: other

#6038 Don't show the uploading progress bar if the upload failed already
  apps/dotcom/client/src/tla/app/TldrawApp.ts
Labels: improvement

#6041 Prevent announcements during interactions
  packages/tldraw/src/lib/ui/components/A11y.tsx
Labels: improvement

#6021 Docs: Remove section on rich text exports
  apps/docs/content/docs/shapes.mdx
Labels: other, docs-hotfix-please

#6025 Embed shape: add figma selection definition
  packages/tldraw/src/lib/defaultEmbedDefinitions.ts
  packages/tldraw/src/lib/utils/embeds/embeds.test.ts
Labels: improvement

#6042 Remove the selection background
  apps/examples/src/examples/exploded/ExplodedExample.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/hooks/useEditorComponents.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/canvas/TldrawSelectionBackground.tsx
Labels: improvement

#6043 Make flattened shapes image use a transparent background
  packages/tldraw/src/lib/ui/hooks/useFlatten.ts
Labels: improvement

#6044 Fix super tight zoom button
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/ZoomMenu/DefaultZoomMenu.tsx
Labels: bugfix

#6046 Sidebar UI fixes
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
  apps/dotcom/client/src/tla/components/TlaIcon/icon.module.css
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarCookieConsent.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarRenameInline.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarUserSettingsMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/components/dialogs/dialogs.module.css
  apps/dotcom/client/src/tla/components/tla-form/form.module.css
Labels: bugfix

#6020 Snap pasted text and embed content to the grid
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: bugfix

#6019 refactor: rename canEditOnly to canEditonly
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/EditingShape.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/PointingShape.ts
Labels: improvement

#6027 Make sure the file exists before uploading it to the bucket.
  apps/dotcom/sync-worker/src/routes/tla/uploads.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/sync-worker/wrangler.toml
Labels: improvement

#6049 fix feedback dialog
  apps/dotcom/client/src/tla/components/dialogs/SubmitFeedbackDialog.tsx
Labels: other

#6053 Simplify the cursor logic
  packages/editor/editor.css
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
Labels: improvement

#5973 a11y: be able to navigate in/out of container shapes
  apps/examples/e2e/tests/test-kbds.spec.ts
  assets/translations/main.json
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/group/GroupShapeUtil.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/test/navigation.test.ts
Labels: improvement

#6001 a11y: address icons and handles
  apps/dotcom/client/src/tla/components/tla-menu/tla-menu.tsx
  apps/examples/src/examples/context-toolbar/ContextToolbar.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
  assets/translations/main.json
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/canvas/TldrawCropHandles.tsx
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/ui/components/Minimap/DefaultMinimap.tsx
  packages/tldraw/src/lib/ui/components/OfflineIndicator/OfflineIndicator.tsx
  packages/tldraw/src/lib/ui/components/SharePanel/PeopleMenuItem.tsx
  packages/tldraw/src/lib/ui/components/Toasts.tsx
  packages/tldraw/src/lib/ui/components/primitives/Button/TldrawUiButtonCheck.tsx
  packages/tldraw/src/lib/ui/components/primitives/Button/TldrawUiButtonIcon.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiDialog.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiDropdownMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiIcon.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiInput.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuCheckboxItem.tsx
  packages/tldraw/src/lib/ui/context/toasts.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
  packages/tldraw/src/test/customSnapping.test.tsx
  packages/tlschema/api-report.api.md
  packages/tlschema/src/misc/TLHandle.ts
Labels: improvement

#6056 Fix queue previews
  apps/dotcom/sync-worker/wrangler.toml
  internal/scripts/deploy-dotcom.ts
  internal/scripts/lib/deploy.ts
  internal/scripts/prune-preview-deploys.ts
Labels: bugfix

#6050 Fix dragging arrows breaking bindings
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Weird-elbow-arrows-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Weird-elbow-arrows-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Weird-elbow-arrows-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Weird-elbow-arrows-light-1-chromium-linux.png
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
Labels: bugfix

#6064 Only create a queue if not a dry run.
  internal/scripts/deploy-dotcom.ts
Labels: improvement

#6065 Remove download option from non-active files.
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
Labels: other

#6066 Associate users with file uploads.
  apps/dotcom/sync-worker/src/routes/tla/uploads.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/zero-cache/migrations/017_associated_users_with_assets.sql
  packages/dotcom-shared/src/tlaSchema.ts
Labels: improvement

#5827 a11y: add way to focus styling menu via kbd
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/TlaFileShareMenu.tsx
  assets/translations/main.json
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/EditLinkDialog.tsx
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiPopover.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiSlider.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement

#6072 ENG-3385 / Auto select text when Edit link menu opens
  packages/tldraw/src/lib/ui/components/EditLinkDialog.tsx
Labels: improvement

#6094 i18n: we dont need fetch-depth 0
  .github/workflows/i18n-download-strings.yml
  .github/workflows/i18n-upload-strings.yml
Labels: other

#6096 [tlsync] Add internal hooks to expose presence changes
  packages/sync-core/api-report.api.md
  packages/sync-core/src/lib/TLSocketRoom.ts
  packages/sync-core/src/lib/TLSyncRoom.ts
Labels: bugfix

#6092 Upgrade transitive dependency prebuild-install
  yarn.lock
Labels: other

#6089 analytics: lay foundation to unify across tldraw properties
  .github/workflows/deploy-dotcom.yml
  apps/analytics/.gitignore
  apps/analytics/package.json
  apps/analytics/src/analytics.tsx
  apps/analytics/src/index.ts
  apps/analytics/src/styles.css
  apps/analytics/src/types.d.ts
  apps/analytics/tsconfig.json
  apps/analytics/vercel.json
  apps/analytics/vite.config.ts
  apps/docs/app/analytics.tsx
  apps/docs/components/common/blue-a.tsx
  apps/docs/components/common/tldraw-link.tsx
  apps/docs/components/content/a.tsx
  apps/docs/components/content/code.tsx
  apps/docs/components/content/image.tsx
  apps/docs/components/content/index.tsx
  apps/docs/components/content/video.tsx
  apps/docs/components/marketing/demo-section.tsx
  apps/docs/components/marketing/what-it-is-section.tsx
  apps/docs/components/navigation/footer.tsx
  apps/docs/package.json
  apps/docs/tsconfig.json
  apps/dotcom/client/package.json
  apps/dotcom/client/src/components/IFrameProtector.tsx
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaLegacyFileEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaLegacySnapshotEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaPublishEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/useFileEditorOverrides.ts
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
  apps/dotcom/client/src/utils/analytics.tsx
  apps/dotcom/client/src/utils/csp.ts
  apps/dotcom/client/src/utils/posthog.tsx
  apps/dotcom/client/src/utils/trackAnalyticsEvent.ts
  apps/dotcom/client/src/utils/useHandleUiEvent.tsx
  yarn.lock
Labels: other

#6097 analytics: tweak vercel.json routing
  apps/analytics/vercel.json
Labels: other

#6102 analytics: expose page/identify/track for computer.tldraw.com
  apps/analytics/src/analytics.tsx
  apps/analytics/src/index.ts
  apps/analytics/src/styles.css
Labels: other

#6105 analytics: ugh posthogs/vercels docs are wrong omg
  apps/analytics/vercel.json
Labels: other

#6103 Improve feedback textarea
  apps/dotcom/client/src/tla/components/dialogs/SubmitFeedbackDialog.tsx
  apps/dotcom/client/src/tla/components/dialogs/dialogs.module.css
  packages/tldraw/src/lib/ui.css
Labels: bugfix

#6107 analytics: once more, with feeling
  apps/analytics/vercel.json
  apps/dotcom/client/src/utils/csp.ts
Labels: other

#6057 scale scrubbing
  packages/editor/src/lib/editor/Editor.ts
Labels: enhancement

#6108 Revert "scale scrubbing"
  packages/editor/src/lib/editor/Editor.ts
Labels: other

#6109 Followups to examples cleanup
  apps/docs/scripts/lib/generateSection.ts
  apps/examples/src/examples/hosted-images/README.md
  apps/examples/src/examples/inset-canvas/inset-canvas.css
  apps/examples/src/examples/toSvg-method-example/CustomShapeToSvgExample.tsx
Labels: other

#6110 Examples cleanup: Sidebar followup
  apps/docs/components/docs/docs-sidebar-menus.tsx
  apps/docs/components/docs/docs-sidebar.tsx
  apps/examples/src/examples/api/README.md
Labels: other

#6111 Add DeepWiki badge
  README.md
Labels: other

#6075 Consolidate mutation logic
  apps/dotcom/client/src/tla/app/ClientCRUD.ts
  apps/dotcom/client/src/tla/app/ClientQuery.ts
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/app/zero-polyfill.ts
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/zero/ServerCrud.ts
  apps/dotcom/sync-worker/src/zero/ServerQuery.ts
  apps/dotcom/sync-worker/src/zero/ZMutationError.ts
  apps/dotcom/sync-worker/src/zero/legacy_assertValidMutation.ts
  packages/dotcom-shared/src/OptimisticAppStore.ts
  packages/dotcom-shared/src/mutators.ts
  packages/dotcom-shared/src/types.ts
  packages/utils/api-report.api.md
  packages/utils/src/index.ts
  packages/utils/src/lib/object.ts
Labels: other

#6114 Fix docs sidebar duplication bug
  apps/docs/components/docs/docs-sidebar.tsx
Labels: other

#6118 Fix two issues with examples refresh
  apps/docs/components/docs/docs-mobile-sidebar.tsx
  apps/docs/next.config.js
Labels: other, docs-hotfix-please

#6122 Fix redirect for `shapes/tools` examples category
  apps/docs/next.config.js
Labels: other, docs-hotfix-please

#6100 Compile fetchEverythingSql ahead of time
  apps/dotcom/sync-worker/package.json
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/fetchEverythingSql.snap.ts
  apps/dotcom/sync-worker/src/fetchEverythingSql.test.ts
  apps/dotcom/sync-worker/src/getFetchEverythingSql.ts
  apps/dotcom/sync-worker/src/parseResultRow.ts
Labels: other

#6119 Change a slideshow example title to have slightly clearer wording
  apps/examples/src/examples/slides/README.md
Labels: other, docs-hotfix-please

#6112 Use PathBuilder for geo & line shapes
  apps/examples/e2e/playwright.config.ts
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Fills-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Fills-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Fills-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Fills-light-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Fonts-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Fonts-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Fonts-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Fonts-light-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Frames-light-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Geo-shapes-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Geo-shapes-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Geo-shapes-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Geo-shapes-light-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Regressions-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Regressions-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Regressions-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Regressions-light-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Text-rendering-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Text-rendering-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Text-rendering-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Text-rendering-light-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Weird-elbow-arrows-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Weird-elbow-arrows-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Weird-elbow-arrows-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Weird-elbow-arrows-light-1-chromium-linux.png
  packages/editor/api-report.api.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/shapes/shared/getPerfectDashProps.ts
  packages/editor/src/lib/primitives/Vec.ts
  packages/editor/src/lib/primitives/geometry/Edge2d.ts
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowPath.tsx
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/components/GeoShapeBody.tsx
  packages/tldraw/src/lib/shapes/geo/geo-shape-helpers.ts
  packages/tldraw/src/lib/shapes/geo/getGeoShapePath.ts
  packages/tldraw/src/lib/shapes/geo/getLines.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/components/getLinePath.ts
  packages/tldraw/src/lib/shapes/line/line-helpers.ts
  packages/tldraw/src/lib/shapes/shared/PathBuilder.test.tsx
  packages/tldraw/src/lib/shapes/shared/PathBuilder.tsx
  packages/tldraw/src/lib/utils/excalidraw/__snapshots__/putExcalidrawContent.test.tsx.snap
  packages/tldraw/src/test/commands/__snapshots__/getSvgString.test.ts.snap
  packages/tldraw/src/test/commands/__snapshots__/zoomToFit.test.ts.snap
Labels: api

#6124 always show elbow arrow outline
  packages/tldraw/src/lib/canvas/TldrawOverlays.tsx
Labels: bugfix, sdk-hotfix-please

#6125 Fix focus manager when editing
  packages/editor/src/lib/editor/managers/FocusManager.ts
Labels: bugfix

#6129 Track max files reached
  apps/dotcom/client/src/tla/app/TldrawApp.ts
Labels: other

#6132 Fix prunning
  internal/scripts/prune-preview-deploys.ts
Labels: bugfix

#6128 Improve resizing frames
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/editor/src/lib/editor/shapes/group/GroupShapeUtil.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
Labels: bugfix, improvement

#6012 clipboard: fix pasting shape data accidentally into a text area
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/shared/useEditablePlainText.ts
  packages/tldraw/src/lib/shapes/shared/useEditableRichText.ts
  packages/tldraw/src/lib/shapes/text/PlainTextArea.tsx
  packages/tldraw/src/lib/shapes/text/RichTextArea.tsx
Labels: bugfix

#6137 clipboard: followup to shape data pasting PR
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/shared/useEditablePlainText.ts
  packages/tldraw/src/lib/shapes/shared/useEditableRichText.ts
Labels: api

#6116 [signia] add async effect deferral
  apps/dotcom/client/src/tla/app/zero-polyfill.ts
  packages/state/api-report.api.md
  packages/state/src/index.ts
  packages/state/src/lib/__tests__/transactions.test.ts
  packages/state/src/lib/transactions.ts
Labels: other

#6143 Fix pruning of queues and workers
  internal/scripts/prune-preview-deploys.ts
Labels: bugfix

#6146 analytics: bunch of fixes and wiring of gtag
  apps/analytics/package.json
  apps/analytics/src/analytics.tsx
  apps/analytics/src/index.ts
  apps/docs/app/analytics.tsx
  apps/docs/components/common/tldraw-link.tsx
  apps/docs/package.json
  apps/dotcom/client/package.json
  apps/dotcom/client/src/utils/analytics.tsx
  yarn.lock
Labels: other, docs-hotfix-please

#6156 analytics: add another domain for csp on dotcom
  apps/dotcom/client/src/utils/csp.ts
Labels: other

#6158 Fix double dialogs.
  apps/dotcom/client/src/tla/components/TlaEditor/TlaLegacyFileEditor.tsx
Labels: bugfix

#6162 Geometry bug fixes
  apps/examples/src/examples/before-create-update-shape/BeforeCreateUpdateShapeExample.tsx
  apps/examples/src/examples/bounds-snapping-shape/PlayingCardShape/playing-card-util.tsx
  apps/examples/src/examples/selection-ui/SelectionUiExample.tsx
  packages/editor/api-report.api.md
  packages/editor/src/lib/primitives/Vec.test.ts
  packages/editor/src/lib/primitives/Vec.ts
  packages/editor/src/lib/primitives/geometry/Arc2d.ts
  packages/editor/src/lib/primitives/geometry/Circle2d.ts
  packages/editor/src/lib/primitives/geometry/CubicBezier2d.test.ts
  packages/editor/src/lib/primitives/geometry/CubicBezier2d.ts
  packages/editor/src/lib/primitives/geometry/CubicSpline2d.ts
  packages/editor/src/lib/primitives/geometry/Edge2d.ts
  packages/editor/src/lib/primitives/geometry/Ellipse2d.ts
  packages/editor/src/lib/primitives/geometry/Point2d.ts
  packages/editor/src/lib/primitives/geometry/Polygon2d.ts
  packages/editor/src/lib/primitives/geometry/Polyline2d.ts
  packages/editor/src/lib/primitives/geometry/Rectangle2d.ts
  packages/editor/src/lib/primitives/geometry/Stadium2d.ts
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/PathBuilder.tsx
Labels: bugfix
