Repository tldraw/tldraw, pull requests merged in 2025-09, with the labels that each got.

#6679 Export `doesGeometryOverlapPolygon`
  packages/editor/api-report.api.md
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
  packages/editor/src/lib/primitives/geometry/Group2d.ts
  packages/editor/src/lib/utils/reparenting.ts
Labels: api

#6670 remove unused deprecated APIs for 4.0
  .gitignore
  apps/dotcom/sync-worker/src/fetchEverythingSql.test.ts
  packages/editor/api-report.api.md
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/misc-types.ts
  packages/editor/src/lib/primitives/Vec.ts
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
  packages/store/README.md
  packages/store/api-report.api.md
  packages/store/src/index.ts
  packages/store/src/lib/RecordType.ts
  packages/store/src/lib/Store.ts
  packages/store/src/lib/StoreSchema.ts
  packages/store/src/lib/migrate.ts
  packages/store/src/lib/test/defineMigrations.test.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/shared/PlainTextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/useEditablePlainText.ts
  packages/tldraw/src/lib/shapes/shared/useImageOrVideoAsset.ts
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/useExportAs.ts
  packages/tldraw/src/lib/utils/export/copyAs.ts
  packages/tldraw/src/lib/utils/export/export.ts
  packages/tldraw/src/lib/utils/export/exportAs.ts
  packages/utils/api-report.api.md
  packages/utils/src/lib/file.ts
Labels: api

#6681 Bump AI template's packages
  apps/docs/package.json
  templates/ai/client/transforms/SimpleText.ts
  templates/ai/client/useTldrawAiExample.ts
  templates/ai/package.json
  templates/ai/worker/do/openai/generate.ts
  templates/ai/worker/do/openai/getSimpleContentFromCanvasContent.ts
  templates/ai/worker/do/openai/prompt.ts
  templates/ai/worker/do/openai/schema.ts
  templates/ai/worker/do/openai/stream.ts
  yarn.lock
Labels: other

#6683 Fix panning perf.
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiTooltip.tsx
Labels: bugfix, dotcom-hotfix-please

#6687 docs improvements
  apps/analytics/src/styles.css
  apps/docs/components/content/code-files.tsx
  apps/docs/components/content/copy-button.tsx
  apps/docs/components/content/pre.tsx
  apps/docs/components/marketing/case-studies-section.tsx
  apps/docs/components/marketing/hero-ctas.tsx
  apps/docs/components/marketing/hero-section.tsx
  apps/docs/public/images/case-study-thumbnails/autodesk-hero.webp
  apps/docs/public/images/case-study-thumbnails/bigbluebutton-hero.webp
  apps/docs/public/images/case-study-thumbnails/clickup-hero.webp
  apps/docs/public/images/case-study-thumbnails/graze-hero.webp
  apps/docs/public/images/case-study-thumbnails/jam-hero.webp
  apps/docs/public/images/case-study-thumbnails/legendkeeper-hero.webp
  apps/docs/public/images/case-study-thumbnails/matilda-hero.webp
  apps/docs/public/images/case-study-thumbnails/mobbin-hero.webp
  apps/docs/public/images/case-study-thumbnails/opennote-hero.webp
  apps/docs/public/images/case-study-thumbnails/padlet-hero.webp
  apps/docs/public/images/case-study-thumbnails/roam-hero.webp
  apps/docs/public/images/case-study-thumbnails/sublime-hero.webp
  packages/editor/src/lib/license/Watermark.tsx
Labels: other

#6673 Fix over-measuring arrow labels, alt take
  packages/tldraw/src/lib/shapes/arrow/arrowLabel.ts
Labels: improvement

#6619 Chat template starter kit
  .claude/settings.json
  .prettierignore
  CLAUDE.md
  templates/chat/.gitignore
  templates/chat/LICENSE.md
  templates/chat/README.md
  templates/chat/next.config.mjs
  templates/chat/package.json
  templates/chat/src/app/api/chat/route.ts
  templates/chat/src/app/favicon.ico
  templates/chat/src/app/layout.tsx
  templates/chat/src/app/page.tsx
  templates/chat/src/app/styles.css
  templates/chat/src/components/Chat.tsx
  templates/chat/src/components/ChatInput.tsx
  templates/chat/src/components/ChatInputImage.tsx
  templates/chat/src/components/ChatMessage.tsx
  templates/chat/src/components/ClearChatIcon.tsx
  templates/chat/src/components/MessageList.tsx
  templates/chat/src/components/WhiteboardModal.tsx
  templates/chat/src/components/icons/ImageIcon.tsx
  templates/chat/src/components/icons/SendIcon.tsx
  templates/chat/src/components/icons/UploadIcon.tsx
  templates/chat/src/components/icons/WhiteboardIcon.tsx
  templates/chat/src/components/icons/XIcon.tsx
  templates/chat/src/hooks/useChatInputState.ts
  templates/chat/src/hooks/useChatMessageStorage.tsx
  templates/chat/src/hooks/useScrollToBottom.ts
  templates/chat/tsconfig.json
  yarn.lock
Labels: other

#6692 Add Claude Code GitHub Workflow
  .github/workflows/claude-code-review.yml
  .github/workflows/claude.yml
Labels: internal

#6576 Update licensing logic
  apps/examples/e2e/tests/test-licensing.spec.ts
  apps/examples/src/misc/end-to-end.tsx
  internal/scripts/generate-test-licenses.ts
  package.json
  packages/editor/api-report.api.md
  packages/editor/src/index.ts
  packages/editor/src/lib/license/LicenseManager.test.ts
  packages/editor/src/lib/license/LicenseManager.ts
  packages/editor/src/lib/license/LicenseProvider.tsx
  packages/editor/src/lib/license/Watermark.tsx
Labels: feature

#6694 Use not_planned as the reason for closing stale issues
  .github/workflows/close-stale-issues.yml
Labels: improvement

#6698 Add README for npm create tldraw CLI tool
  packages/create-tldraw/README.md
Labels: other

#6703 Remove mcp
  .gitignore
  .mcp.json
Labels: other

#6708 pg connect logs
  apps/dotcom/sync-worker/src/postgres.ts
  apps/dotcom/sync-worker/src/utils/analytics.ts
Labels: other

#6699 Dynamically sized shape example
  apps/examples/src/examples/size-from-dom/README.md
  apps/examples/src/examples/size-from-dom/SizeFromDomExample.tsx
  apps/examples/src/examples/size-from-dom/contents.ts
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/derivations/notVisibleShapes.ts
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/src/test/getCulledShapes.test.tsx
Labels: api

#6715 chat template: add uploads, temporarily disable image output
  templates/chat/package.json
  templates/chat/src/app/api/chat/route.ts
  templates/chat/src/app/api/upload/route.ts
  templates/chat/src/components/Chat.tsx
  templates/chat/src/utils/uploadMessageContents.ts
  yarn.lock
Labels: other

#6717 Remove DO and add hosting to branching chat template
  templates/branching-chat/worker/do.ts
  templates/branching-chat/worker/routes/generate.ts
  templates/branching-chat/worker/routes/stream.ts
  templates/branching-chat/worker/types.ts
  templates/branching-chat/worker/worker.ts
  templates/branching-chat/wrangler.toml
Labels: other

#6732 license: have NATIVE_LICENSE use a regex
  packages/editor/src/lib/license/LicenseManager.test.ts
  packages/editor/src/lib/license/LicenseManager.ts
Labels: improvement

#6729 Fix: bug when pasting in readonly mode
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/Editor.test.ts
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix, sdk-hotfix-please, dotcom-hotfix-please

#6744 Update earthquake node label to 'Earthquake data'
  templates/workflow/src/nodes/types/EarthquakeNode.tsx
Labels: other

#6733 replace stopEventPropagation with markEventAsHandled and kill `e.isKilled`
  apps/examples/src/examples/custom-clipping-shape/CustomClippingExample.tsx
  apps/examples/src/examples/editable-shape/EditableShapeUtil.tsx
  apps/examples/src/examples/exam-marking/add-mark-util.tsx
  apps/examples/src/examples/popup-shape/PopupShapeUtil.tsx
  apps/examples/src/examples/rich-text-font-extensions/RichTextFontExtension.tsx
  apps/examples/src/examples/selection-ui/SelectionUiExample.tsx
  apps/examples/src/examples/slides/SlidesPanel.tsx
  apps/examples/src/examples/slideshow/SlideShowExample.tsx
  apps/examples/src/examples/sync-custom-shape/CounterShape.tsx
  apps/examples/src/examples/text-search/TextSearchPanel.tsx
  apps/examples/src/examples/things-on-the-canvas/OnTheCanvasExample.tsx
  packages/editor/api-report.api.md
  packages/editor/setupVitest.js
  packages/editor/src/index.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/hooks/useCanvasEvents.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/editor/src/lib/hooks/useFixSafariDoubleTapZoomPencilEvents.ts
  packages/editor/src/lib/hooks/useGestureEvents.ts
  packages/editor/src/lib/hooks/useHandleEvents.ts
  packages/editor/src/lib/hooks/useSelectionEvents.ts
  packages/editor/src/lib/license/Watermark.tsx
  packages/editor/src/lib/test/InFrontOfTheCanvas.test.tsx
  packages/editor/src/lib/utils/dom.test.ts
  packages/editor/src/lib/utils/dom.ts
  packages/editor/src/lib/utils/getPointerInfo.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/bookmark/BookmarkShapeUtil.tsx
  packages/tldraw/src/lib/shapes/frame/components/FrameLabelInput.tsx
  packages/tldraw/src/lib/shapes/shared/HyperlinkButton.tsx
  packages/tldraw/src/lib/shapes/shared/useEditablePlainText.ts
  packages/tldraw/src/lib/shapes/text/PlainTextArea.tsx
  packages/tldraw/src/lib/shapes/text/RichTextArea.tsx
  packages/tldraw/src/lib/ui/components/A11y.tsx
  packages/tldraw/src/lib/ui/components/PageMenu/DefaultPageMenu.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiContextualToolbar.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiInput.tsx
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  templates/branching-chat/client/connection/ConnectionShapeUtil.tsx
  templates/branching-chat/client/nodes/types/MessageNode.tsx
  templates/workflow/src/components/OnCanvasComponentPicker.tsx
  templates/workflow/src/components/WorkflowRegions.tsx
  templates/workflow/src/connection/ConnectionShapeUtil.tsx
  templates/workflow/src/nodes/types/SliderNode.tsx
Labels: api

#6734 a11y: add "selected" to style panel/sidebar for clarity
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  assets/translations/main.json
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/StylePanel/StylePanelButtonPicker.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiToolbar.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement

#6750 a11y: many more little fixes
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaExportTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaInviteTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaManageCookiesDialog.tsx
  apps/dotcom/client/src/tla/components/tla-menu/tla-menu.tsx
  apps/examples/e2e/tests/fixtures/menus/NavigationPanel.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/LanguageMenu.tsx
  packages/tldraw/src/lib/ui/components/Minimap/DefaultMinimap.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/AltTextEditor.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/LinkEditor.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiToolbar.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiTooltip.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuCheckboxItem.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
Labels: bugfix

#6749 Update `npm create tldraw` with new starter kits
  internal/scripts/export-template.ts
  internal/scripts/lib/types.ts
  internal/scripts/refresh-create-templates.ts
  packages/create-tldraw/README.md
  packages/create-tldraw/src/group-select.ts
  packages/create-tldraw/src/main.ts
  packages/create-tldraw/src/templates.ts
  packages/create-tldraw/src/utils.ts
  packages/create-tldraw/src/wrap-ansi.test.ts
  packages/create-tldraw/src/wrap-ansi.ts
  templates/agent/package.json
  templates/branching-chat/package.json
  templates/chat/package.json
  templates/nextjs/package.json
  templates/simple-server-example/package.json
  templates/sync-cloudflare/package.json
  templates/vite/package.json
  templates/vue/package.json
  templates/workflow/package.json
  templates/workflow/src/nodes/types/shared.tsx
Labels: other

#6751 fix chat snaps
  templates/chat/src/utils/uploadMessageContents.ts
Labels: other

#6759 docs: fix up search bar at different sizes
  apps/docs/components/docs/docs-search-bar.tsx
Labels: other

#6753 Latest changes
  apps/docs/next.config.js
Labels: improvement

#6757 Add keyboard shortcut to toggle lock tooltip description
  packages/tldraw/src/lib/ui/components/Toolbar/ToggleToolLockedButton.tsx
Labels: improvement

#6778 Add a menu item for tldraw.dev
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarHelpMenu.tsx
  apps/dotcom/client/src/tla/components/menu-items/menu-items.tsx
Labels: other

#6780 License change for 4.0
  LICENSE.md
  templates/agent/LICENSE.md
Labels: other

#6783 style panel: fix certain labels on mobile
  packages/tldraw/src/lib/ui.css
Labels: other

#6782 Docs path change: releases-versioning -> releases
  apps/docs/components/docs/docs-sidebar-menu.tsx
  apps/docs/content/getting-started/installation.mdx
  apps/docs/content/getting-started/releases.mdx
  apps/docs/content/starter-kits/overview.mdx
  apps/docs/next.config.js
  apps/docs/scripts/lib/fetchReleases.ts
  apps/docs/scripts/lib/generateSection.ts
Labels: other

#6788 publish arrow target state
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/arrow/arrowTargetState.ts
Labels: api

#6789 Improve .dev sitemap
  apps/docs/app/sitemap.ts
Labels: improvement

#6768 Docs: change license page language
  apps/docs/content/community/license.mdx
Labels: docs, other

#6795 Docs: unbold the first sentence
  apps/docs/content/starter-kits/agent.mdx
  apps/docs/content/starter-kits/branching-chat.mdx
  apps/docs/content/starter-kits/chat.mdx
  apps/docs/content/starter-kits/multiplayer.mdx
  apps/docs/content/starter-kits/workflow.mdx
Labels: docs, other, docs-hotfix-please

#6804 fix template exports
  internal/scripts/export-template.ts
Labels: other, docs-hotfix-please

#6802 Consolidate preferences menu groups
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
Labels: dotcom, sdk, sdk-hotfix-please, dotcom-hotfix-please

#6801 Only deploy dotcom previews with a label?
  .github/workflows/deploy-dotcom.yml
Labels: other

#6805 docs: fix logo lol
  apps/docs/components/common/logo.tsx
  apps/docs/components/navigation/footer.tsx
Labels: other, docs-hotfix-please

#6810 Fix agent context items offset being wrong
  templates/agent/client/agent/TldrawAgent.ts
  templates/agent/shared/parts/ChatHistoryPartUtil.ts
Labels: bugfix, sdk-hotfix-please

#6811 kbd shortcuts: fix typo with entering/leaving container
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
Labels: bugfix

#6815 Focus mode sdk hotfix
  packages/tldraw/src/lib/ui/context/actions.tsx
Labels: other

#6817 fix: prevent opening a new window for empty href
  packages/tldraw/src/lib/shapes/shared/RichTextLabel.tsx
Labels: bugfix

#6820 fix sign up
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/sync-worker/src/fetchEverythingSql.snap.ts
  apps/dotcom/sync-worker/src/replicator/test-helpers.ts
  apps/dotcom/zero-cache/migrations/022_add_input_mode_preference.sql
  packages/dotcom-shared/src/tlaSchema.ts
Labels: other, dotcom-hotfix-please

#6835 Add ascii branding console message on dot-com
  apps/dotcom/client/src/main.tsx
  apps/dotcom/client/src/utils/consoleBranding.ts
Labels: other

#6849 Fix spelling typos in documentation
  apps/dotcom/image-resize-worker/README.md
  apps/examples/src/examples/sync-custom-people-menu/README.md
  apps/examples/writing-examples.md
  apps/vscode/extension/CHANGELOG.md
  templates/sync-cloudflare/README.md
Labels: bugfix

#6844 license: make the flags msg a warning
  packages/editor/src/lib/license/LicenseManager.ts
Labels: other

#6851 license: send up NODE_ENV
  packages/editor/src/lib/license/LicenseManager.ts
Labels: other

#6842 Eslint improvements
  .eslintplugin.js
  .github/workflows/claude.yml
  .prettierignore
  MARKETING_STYLE_GUIDE.md
  eslint.config.mjs
  internal/scripts/eslint/eslint-plugin.mjs
  internal/scripts/eslint/eslint-plugin.mts
  internal/scripts/eslint/tsconfig.json
  lazy.config.ts
Labels: improvement

#6853 Delete user's data in analytics.
  .github/workflows/deploy-dotcom.yml
  apps/dotcom/sync-worker/src/adminRoutes.ts
  apps/dotcom/sync-worker/src/types.ts
  internal/scripts/deploy-dotcom.ts
Labels: improvement
