Repository tldraw/tldraw, pull requests merged in 2025-02, with the labels that each got.

#5344 Don't allow setting file name to null. Fix drag and drop import.
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
Labels: bugfix

#5341 Add "select geo tool" shortcut
  packages/tldraw/src/lib/ui/context/actions.tsx
Labels: feature

#5348 Move to server side slurping.
  apps/dotcom/client/src/pages/tla-new.tsx
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopRightPanel.tsx
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarCreateFileButton.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaDeleteFileDialog.tsx
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
  apps/dotcom/client/src/tla/pages/file.tsx
  apps/dotcom/client/src/tla/pages/local.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/utils/tla/getLegacyRoomData.ts
  apps/dotcom/zero-cache/migrations/011_file_creation_column.sql
  packages/dotcom-shared/src/index.ts
  packages/dotcom-shared/src/routes.ts
  packages/dotcom-shared/src/tlaSchema.ts
  packages/dotcom-shared/src/types.ts
Labels: improvement

#5350 Fix tldr file upload
  .husky/pre-commit
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaAccountMenu/TlaAccountMenu.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/sneaky/SneakyFileDropHandler.tsx
  apps/dotcom/client/src/tla/hooks/useTldrFileDrop.ts
  apps/dotcom/sync-worker/src/routes/tla/createFiles.ts
  apps/dotcom/sync-worker/src/utils/tla/getAuth.ts
  apps/dotcom/sync-worker/src/utils/validateSnapshot.ts
Labels: bugfix

#5353 add a captureException to catch file.name not being defined
  apps/dotcom/client/src/tla/app/TldrawApp.ts
Labels: other

#5340 Add option to disable numbered shortcuts on the toolbar
  packages/editor/api-report.api.md
  packages/editor/src/lib/options.ts
  packages/tldraw/src/lib/ui/components/Toolbar/OverflowingToolbar.tsx
Labels: api

#5351 make websocket bootstrap time much faster
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/app/zero-polyfill.ts
  apps/dotcom/client/src/tla/hooks/useAppState.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
Labels: other

#5358 Fix keyboard shortcut `1` not working for selecting the first tool
  packages/tldraw/src/lib/ui/components/Toolbar/OverflowingToolbar.tsx
Labels: bugfix

#5355 Only send once.
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
Labels: improvement

#5359 Add 'report a problem' dialog
  .github/workflows/deploy-dotcom.yml
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaAppMenuGroup/TlaAppMenuGroup.tsx
  apps/dotcom/client/src/tla/components/TlaFileError/TlaFileError.tsx
  apps/dotcom/client/src/tla/components/dialogs/SubmitFeedbackDialog.tsx
  apps/dotcom/client/src/tla/components/tla-form/tla-form.tsx
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/routes/submitFeedback.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/src/worker.ts
  internal/scripts/deploy-dotcom.ts
  packages/dotcom-shared/src/types.ts
Labels: other

#5364 better copy on feedback form
  apps/dotcom/client/src/tla/components/dialogs/SubmitFeedbackDialog.tsx
Labels: other

#5367 buffer posthog events submitted before posthog initializes
  apps/dotcom/client/src/utils/posthog.tsx
Labels: other

#5365 Commit the copy changes.
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
Labels: bugfix

#5366 Fix dialog interactions.
  packages/tldraw/src/lib/ui/components/Dialogs.tsx
Labels: improvement

#5369 Fix dancing icons.
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/TlaSidebarLayout.tsx
Labels: improvement

#5372 Landing page text
  apps/docs/components/marketing/hero-section.tsx
  apps/docs/components/search/SearchAutocomplete.tsx
Labels: other

#5370 Fix pricing and license links
  apps/docs/components/common/blue-a.tsx
  apps/docs/components/marketing/faq-section.tsx
  apps/docs/components/marketing/watermark-section.tsx
Labels: other

#5361 Use tick for asset debounce
  packages/tldraw/src/lib/shapes/shared/useImageOrVideoAsset.ts
Labels: improvement

#5373 dotdev: add hubspot tracking and cookie policy
  apps/docs/app/analytics.tsx
  apps/docs/app/layout.tsx
  apps/docs/components/navigation/footer.tsx
  apps/docs/package.json
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarCookieConsent.tsx
  yarn.lock
Labels: other

#5377 Track tracking
  apps/docs/app/analytics.tsx
Labels: other

#5378 Numeric shortcuts were still getting triggered when used inside some inputs (like the file rename input)
  packages/editor/api-report.api.md
  packages/editor/src/index.ts
  packages/editor/src/lib/hooks/useDocumentEvents.ts
  packages/editor/src/lib/utils/dom.ts
  packages/tldraw/src/lib/ui/components/Toolbar/OverflowingToolbar.tsx
Labels: bugfix

#5379 Fix local drafts
  apps/docs/content/sections.json
  apps/docs/scripts/lib/refreshContent.ts
  apps/docs/watcher.ts
Labels: other

#5380 Track user do cold start time on server side replicator
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/types.ts
Labels: improvement

#5383 Make sure compiled localizations are up to date.
  .github/workflows/checks.yml
Labels: improvement

#5384 add missing socket upgrade check
  apps/dotcom/sync-worker/src/worker.ts
Labels: other

#5371 Improve published file experience
  apps/dotcom/client/e2e/tests/sharing.spec.ts
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaPublishEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor-messages.ts
  apps/dotcom/client/src/tla/components/TlaEditor/useFileEditorOverrides.ts
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/pages/local-file.tsx
  apps/dotcom/client/src/tla/pages/publish.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/routes/tla/getPublishedFile.ts
  packages/dotcom-shared/src/index.ts
  packages/dotcom-shared/src/routes.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/utils/export/exportAs.ts
Labels: improvement

#5390 Dismiss the sidebar on mobile (after you select a file).
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
Labels: improvement

#5394 Add dev env variable (makes the asset association work locally)
  apps/dotcom/sync-worker/wrangler.toml
Labels: improvement

#5396 Show errors when loading legacy multiplayer rooms and when logged in
  apps/dotcom/client/src/tla/components/TlaEditor/TlaLegacyFileEditor.tsx
Labels: bugfix

#5398 Remove file delete route
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/sync-worker/src/routes/tla/deleteFile.ts
  apps/dotcom/sync-worker/src/worker.ts
Labels: improvement

#5397 Make updates less frequent
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
Labels: improvement

#5399 ShapeUtil.configure for shape options
  apps/examples/src/examples/resize-note/ResizeNoteExample.tsx
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/Tldraw.tsx
  packages/tldraw/src/lib/shapes/draw/DrawShapeUtil.tsx
  packages/tldraw/src/lib/shapes/draw/toolStates/Drawing.ts
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/test/resizing.test.ts
  packages/utils/api-report.api.md
  packages/utils/src/index.ts
  packages/utils/src/lib/array.ts
Labels: api

#5403 Add more info to the log
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
Labels: improvement

#5400 Fix file permissions
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
Labels: bugfix

#5404 Make sure we only allow asset uploads.
  apps/dotcom/client/src/utils/config.ts
  apps/dotcom/client/src/utils/multiplayerAssetStore.ts
  apps/dotcom/image-resize-worker/package.json
  apps/dotcom/image-resize-worker/src/worker.ts
  apps/dotcom/image-resize-worker/tsconfig.json
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  packages/dotcom-shared/src/routes.ts
  yarn.lock
Labels: improvement

#5406 add create-user event
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
Labels: other

#5407 Add is_signed_in property to posthog events
  apps/dotcom/client/src/utils/posthog.tsx
Labels: other

#5409 Create a new stub each time
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
Labels: improvement

#5413 Move computation to where it is needed
  packages/tldraw/src/lib/shapes/frame/frameHelpers.ts
Labels: improvement

#5414 use correct domain for app socket connection
  apps/dotcom/client/src/tla/app/TldrawApp.ts
Labels: other

#5402 Add tldraw and excalidraw to external content types
  apps/examples/src/examples/custom-paste/CustomPasteExample.tsx
  apps/examples/src/examples/custom-paste/README.md
  apps/examples/src/index.tsx
  packages/editor/api-report.api.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/types/external-content.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/ui/hooks/clipboard/pasteTldrawContent.ts
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
  packages/tldraw/src/lib/utils/excalidraw/__snapshots__/putExcalidrawContent.test.tsx.snap
  packages/tldraw/src/lib/utils/excalidraw/excalidraw-test-fixtures/bound-arrows.json
  packages/tldraw/src/lib/utils/excalidraw/excalidraw-test-fixtures/image.json
  packages/tldraw/src/lib/utils/excalidraw/excalidraw-test-fixtures/line-drawing.json
  packages/tldraw/src/lib/utils/excalidraw/putExcalidrawContent.test.tsx
  packages/tldraw/src/lib/utils/excalidraw/putExcalidrawContent.ts
Labels: api

#5411 support dragging urls onto the canvas
  packages/editor/src/lib/hooks/useCanvasEvents.ts
Labels: improvement

#5416 Add additional reboot info.
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/types.ts
Labels: improvement

#5419 Secret local file index
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/routeDefs.ts
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/client/src/tla/pages/local-file-index.tsx
  apps/dotcom/client/src/tla/pages/local-file.tsx
Labels: other

#5426 Prevent renaming twice
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarRenameInline.tsx
Labels: bugfix

#5427 fix svg image export mime type
  packages/editor/src/lib/editor/Editor.ts
Labels: bugfix

#5425 Actively prune users.
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
Labels: improvement

#5430 Replace postgres.js pt 1
  apps/dotcom/client/e2e/fixtures/Database.ts
  apps/dotcom/client/package.json
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/postgres.ts
  apps/dotcom/zero-cache/migrate.ts
  apps/dotcom/zero-cache/package.json
  internal/scripts/clean.sh
  yarn.lock
Labels: other

#5443 i18n: simplify string
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/dialogs/SubmitFeedbackDialog.tsx
Labels: other

#5445 Remove file creation route.
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/pages/public-touchscreen-side-panel.tsx
  apps/dotcom/client/src/routeDefs.ts
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/sync-worker/src/routes/createRoom.ts
  apps/dotcom/sync-worker/src/worker.ts
Labels: improvement

#5440 Add dotcom checks that will serve for alerting
  .github/workflows/deploy-dotcom.yml
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLStatsDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/healthCheckRoutes.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/src/utils/durableObjects.ts
  apps/dotcom/sync-worker/src/utils/tla/getAuth.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/sync-worker/wrangler.toml
  internal/scripts/deploy-dotcom.ts
Labels: improvement

#5450 Add link to developer survey
  apps/docs/app/analytics.tsx
  apps/docs/app/layout.tsx
  apps/docs/components/common/talk-to-me.tsx
  apps/docs/content/getting-started/releases-versioning.mdx
Labels: other

#5453 assets: fix up regression with temporaryAssetPreview
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: bugfix

#5433 switch to pg-logical-replication
  .yarn/patches/postgres-npm-3.4.5-8a680ccbcd.patch
  apps/dotcom/client/src/tla/pages/worker-debug-tail.tsx
  apps/dotcom/sync-worker/package.json
  apps/dotcom/sync-worker/src/TLLoggerDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/testRoutes.ts
  apps/dotcom/sync-worker/src/worker.ts
  apps/dotcom/zero-cache/clean.sh
  apps/dotcom/zero-cache/docker/docker-compose.yml
  packages/utils/api-report.api.md
  packages/utils/src/lib/ExecutionQueue.ts
  yarn.lock
Labels: other

#5448 Add backend check for max files
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  packages/dotcom-shared/src/constants.ts
  packages/dotcom-shared/src/index.ts
  packages/dotcom-shared/src/types.ts
Labels: improvement

#5460 retry slurping document records if need be
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/utils/slurping.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  packages/dotcom-shared/src/routes.ts
Labels: bugfix

#5465 Deleted files improvements
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/getFetchEverythingSql.ts
Labels: improvement

#5464 Fix typo and missing word
  apps/docs/content/docs/persistence.mdx
Labels: other

#5461 Add sidebar context menu
  apps/dotcom/client/package.json
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
  yarn.lock
Labels: improvement

#5470 [hotfixme] Option-cloning text shapes
  packages/tldraw/src/lib/shapes/frame/components/FrameLabelInput.tsx
  packages/tldraw/src/lib/shapes/text/TextArea.tsx
Labels: bugfix

#5462 [botcom] Only prune the users that haven't been active for 10 minutes.
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
Labels: improvement

#5484 i18n: if no new strings, just exit
  .github/workflows/i18n-download-strings.yml
Labels: other

#5482 fix copy as svg mime type
  packages/tldraw/src/lib/utils/clipboard.ts
  packages/tldraw/src/lib/utils/export/copyAs.ts
  packages/tldraw/src/lib/utils/export/export.ts
Labels: bugfix

#5485 Fix tooltips.
  apps/dotcom/client/src/tla/components/TlaTooltip/tooltip.module.css
Labels: bugfix

#5486 Fix safari tooltip arrow appears late
  apps/dotcom/client/src/tla/components/TlaTooltip/tooltip.module.css
Labels: bugfix

#5483 Use a sprite for our dotcom icons.
  apps/dotcom/client/index.html
  apps/dotcom/client/public/tla/0_merged_tla.svg
  apps/dotcom/client/public/tla/icon-check.svg
  apps/dotcom/client/public/tla/icon-chevron-down-strong.svg
  apps/dotcom/client/public/tla/icon-chevron-down.svg
  apps/dotcom/client/public/tla/icon-chevron-right-strong.svg
  apps/dotcom/client/public/tla/icon-chevron-right.svg
  apps/dotcom/client/public/tla/icon-chevron-up-strong.svg
  apps/dotcom/client/public/tla/icon-chevron-up.svg
  apps/dotcom/client/public/tla/icon-close-strong.svg
  apps/dotcom/client/public/tla/icon-close.svg
  apps/dotcom/client/public/tla/icon-copy-strong.svg
  apps/dotcom/client/public/tla/icon-copy.svg
  apps/dotcom/client/public/tla/icon-doc-strong.svg
  apps/dotcom/client/public/tla/icon-doc.svg
  apps/dotcom/client/public/tla/icon-dots-horizontal-strong.svg
  apps/dotcom/client/public/tla/icon-dots-horizontal.svg
  apps/dotcom/client/public/tla/icon-dots-vertical-strong.svg
  apps/dotcom/client/public/tla/icon-dots-vertical.svg
  apps/dotcom/client/public/tla/icon-draw.svg
  apps/dotcom/client/public/tla/icon-edit-strong.svg
  apps/dotcom/client/public/tla/icon-edit.svg
  apps/dotcom/client/public/tla/icon-export.svg
  apps/dotcom/client/public/tla/icon-external.svg
  apps/dotcom/client/public/tla/icon-group-strong.svg
  apps/dotcom/client/public/tla/icon-group.svg
  apps/dotcom/client/public/tla/icon-home-strong.svg
  apps/dotcom/client/public/tla/icon-home.svg
  apps/dotcom/client/public/tla/icon-import.svg
  apps/dotcom/client/public/tla/icon-info.svg
  apps/dotcom/client/public/tla/icon-link-strong.svg
  apps/dotcom/client/public/tla/icon-link.svg
  apps/dotcom/client/public/tla/icon-more.svg
  apps/dotcom/client/public/tla/icon-pin-strong.svg
  apps/dotcom/client/public/tla/icon-pin.svg
  apps/dotcom/client/public/tla/icon-plus-strong.svg
  apps/dotcom/client/public/tla/icon-plus.svg
  apps/dotcom/client/public/tla/icon-qr.svg
  apps/dotcom/client/public/tla/icon-question-circle.svg
  apps/dotcom/client/public/tla/icon-share.svg
  apps/dotcom/client/public/tla/icon-sidebar-strong.svg
  apps/dotcom/client/public/tla/icon-sidebar.svg
  apps/dotcom/client/public/tla/icon-sign-in.svg
  apps/dotcom/client/public/tla/icon-spinner.svg
  apps/dotcom/client/public/tla/icon-star-fill.svg
  apps/dotcom/client/public/tla/icon-star-strong-fill.svg
  apps/dotcom/client/public/tla/icon-star-strong.svg
  apps/dotcom/client/public/tla/icon-star.svg
  apps/dotcom/client/public/tla/icon-tldraw.svg
  apps/dotcom/client/public/tla/icon-update.svg
  apps/dotcom/client/public/tla/spinner.svg
  apps/dotcom/client/src/tla/components/TlaIcon/TlaIcon.tsx
  internal/scripts/refresh-assets.ts
Labels: improvement

#5491 Add analytics to examples site
  apps/examples/src/index.tsx
Labels: other

#5492 Landing page fixes
  apps/docs/components/marketing/testimonials-section.tsx
  apps/docs/components/navigation/footer.tsx
  apps/docs/components/navigation/header.tsx
Labels: other

#5488 Remove canvas size dependency
  .yarn/patches/canvas-size-npm-2.0.0-822398a242.patch
  package.json
  packages/editor/api-report.api.md
  packages/editor/package.json
  packages/editor/src/lib/exports/getSvgAsImage.ts
  packages/editor/src/lib/globals/environment.ts
  packages/editor/src/lib/utils/browserCanvasMaxSize.ts
  packages/tldraw/src/lib/utils/assets/assets.ts
  yarn.lock
Labels: improvement

#5487 Fix text padding, add context to shape geometry
  packages/editor/api-report.api.md
  packages/editor/src/index.ts
  packages/editor/src/lib/editor/Editor.ts
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/arrow/shared.ts
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
Labels: improvement, api

#5498 icons: followup to add crossorigin
  apps/dotcom/client/index.html
Labels: other

#5435 [botcom] Fix slow export menu in big files
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaExportTab.tsx
  packages/editor/src/lib/exports/getSvgJsx.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
Labels: bugfix

#5499 SEO keywords / description for dotcom
  apps/dotcom/client/index.html
Labels: other

#5501 Improve triggers and hopefully fix an issue with deadlocks
  apps/dotcom/zero-cache/migrations/012_prevent_deadlocks.sql
Labels: bugfix

#5490 Use vite to load the assets
  apps/dotcom/client/assets/icons/icon/icon-check.svg
  apps/dotcom/client/assets/icons/icon/icon-chevron-down-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-chevron-down.svg
  apps/dotcom/client/assets/icons/icon/icon-chevron-right-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-chevron-right.svg
  apps/dotcom/client/assets/icons/icon/icon-chevron-up-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-chevron-up.svg
  apps/dotcom/client/assets/icons/icon/icon-close-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-close.svg
  apps/dotcom/client/assets/icons/icon/icon-copy-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-copy.svg
  apps/dotcom/client/assets/icons/icon/icon-doc-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-doc.svg
  apps/dotcom/client/assets/icons/icon/icon-dots-horizontal-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-dots-horizontal.svg
  apps/dotcom/client/assets/icons/icon/icon-dots-vertical-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-dots-vertical.svg
  apps/dotcom/client/assets/icons/icon/icon-draw.svg
  apps/dotcom/client/assets/icons/icon/icon-edit-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-edit.svg
  apps/dotcom/client/assets/icons/icon/icon-export.svg
  apps/dotcom/client/assets/icons/icon/icon-external.svg
  apps/dotcom/client/assets/icons/icon/icon-group-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-group.svg
  apps/dotcom/client/assets/icons/icon/icon-home-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-home.svg
  apps/dotcom/client/assets/icons/icon/icon-import.svg
  apps/dotcom/client/assets/icons/icon/icon-info.svg
  apps/dotcom/client/assets/icons/icon/icon-link-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-link.svg
  apps/dotcom/client/assets/icons/icon/icon-more.svg
  apps/dotcom/client/assets/icons/icon/icon-pin-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-pin.svg
  apps/dotcom/client/assets/icons/icon/icon-plus-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-plus.svg
  apps/dotcom/client/assets/icons/icon/icon-qr.svg
  apps/dotcom/client/assets/icons/icon/icon-question-circle.svg
  apps/dotcom/client/assets/icons/icon/icon-share.svg
  apps/dotcom/client/assets/icons/icon/icon-sidebar-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-sidebar.svg
  apps/dotcom/client/assets/icons/icon/icon-sign-in.svg
  apps/dotcom/client/assets/icons/icon/icon-spinner.svg
  apps/dotcom/client/assets/icons/icon/icon-star-fill.svg
  apps/dotcom/client/assets/icons/icon/icon-star-strong-fill.svg
  apps/dotcom/client/assets/icons/icon/icon-star-strong.svg
  apps/dotcom/client/assets/icons/icon/icon-star.svg
  apps/dotcom/client/assets/icons/icon/icon-tldraw.svg
  apps/dotcom/client/assets/icons/icon/icon-update.svg
  apps/dotcom/client/index.html
  apps/dotcom/client/scripts/build.ts
  apps/dotcom/client/src/assets/0_merged_tla.svg
  apps/dotcom/client/src/tla/components/TlaIcon/TlaIcon.tsx
  internal/scripts/refresh-assets.ts
  lazy.config.ts
Labels: improvement

#5509 getImageSize: Fix inaccurate PNG image width height calculation by using exact pixels per meter value
  packages/utils/src/lib/media/media.ts
Labels: bugfix

#5496 Add `AtomMap` & refactor store
  apps/dotcom/client/index.html
  packages/editor/src/lib/editor/Editor.ts
  packages/store/api-report.api.md
  packages/store/src/index.ts
  packages/store/src/lib/AtomMap.ts
  packages/store/src/lib/Store.ts
  packages/store/src/lib/StoreQueries.ts
  packages/store/src/lib/test/AtomMap.test.ts
Labels: api

#5512 Stabilize useSync invocation
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
Labels: other

#5514 Docs improvements, add FAQ to repo.
  FAQ.md
  apps/docs/app/(marketing)/page.tsx
  apps/docs/app/layout.tsx
  apps/docs/app/not-found.tsx
  apps/docs/components/common/talk-to-me.tsx
  apps/docs/components/docs/docs-category-menu.tsx
  apps/docs/components/marketing/hero-section.tsx
  apps/docs/components/marketing/pricing-section.tsx
  apps/docs/content/docs/editor.mdx
  apps/docs/utils/autoLinkDocs.ts
  apps/examples/src/examples.tsx
  apps/examples/src/examples/camera-options/README.md
  apps/examples/src/examples/lock-camera-zoom/README.md
  apps/examples/src/examples/snapshots/README.md
  apps/examples/src/examples/ui-events/README.md
Labels: other

#5510 Fix file dropdown crashing the app on slow connections
  apps/dotcom/client/src/tla/components/TlaEditor/useFileEditorOverrides.ts
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
Labels: bugfix

#5495 Fix issue with duplicating bound arrows.
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/src/test/bindings.test.tsx
Labels: bugfix

#5518 Fix header width
  apps/docs/components/marketing/hero-section.tsx
Labels: other

#5497 no reboot user data on deploy
  apps/bemo-worker/package.json
  apps/dotcom/asset-upload-worker/package.json
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/app/zero-polyfill.ts
  apps/dotcom/image-resize-worker/package.json
  apps/dotcom/sync-worker/package.json
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserChangeCollator.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/getFetchEverythingSql.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/tsconfig.json
  apps/dotcom/sync-worker/wrangler.toml
  apps/dotcom/zero-cache/migrations/013_add_userid_to_file_key.sql
  internal/health-worker/package.json
  packages/dotcom-shared/src/OptimisticAppStore.ts
  packages/dotcom-shared/src/types.ts
  packages/worker-shared/package.json
  yarn.lock
Labels: other

#5519 icons: add crossorigin property for the new sprite loading
  apps/dotcom/client/src/utils/assetUrls.ts
Labels: other

#5520 Admin UI + backend fixes
  apps/dotcom/client/src/__snapshots__/routes.test.tsx.snap
  apps/dotcom/client/src/pages/admin.tsx
  apps/dotcom/client/src/routes.tsx
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/adminRoutes.ts
  apps/dotcom/sync-worker/src/types.ts
  apps/dotcom/sync-worker/src/worker.ts
Labels: other

#5521 Use a deep link
  apps/dotcom/client/src/tla/components/TlaFileMenu/TlaFileMenu.tsx
Labels: bugfix

#5522 Do hard deletes reactively
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/routes/tla/getPublishedFile.ts
  apps/dotcom/zero-cache/migrations/014_add_publishedSlug_to_file_key.sql
Labels: other
