Repository tldraw/tldraw, pull requests merged in 2025-10, with the labels that each got.

#6854 Don't filter out inputMode preferences when it's null (the default) when updating preferences on the backend
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  packages/dotcom-shared/src/types.ts
Labels: bugfix

#6830 feat: add Numpad Enter support for text shape editing
  packages/tldraw/src/lib/shapes/text/TextShapeTool.test.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/Idle.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Idle.ts
Labels: feature

#6858 update wranglers
  templates/agent/wrangler.toml
  templates/branching-chat/wrangler.toml
  templates/sync-cloudflare/wrangler.toml
Labels: other

#6864 fix e2e tests in newer node versions
  apps/dotcom/client/package.json
  apps/examples/package.json
Labels: other

#6865 docs: fix ShapeUtil reference from getBounds to getGeometry
  apps/docs/content/docs/shapes.mdx
Labels: other

#6860 Add comprehensive JSDoc documentation for useReactor
  packages/state-react/api-report.api.md
  packages/state-react/src/lib/useReactor.ts
Labels: docs

#6863 Fix layer panel visibility toggle buttons
  apps/examples/src/examples/layer-panel/ShapeList.tsx
  apps/examples/src/examples/layer-panel/layer-panel.css
Labels: other

#6327 minimap: omit arrows/lines
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/ui/components/Minimap/MinimapManager.ts
Labels: improvement

#6873 license: make the watermark hoverable if present
  packages/editor/src/lib/license/Watermark.tsx
Labels: other

#6871 Make sure templates don't use internal functions
  eslint.config.mjs
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/Editor.ts
  packages/store/api-report.api.md
  packages/store/src/lib/RecordsDiff.ts
  templates/agent/client/agent/TldrawAgent.ts
  templates/workflow/src/nodes/types/AddNode.tsx
  templates/workflow/src/nodes/types/ConditionalNode.tsx
  templates/workflow/src/nodes/types/DivideNode.tsx
  templates/workflow/src/nodes/types/EarthquakeNode.tsx
  templates/workflow/src/nodes/types/MultiplyNode.tsx
  templates/workflow/src/nodes/types/SliderNode.tsx
  templates/workflow/src/nodes/types/SubtractNode.tsx
  templates/workflow/src/utils/sleep.ts
Labels: api, sdk-hotfix-please

#6877 Reduce claude reviews
  .github/workflows/claude-code-review.yml
Labels: other

#6876 localStorageAtom
  packages/state/api-report.api.md
  packages/state/src/index.ts
  packages/state/src/lib/__tests__/localStorageAtom.test.ts
  packages/state/src/lib/localStorageAtom.ts
Labels: api

#6847 Shader starter kit
  apps/docs/content/getting-started/releases.mdx
  packages/create-tldraw/src/templates.ts
  templates/shader/.gitignore
  templates/shader/LICENSE.md
  templates/shader/README.md
  templates/shader/index.html
  templates/shader/package.json
  templates/shader/public/favicon.ico
  templates/shader/src/App.tsx
  templates/shader/src/WebGLCanvas.tsx
  templates/shader/src/WebGLManager.ts
  templates/shader/src/config-panel/ConfigPanel.tsx
  templates/shader/src/config-panel/ConfigPanelBooleanControl.tsx
  templates/shader/src/config-panel/ConfigPanelLabel.tsx
  templates/shader/src/config-panel/ConfigPanelSlider.tsx
  templates/shader/src/config-panel/config-panel.md
  templates/shader/src/fluid/FluidConfigPanel.tsx
  templates/shader/src/fluid/FluidManager.ts
  templates/shader/src/fluid/FluidRenderer.tsx
  templates/shader/src/fluid/config.ts
  templates/shader/src/fluid/fluid.md
  templates/shader/src/fluid/fluid.ts
  templates/shader/src/index.css
  templates/shader/src/main.tsx
  templates/shader/src/minimal/MinimalConfigPanel.tsx
  templates/shader/src/minimal/MinimalRenderer.tsx
  templates/shader/src/minimal/MinimalShaderManager.ts
  templates/shader/src/minimal/config.ts
  templates/shader/src/minimal/fragment.glsl
  templates/shader/src/minimal/minimal-example.md
  templates/shader/src/minimal/vertex.glsl
  templates/shader/src/rainbow/RainbowConfigPanel.tsx
  templates/shader/src/rainbow/RainbowRenderer.tsx
  templates/shader/src/rainbow/RainbowShaderManager.ts
  templates/shader/src/rainbow/config.ts
  templates/shader/src/rainbow/fragment.glsl
  templates/shader/src/rainbow/rainbow-example.md
  templates/shader/src/rainbow/vertex.glsl
  templates/shader/src/shader.css
  templates/shader/src/shadow/ShadowControlPanel.tsx
  templates/shader/src/shadow/ShadowRenderer.tsx
  templates/shader/src/shadow/ShadowShaderManager.ts
  templates/shader/src/shadow/config.ts
  templates/shader/src/shadow/fragment.glsl
  templates/shader/src/shadow/shadow-example.md
  templates/shader/src/shadow/vertex.glsl
  templates/shader/src/vite-env.d.ts
  templates/shader/tsconfig.json
  templates/shader/vite-env.d.ts
  templates/shader/vite.config.ts
  yarn.lock
Labels: other

#6874 Make the new embedOnPaste option a non-breaking change
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: other

#6885 Handle no vertices gracefully
  packages/editor/src/lib/primitives/geometry/Geometry2d.ts
Labels: bugfix, sdk-hotfix-please

#6889 Remove unnecessary console.log from TldrawApp
  apps/dotcom/client/src/tla/app/TldrawApp.ts
Labels: internal

#6895 Improve mobile breakpoints
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopRightPanel.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
  apps/dotcom/client/src/tla/styles/tla.css
  packages/tldraw/src/lib/ui/components/SharePanel/PeopleMenu.tsx
Labels: improvement

#6896 docs: fix sync demo link
  apps/docs/content/docs/collaboration.mdx
Labels: other, docs-hotfix-please
