Repository tldraw/tldraw, pull requests merged in 2025-08, with the labels that each got.

#6530 Track room load duration
  apps/dotcom/client/src/hooks/useRoomLoadTracking.ts
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditor.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaLegacyFileEditor.tsx
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  packages/dotcom-shared/src/constants.ts
Labels: improvement

#6531 add EditorAtom helper
  packages/editor/api-report.api.md
  packages/editor/src/index.ts
  packages/editor/src/lib/utils/EditorAtom.ts
Labels: api

#6524 Add solo sync mode
  packages/sync-core/api-report.api.md
  packages/sync-core/src/index.ts
  packages/sync-core/src/lib/TLSyncClient.ts
  packages/sync-core/src/test/presenceMode.test.ts
  packages/sync/src/useSync.ts
Labels: improvement

#6549 Fix: change handlers not passed to new room instance
  packages/sync-core/src/lib/TLSocketRoom.ts
  packages/sync-core/src/test/TLSocketRoom.test.ts
Labels: bugfix, sdk-hotfix-please, dotcom-hotfix-please

#6548 changes room name to avoid overcrowding
  apps/docs/content/getting-started/quick-start.mdx
  apps/docs/content/getting-started/releases-versioning.mdx
Labels: other

#6444 a11y: add preference to show labels/tooltips
  apps/dotcom/client/e2e/fixtures/Database.ts
  apps/dotcom/client/e2e/tests/sharing.spec.ts
  apps/dotcom/client/src/tla/app/TldrawApp.ts
  apps/dotcom/client/src/tla/components/TlaSidebar/components/TlaSidebarFileLink.tsx
  apps/dotcom/client/src/tla/components/TlaTooltip/TlaTooltip.tsx
  apps/dotcom/client/src/tla/components/TlaTooltip/tooltip.module.css
  apps/dotcom/client/src/tla/components/tla-menu/tla-menu.tsx
  apps/dotcom/sync-worker/src/fetchEverythingSql.snap.ts
  apps/dotcom/sync-worker/src/replicator/test-helpers.ts
  apps/dotcom/zero-cache/migrations/020_add_show_ui_labels_pref.sql
  assets/translations/main.json
  packages/dotcom-shared/src/tlaSchema.ts
  packages/dotcom-shared/src/types.ts
  packages/editor/api-report.api.md
  packages/editor/editor.css
  packages/editor/src/lib/config/TLUserPreferences.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager/UserPreferencesManager.test.ts
  packages/editor/src/lib/editor/managers/UserPreferencesManager/UserPreferencesManager.ts
  packages/editor/src/lib/options.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/shapes/shared/usePrefersReducedMotion.tsx
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/AccessibilityMenu.tsx
  packages/tldraw/src/lib/ui/components/MainMenu/DefaultMainMenuContent.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanel.tsx
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/OverflowingToolbar.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/ToggleToolLockedButton.tsx
  packages/tldraw/src/lib/ui/components/menu-items.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiToolbar.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiTooltip.tsx
  packages/tldraw/src/lib/ui/context/TldrawUiContextProvider.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: improvement

#6533 Unsaved changes examples
  apps/examples/src/examples/unsaved-changes/README.md
  apps/examples/src/examples/unsaved-changes/UnsavedChangesExample.tsx
  packages/store/api-report.api.md
  packages/store/src/lib/RecordsDiff.ts
Labels: api, other

#6560 Add delete user button to admin dashboard
  apps/dotcom/client/src/pages/admin.module.css
  apps/dotcom/client/src/pages/admin.tsx
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/adminRoutes.ts
Labels: other, dotcom-hotfix-please

#6562 Update the tldraw sync server readme
  templates/sync-cloudflare/README.md
Labels: other

#6466 Flatten color theme object
  apps/examples/src/examples/custom-config/CardShape/CardShapeUtil.tsx
  apps/examples/src/examples/custom-renderer/CustomRenderer.tsx
  apps/examples/src/examples/shape-with-tldraw-styles/ShapeWithTldrawStylesExample.tsx
  apps/examples/src/examples/speech-bubble/SpeechBubble/SpeechBubbleUtil.tsx
  packages/editor/src/lib/exports/getSvgJsx.tsx
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/draw/DrawShapeUtil.tsx
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/GeoShapeUtil.tsx
  packages/tldraw/src/lib/shapes/geo/components/GeoShapeBody.tsx
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx
  packages/tldraw/src/lib/shapes/shared/ShapeFill.tsx
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
  packages/tldraw/src/lib/ui/components/MobileStylePanel.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiButtonPicker.tsx
  packages/tlschema/api-report.api.md
  packages/tlschema/src/index.ts
  packages/tlschema/src/styles/TLColorStyle.ts
  templates/ai/worker/do/openai/getTldrawAiChangesFromSimpleEvents.ts
Labels: improvement, api

#6556 Initial slides in the Slides Example
  apps/examples/src/examples/slides/SlidesExample.tsx
Labels: other

#6532 Vertical toolbar example
  apps/examples/src/examples/toolbar-groups/README.md
  apps/examples/src/examples/toolbar-groups/ToolbarGroupsExample.tsx
  apps/examples/src/examples/vertical-toolbar/README.md
  apps/examples/src/examples/vertical-toolbar/VerticalToolbarExample.tsx
  apps/examples/src/styles.css
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/TldrawUi.tsx
  packages/tldraw/src/lib/ui/components/ActionsMenu/DefaultActionsMenu.tsx
  packages/tldraw/src/lib/ui/components/MobileStylePanel.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultToolbar.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/OverflowingToolbar.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiToolbar.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiTooltip.tsx
  packages/tldraw/src/lib/ui/components/primitives/layout.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuGroup.tsx
Labels: api

#6575 Stop tracking app events in GA, manually track page views.
  apps/dotcom/client/src/utils/analytics.tsx
Labels: improvement

#6568 namespace css variables
  apps/dotcom/client/src/tla/components/TlaButton/button.module.css
  apps/dotcom/client/src/tla/components/TlaCtaButton/cta-button.module.css
  apps/dotcom/client/src/tla/components/TlaEditor/SlurpFailure.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/editor.module.css
  apps/dotcom/client/src/tla/components/TlaEditor/top.module.css
  apps/dotcom/client/src/tla/components/TlaLogo/logo.module.css
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/components/dialogs/dialogs.module.css
  apps/dotcom/client/src/tla/components/tla-menu/menu.module.css
  apps/dotcom/client/src/tla/layouts/TlaSidebarLayout/sidebar-layout.module.css
  apps/dotcom/client/src/tla/styles/tla.css
  apps/dotcom/client/styles/globals.css
  apps/examples/src/examples/camera-options/CameraOptionsExample.tsx
  apps/examples/src/examples/drag-and-drop-tray/drag-and-drop-tray.css
  apps/examples/src/examples/editor-focus/editor-focus.css
  apps/examples/src/examples/image-annotator/image-annotator.css
  apps/examples/src/examples/pdf-editor/pdf-editor.css
  apps/examples/src/examples/screenshot-tool/ScreenshotToolExample.tsx
  apps/examples/src/examples/selection-color-condition/SelectionColorConditionExample.tsx
  apps/examples/src/examples/shape-with-custom-styles/ShapeWithCustomStylesExample.tsx
  apps/examples/src/examples/shape-with-tldraw-styles/ShapeWithTldrawStylesExample.tsx
  apps/examples/src/examples/slides/SlideShapeUtil.tsx
  apps/examples/src/examples/slides/SlidesPanel.tsx
  apps/examples/src/examples/slides/slides.css
  apps/examples/src/examples/text-search/text-search.css
  apps/vscode/editor/public/index.css
  packages/editor/editor.css
  packages/editor/src/lib/components/default-components/DefaultCollaboratorHint.tsx
  packages/editor/src/lib/components/default-components/DefaultScribble.tsx
  packages/editor/src/lib/components/default-components/DefaultShapeIndicator.tsx
  packages/editor/src/lib/license/Watermark.tsx
  packages/tldraw/src/lib/canvas/TldrawScribble.tsx
  packages/tldraw/src/lib/shapes/arrow/elbow/ElbowArrowDebug.tsx
  packages/tldraw/src/lib/shapes/embed/EmbedShapeUtil.tsx
  packages/tldraw/src/lib/shapes/frame/components/FrameHeading.tsx
  packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx
  packages/tldraw/src/lib/shapes/video/VideoShapeUtil.tsx
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/Minimap/MinimapManager.ts
  packages/tldraw/src/lib/ui/components/MobileStylePanel.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultImageToolbarContent.tsx
Labels: api

#6559 Add consent form for logged out users.
  apps/dotcom/client/src/components/LocalEditor.tsx
  apps/dotcom/client/src/components/TlaLoggedOutCookieConsent.module.css
  apps/dotcom/client/src/components/TlaLoggedOutCookieConsent.tsx
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopLeftPanel.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/TlaSidebar.tsx
  apps/dotcom/client/src/tla/components/TlaSidebar/sidebar.module.css
  apps/dotcom/client/src/tla/components/dialogs/TlaCookieConsent.tsx
  apps/dotcom/client/src/tla/components/dialogs/TlaManageCookiesDialog.tsx
  apps/dotcom/client/src/tla/components/dialogs/dialogs.module.css
  apps/dotcom/client/src/tla/hooks/useAnalyticsConsent.tsx
  apps/dotcom/client/src/utils/analytics.tsx
Labels: improvement

#6582 Tooltip fixes
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiTooltip.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuContext.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuGroup.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuItem.tsx
Labels: other

#6583 no frame color
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
Labels: other

#6587 fix shape fills
  packages/tldraw/src/lib/shapes/shared/ShapeFill.tsx
Labels: other

#6584 fix mobile cookie tooltip
  apps/dotcom/client/src/tla/components/dialogs/TlaManageCookiesDialog.tsx
  apps/dotcom/client/src/tla/components/tla-menu/tla-menu.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiTooltip.tsx
Labels: other

#6555 Add `zoomToBounds` example
  apps/examples/src/examples/education-canvas/README.md
  apps/examples/src/examples/zoom-to-bounds/README.md
  apps/examples/src/examples/zoom-to-bounds/ZoomToBoundsExample.tsx
Labels: feature

#6554 Accel key to only erase the top shape
  packages/tldraw/src/lib/tools/EraserTool/childStates/Erasing.ts
  packages/tldraw/src/lib/tools/EraserTool/childStates/Pointing.ts
  packages/tldraw/src/test/EraserTool.test.ts
Labels: bugfix

#6543 Fix dragging within multiple editors
  packages/editor/src/lib/hooks/useCanvasEvents.ts
Labels: bugfix

#6412 Workflow builder starter kit
  apps/analytics/package.json
  apps/docs/package.json
  apps/dotcom/client/package.json
  apps/dotcom/client/src/tla/utils/i18n.tsx
  apps/examples/package.json
  eslint.config.mjs
  internal/scripts/dev-template.sh
  packages/editor/src/lib/editor/Editor.ts
  packages/tldraw/package.json
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuItem.tsx
  templates/workflow/.gitignore
  templates/workflow/LICENSE.md
  templates/workflow/README.md
  templates/workflow/alex-notes.md
  templates/workflow/index.html
  templates/workflow/package.json
  templates/workflow/public/favicon.ico
  templates/workflow/src/App.tsx
  templates/workflow/src/components/MathematicalToolbarItem.tsx
  templates/workflow/src/components/OnCanvasComponentPicker.tsx
  templates/workflow/src/components/WorkflowRegions.tsx
  templates/workflow/src/components/WorkflowToolbar.tsx
  templates/workflow/src/components/icons/AddIcon.tsx
  templates/workflow/src/components/icons/ConditionalIcon.tsx
  templates/workflow/src/components/icons/DivideIcon.tsx
  templates/workflow/src/components/icons/MathematicalIcon.tsx
  templates/workflow/src/components/icons/MultiplyIcon.tsx
  templates/workflow/src/components/icons/PlayIcon.tsx
  templates/workflow/src/components/icons/SliderIcon.tsx
  templates/workflow/src/components/icons/StopIcon.tsx
  templates/workflow/src/components/icons/SubtractIcon.tsx
  templates/workflow/src/connection/ConnectionBindingUtil.tsx
  templates/workflow/src/connection/ConnectionShapeUtil.tsx
  templates/workflow/src/connection/insertNodeWithinConnection.tsx
  templates/workflow/src/connection/keepConnectionsAtBottom.tsx
  templates/workflow/src/constants.tsx
  templates/workflow/src/disableTransparency.tsx
  templates/workflow/src/execution/ExecutionGraph.tsx
  templates/workflow/src/execution/executionState.ts
  templates/workflow/src/hooks/useDragToCreate.ts
  templates/workflow/src/index.css
  templates/workflow/src/main.tsx
  templates/workflow/src/nodes/NodeShapeUtil.tsx
  templates/workflow/src/nodes/nodePorts.tsx
  templates/workflow/src/nodes/nodeTypes.tsx
  templates/workflow/src/nodes/types/AddNode.tsx
  templates/workflow/src/nodes/types/ConditionalNode.tsx
  templates/workflow/src/nodes/types/DivideNode.tsx
  templates/workflow/src/nodes/types/MultiplyNode.tsx
  templates/workflow/src/nodes/types/SliderNode.tsx
  templates/workflow/src/nodes/types/SubtractNode.tsx
  templates/workflow/src/nodes/types/shared.tsx
  templates/workflow/src/ports/PointingPort.tsx
  templates/workflow/src/ports/Port.tsx
  templates/workflow/src/ports/getPortAtPoint.tsx
  templates/workflow/src/ports/portState.ts
  templates/workflow/src/utils.ts
  templates/workflow/tsconfig.json
  templates/workflow/vite.config.ts
  yarn.lock
Labels: other

#6596 increase drag threshold for mobile toolbar
  packages/editor/api-report.api.md
  packages/editor/src/lib/options.ts
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuItem.tsx
Labels: bugfix, dotcom-hotfix-please

#6600 Add more context, maybe
  CLAUDE.md
  CONTEXT.md
  README.md
  internal/scripts/context.ts
  internal/scripts/refresh-context.ts
  lazy.config.ts
  package.json
  packages/ai/package.json
  packages/assets/package.json
  packages/create-tldraw/package.json
  packages/dotcom-shared/package.json
  packages/editor/package.json
  packages/namespaced-tldraw/package.json
  packages/state-react/package.json
  packages/state/package.json
  packages/store/package.json
  packages/sync-core/package.json
  packages/sync/package.json
  packages/tldraw/package.json
  packages/tlschema/package.json
  packages/utils/package.json
  packages/validate/package.json
  packages/worker-shared/package.json
Labels: other

#6613 fix extra dropdown slot and bad gradient in style panel
  packages/tldraw/src/lib/ui.css
  packages/tldraw/src/lib/ui/components/StylePanel/DropdownPicker.tsx
Labels: other

#6625 Expose `notifyIfFileNotAllowed` helper
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
Labels: api

#6639 examples: dont minify the JS bundle for debuggability in prod
  apps/examples/vite.config.ts
Labels: other

#6638 kbd shortcuts: fix up some badly formatted ones on win/linux
  packages/tldraw/src/lib/ui/components/KeyboardShortcutsDialog/DefaultKeyboardShortcutsDialogContent.tsx
  packages/tldraw/src/lib/ui/kbd-utils.ts
Labels: bugfix

#6653 Add translation key for rhombus
  assets/translations/main.json
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/hooks/useTranslation/TLUiTranslationKey.ts
  packages/tldraw/src/lib/ui/hooks/useTranslation/defaultTranslation.ts
Labels: bugfix

#6654 Track which url was opened.
  apps/dotcom/client/src/hooks/useOpenUrlAndTrack.ts
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaInviteTab.tsx
  apps/dotcom/client/src/tla/components/TlaFileShareMenu/Tabs/TlaPublishTab.tsx
  apps/dotcom/client/src/tla/utils/app-ui-events.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/context/events.tsx
Labels: bugfix

#6666 Save and reinstate documentClock properly
  packages/sync-core/api-report.api.md
  packages/sync-core/src/lib/TLSocketRoom.ts
  packages/sync-core/src/lib/TLSyncRoom.ts
  packages/sync-core/src/test/TLSocketRoom.test.ts
  packages/sync-core/src/test/TLSyncRoom.test.ts
Labels: bugfix

#6668 Updates language (license page)
  apps/docs/content/community/license.mdx
Labels: other, docs-hotfix-please

#6665 Fix internal license logic.
  apps/examples/e2e/tests/test-licensing.spec.ts
  apps/examples/src/misc/end-to-end.tsx
  packages/editor/api-report.api.md
  packages/editor/src/index.ts
  packages/editor/src/lib/license/LicenseManager.test.ts
  packages/editor/src/lib/license/LicenseManager.ts
  packages/editor/src/lib/license/LicenseProvider.tsx
  packages/editor/src/lib/license/useLicenseManagerState.ts
Labels: bugfix, sdk-hotfix-please

#6662 bump Next.js to 15.4.6
  apps/docs/app/(docs)/[...slug]/page.tsx
  apps/docs/app/(marketing)/legal/[slug]/page.tsx
  apps/docs/app/blog/[...slug]/page.tsx
  apps/docs/components/content/index.tsx
  apps/docs/next-env.d.ts
  apps/docs/next.config.js
  apps/docs/package.json
  templates/nextjs/package.json
  yarn.lock
Labels: other

#6675 Fix dotcom e2e tests
  apps/dotcom/client/e2e/fixtures/HomePage.ts
Labels: bugfix
