Repository tldraw/tldraw, pull requests merged in 2025-07, with the labels that each got.

#6323 crop: improve preserving crop across aspect ratios and replacement
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/shapes/shared/crop.ts
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultImageToolbar.tsx
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultImageToolbarContent.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiContextualToolbar.tsx
  packages/tldraw/src/test/crop.test.ts
Labels: improvement

#6358 a11y: fix some issues from the audit
  apps/dotcom/client/src/tla/components/TlaLogo/TlaLogo.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/arrow/ArrowShapeUtil.tsx
  packages/tldraw/src/lib/shapes/draw/DrawShapeUtil.tsx
  packages/tldraw/src/lib/shapes/highlight/HighlightShapeUtil.tsx
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiButtonPicker.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiToolbar.tsx
Labels: improvement

#6362 Examples guide
  apps/examples/README.md
  apps/examples/writing-examples.md
Labels: other

#6367 Example: outline text (custom rich text plugin)
  apps/examples/src/examples/outlined-text/OutlinedTextExample.css
  apps/examples/src/examples/outlined-text/OutlinedTextExample.tsx
  apps/examples/src/examples/outlined-text/README.md
Labels: other

#6365 New release process
  .github/workflows/get-changelog.yml
  .github/workflows/publish-manual.yml
  .github/workflows/publish-new.yml
  .github/workflows/publish-patch.yml
  CHANGELOG.md
  apps/docs/CHANGELOG.md
  apps/docs/version.ts
  apps/dotcom/client/version.ts
  internal/scripts/lib/publishing.ts
  internal/scripts/publish-manual.ts
  internal/scripts/publish-new.ts
  internal/scripts/publish-patch.ts
  internal/scripts/publish-prerelease.ts
  lerna.json
  packages/ai/CHANGELOG.md
  packages/ai/package.json
  packages/assets/CHANGELOG.md
  packages/assets/package.json
  packages/dotcom-shared/package.json
  packages/editor/CHANGELOG.md
  packages/editor/package.json
  packages/editor/src/version.ts
  packages/namespaced-tldraw/CHANGELOG.md
  packages/namespaced-tldraw/package.json
  packages/state-react/CHANGELOG.md
  packages/state-react/package.json
  packages/state/CHANGELOG.md
  packages/state/package.json
  packages/store/CHANGELOG.md
  packages/store/package.json
  packages/sync-core/CHANGELOG.md
  packages/sync-core/package.json
  packages/sync/CHANGELOG.md
  packages/sync/package.json
  packages/tldraw/CHANGELOG.md
  packages/tldraw/package.json
  packages/tldraw/src/lib/ui/version.ts
  packages/tlschema/CHANGELOG.md
  packages/tlschema/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
  packages/validate/CHANGELOG.md
  packages/validate/package.json
Labels: other

#6373 Remove auto switch to draw tool
  apps/dotcom/client/src/tla/components/TlaEditor/sneaky/SneakyToolSwitcher.tsx
Labels: other

#6376 Hide crop toolbar while cropping
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/tools/SelectTool/childStates/Crop/children/PointingCrop.ts
  packages/tldraw/src/lib/ui/components/Toolbar/DefaultImageToolbar.tsx
Labels: improvement

#6379 New release process (again)
  .github/workflows/bump-versions.yml
  .github/workflows/get-changelog.yml
  .github/workflows/publish-manual.yml
  .github/workflows/publish-new.yml
  .github/workflows/publish-patch.yml
  CHANGELOG.md
  apps/docs/CHANGELOG.md
  internal/scripts/bump-versions.ts
  internal/scripts/lib/publishing.ts
  internal/scripts/publish-manual.ts
  internal/scripts/publish-new.ts
  internal/scripts/publish-patch.ts
  internal/scripts/publish-prerelease.ts
  packages/ai/CHANGELOG.md
  packages/assets/CHANGELOG.md
  packages/editor/CHANGELOG.md
  packages/namespaced-tldraw/CHANGELOG.md
  packages/state-react/CHANGELOG.md
  packages/state/CHANGELOG.md
  packages/store/CHANGELOG.md
  packages/sync-core/CHANGELOG.md
  packages/sync/CHANGELOG.md
  packages/tldraw/CHANGELOG.md
  packages/tlschema/CHANGELOG.md
  packages/utils/CHANGELOG.md
  packages/validate/CHANGELOG.md
Labels: other

#6387 docs: track copy event
  apps/docs/app/analytics.tsx
  apps/docs/content/getting-started/installation.mdx
Labels: other, docs-hotfix-please

#6389 docs: track copy event, pt 2
  apps/docs/app/analytics.tsx
Labels: other, docs-hotfix-please

#6382 analytics: bring back reo; add redaction to reo+posthog
  apps/dotcom/client/public/reo.html
  apps/dotcom/client/src/utils/analytics.tsx
  apps/dotcom/client/src/utils/csp.ts
Labels: other

#6401 Update DragAndDropExample.tsx
  apps/examples/src/examples/drag-and-drop/DragAndDropExample.tsx
Labels: other

#6400 Remove file upsert + legacy mutations
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/zero/legacy_assertValidMutation.ts
  packages/dotcom-shared/src/mutators.ts
  packages/dotcom-shared/src/types.ts
Labels: other

#6404 Faster User DO Resume
  apps/dotcom/sync-worker/src/TLPostgresReplicator.ts
  apps/dotcom/sync-worker/src/UserDataSyncer.ts
  apps/dotcom/sync-worker/src/types.ts
Labels: other

#6406 Start with 1
  apps/dotcom/client/src/tla/app/TldrawApp.ts
Labels: improvement

#6411 Show max shapes alert when duplicating shapes.
  packages/tldraw/src/lib/ui/context/actions.tsx
Labels: improvement

#6416 intersect.ts tests
  packages/editor/src/lib/primitives/intersect.test.ts
Labels: other

#6420 Fix entering the verification code
  apps/dotcom/client/e2e/fixtures/HomePage.ts
Labels: bugfix

#6417 Fix diagonal arrow issue
  apps/examples/e2e/tests/export-snapshots.spec.tsx
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Regressions-dark-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Regressions-dark-1-chromium-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Regressions-light-1-Mobile-Chrome-linux.png
  apps/examples/e2e/tests/export-snapshots.spec.tsx-snapshots/Export-snapshots-Regressions-light-1-chromium-linux.png
  packages/editor/api-report.api.md
  packages/editor/src/lib/primitives/intersect.test.ts
  packages/editor/src/lib/primitives/intersect.ts
  packages/editor/src/lib/primitives/utils.ts
Labels: bugfix, sdk-hotfix-please

#6419 Fix text measurement style leakage
  packages/editor/src/lib/editor/managers/TextManager/TextManager.ts
Labels: other, sdk-hotfix-please

#6423 Fix fixed-size text measurement
  packages/tldraw/src/lib/shapes/text/TextShapeUtil.tsx
Labels: bugfix

#6415 Improve frame rendering performance by avoiding re-rendering frame shapes on zoom
  packages/tldraw/src/lib/shapes/frame/FrameShapeUtil.tsx
Labels: improvement

#6386 Improve select-all action
  packages/editor/src/lib/editor/Editor.test.ts
  packages/editor/src/lib/editor/Editor.ts
Labels: improvement

#6396 clipboard: fix up html entities being escaped
  packages/tldraw/src/lib/ui/hooks/useClipboardEvents.ts
Labels: bugfix, sdk-hotfix-please

#6431 a11y: fix up aria slider values and make dialogs scrollable via keyboard
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/ui/components/StylePanel/DefaultStylePanelContent.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiDialog.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiSlider.tsx
Labels: bugfix

#6409 Consistent throttle to next frame.
  packages/utils/src/lib/throttle.ts
Labels: bugfix

#6438 Add missing export of HeartToolbarItem
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
Labels: bugfix

#6434 Add hotfixing for closed PRs.
  .github/workflows/trigger-dotcom-hotfix.yml
  .github/workflows/trigger-sdk-hotfix.yml
  internal/scripts/lib/pr-info.ts
  internal/scripts/trigger-dotcom-hotfix.ts
  internal/scripts/trigger-sdk-hotfix.ts
Labels: other

#6442 Fix links and typos.
  packages/ai/README.md
  packages/store/README.md
  packages/tlschema/README.md
  templates/ai/README.md
Labels: other

#6445 Poll for changes and merge if PR can be merged
  .github/workflows/trigger-dotcom-hotfix.yml
  internal/scripts/lib/pr-info.ts
  internal/scripts/trigger-dotcom-hotfix.ts
Labels: bugfix

#6453 [backend] check wake up behavior
  apps/dotcom/sync-worker/src/TLUserDurableObject.ts
  apps/dotcom/sync-worker/src/types.ts
Labels: other, dotcom-hotfix-please

#6456 i18n: fix up compiled messages logic
  apps/dotcom/client/src/tla/providers/TlaRootProviders.tsx
Labels: other

#6455 Use a different api to get the checks.
  internal/scripts/trigger-dotcom-hotfix.ts
Labels: other

#6437 a11y: mark `<svg>` elements and text as aria-hidden
  packages/editor/src/lib/components/SVGContainer.tsx
  packages/editor/src/lib/components/default-components/DefaultBrush.tsx
  packages/editor/src/lib/components/default-components/DefaultCanvas.tsx
  packages/editor/src/lib/components/default-components/DefaultCollaboratorHint.tsx
  packages/editor/src/lib/components/default-components/DefaultCursor.tsx
  packages/editor/src/lib/components/default-components/DefaultGrid.tsx
  packages/editor/src/lib/components/default-components/DefaultHandles.tsx
  packages/editor/src/lib/components/default-components/DefaultShapeIndicator.tsx
  packages/editor/src/lib/components/default-components/DefaultSnapIndictor.tsx
  packages/tldraw/src/lib/canvas/TldrawCropHandles.tsx
  packages/tldraw/src/lib/canvas/TldrawHandles.tsx
  packages/tldraw/src/lib/canvas/TldrawOverlays.tsx
  packages/tldraw/src/lib/canvas/TldrawSelectionForeground.tsx
  packages/tldraw/src/lib/shapes/shared/PlainTextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/RichTextLabel.tsx
Labels: bugfix

#6460 gtag: add ads conversion tracking
  apps/analytics/src/analytics.tsx
  apps/analytics/src/index.ts
  apps/docs/app/analytics.tsx
Labels: other, docs-hotfix-please

#6463 Default title dotcom CTA
  apps/dotcom/client/public/tla/locales-compiled/en.json
  apps/dotcom/client/public/tla/locales/en.json
  apps/dotcom/client/src/tla/components/TlaEditor/TlaEditorTopRightPanel.tsx
Labels: other

#6471 a11y: toggle aria-hidden depending if editing
  packages/tldraw/src/lib/shapes/shared/PlainTextLabel.tsx
  packages/tldraw/src/lib/shapes/shared/RichTextLabel.tsx
Labels: bugfix

#6479 npm: update fractional-indexing-jittered
  packages/utils/package.json
  yarn.lock
Labels: bugfix

#6486 allow custom jsx for icons
  apps/examples/src/examples/bounds-snapping-shape/ui-overrides.tsx
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/styles.tsx
  packages/tldraw/src/lib/ui/components/primitives/Button/TldrawUiButtonIcon.tsx
  packages/tldraw/src/lib/ui/components/primitives/TldrawUiIcon.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuCheckboxItem.tsx
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuItem.tsx
  packages/tldraw/src/lib/ui/context/actions.tsx
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
Labels: improvement

#6489 More shapeutil callbacks
  .cursor/rules/repo.mdc
  packages/editor/api-report.api.md
  packages/editor/src/lib/editor/shapes/ShapeUtil.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/lib/shapes/line/LineShapeUtil.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/DraggingHandle.tsx
  packages/tldraw/src/lib/tools/SelectTool/childStates/Resizing.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Rotating.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/test/shapeutils.test.ts
Labels: api

#6498 posthog: update paths
  apps/analytics/src/analytics.tsx
  apps/analytics/vercel.json
  apps/dotcom/client/src/utils/analytics.tsx
Labels: other, dotcom-hotfix-please

#6502 Fix hotfixing
  internal/scripts/trigger-dotcom-hotfix.ts
Labels: bugfix

#6506 fix packaging & publishing for `npm create tldraw`
  packages/create-tldraw/package.json
Labels: other

#6510 Chunked persist.
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
  apps/dotcom/sync-worker/src/snapshotUtils.test.ts
  apps/dotcom/sync-worker/src/snapshotUtils.ts
Labels: improvement

#6513 feat: export additional components and methods
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/canvas/TldrawCropHandles.tsx
  packages/tldraw/src/lib/defaultExternalContentHandlers.ts
  packages/tldraw/src/lib/tools/selection-logic/getHitShapeOnCanvasPointerDown.ts
  packages/tldraw/src/lib/ui/components/Toolbar/ToggleToolLockedButton.tsx
  packages/tldraw/src/lib/ui/hooks/menu-hooks.ts
Labels: api

#6519 Improve multipart upload handling
  apps/dotcom/sync-worker/src/TLDrawDurableObject.ts
Labels: improvement, dotcom-hotfix-please

#6515 Adds a `data-state` attribute with the current state-tree path to tl-container
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/hooks/useStateAttribute.ts
Labels: api

#6522 perf: tweak regression thresholds
  .github/workflows/playwright-examples.yml
  apps/examples/e2e/tests/baselines/fps-baselines.json
  apps/examples/e2e/tests/fixtures/baseline-manager.ts
  apps/examples/e2e/tests/fixtures/perf-utils.ts
  apps/examples/e2e/tests/test-perf.spec.ts
Labels: other

#4793 Permit drag out of toolbar
  apps/examples/e2e/tests/fixtures/menus/Toolbar.ts
  apps/examples/e2e/tests/test-toolbar.spec.ts
  packages/editor/src/lib/TldrawEditor.tsx
  packages/editor/src/lib/components/MenuClickCapture.tsx
  packages/editor/src/lib/hooks/useCanvasEvents.ts
  packages/tldraw/api-report.api.md
  packages/tldraw/src/index.ts
  packages/tldraw/src/lib/tools/SelectTool/childStates/Translating.ts
  packages/tldraw/src/lib/ui/components/primitives/menus/TldrawUiMenuItem.tsx
  packages/tldraw/src/lib/ui/context/events.tsx
  packages/tldraw/src/lib/ui/hooks/useTools.tsx
Labels: improvement
